### ISSUE TITLE
Spinning beach ball / pinwheel on driver install

### ISSUE THREAD

**Issue by erikhuizinga** [bitgapp/eqMac#1]
When opening eqMac Beta v0.0.0 for the first time the user is prompted to install drivers. After clicking ok and entering credentials, the dialog stays visible and the mouse pointer turns into the spinning beach ball / pinwheel indicating the app is hanging.

**Comment by garfbargle** [comment]
I encountered this too, though it did resolve after finishing. DispatchQueue.global.async { }  :)

**Comment by nodeful** [comment]
![image](https://user-images.githubusercontent.com/8472525/72052596-5e44db00-32bd-11ea-937a-7f9ebb8b6784.png)
Yup, aware of this

**Comment by nodeful** [comment]
This should now be fixed on release v0.0.1
Not sure if you can test it or not. You would have to uninstall and reinstall the app fully (using the Uninstall button in the app settings).
But it definitely should be fixed now. Closing
Thanks for reporting this

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
