### ISSUE TITLE
Will this project be open-source?

### ISSUE THREAD

**Issue by c-bandy** [bitgapp/eqMac#11]
Will this project be open-source or is it a closed source company thing?

I'd love to contribute, having EQ working on my Mac is a top priority right now ^^

**Comment by nodeful** [comment]
Currently the plan is to keep the app closed source as I have invested a lot of time into R&D and would like to keep some intellectual property to myself. Maybe if the project is going to be either super unpopular or super popular I will consider open sourcing it.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
