### ISSUE TITLE
Confirmation Dialog rendering Empty

### ISSUE THREAD

**Issue by Sciman3** [bitgapp/eqMac#13]
Clicking the "X" on the GUI used to bring up a confirmation dialog with buttons. Now, the dialog appears, but it is small and contains no text or buttons. I have to force quit eqmac from Activity Monitor for now.

<img width="402" alt="Screenshot 2020-01-21 15 25 26" src="https://user-images.githubusercontent.com/1441963/72841173-db7c3280-3c63-11ea-8802-fcbe937bc27b.png">

This has started happening since the fix for the eq presets save dialog.

As well, I always forget that the "X" shuts down eqmac and doesn't just close the GUI. Maybe there could be an option to change that behaviour?

**Comment by nodeful** [comment]
I haven't managed to replicate this UI rendering issue on my system yet, so more information would be helpful. Like what kind of Mac system you have, macOS version and User Agent in your Safari browser. As a workaround you can `⌘ + Q` which will force exit the app.

**Comment by Sciman3** [comment]
Hmm, I just went back to try it again, and it seems to be working now. Strange.

In case it pops up again or is helpful at all, I'm running a MacBook Pro (Retina, 15-inch, Mid 2014), running OS 10.15.1. My user agent is "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15"

I'll let you know if I encounter it again.

**Comment by nodeful** [comment]
Thanks for the info. 
Can I ask you to perform a quick test: Try to turn your internet off and restart eqMac.

**Comment by Sciman3** [comment]
Sure!

I tried turning off my internet and restarting eqMac. I didn't encounter any issues doing so, and when I tried exiting eqMac, the dialog was working fine too.

**Comment by jpcloureiro** [comment]
It is related to the equalizer toggle.

if disabled, dialog renders no content.
If enabled, dialog renders correctly

**Comment by Sciman3** [comment]
> It is related to the equalizer toggle.
> 
> if disabled, dialog renders no content.
> If enabled, dialog renders correctly

Ah! Yes, I experience the same behaviour here.

**Comment by nodeful** [comment]
@jpcloureiro thanks for pointing this out!
I have release an over the air UI update, no action required from you guys.
Check if it works now.

**Comment by Sciman3** [comment]
Yup, that works for me!

**Comment by nodeful** [comment]
Awesome, closing the issue. Thanks for your feedback

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
