### ISSUE TITLE
Unable to change custom eq preset

### ISSUE THREAD

**Issue by firebat75** [bitgapp/eqMac#15]
Whenever I try to change the EQ sliders in a custom preset it snaps back to manual, and then when I click the custom preset they slide back to 0.

[![Image from Gyazo](https://i.gyazo.com/992ad94cb972b76ab105e9bdb559f7a1.gif)](https://gyazo.com/992ad94cb972b76ab105e9bdb559f7a1)

**Comment by prpatel78** [comment]
The preset you have made has been created with each slider at the 0 level, when you adjust a slider from its set position, the preset changes to manual, this is normal behaviour as you are deviating from the set values in each preset. 

What you need to do, is set each slider to the level you desire, then click the + beside the preset selector, to save your settings. I'm not sure if you can overwrite the custom one you have made or have to save as new preset and delete the old one.

**Comment by firebat75** [comment]
Thank you!

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
