### ISSUE TITLE
Is this project dead? NO! A quick update on eqMac

### ISSUE THREAD

**Issue by nodeful** [bitgapp/eqMac#164]
Hey everyone. Just a quick rant on the state of eqMac and where it's heading.
For the past 2 years I've been slowly redeveloping the whole project from scratch.
Unfortunately, this has taken me some time as I still work full-time as a Web Developer and I try to be active in life besides work, like doing sports and socialising (otherwise I'll just go insane).
I've learned a lot about Swift programming language and the new Apple Audio API's and Frameworks. The new eqMac version will be miles better and more extendable than eqMac2 as it's using all the latest tech and features on the market.

Unfortunately, during the development time I came across some bugs in Apple API's and for the past 3 MONTH (!) I've been in contact with Apple to try and resolve them, but they haven't seem to have resolves those issues yet. The issues might have affected eqMac2 in many ways, thus why people are complaining about degrading audio and other bugs in eqMac2.
The main issue currently is that there's some Audio Protocol compression issues within macOS that are out of control for any developer to solve. Once this issue will be resolved you can expect the new version to be released shorty.

The new version will functionally be very similar to eqMac2 but more stable, better looking, less buggy and more extendable. This means that I will be able to release new features very quickly, and I have a lot of cool features planned!

Now, regarding monetisation of this project, unfortunately, I have spent disproportionally more time on this project than I have gained in return, but I still feel that the fact eqMac is free is the biggest drive for users to use it (currently eqMac is used by ~50,000 people every day). System Audio equalisation will always stay free, but my plan is to up-sell other more advanced features on a small subscription basis. My hope is that this more reliable revenue stream will allow me to slowly dedicate more and more time towards eqMac and user support.

Here a quick preview on the new UI and how it's going to look on the initial release:

<img width="472" alt="Promo" src="https://user-images.githubusercontent.com/8472525/58753803-bb251b00-84bc-11e9-8b17-f7bb41b9775c.png">

Advanced Equalizer:
![advanced-equalizer](https://user-images.githubusercontent.com/8472525/58753806-c11afc00-84bc-11e9-90f1-060ad21fd3bd.jpg)

Hope this clears some things up. If you have any other questions about the new version please leave a comment right in this issue.
Thank you everyone!

**Comment by stpoa** [comment]
Waiting for eqMac3. I would consider different / simpler ui design, something that would match whole MacOS style, also it would be cool if it would support dark / light mode.

**Comment by nodeful** [comment]
@stpoa too late at this point for a new design. I do agree this design looks nothing like native macOS design, however this is what I managed to get by buying a Design Kit, I'm not great at design myself and don't have the resources to hire a UI/UX designer. Some people have submitted their design ideas for me on Twitter, but I haven't fell in love with any of them, most just would not work for the amount of features planned in the future.

**Comment by Dale-Cotton** [comment]
Personally, I like the new interface design. I can see instantly how to operate the new controls just by looking at them. Surely that’s key. 

What would be killer for me would be 10 or more bands of parametric EQ. Is that hidden behind your teasers by any chance? Or one of the for-pay enhancements? 

Other things I'm hoping to see in ver 3: 
1. “pre-amp” control
2. ability to read the tiny Hz and dB scale numbers on the 31 band graph without zooming in
3. ability to save EQ plots to disk, edit them with a text editor, then re-load them into the app. 

Meanwhile, I continue to limp along with eqMac2 and refuse to upgrade MacOS beyond Sierra for fear doing so will render eqMac2 unusable. That's how important a part of my life it is. Thanks for creating it!

**Comment by orhuidobro** [comment]
I'm using eqMac2 in Mojave, it works just fine. I love it.

I'd like to have a way to save/restore my presets (locally, cloud), in order to reuse them in a different/new machine.

**Comment by philraj** [comment]
Glad to hear it's coming along. Regarding the new UI, I think it looks good, I just wish the dark green text (e.g. gain amount) were more readable. Please consider increasing the contrast a little bit.

**Comment by ericreeves** [comment]
I've been dealing with a bunch of issues with eqMac2, Mojave, and Qobuz lately.  Sometimes it works, but more often I can't get audio to stream from Qobuz -> eqMac2 -> DAC.  If there's any information I can provide to assist in the debugging process I'd be happy to.

In any case, thank you for your selfless effort and contribution to the community!

**Comment by erikhuizinga** [comment]
Congrats on the new developments!

What about the crackling issues (#152, #156)? Did you manage to fix them? And what about those 'Audio Protocol compression issues within macOS' you mention? Is there some way we can help put the pressure on Apple to fix these issues?

Is there an issue or thread we can thumbs-up 👍, star ⭐️, or something? I really like eqMac2, but the crackling issue makes it hard to enjoy.

**Comment by glekner** [comment]
Thank you for your work and time, looking forward to the new release. Subscription is meh, and scary. I would gladly pay a good amount for a 1 purchase.

**Comment by therealchiko** [comment]
Awesome, can't wait for the new update to get rolled out & hopefully contribute in the next coming months :)

**Comment by MariuzM** [comment]
Now sure how I feel about the subscription, I would prefer one of payment even if it's a bigger payment than usual but subscription is no no for me.

**Comment by Palidino** [comment]
Since this major update doesn't seem to be getting released anytime soon, can we get a bug fix for the crackling sound that happens? I just picked this up because it's the only free EQ software available, but it starts crackling after a few minutes.

**Comment by MariuzM** [comment]
From my understanding there will not be any fixes to the current version so you just have to wait for major update. But I found app Sound Control this one does not have any issues, it is trial version but then you can pay, I prefer this over Boom 2

**Comment by Satori83** [comment]
> @stpoa too late at this point for a new design. I do agree this design looks nothing like native macOS design, however this is what I managed to get by buying a Design Kit, I'm not great at design myself and don't have the resources to hire a UI/UX designer. Some people have submitted their design ideas for me on Twitter, but I haven't fell in love with any of them, most just would not work for the amount of features planned in the future.

Hey man! I been using eqMac since the start and love it. Unfortunately I was never able to contribute because my coding stops with front end/wordpress shit. But I actually decided to pivot careers from my web shop and im in a program at Career Foundry for UX design with UI concentration. Granted ive just started there but I need to work on stuff for my portfolio and I already had a killer idea for a diff music app that i couldnt code so was gonna design the UI. I would be more than happy to work with you and iterate through some design stuff in a month or so for free if you'd like the free expertise;-) We could always trade biz/marketing ideas for it too. I like thinking bout that shit lol. Let me know and great work!

**Comment by rv-bnowak** [comment]
Cracking issues are actually a non issue IMHO.  They are a user settings / user guide / documentation issue!
https://github.com/nodeful/eqMac2/issues/152#issuecomment-545989613

**Comment by nifhanif** [comment]
31 band equalizer is very great. I am hoping in the next version, this feature is still available.

Rather than subscription basis, I thought one time purchase is better for people whose not using all the features. And one thing, I wish there is no payment for every month's system.

**Comment by ericreeves** [comment]
I am NOT trying to speak negatively about this project, or the effort behind it.  It is ALL COMMENDABLE AND AWESOME!

But if you need a reliable EQ solution right now in OSX, I can highly recommend Boom3D.  It's a system-wide EQ that doesn't require you to route every single individual application through it.  It takes over by default if it's running.

KEEP UP THE GOOD WORK, HERE!

**Comment by ronggong** [comment]
@nodeful Hi, any plan to support equalizing individual app audio?

**Comment by nodeful** [comment]
@ronggong yeap, on the roadmap that is mile long. Look into BackgroundMusic for the moment.

**Comment by ronggong** [comment]
@nodeful ok, but what BackgroundMusic does is just volume change for app. I wonder how can we implement this function? The current eqMac gets the system audio stream from soundflower output, then sends it to an AUGraph, then finally sends the processed stream to an output device. Correct me if I am wrong. But how would you do to get the audio stream of an individual app?

**Comment by agiorlando** [comment]
@ericreeves Boom has the same audio issues as eqMac it just resets itself every time it happens.

@nodeful I have been using Boom in the meantime since the degrading audio issues, is that still an issue on Catalina?

**Comment by leocoracini** [comment]
Hello @nodeful ! Thanks for your great work since eqMac1. I'm using eqMac2.2 with 31 Bands and it's just amazing how much improvement in sound it can make, once configured wisely. I want to support your job. How to? ✌️ 
Also, I'm looking forward to see the new eqMac3 😍

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by mrrroy** [comment]
just downloaded eqmac.app.  It's working nicely on my machine.  Simple yet powerful,  Thank you!

**Comment by zodywoolsey** [comment]
I've gotta say, I have seen so many developers have tons of issues with the current state of macos. It makes me very angry to see such buggy software on the OS that "Just works"... I'm honestly considering just loading linux on my work macbook pro just so I can finally have a stable workflow again. It's honestly sad when the open source free projects are more stable than the paid software form multibillion and trillion dollar companies.

**Comment by marllij** [comment]
I have downloaded and tried to use your equaliser multiple times on my Mac running OS X Catalina, yet I'm having issues opening the application. I will click to open it, and the icon expands as if opening, however, no application is started. I'm not sure if this is just a bug, in which case, I shall be patient as I assume there will be an update. I simply cannot get the program to start whatsoever and I really would like to use it. I work with music production, and eq is a big part of creating a neutral sound in non-neutral headphones/speakers. So I would really like to see your program work and I trust you have spent much time diligently working on it. Any help would be much appreciated. Thank you.

**Comment by LeeBinder** [comment]
> I've gotta say, I have seen so many developers have tons of issues with the current state of macos. It makes me very angry to see such buggy software on the OS that "Just works"... I'm honestly considering just loading linux on my work macbook pro just so I can finally have a stable workflow again. It's honestly sad when the open source free projects are more stable than the paid software form multibillion and trillion dollar companies.

just do as I and *many* others do: stick with Mojave! Nobody forces you to upgrade to Catalina, and Mojave will be supported with security updates for a long time to come!!

**Comment by zodywoolsey** [comment]
> > I've gotta say, I have seen so many developers have tons of issues with the current state of macos. It makes me very angry to see such buggy software on the OS that "Just works"... I'm honestly considering just loading linux on my work macbook pro just so I can finally have a stable workflow again. It's honestly sad when the open source free projects are more stable than the paid software form multibillion and trillion dollar companies.
> 
> just do as I and _many_ others do: stick with Mojave! Nobody forces you to upgrade to Catalina, and Mojave will be supported with security updates for a long time to come!!

Yeah, I was thinking scout doing that. Only problem is that a lot of people are using Catalina so if I'm on an older OS version, my code won't work on their machines...
To be honest, the most stable os out right now, from my testing, is Linux! Any of the major distros are significantly more stable than both Windows and macos. I mean in every occasion. When I have a game/app/site crash or just not work it'll work on Linux. Even steam's playonlinux is way more stable than the game is normally on Windows in many occasions. Most times, I even get improved performance!!

**Comment by LeeBinder** [comment]
Sounds familiar. My ex boss was (and very most likely still is) running Ubuntu (or some close flavor) as his main every-day OS both at work and at home, and would switch to Windows and (back then still) OS X (most current and recent versions of both OSes via bootmanager) to the left and (respectively) to the right only for testing, and get back out always asap.

I have High Sierra, Mojave and Catalina installed in one APFS container sharing space, in 10.13 and 10.15 with a bunch of SymLinks pointed to shared Mojave folders, sharing Desktop, Downloads + many prefs files and folders. It took a few hours to set up, but is working beautifully so I can seemlessly switch between 10.13/14/15 and always continue work/ testing/ debugging etc. with the look-&-feel of just one OS.

**Comment by odinian** [comment]
Add a good crossfeed, and I think it will make the paid version much more marketable.

**Comment by LeeBinder** [comment]
@odinian : hum? Has nodeful made any progress on a paid version?

**Comment by odinian** [comment]
@LeeBinder - sorry, no idea. I was just adding my 2 cents based on what I saw on https://eqmac.app/

It looks like "expert" mode might not be free, based on inferences from the site.

I would pay $15 if it had AU support. Much more, and I will continue to use BlackHole and GarageBand.

**Comment by ScrollLocker** [comment]
Guys, I don't know if this is the correct channel to report this but in Eqmac2 using Mojave I was having problems after 30 min playing music, the audio starts to cut and fail. This issue was solved by EqMac3, but yesterday I received a message to update, I updated it and starts to cut the audio again as EqMac2 did. Just a feedback, sorry if it's not the correct channel.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nadstaky** [comment]
@nodeful 
How to compile the source from macOS Mojave 10.14.6 with Xcode 10.13.1 PLEASE ?

I've download eqMac Beta on your official Web site, I don't have the new UI (I'm Mojave 10.14.6)

Please help me !

Best,
Nad

**Comment by J3141592** [comment]
I was using eqmac just fine, beta I blieve on macOS 10.14.6  AMAZING Difference in sound quality from all of my speakers and headphones. 
all was well, and now it's not opening... Tried to uninstall it, and re install. of no avail. 
suggestions? I really liked how it was able to save my settings for different outputs/ speakers headphones etc. HELP ! :)

**Comment by persus** [comment]
2023 is almost gone, we now have ARM processors from Apple and Apple is continuing to close up MacOS with ties while the last comment here was over three years ago.

The question may be asked again: Is this project dead?

**Comment by persus** [comment]
Oh, I didn't see. Sorry for being blind 😵‍💫
