### ISSUE TITLE
Beta eqMac crash at startup

### ISSUE THREAD

**Issue by Joachim-42he** [bitgapp/eqMac#181]
On my Mac Book Pro with Catalina (10.15.2), eqMac (Beta) keeps crashing with the following error whe I try to start it:
` Fatal error: Unable to bridge NSNumber to Bool: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_overlay_Foundation/swiftlang-1100.8.280/swift/stdlib/public/Darwin/Foundation/NSNumber.swift, line 571`

BTW: The Slack invitation link mentioned in the Issue panel is out of date.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment]
This error should have been fixed a couple weeks ago with the v0.0.1 update
