### ISSUE TITLE
Beta EQMac Won't open

### ISSUE THREAD

**Issue by Ashteroide** [bitgapp/eqMac#182]
The new EQMac Beta won't open on Catalina, I've tried reinstalling and restarting my computer

**Comment by Ashteroide** [comment]
Still won't open, I've tried everything

**Comment by Ashteroide** [comment]
Just spammed it open a bunch of times, it showed in Activity monitor but that was all, not working

**Comment by victoria-viola** [comment]
I've had the same problem too. Mine's not even showing on Activity monitor.

**Comment by luccasclezar** [comment]
Same, mine doesn't show on Activity Monitor too.

**Comment by samelie** [comment]
All of a sudden stopped working for me too. Catalina

**Comment by Ashteroide** [comment]
After the last 2 Beta updates on Catalina it has started working more

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment]
Please reference issue #223 from now on.
