### ISSUE TITLE
How to clean uninstall eqmac2

### ISSUE THREAD

**Issue by prpatel78** [bitgapp/eqMac#183]
I recently tried to uninstall eqmac2 so that I can use the new version, however, eqMac2 still remains as an audio device. I am unable to remove the device as the remove button is greyed out.

Can you help?

![image](https://user-images.githubusercontent.com/55404517/73974502-0fa15580-48ea-11ea-845c-fc28f113f2c4.png)

**Comment by watchthesunrise** [comment]
Just to be clear, you uninstalled by clicking "uninstall" in the bottom right hand corner of the dropdown? Doing this + restarting your Mac should be all you need to do.

**Comment by prpatel78** [comment]
That is correct, but emac2 still shows up as an available speaker/audio source.

.........................................
Priyesh Patel

Your "Tech"  in Technology
(m) 972-591-1114
priyesh@astrea.co.uk

Visit us on the web:
www.astrea.co.uk

**Comment by Joachim-42he** [comment]
Same here. Uninstalled eqmac2 (to install eqmac beta) but the device is still listed.

**Comment by Martin10110** [comment]
Same here. Clicked on uninstall in eqmac2 and restarted. The device is still listed in sound preferences.

Also, did a kexstat command and the below kernel extension is still showing so it has not been uninstalled cleanly. 

com.bitgapp.eqMac2Driver (2.0) C8E2C7F3-989B-3EF0-AE56-80D339AC2703 <88 6 5 3>

Has anyone managed to resolve?

Thanks

**Comment by Martin10110** [comment]
I have sorted this myself if anybody has the same problem.

Go to /Library/StagedExtensions/Library and delete eqMac2Driver.kext

Sound preferences does not now show eqMac2 as an option.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by siemiatj** [comment]
I've also removed `eqmac` from `/Library/Preferences/audio/com.apple.audio.DeviceSettings.plist` and `/Library/Preferences/audio/com.apple.audio.SystemSettings.plist`

**Comment by Joachim-42he** [comment]
On MacOS Catalina, I was finally successful by removing two .kext folders from my system with SIP (System Integrity Protection) disabled (for which I needed to boot to recovery mode).
```
sudo reboot
(Press Cmd + R during boot)
(Select "Teminal" from the top menu "Utilities")
csrutil disable
reboot
(in Teminal:)
sudo rm -rf /System/Volumes/Data/Library/Extensions/eqMac2Driver.kext
sudo rm -rf /Library/StagedExtensions/Library/Extensions/eqMac2Driver.kext
reboot
(Press Cmd + R during boot)
(Select "Teminal" from the top menu "Utilities")
csrutil enable
reboot
```

**Comment by ssent1** [comment]
> On MacOS Catalina, I was finally successful by removing two .kext folders from my system with SIP (System Integrity Protection) disabled (for which I needed to boot to recovery mode).
> 
> ```
> sudo reboot
> (Press Cmd + R during boot)
> (Select "Teminal" from the top menu "Utilities")
> csrutil disable
> reboot
> (in Teminal:)
> sudo rm -rf /System/Volumes/Data/Library/Extensions/eqMac2Driver.kext
> sudo rm -rf /Library/StagedExtensions/Library/Extensions/eqMac2Driver.kext
> reboot
> (Press Cmd + R during boot)
> (Select "Teminal" from the top menu "Utilities")
> csrutil enable
> reboot
> ```

Finally!! This works like a charm!!

**Comment by nodeful** [comment]
Closing in favour of #247

**Comment by siemiatj** [comment]
On El Capitan
```
sudo rm -rf /System/Library/Extensions/eqMac2Driver.kext 
```

**Comment by greyskymedia** [comment]
I wanted to comment that while the below DID work, for me, I had to actually go back a number of levels til I reached the HD selection... I first had to `../../../` to get to root root, then follow the path from Macintosh HD through to the kext. I used `find / eqMac2Driver.kext` to find the full location, then this worked. Hope it helps someone as frustrated as I have been.

> On MacOS Catalina, I was finally successful by removing two .kext folders from my system with SIP (System Integrity Protection) disabled (for which I needed to boot to recovery mode).
> 
> ```
> sudo reboot
> (Press Cmd + R during boot)
> (Select "Teminal" from the top menu "Utilities")
> csrutil disable
> reboot
> (in Teminal:)
> sudo rm -rf /System/Volumes/Data/Library/Extensions/eqMac2Driver.kext
> sudo rm -rf /Library/StagedExtensions/Library/Extensions/eqMac2Driver.kext
> reboot
> (Press Cmd + R during boot)
> (Select "Teminal" from the top menu "Utilities")
> csrutil enable
> reboot
> ```

**Comment by nicolassrod** [comment]
sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/ && sudo launchctl kickstart -k system/com.apple.audio.coreaudiod &>/dev/null

**Comment by Tonny33dk** [comment]
Hi how to get Eqmac2 out form my Mac I have (macOS Big Sur) I have try all that's have tried the solutions that are here pls help my make a video ?

**Comment by Jewboy54** [comment]
I have deleted the app, but cannot delete eqMac2Driver.kext
Please advise.
Thank you in advance

**Comment by SamClayton** [comment]
Perfect! This worked for me on Mojave.

> `sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/ && sudo launchctl kickstart -k system/com.apple.audio.coreaudiod &>/dev/null`

**Comment by geschriever** [comment]
> sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/ && sudo launchctl kickstart -k system/com.apple.audio.coreaudiod &>/dev/null

Great, thank you, this was the solution!

**Comment by EQPEW** [comment]
eqMAC THE WORST THING I EVER INSTALLED

**Comment by nodeful** [comment]
Unfortunately there's nothing I can do to automate this process, but I have added a section about this in the FAQ: https://eqmac.app/#uninstall-eqmac2

**Comment by dalegaspi** [comment]
> sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/ && sudo launchctl kickstart -k system/com.apple.audio.coreaudiod &>/dev/null

at least for Big Sur you need to reboot afterwards, but it worked.

**Comment by realitymolder** [comment]
> `sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/ && sudo launchctl kickstart -k system/com.apple.audio.coreaudiod &>/dev/null`

Works like a charm on M1 Max Ventura.

**Comment by ngnvuan** [comment]
> `sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/ && sudo launchctl kickstart -k system/com.apple.audio.coreaudiod &>/dev/null`

It works for me on Sonoma 14.3.1. Thank you!

**Comment by kjoesch** [comment]
> `sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/ && sudo launchctl kickstart -k system/com.apple.audio.coreaudiod &>/dev/null`

Works on Tahoe 26.1 🙏
