### ISSUE TITLE
Can't install drivers

### ISSUE THREAD

**Issue by guilhermecapelo** [bitgapp/eqMac#185]
Hey! I had eqmac2 installed on my mac that MacOSCatalina and it all worked very well. But i formated my mac and now i can't install eq mac 2 with gives me a error message:  
<img width="487" alt="Captura de ecrã 2020-02-11, às 17 44 29" src="https://user-images.githubusercontent.com/42043108/74263232-5500c100-4cf6-11ea-8a77-cbe395accba7.png">

And i do everything that they say i insert my password to allow te installation, and it gives me this error message: 
<img width="487" alt="Captura de ecrã 2020-02-11, às 17 44 37" src="https://user-images.githubusercontent.com/42043108/74263312-72358f80-4cf6-11ea-989d-497b5d4c12d5.png">
 
But my configurations are all good, they are authorized to install from all sources.

<img width="1157" alt="Captura de ecrã 2020-02-11, às 17 44 37 2" src="https://user-images.githubusercontent.com/42043108/74263335-7feb1500-4cf6-11ea-89f6-f89b7f2c5d13.png">

I clicked on "i have change my configurations" but it still doesn't work and the program tells me to chat it the developer...
I don't know what to do more, i like mac EQ allot but i can't use it...

**Comment by fbrinkmann** [comment]
The same problem like #184 and I´m having the same issue on Catalina 10.15.3

**Comment by cjmaria** [comment]
Same issue on Catalina 10.15.3 (SIP disabled).
I also tried to install via Homebrew, and got a more verbose error. The homebrew error output is attached.
[EqmacError.txt](https://github.com/nodeful/eqMac2/files/4194600/EqmacError.txt)

**Comment by SantiMoskito** [comment]
Hi all, anyone got any luck installing the driver? Thanks!!!

**Comment by lalala** [comment]
I'm having the same issue since purchasing a new mac :-)

**Comment by kalantal** [comment]
Same issue as everyone else, have not found a solution yet.

**Comment by nutzaalex** [comment]
I fixed this in the following way [link](https://github.com/nodeful/eqMac2/issues/184#issuecomment-588878904)

**Comment by mskl** [comment]
> I fixed this in the following way [link](https://github.com/nodeful/eqMac2/issues/184#issuecomment-588878904)

disabling csrutil did not help on 10.15.3

**Comment by mdiloreto16** [comment]
Any update on this?

**Comment by nutzaalex** [comment]
@mskl  @mdiloreto16 try the method I linked while also doing `sudo mount -uw /`, that should do the trick.

**Comment by mdiloreto16** [comment]
@nutzaalex this worked for me

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment]
Closing issue as people should try and use the new eqMac beta release :) Thanks
