### ISSUE TITLE
Infinite Glitching after every reboot

### ISSUE THREAD

**Issue by sobersherlock** [bitgapp/eqMac#187]
I'm using v2.3.3 and I never have any installation problems, but there's another issue in which the volume would glitch out until I uninstall the program and install it again. Does anyone know how to fix this?

**Comment by olegnaumenko** [comment]
@sobersherlock , does quitting/starting the eqMac app help? when You experience glitches, in System Settings -> Audio output, do You see default device selection jumping?

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment]
Moving discussion and tracking of this issue to #224
