### ISSUE TITLE
brew install fails

### ISSUE THREAD

**Issue by mpbunch** [bitgapp/eqMac#188]
brew cask install eqmac
Brew fails with following warning:

==> Purging files for version 2.2 of Cask eqmac
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/install_driver.sh` exited with 1. Here's the output:
Unable to determine realpath for /System/Library/Extensions/eqMacDriver.kext - failing.
Can't create /System/Library/Extensions/eqMacDriver.kext.
Unable to determine realpath for /System/Library/Extensions/eqMac2Driver.kext - failing.
Can't create /System/Library/Extensions/eqMac2Driver.kext.
touch: /System/Library/Extensions: Read-only file system
cp: /System/Library/Extensions/eqMac2Driver.kext: Read-only file system
cp: /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/eqMac2Driver.kext: unable to copy extended attributes to /System/Library/Extensions/eqMac2Driver.kext: Read-only file system
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents: No such file or directory
cp: /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/eqMac2Driver.kext/Contents: unable to copy extended attributes to /System/Library/Extensions/eqMac2Driver.kext/Contents: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/_CodeSignature: No such file or directory
cp: /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/eqMac2Driver.kext/Contents/_CodeSignature: unable to copy extended attributes to /System/Library/Extensions/eqMac2Driver.kext/Contents/_CodeSignature: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/_CodeSignature/CodeResources: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/MacOS: No such file or directory
cp: /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/eqMac2Driver.kext/Contents/MacOS: unable to copy extended attributes to /System/Library/Extensions/eqMac2Driver.kext/Contents/MacOS: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/MacOS/eqMac2Driver: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/Info.plist: No such file or directory
Notice: -print-diagnostics (-t) ignored; use kextutil(8) to test kexts.
Requesting load of /System/Library/Extensions/eqMac2Driver.kext.
/System/Library/Extensions/eqMac2Driver.kext failed to load - (libkern/kext) not found; check the system/kernel logs for errors or try kextutil(8).
touch: /System/Library/Extensions: Read-only file system

**Comment by juliomsilva** [comment]
yes, same here. can't install with brew or even the package downloaded from the homepage.

```sh
==> Purging files for version 2.2 of Cask eqmac
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/install_driver.sh` exited with 1. Here's the output:
Unable to determine realpath for /System/Library/Extensions/eqMacDriver.kext - failing.
Can't create /System/Library/Extensions/eqMacDriver.kext.
```

**Comment by Jolg42** [comment]
Same here 😭 

```
Tapped 1 command and 3522 casks (3,638 files, 205.8MB).
==> Downloading https://github.com/nodeful/eqMac2/releases/download/V2.2/eqMac2.dmg
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/98095061/7948ae72-d793-11e7-8470-803257c
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'eqmac'.
==> Installing Cask eqmac
==> Running installer script '/usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/install_driver.sh'
Password:
Unable to determine realpath for /System/Library/Extensions/eqMacDriver.kext - failing.
Can't create /System/Library/Extensions/eqMacDriver.kext.
Unable to determine realpath for /System/Library/Extensions/eqMac2Driver.kext - failing.
Can't create /System/Library/Extensions/eqMac2Driver.kext.
touch: /System/Library/Extensions: Read-only file system
cp: /System/Library/Extensions/eqMac2Driver.kext: Read-only file system
cp: /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/eqMac2Driver.kext: unable to copy extended attributes to /System/Library/Extensions/eqMac2Driver.kext: Read-only file system
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents: No such file or directory
cp: /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/eqMac2Driver.kext/Contents: unable to copy extended attributes to /System/Library/Extensions/eqMac2Driver.kext/Contents: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/_CodeSignature: No such file or directory
cp: /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/eqMac2Driver.kext/Contents/_CodeSignature: unable to copy extended attributes to /System/Library/Extensions/eqMac2Driver.kext/Contents/_CodeSignature: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/_CodeSignature/CodeResources: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/MacOS: No such file or directory
cp: /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/eqMac2Driver.kext/Contents/MacOS: unable to copy extended attributes to /System/Library/Extensions/eqMac2Driver.kext/Contents/MacOS: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/MacOS/eqMac2Driver: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/Info.plist: No such file or directory
Notice: -print-diagnostics (-t) ignored; use kextutil(8) to test kexts.
Requesting load of /System/Library/Extensions/eqMac2Driver.kext.
/System/Library/Extensions/eqMac2Driver.kext failed to load - (libkern/kext) not found; check the system/kernel logs for errors or try kextutil(8).
touch: /System/Library/Extensions: Read-only file system
==> Purging files for version 2.2 of Cask eqmac
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/install_driver.sh` exited with 1. Here's the output:
Unable to determine realpath for /System/Library/Extensions/eqMacDriver.kext - failing.
Can't create /System/Library/Extensions/eqMacDriver.kext.
Unable to determine realpath for /System/Library/Extensions/eqMac2Driver.kext - failing.
Can't create /System/Library/Extensions/eqMac2Driver.kext.
touch: /System/Library/Extensions: Read-only file system
cp: /System/Library/Extensions/eqMac2Driver.kext: Read-only file system
cp: /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/eqMac2Driver.kext: unable to copy extended attributes to /System/Library/Extensions/eqMac2Driver.kext: Read-only file system
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents: No such file or directory
cp: /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/eqMac2Driver.kext/Contents: unable to copy extended attributes to /System/Library/Extensions/eqMac2Driver.kext/Contents: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/_CodeSignature: No such file or directory
cp: /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/eqMac2Driver.kext/Contents/_CodeSignature: unable to copy extended attributes to /System/Library/Extensions/eqMac2Driver.kext/Contents/_CodeSignature: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/_CodeSignature/CodeResources: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/MacOS: No such file or directory
cp: /usr/local/Caskroom/eqmac/2.2/eqMac2.app/Contents/Resources/eqMac2Driver.kext/Contents/MacOS: unable to copy extended attributes to /System/Library/Extensions/eqMac2Driver.kext/Contents/MacOS: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/MacOS/eqMac2Driver: No such file or directory
cp: /System/Library/Extensions/eqMac2Driver.kext/Contents/Info.plist: No such file or directory
Notice: -print-diagnostics (-t) ignored; use kextutil(8) to test kexts.
Requesting load of /System/Library/Extensions/eqMac2Driver.kext.
/System/Library/Extensions/eqMac2Driver.kext failed to load - (libkern/kext) not found; check the system/kernel logs for errors or try kextutil(8).
touch: /System/Library/Extensions: Read-only file system
```

**Comment by Jolg42** [comment]
Could be related to 
https://github.com/Homebrew/homebrew-cask/issues/76377
https://github.com/nodeful/eqMac2/issues/172
as I'm on Catalina too

**Comment by Jolg42** [comment]
Fixed manually with https://github.com/nodeful/eqMac2/issues/172#issuecomment-606548728

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment]
closing in favour of #249
