### ISSUE TITLE
Long delay between clicking system tray icon and GUI loading

### ISSUE THREAD

**Issue by edbird** [bitgapp/eqMac#189]
I've read the updates regarding the new version, so perhaps this will be fixed in the new app?

I report this issue incase it is not known about by the dev. (Does anyone else have this issue.)

Steps to reproduce: Click the system tray icon in the upper right side of the screen.

Takes between 10 and 30 seconds for GUI to appear.

**Comment by edbird** [comment]
(Mac "waiting wheel" appears during this time)

**Comment by edbird** [comment]
I changed (upgraded) to High Sierra - I had problems with eqMac and the volume adjustment. I removed it and re-installed it using the brew installation method - now the issues seems to have gone away, I assume it was fixed in a later version

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment]
Moving discussion here: #230
