### ISSUE TITLE
Import/Export button hangs up the whole app

### ISSUE THREAD

**Issue by Miigon** [bitgapp/eqMac#19]
- **Version:** Downloaded from http://eqmac.app on Feb 13,2020
- **OS Version:** macOS Mojave 10.14.6
- **Description:**  
App hangs up completely upon clicking import/export button and doesn't recover.
CPU Usage is around 3%.

- **Reproduce:**  
  1. Open the app
  2. Switch to Advanced Equalizer
  3. Click the gear button to open Advanced Equalizer Settings 
  4. Click Import or Export
  5. App hangs up (100% of the times)

- **Process Sample:**
https://pastebin.com/n5B4TktG
------------------
It seems like it's stuck in the render routine. Maybe a death lock?
I've installed eqMac2 before but have already uninstalled it using the `Uninstall` button in the app.

**Comment by Miigon** [comment]
Also tell me what can I do to help and make this awesome app better.

**Comment by nodeful** [comment]
Yeah it's happening to me as well. Will fix in the next update

**Comment by nodeful** [comment]
I have just release a new update. Please check if the problem still persists. Thank you

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
