### ISSUE TITLE
EQ sliders too small / range too large to be useful for small audio adjustments

### ISSUE THREAD

**Issue by edbird** [bitgapp/eqMac#190]
Having a large dB range on the sliders is arguably good/useful, but the sliders are too short to be able to make fine changes easily.

A possible solution:

- Increase GUI size to be 2-3 times larger in height, so that sliders are several times longer, allowing for easier fine adjustment.

- Have a "major" and "minor" slider for each channel/frequency. Minor slider adjusts 10x smaller range.

- Have a "log scale" checkbox/option to allow fine adjustment close to the zero point of the slider.

Hopefully those 3 suggestions are clear, if not add a comment and I will give a more detailed/clear explanation

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment]
Closing in favour of #233
