### ISSUE TITLE
"Sponsor" is not working

### ISSUE THREAD

**Issue by Jolg42** [bitgapp/eqMac#193]
<img width="464" alt="Screenshot 2020-04-05 at 20 47 36" src="https://user-images.githubusercontent.com/1328733/78507282-825e6e00-777f-11ea-9341-e97a56199a7e.png">

Hi!

Just to let you know that it's not working yet.

Can't wait for the new version 🎊 😃

**Comment by nodeful** [comment]
Yeah I'm still under review. The sponsor thing is just a test for now :)

**Comment by nodeful** [comment]
The new version is already out: https://eqmac.app
It has almost all features from eqMac2, should be more stable, but some features are lacking like the 32 band EQ

**Comment by Jolg42** [comment]
Ok 👍 

For the new version the link points to the 2017 download here https://github.com/bitgapp/eqmac/releases

**Comment by nodeful** [comment]
Oh wow thanks for pointing that out!

**Comment by nodeful** [comment]
That's now fixed
