### ISSUE TITLE
Any Discussion Forum?

### ISSUE THREAD

**Issue by heronimus** [bitgapp/eqMac#194]
Hey, congratulation for the new release 🎉, It nice that this open-source project is coming to the new phase!
While we try the beta version, is there any forum like glitter, discord, or just use this Github issue to discuss further possible bug or improvement?

**Comment by nodeful** [comment]
Sure. We used to have Slack, but I think Discord is taking world by storm.
Here's the Discord server: https://discord.gg/BA22ceW

**Comment by heronimus** [comment]
Great thanks for providing Discord channel 👍  , as this already mentioned too in the Readme file, I'll close this issue.
