### ISSUE TITLE
Preventing sleep issue [Migrate issue from  bitgapp/new-eqmac-archive#25]

### ISSUE THREAD

**Issue by jinh574** [bitgapp/eqMac#195]
[Migrate issue from  bitgapp/new-eqmac-archive#25]

First, I want to say thank u for developing good app.

I am aware that there was an issue with sleep prevention since the previous version. In order to use sleep, I turn off the eqMac when I am not using it, and when I use it again, the sound switches every time, but I keep experiencing the issue that the eqMac does not work properly.

I'm not sure if sleep protection is a necessary limitation in providing eqMac. Is this an unresolvable part?

and, it is same issue bitgapp/new-eqmac-archive#23 too

------
Reply
@nodeful 
It's definitely should be possible to stop the sleep prevention. I just need to analyse the audio pipeline and stop the processing engine if there's no sound for a while. Otherwise the Audio Engine keeps piping sound which probably what causes the computer to not go to sleep.

@nodeful 
I will look into that soon

**Comment by nodeful** [comment]
Thanks for reposting this issue here :)

**Comment by nodeful** [comment]
Moving discussing of this issue to #228
