### ISSUE TITLE
If Show Icon set to Status Bar, Closing eqmac should just close the window, not the whole app.

### ISSUE THREAD

**Issue by glekner** [bitgapp/eqMac#196]
as title says, just a behaviour issue.

**Comment by nodeful** [comment]
Just click the minimise button next to the close button and it will minimise

**Comment by glekner** [comment]
Yes, i'm aware of this behavior, but UX wise, minimizing feels like the app stays on the dock when we don't want to.

**Comment by nodeful** [comment]
How would you go about quitting eqMac process if we use the "X" in the top left to minimise instead of quitting?

**Comment by Takuro-Ito** [comment]
I agree with @glekner.
Thanks in advance for your great work!

**Comment by nodeful** [comment]
Moving discussion here: #230
