### ISSUE TITLE
Transition from eqMac2 to the new eqMac

### ISSUE THREAD

**Issue by Harosatchi** [bitgapp/eqMac#198]
1. Do I need to remove eqMac2 or install on top of it? If necessary, how to do it correctly (they wrote here that it is not completely deleted and remains in audio devices)
2. How to transfer saved presets?

**Comment by nodeful** [comment]
the new eqMac upon installation nukes the driver for eqMac2 to avoid potential issues as seen here:
https://github.com/bitgapp/eqMac/blob/master/native/app/Source/Scripts/install_driver.sh#L6-L12
I've tested on my machine and it does remove eqMac2 audio device from the list. Not sure what's going on if it stays there for you :(
In terms of transitioning presets, that should be shipped very soon (for the advanced 10 band EQ)

**Comment by nodeful** [comment]
Closing in favour of #234
