### ISSUE TITLE
eqMac beta v0.0.1 : import/export issue

### ISSUE THREAD

**Issue by nadstaky** [bitgapp/eqMac#200]
I've set my eq and saved it.
Then I've exported it.
When I import, my settings won't load.

**Comment by bhushan-n** [comment]
Same issue. Please help us hotfix it for now.

**Comment by nodeful** [comment]
I will look into this very soon. Thanks for letting me know, quite crucial functionality. I haven't seen this happen to me personally though, but I don't use presets that much.

**Comment by bhushan-n** [comment]
I would be happy to help, let me know if I can help you recreate the issue.
`[
  {
    "isDefault" : false,
    "name" : "AudioTechnica",
    "id" : "manual",
    "gains" : {
      "global" : -5.8,
      "bands" : [
        5.1,
        1.5,
        -2.0,
        2.0,
        0.9,
        0.8,
        -0.7,
        -1.4,
        -1.1,
        -15.9
      ]
    }
  }
]`
This was the JSON i was trying to import.

**Comment by inkubux** [comment]
Same issue here I cannot import

**Comment by saltycr2** [comment]
bump

**Comment by nodeful** [comment]
Moving this discussion to #232
