### ISSUE TITLE
"eqMac Beta v0.0.1" is marked as 'Latest Release' instead of 'Prerelease"

### ISSUE THREAD

**Issue by core-code** [bitgapp/eqMac#202]
"eqMac Beta v0.0.1" is marked as 'Latest Release' instead of 'Prerelease" in the GitHub Release Page

**Comment by nodeful** [comment]
That's fine

**Comment by core-code** [comment]
just FYI:
incorrectly marked releases like this incur a significant overhead e.g. at Homebrew Cask who enable a 'brew cask install eqmac' for the convenience of your users.

**Comment by nodeful** [comment]
I need to redo the brew cask anyway, Even though the new eqMac is still in beta I'd rather people use that over the 3 year old one that is fully deprecated at this point. I will fix the cask over the next few days.

**Comment by core-code** [comment]
ok thanks.
