### ISSUE TITLE
Consumes a lot of RAM

### ISSUE THREAD

**Issue by Samplik** [bitgapp/eqMac#203]
Program Consumes ~396 mb Ram. This is too much for a similar program. Here is screen: https://prnt.sc/rwii7c

**Comment by caverym** [comment]
I'd say be patient and wait it out until the rewrite obviously stated in the readme

**Comment by nodeful** [comment]
Thanks for making me aware of this :) I'm spoiled with a very powerful Mac. I can definitely make it more like 100MB at most. Will try to push an update this weekend

**Comment by ddrt** [comment]
Mine is using 100mb and I've been going crazy with settings. Never breached 100mb…

**Comment by nodeful** [comment]
Moving this discussion to #229
