### ISSUE TITLE
eqmac beta: add usability precision improvements

### ISSUE THREAD

**Issue by mmoole** [bitgapp/eqMac#204]
Dear nodeful,

great to see the new version of eqMac alive! I am totally excited! Now I am in the re-making of my presets...
I suggest those tiny features:
* in Advanced Equalizer: press <kbd>shift</kbd> + <kbd>↑</kbd> or <kbd>shift</kbd>+<kbd>↓</kbd> to change volume for a selected band in very small steps to allow precise setting
-> that would allow for better setting - right now using the mouse it goes from 0 straight to 1.4dB, that is to much.
   * an alternative could be to click-hold the slider and then press <kbd>↑</kbd> or <kbd>↓</kbd>
   * another alternative could be to click and hold down <kbd>alt</kbd> while changing volume for a band
* in Basic Equalizer: click&hold knob + <kbd>shift</kbd> then move mouse vertically to precisely set volume in 0.1 increments. The smallest increment I could get was from 0 to 1.0db, but I mostly 'lost the grip' when turning the knob even with very small movements.

Being able to very precisely set the volume of the EQ bands would allow us for more precise sound settings an thus use eqMac to its full potential 👍👍

**Comment by nodeful** [comment]
I was planning to give ability to click on the value screen:
![image](https://user-images.githubusercontent.com/8472525/79019198-b239b700-7b6d-11ea-8852-782a62831ee2.png)
And that would turn it into a input field, where you can enter your desired value manually. 
This is the easiest in terms of development, I can maybe push that this weekend 😄 
Would that be enough in terms of UX?

**Comment by mmoole** [comment]
entering the value directly would be the most precise way I would say 👍. It would take some tries in order to reach the optimal value for each band, but if it's the fastest to implement, please just include that `.` and `,` be treated as decimal marker for us non-imperial keyboard users 😀

**Comment by nodeful** [comment]
Closing in favour of #233
