### ISSUE TITLE
Feature: Allow hosting 3rd party AU Units through eqMac audio pipeline

### ISSUE THREAD

**Issue by mmoole** [bitgapp/eqMac#205]
this is more of a roadmap idea than a short term feature:

Instead of doing all sound processing with eqMac itself, why not have a plugins chain and let existing audio plugins do the processing work..:
* would be an additional module besides 'Basic Equalizer' and 'Advanced Equalizer'
* look could be inspired a bit by the old free [Acon Effect Chainer](https://acondigital.com/docs/EffectChainer10us.pdf): 
   ![grafik](https://user-images.githubusercontent.com/678765/79040059-244de280-7be6-11ea-8076-873bbd7a490a.png)
* first allow for including AU plugins
* then in extension maybe also include VST plugins support
* save presets of chains (would include settings of plugins)
* that would allow users to use their existing plugins they are familiar with
* spend not too much ressources of eqMac development on specific audio processing stuff that plugins maybe already handle
* allow pro users to use their purchased plugins all day long for playback etc...
* if a processing delay occurs, then calculate and display it in a status bar so that playback settings can be manually adjusted

**Comment by nodeful** [comment]
This has now been implemented in v1.7
