### ISSUE TITLE
Nothing happens after running eqMac

### ISSUE THREAD

**Issue by smolendawid** [bitgapp/eqMac#206]
When I click on the application, nothing happens. When I click a few times one-by-one when I'm angry, I can see such a window, that disappears in a second:
<img width="616" alt="Zrzut ekranu 2020-04-13 o 21 49 14" src="https://user-images.githubusercontent.com/9264154/79155144-fe386600-7dd0-11ea-8c1f-ec61cdc81b4d.png">

**Comment by nodeful** [comment]
I suspect that could be happening when you don't have an internet connection. 
Could it be the case you are offline when trying to use eqMac?

**Comment by jonahJS** [comment]
Yup that happens to me as well. Stopped working after the first day. Please advise! Fresh re-install, rebooted laptop, did the whole thing.

**Comment by nodeful** [comment]
I can't rely on just air. I need more information

**Comment by smolendawid** [comment]
macOS Catalina 10.15.4 (19E287), I don't know what more I can say. It was working, it's not working anymore. 
<img width="232" alt="Zrzut ekranu 2020-04-20 o 21 42 30" src="https://user-images.githubusercontent.com/9264154/79792864-ed976b00-834f-11ea-9a5c-cbaade2c1adc.png">
As far as I understand the driver is installed.

**Comment by cesalt14** [comment]
Same problem with my Macbook as well.

**Comment by cesalt14** [comment]
Downloaded it and it worked fine until I deleted the application, went to redownload and this problem happened. I've tried over and over again too. Loads a window as pictured above for a second then disappears.

**Comment by nodeful** [comment]
![image](https://user-images.githubusercontent.com/8472525/80261133-7cbebe80-8681-11ea-8ba2-ff381218a74f.png)
Are you guys aware you need to click on the eqMac icon on the top to open the app?

**Comment by cesalt14** [comment]
there is no icon

**Comment by nodeful** [comment]
@cesalt14 for you I imagine it's related for either #223 or #236 I would need crash logs to know for sure.

**Comment by nodeful** [comment]
@smolendawid I would need more information like macOS version and any logs. Please file a new Issue and follow the Bug report template.
Closing for now until I get more info
