### ISSUE TITLE
Can't download app from the web

### ISSUE THREAD

**Issue by kyxap** [bitgapp/eqMac#207]
On mac I've tried: firefox, chrome, safari and nothing happens when I click Download button on the website (https://eqmac.app/)

![image](https://user-images.githubusercontent.com/3080529/79156471-ceb13b80-7d87-11ea-97c9-fb793ae31039.png)

**Comment by nodeful** [comment]
This should have been resolved by now, but I will make sure to hardcode a fallback within the website instead of fully relying in GitHub API.
