### ISSUE TITLE
When launching eqmac, nothing "happens" except there is no sound anymore

### ISSUE THREAD

**Issue by francoisBouchet** [bitgapp/eqMac#208]
It's been a couple of days, I don't know why, but eqmac is not "launching" anymore. After launching the app: 

1. I can't see the icon on the Dock
2. I can't see the mini-icon in the top-right corner of the mac-display (systray ?)
3. sometimes the sound is disabled >> I can see the eqmac audio-profile selected in the sound settings, but if I want to hear the audio again, I'm forced to go back directly with the native audio-out of my Imac (écouteurs)

I'm on Mac OSX Mojave 10.14.6
I have an imac 17,1 (27" core i7 4ghz)

====
Console log : 
par défaut	14:35:43.377614 +0200	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : eqMac
par défaut	14:35:43.450446 +0200	launchservicesd	CHECKIN:0x0-0x50050 915 com.bitgapp.eqmac
par défaut	14:35:43.451681 +0200	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : eqMac
par défaut	14:35:43.469923 +0200	eqMac	Current system appearance, (HLTB: 1), (SLS: 0)
par défaut	14:35:43.472321 +0200	eqMac	Post-registration system appearance: (HLTB: 1)
par défaut	14:35:43.476138 +0200	distnoted	register name: com.apple.xctest.FakeForceTouchDevice object: com.bitgapp.eqmac token: f4263 pid: 915
par défaut	14:35:43.480392 +0200	eqMac	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600001d35bd0
 (
    "<NSAquaAppearance: 0x600002b32bc0>",
    "<NSSystemAppearance: 0x600002b32d00>"
)>
par défaut	14:35:43.504503 +0200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier com.bitgapp.eqmac, type: 0: 0x7fe9fd905d40 at /Applications/eqMac.app
par défaut	14:35:43.517848 +0200	eqMac	Sentry Started -- Version: 4.4.0
par défaut	14:35:43.525944 +0200	eqMac	Task <C434AFC6-18AE-49C3-A1E9-D610D88E403A>.<1> resuming, QOS(0x19)
par défaut	14:35:43.527491 +0200	eqMac	Task <C434AFC6-18AE-49C3-A1E9-D610D88E403A>.<1> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
par défaut	14:35:43.528050 +0200	eqMac	Task <D63E2981-A92C-4D57-8083-7BAFF4AA2C41>.<2> resuming, QOS(0x19)
par défaut	14:35:43.528505 +0200	eqMac	TIC Enabling TLS [1:0x600000b3d380]
par défaut	14:35:43.528679 +0200	eqMac	TIC TCP Conn Start [1:0x600000b3d380]
par défaut	14:35:43.529105 +0200	eqMac	[C1 Hostname#a3bda9b4:443 tcp, url hash: 9b9dde0d, tls] start
par défaut	14:35:43.529765 +0200	eqMac	nw_connection_report_state_with_handler_locked [C1] reporting state preparing
par défaut	14:35:43.530123 +0200	eqMac	Task <107112F6-15E9-4EBD-BFD5-4E0AF09B522A>.<3> resuming, QOS(0x19)
par défaut	14:35:43.530408 +0200	eqMac	Task <C434AFC6-18AE-49C3-A1E9-D610D88E403A>.<1> setting up Connection 1
par défaut	14:35:43.530512 +0200	eqMac	Task <D63E2981-A92C-4D57-8083-7BAFF4AA2C41>.<2> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
par défaut	14:35:43.530566 +0200	eqMac	Task <107112F6-15E9-4EBD-BFD5-4E0AF09B522A>.<3> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
par défaut	14:35:43.566203 +0200	eqMac	  no saved enable hardware sample rate converter preference found
par défaut	14:35:43.578244 +0200	eqMac	HALDefaultDevice.cpp:780:SetData:  HALDefaultDeviceProperty::SetData:kAudioHardwarePropertyDefaultOutputDevice  to EQMDevice (Object: 61)
erreur	14:35:43.680099 +0200	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: com.bitgapp.eqmac, PID[915], auid: 501, euid: 501, binary path: '/Applications/eqMac.app/Contents/MacOS/eqMac'}, REQ:{ID: com.apple.appleeventsd, PID[50], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}
par défaut	14:35:43.728248 +0200	eqMac	nw_socket_handle_socket_event [C1.1:3] Socket received CONNECTED event
par défaut	14:35:43.728364 +0200	eqMac	nw_endpoint_flow_protocol_connected [C1.1 IPv4#c800f0bb:443 in_progress socket-flow (satisfied)] Transport protocol connected
par défaut	14:35:43.729729 +0200	eqMac	TIC TLS Event [1:0x600000b3d380]: 1, Pending(0)
par défaut	14:35:43.862818 +0200	eqMac	TIC TLS Event [1:0x600000b3d380]: 11, Pending(0)
par défaut	14:35:43.862926 +0200	eqMac	TIC TLS Event [1:0x600000b3d380]: 14, Pending(0)
par défaut	14:35:43.871339 +0200	eqMac	UNIX error exception: 17
par défaut	14:35:43.876306 +0200	eqMac	UNIX error exception: 17
par défaut	14:35:43.879133 +0200	eqMac	UNIX error exception: 17
par défaut	14:35:43.882103 +0200	eqMac	System Trust Evaluation yielded status(0)
par défaut	14:35:43.884139 +0200	eqMac	TIC TLS Trust Result [1:0x600000b3d380]: 0
par défaut	14:35:43.884702 +0200	eqMac	TIC TLS Event [1:0x600000b3d380]: 2, Pending(0)
par défaut	14:35:44.015087 +0200	eqMac	nw_endpoint_flow_protocol_connected [C1.1 IPv4#c800f0bb:443 in_progress socket-flow (satisfied)] Output protocol connected
par défaut	14:35:44.015160 +0200	eqMac	nw_connection_report_state_with_handler_locked [C1] reporting state ready
par défaut	14:35:44.015454 +0200	eqMac	TIC TLS Event [1:0x600000b3d380]: 20, Pending(0)
par défaut	14:35:44.015482 +0200	eqMac	TIC TCP Conn Connected [1:0x600000b3d380]: Err(16)
par défaut	14:35:44.015629 +0200	eqMac	TIC TCP Conn Event [1:0x600000b3d380]: 1
par défaut	14:35:44.015643 +0200	eqMac	TIC TCP Conn Event [1:0x600000b3d380]: 8
par défaut	14:35:44.015653 +0200	eqMac	TIC TLS Handshake Complete [1:0x600000b3d380]
par défaut	14:35:44.015822 +0200	eqMac	Task <C434AFC6-18AE-49C3-A1E9-D610D88E403A>.<1> now using Connection 1
par défaut	14:35:44.015941 +0200	eqMac	nw_endpoint_flow_protocol_connected [C1.1 IPv4#c800f0bb:443 ready socket-flow (satisfied)] Output protocol connected
par défaut	14:35:44.017392 +0200	eqMac	TIC Enabling TLS [2:0x600000b3c180]
par défaut	14:35:44.017421 +0200	eqMac	TIC TCP Conn Start [2:0x600000b3c180]
par défaut	14:35:44.017491 +0200	eqMac	[C2 Hostname#a3bda9b4:443 tcp, url hash: 9b9dde0d, tls] start
par défaut	14:35:44.017693 +0200	eqMac	nw_connection_report_state_with_handler_locked [C2] reporting state preparing
par défaut	14:35:44.018202 +0200	eqMac	Task <D63E2981-A92C-4D57-8083-7BAFF4AA2C41>.<2> setting up Connection 2
par défaut	14:35:44.018279 +0200	eqMac	TIC Enabling TLS [3:0x600000b3e1c0]
par défaut	14:35:44.018306 +0200	eqMac	TIC TCP Conn Start [3:0x600000b3e1c0]
par défaut	14:35:44.018367 +0200	eqMac	[C3 Hostname#a3bda9b4:443 tcp, url hash: 9b9dde0d, tls] start
par défaut	14:35:44.018703 +0200	eqMac	nw_connection_report_state_with_handler_locked [C3] reporting state preparing
par défaut	14:35:44.019275 +0200	eqMac	Task <107112F6-15E9-4EBD-BFD5-4E0AF09B522A>.<3> setting up Connection 3
par défaut	14:35:44.019373 +0200	eqMac	Task <C434AFC6-18AE-49C3-A1E9-D610D88E403A>.<1> sent request, body S
par défaut	14:35:44.132975 +0200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier com.bitgapp.eqmac, type: 0: 0x7facfd625580 at /Applications/eqMac.app
par défaut	14:35:44.178233 +0200	eqMac	nw_socket_handle_socket_event [C2.1:3] Socket received CONNECTED event
par défaut	14:35:44.178311 +0200	eqMac	nw_endpoint_flow_protocol_connected [C2.1 IPv4#c800f0bb:443 in_progress socket-flow (satisfied)] Transport protocol connected
par défaut	14:35:44.179212 +0200	eqMac	nw_socket_handle_socket_event [C3.1:3] Socket received CONNECTED event
par défaut	14:35:44.179283 +0200	eqMac	nw_endpoint_flow_protocol_connected [C3.1 IPv4#c800f0bb:443 in_progress socket-flow (satisfied)] Transport protocol connected
par défaut	14:35:44.180544 +0200	eqMac	TIC TLS Event [2:0x600000b3c180]: 1, Pending(0)
par défaut	14:35:44.180967 +0200	eqMac	TIC TLS Event [3:0x600000b3e1c0]: 1, Pending(0)
erreur	14:35:44.185877 +0200	eqMac	AVAEInternal.h:70:_AVAE_Check: required condition is false: [AVAudioIONodeImpl.mm:911:SetOutputFormat: (format.sampleRate == hwFormat.sampleRate)]
erreur	14:35:44.192688 +0200	eqMac	An uncaught exception was raised
erreur	14:35:44.192712 +0200	eqMac	<private>
erreur	14:35:44.192744 +0200	eqMac	<private>
par défaut	14:35:44.192864 +0200	eqMac	*** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: format.sampleRate == hwFormat.sampleRate'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff357f7acd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff5fedaa17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff358127e6 +[NSException raise:format:arguments:] + 98
	3   AVFAudio                            0x00007fff31942304 _Z19AVAE_RaiseExceptionP8NSStringz + 156
	4   AVFAudio                            0x00007fff3191df9f _Z11_AVAE_CheckPKciS0_S0_b + 295
	5   AVFAudio                            0x00007fff31993b41 _ZN17AVAudioIONodeImpl15SetOutputFormatEmP13AVAudioFormat + 349
	6   AVFAudio                            0x00007fff31974f58 _ZN18AVAudioEngineGraph8_ConnectEP19AVAudioNodeImplBaseS1_jjP13AVAudioFormat + 1670
	7   AVFAudio                            0x00007fff3199b4bd _ZN17AVAudioEngineImpl7Conn<…>
par défaut	14:35:44.199284 +0200	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:eqMac, _appTrackingState = 2
par défaut	14:35:44.655115 +0200	ReportCrash	Saved crash report for eqMac[915] version v0.0.1 (0.0.1) to eqMac_2020-04-14-143544_iMac-de-Francois.crash

**Comment by nodeful** [comment]
![image](https://user-images.githubusercontent.com/8472525/79226536-78f79480-7e56-11ea-89b1-44d396512fdd.png)
from this I can assume something went wrong with eqMac driver sample rate. Open your `Audio MIDI Setup.app` and make sure the eqMac device Sample rate matches the device you're trying to output the audio to. 
Eventually I need to do this check programmatically from within eqMac

**Comment by francoisBouchet** [comment]
here my Speaker output:
<img width="741" alt="Capture d’écran 2020-04-14 à 16 15 38" src="https://user-images.githubusercontent.com/36815410/79234967-4c9a4300-7e6b-11ea-8f74-e6d3243ea68a.png">

here my eqmac input:
<img width="742" alt="Capture d’écran 2020-04-14 à 16 15 21" src="https://user-images.githubusercontent.com/36815410/79235059-689de480-7e6b-11ea-935f-181bc23dbe0b.png">

here my eqmac output:
<img width="742" alt="Capture d’écran 2020-04-14 à 16 15 30" src="https://user-images.githubusercontent.com/36815410/79235084-6fc4f280-7e6b-11ea-8194-0b9c438781b8.png">

**Comment by francoisBouchet** [comment]
... and eqmac is launching again! thank you very much!

**Comment by nodeful** [comment]
Reopening so other people can see the workaround for now!

**Comment by iqovoid** [comment]
Unfortunately it doesnt work for me :/

**Comment by nodeful** [comment]
set the input of eqMac to 44.1kHz

**Comment by iqovoid** [comment]
Oh, really sorry, i was thinking that i should set it the same as my headphones, thank you, it works.

**Comment by PaulMcAdam** [comment]
Setting everything to match and to be 44.1Khz works and allows eqMac to start but it also introduces the 'crackling bug' after about 20 minutes of playing. For me the fix for that was to set everything to 48KHz but that is no longer possible as then eqMac won't start.

This on Mojave 10.14.6

**Comment by nodeful** [comment]
Please reference issue #223 from now on.
