### ISSUE TITLE
Launching eqMac, no response, no audio.

### ISSUE THREAD

**Issue by iqovoid** [bitgapp/eqMac#209]
Mac OS Catalina
2020-04-15 01:11:02.891 eqMac[969:23029] Sentry Started -- Version: 4.4.0
2020-04-15 01:11:03.528 eqMac[969:23029] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: format.sampleRate == hwFormat.sampleRate'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff31569d07 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6a0f45bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff31592ec8 +[NSException raise:format:arguments:] + 88
	3   AVFAudio                            0x00007fff2cf18aa7 _Z19AVAE_RaiseExceptionP8NSStringz + 156
	4   AVFAudio                            0x00007fff2cf189be _Z11_AVAE_CheckPKciS0_S0_b + 326
	5   AVFAudio                            0x00007fff2cf95b79 _ZN17AVAudioIONodeImpl15SetOutputFormatEmP13AVAudioFormat + 387
	6   AVFAudio                            0x00007fff2cf83601 _ZN18AVAudioEngineGraph8_ConnectEP19AVAudioNodeImplBaseS1_jjP13AVAudioFormat + 2665
	7   AVFAudio                            0x00007fff2cfa04ef _ZN17AVAudioEngineImpl7ConnectEP11AVAudioNodeS1_mmP13AVAudioFormat + 589
	8   AVFAudio                            0x00007fff2cf9b6fb -[AVAudioEngine connect:to:format:] + 142
	9   eqMac                               0x000000010dc04b38 eqMac + 52024
	10  eqMac                               0x000000010dc04161 eqMac + 49505
	11  eqMac                               0x000000010dbff764 eqMac + 30564
	12  eqMac                               0x000000010dc3616c eqMac + 254316
	13  eqMac                               0x000000010dc3607a eqMac + 254074
	14  eqMac                               0x000000010dbff5e9 eqMac + 30185
	15  eqMac                               0x000000010dc0104d eqMac + 36941
	16  eqMac                               0x000000010dc1992e eqMac + 137518
	17  eqMac                               0x000000010dc199d1 eqMac + 137681
	18  eqMac                               0x000000010dc19660 eqMac + 136800
	19  libdispatch.dylib                   0x00007fff6b242658 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x00007fff6b244818 _dispatch_continuation_pop + 414
	21  libdispatch.dylib                   0x00007fff6b2544be _dispatch_source_invoke + 2084
	22  libdispatch.dylib                   0x00007fff6b24db6d _dispatch_main_queue_callback_4CF + 618
	23  CoreFoundation                      0x00007fff3152d041 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	24  CoreFoundation                      0x00007fff314ece47 __CFRunLoopRun + 2028
	25  CoreFoundation                      0x00007fff314ebffe CFRunLoopRunSpecific + 462
	26  HIToolbox                           0x00007fff3011fabd RunCurrentEventLoopInMode + 292
	27  HIToolbox                           0x00007fff3011f7d5 ReceiveNextEventCommon + 584
	28  HIToolbox                           0x00007fff3011f579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	29  AppKit                              0x00007fff2e76ac99 _DPSNextEvent + 883
	30  AppKit                              0x00007fff2e7694e0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
	31  AppKit                              0x00007fff2e75b1ee -[NSApplication run] + 658
	32  AppKit                              0x00007fff2e72cff6 NSApplicationMain + 777
	33  eqMac                               0x000000010dbfad59 eqMac + 11609
	34  libdyld.dylib                       0x00007fff6b29bcc9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by nodeful** [comment]
Workaround: #208

**Comment by iqovoid** [comment]
Unfortunately it doesnt work for me :/
