### ISSUE TITLE
eqMac sound distortion and other bugs

### ISSUE THREAD

**Issue by MariuzM** [bitgapp/eqMac#210]
I've noticed couple of bugs running the beta

- From time to time sound start to be distorted 
- Example: when i start watching Youtube (on Chrome) the hole video is just frozen but sound is still coming, clicking on time line bar it jumps to that place with new image but still frozen and does not move, but again sound is still coming. 

For both of these to be fixed i had to close the eqMac but opening again no issues, until next time. 

MacOS - Mojave

**Comment by jkeller13** [comment]
^ same sound distortion issue. Seems like it starts after ~5 mins and get crackling. Restart app and it works great for another 5 mins or so.

**Comment by nodeful** [comment]
Moving discussion and tracking of this issue to #224

**Comment by ninjit** [comment]
Is there another issue open for the video freeze problem?
I just noticed the same problem – any video player in a chromium-based browser (Chrome, Safari, Opera) would freeze while eqmac is running – firefox seems to be unaffected.
Quitting eqmac fixes the problem
