### ISSUE TITLE
Audio delay/latency issue

### ISSUE THREAD

**Issue by northamerican** [bitgapp/eqMac#212]
With eqMac enabled, an audio delay forms and gets longer and more noticeable the longer it runs.
After about an hour it becomes unmistakable. If I leave eqMac enabled overnight, it's a several second delay. 

This happens with eqMac enabled and an HDMI output source on Catalina. 

The same issue would happen with SoundFlower which I had tried using years back to have keyboard audio control of HDMI devices (my TV).

Switching the source to Internal Speakers, then back to eqMac resolves the delay temporarily.

**Comment by northamerican** [comment]
possibly related:

https://arstechnica.com/civis/viewtopic.php?f=19&t=1289815
https://github.com/SakuraG/soundflower/issues/43

**Comment by nodeful** [comment]
I'm moving the discussion around this issue to #225
