### ISSUE TITLE
eqMac v0.0.1 UI v0.0.3 crashes consistently on Mac

### ISSUE THREAD

**Issue by t0mn** [bitgapp/eqMac#215]
Using eMac 0.0.3 with bluetooth earpods on Mac Catalina - works fine.  But if the earpods are reassigned to another device (i.e. select them for use on a phone) eqMac crashes - quite consistently.  It should recognise this and revert to internal speakers on Mac.  Crash dump is attached.
[eqMac crash dump.pdf](https://github.com/bitgapp/eqMac/files/4490921/eqMac.crash.dump.pdf)

**Comment by nadstaky** [comment]
Hello,
Ain't you wrong with the eqMac version ? As far I as know, the latest version is 0.0.1

**Comment by t0mn** [comment]
Yes you are correct - UI is v0.0.3, app is 0.0.1.

**Comment by nodeful** [comment]
Moving the discussion of this issue to #227
