### ISSUE TITLE
eqMac v0.0.1 UI not loading

### ISSUE THREAD

**Issue by robinsonleiu** [bitgapp/eqMac#218]
Can anyone help me with this issue? It's working for quite some time but out of sudden the UI doesn't work anymore which I can't change the profile.

Audio working fine with eqMac v0.0.1.

![Screenshot 2020-04-19 at 5 31 26 PM](https://user-images.githubusercontent.com/18711458/79684402-9c11b200-8263-11ea-95ed-6aefdc0fec42.png)

**Comment by robinsonleiu** [comment]
Apparently is the cert issue to the UI with the url: https://ui-v000.eqmac.app/
![image](https://user-images.githubusercontent.com/18711458/79684953-c4031480-8267-11ea-8450-0fba91862c97.png)

**Comment by nodeful** [comment]
Yeah sorry made a mistake debugging the UI
