### ISSUE TITLE
The new eqMac has an icon in the Dock

### ISSUE THREAD

**Issue by Jaaap** [bitgapp/eqMac#219]
Unlike the previous eqMac, the new one has an icon on the macOS Dock.
This takes up a lot of space that i'd rather use for other apps.

Is it possible to remove the Dock icon?

macOS Catalina 10.15.4

**Comment by nodeful** [comment]
![Uploading image.png…]()

**Comment by nodeful** [comment]
![image](https://user-images.githubusercontent.com/8472525/79690005-29e3a200-8250-11ea-8377-b578dd4847dd.png)

**Comment by nodeful** [comment]
There are settings for this. Explore the app first before creating issues and wasting both of our time

**Comment by Jaaap** [comment]
Oh you're right.
Sorry about that.
