### ISSUE TITLE
Bug: Bluetooth/Wireless devices sometimes go into Headset mode which lowers audio quality or produces no audio outright

### ISSUE THREAD

**Issue by nodeful** [bitgapp/eqMac#226]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
This is a very annoying bug I came across many times. 
Mostly due to Apple's handling of Bluetooth device connectivity and timing issues the device sometimes goes into headset mode where it transmits the microphone audio and sound over a low quality stream...
Sometimes it's also caused by eqMac switching between devices too quickly and trying to playback audio too early. 

Possibly also reported in #107 

**Steps to Reproduce**
Can't precisely reproduce the issue, but you can sort of simulate it if you select the bluetooth device to be the default Input device in System preferences.

**Expected behaviour**
eqMac should work around the issue either by waiting for device to be in the correct state, or forcefully putting it in the correct state. But forcing the device might go against users preferences. What if they want to run the bluetooth device in headset mode? 😕 

**Setup information:**
 - Audio device used for playback: Any bluetooth device with microphone.
 - Audio transmission interface: Bluetooth and probably AirPlay
 - macOS Version: Most likely all versions of eqMac

**Comment by Rastafabisch** [comment]
[Yepp](https://github.com/bitgapp/eqMac/issues/162). As you already suspected AirPlay is affected as well.

**Comment by nodeful** [comment]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/8472525/190491677-af1d47d1-a0b9-4b38-b6ea-9cbddcd7dd14.png">
There's now a Force Built-In Microphone option in Output Settings in v1.6.2 and it should mitigate the issue.
