### ISSUE TITLE
Refactoring: Improve RAM/CPU usage

### ISSUE THREAD

**Issue by nodeful** [bitgapp/eqMac#229]
**Description:**

Requested in #203 #148 #113

Currently eqMac is using:
RAM:
- ~100MB of RAM for Audio Processing 
- ~150MB of RAM for for UI Rendering
- ~50MB for UI offline cache
- ~30MB for Network activity

CPU: 
- 2-3% for Audio Processing
- ~1% for other stuff

Battery:
Here's how it stands compared to other apps:
![image](https://user-images.githubusercontent.com/8472525/79701253-85834f00-8293-11ea-8f5f-a79f182fb575.png)

Probably not much to be gained on the CPU side, unless one with lower level language implementation like C++, but I'm not doing that 😄Maybe somehow de-rendering the UI, but I think that should be handled by the OS.

In terms of RAM:
UI offline caching can go out of RAM completely once I move away from using Service Workers.
UI Rendering can probably be cut in 2 at least.
Not sure why there's so much network activity RAM usage, only collecting anonymous Analytics data at the moment.
Audio processing can probably be cut down in 2 as well.

Battery:
Not sure how much can be done there, I guess would need to see how other improvements/fixes will improve this metric.

**Comment by nodeful** [comment]
![image](https://user-images.githubusercontent.com/8472525/80503910-6b6bff80-896a-11ea-96ae-205a8aa96337.png)
I have release a new update v0.1.0 where I substantially improved RAM usage
So I'm considering this issue solved. Please reopen thee issue if you feel like there can still be improvements made. 
Thanks

**Comment by GumbyTheGreen1** [comment]
eqMac plus audiocored are using close to 5% of my CPU at all times _when idle_ - even when I have no other apps open! Why would it need to use so much when it's not doing anything? This is unacceptable and makes me think I probably shouldn't be using this app at all. I'd really like to be able to keep using it though. Is there anything that can be done about this? There's clearly a problem somewhere.
![eqMac CPU Usage When Idle](https://user-images.githubusercontent.com/64051699/82739859-ac083000-9d00-11ea-8d51-c72139bf6c92.png)

**Comment by ashinlaurel** [comment]
![image](https://user-images.githubusercontent.com/44382446/153222995-c64042a4-4bf0-4a55-97c7-721c30c3cf02.png)
This is the energy impact I'm facing. I'm using Monterey Version: 12.2. Hope there is some solution to reduce the battery drain.
