### ISSUE TITLE
Feature: Save different profiles per device, optionally when that device connects, switch to a preferred profile.

### ISSUE THREAD

**Issue by nodeful** [bitgapp/eqMac#231]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
Requested if #171 #165 #67

Most people will have different settings depending on the audio device they are currently using.
Would be awesome for eqMac to automatically switch to the preferred profile.

**User flow & interface:**
A couple of questions to consider:
- Which "effects"/settings would be saved for each profile? (Volume, Balance, EQ) and what about future effects?
- How would the UI looks like? eqMac currently has quite compact UI, would have to hide all of this profile setting menu behind modals, unless the to be expanded.

**Comment by Intenditore** [comment]
> Which "effects"/settings would be saved for each profile? 
I think all of them, but the volume level must not be treated as a part of preset so user would have no need to change it every time to his linking. Standard system-like behaviour it needed. This also will fix to #248 248

> How would the UI looks like? 
I think current one if lovely. A drop-out with devices (which is there but doesn't work as a menu) will be handy enough. 

But let me note one more interface suggestion - it would be much better if the interface will be a kind of fly-out menu dropping out of the icon, in iStats Menu style. Also this will solve the confusion with the X button which quits the app (another dedicated button for killing the process would be needed than though).
Taking different approach, you could save the current UI as a window, but adding a fast preset/device switching to icon drop-out menu. 

Thank you for your work once again! Waiting for the automatic preset switching passionately, I hope it'll be there soon (even if paid upgrade)

**Comment by mvdam** [comment]
It would also be nice if the presents have unique names. In my case I used the same name for different presets and you cannot tell which is what.

![Screenshot 2020-05-04 at 12 54 18](https://user-images.githubusercontent.com/21951794/80959157-82956c00-8e06-11ea-9515-9516b327078a.png)

BTW I really like the app!

**Comment by alexandrerochasalles** [comment]
> > Which "effects"/settings would be saved for each profile?
> 
> I think all of them but the volume, it's level must not be treated as a part of preset so user would have no need to change it every time to his linking. Standard system-like behaviour it needed. This also will fix #248
> 
> > How would the UI looks like?
> 
> I think current one if lovely. A drop-out with devices (which is there but doesn't work as a menu) will be handy enough.
> 
> But let me note one more interface suggestion - it would be much better if the interface will be a kind of fly-out menu dropping out of the icon, iStats Menu style. Also this will solve the confusion with the X button which quits the app (another dedicated button for killing the process would be needed than though).
> Taking different approach, you could save the current UI as a window, but adding a fast preset/device switching to icon drop-out menu.
> 
> Thank you for your work once again! Waiting for the automatic preset switching passionately, I hope it'll be there soon (even if paid upgrade)


Great comment Intenditore, you have explained every improvement that I could expect for the app.

1. The fly-out menu dropping out of the icon, instead of the window with the X button.
2. Keeping the volume level on profile changes, but everything else could be saved for the profile.

I think that one issue that I'm having is also related with that topic.
Every time that I turn off my monitor, or take away my MacBook, the eqMac just close itself, making me go to applications reopen it, and select the playback device (monitor).
I'm the only one with that issue??

Congratulations for your great job, the app is just amazing and it's getting even better.

**Comment by coraunderhill** [comment]
> * Which "effects"/settings would be saved for each profile? (Volume, Balance, EQ) and what about future effects?
Volume automatically gets handled by the OS (at least in Catalina), so I feel like balance and EQ would be the notables. 

> * How would the UI looks like? eqMac currently has quite compact UI, would have to hide all of this profile setting menu behind modals, unless the to be expanded.
Not necessarily. It could be as simple as a small checkbox labeled "Remember device settings" nearby the dropdown selector. I would think you could handle checking/unchecking the box appropriately depending on the new device using something like `onChange`

**Comment by Doridian** [comment]
@nodeful Thanks for the great release, I was aondering what you were working on :)

Anyway, how do you assign an EQ to a preset? I have tried creating the preset with my desired EQ set, or setting it while the preset is selected and then clicking save in the dialog.
But my EQ (Expert mode) never changes at all when I swap profiles.
Am I not seeing the right button? Or missing something else?

**Comment by nodeful** [comment]
Sorry @Doridian I missed your question, I replied to a similar question here: https://github.com/bitgapp/eqMac/issues/732
Here's a copy paste:

> I knew this would come up at some point as I agree the User Experience is not the most straight forward with this feature.
> You know how when you have an EQ preset selected and you made a change the presets switches to Manual and you have  to save the preset again if you want those settings to apply to a preset.
> With Super Presets the behaviour is a little different. If you have a Super Preset selected and you make any changes it is 
> instantly saved to the selected preset. So what probably happened in your case is that you created a preset for 1 setup, 
> then instantly started to create a setup for the 2nd preset, but this whole time you were applying the new settings to the 
1st preset.
> What you need to do once you created the first preset is press the "Deselect" button or create a new preset straight away. Only then start applying the settings that you want for the 2nd preset.
> I hope this explains the behaviour, if you have a suggestion on how I can make this better, please let me know, I'm open to  discuss and modify this feature.

I will be closing this issue for house keeping, feel free to comment regardless on this issue or the one I referenced. Thank you for your cooperation and patience!

**Comment by MikixIT** [comment]
I don't understand, is this feature active? I can't find it anywhere.
I want to activate eqMac only on the external monitor.

Can you explain how? Thanks

**Comment by Aghiles97** [comment]
I also want to know the answer

**Comment by Aghiles97** [comment]
> I don't understand, is this feature active? I can't find it anywhere. I want to activate eqMac only on the external monitor.
> 
> Can you explain how? Thanks

I believe I found the solution, you should use Super Preset, create different profiles, say one for you Mac and one for your headphone, then in the equalizer select a different profile for each, say for Mac use the default one, that is flat, and for your headphone use a custom eq, now go switch between audio device output, you will see each time to switch there, it will also switch in the eqMac.
