### ISSUE TITLE
Enhancement: Give users ability to precisely enter a dB value by clicking on the Value Screen

### ISSUE THREAD

**Issue by nodeful** [bitgapp/eqMac#233]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
As requested in #204 #190
Some users want the ability to enter a precise gain value. 

**User flow & interface:**
The easiest way to achieve that is to show a modal when user clicks on the Value Screen. They can enter the desired dB value in the modal input field and apply the setting.

**Comment by ssent1** [comment]
+1 for entering dB values directly.

**Comment by karmarube** [comment]
+1 same. Or add a button to open the folder where my custom presets are saved and I'll manually edit the file (I've looked everywhere for the folder and I can't find it)

**Comment by nodeful** [comment]
Hey everyone, just wanted to mentions that this functionality is available in Expert EQ now, but that is part of the paid Pro plan. Eventually I'll add this to Advanced and Basic EQ's as well so I'm not closing this issue yet, but wanted to let you know that for now it's not on the top of my priority list. Thanks for your patience

**Comment by nodeful** [comment]
This has been implemented for Advanced EQ in UI Version v4.3.0
If you have eqMac version v1.5 or higher and have OTA Updates enabled in the Settings, you can just restart eqMac and see the functionality working.
Will be closing this issue as resolved now.
Thank you for your patience!
