### ISSUE TITLE
Bug: Can not start eqmac after fresh installation

### ISSUE THREAD

**Issue by gobozov** [bitgapp/eqMac#235]
Just installed new eqmac but app is not starting after launch. Macbook pro 16 2019, Catalina 10.15.4. Crash file attached.
[eqMac_2020-04-20-001232_macbook.txt](https://github.com/bitgapp/eqMac/files/4501836/eqMac_2020-04-20-001232_macbook.txt)

**Comment by nodeful** [comment]
You haven't followed existing GitHub templates to file an issue.
