### ISSUE TITLE
Bug: Impossible to adjust volume in app

### ISSUE THREAD

**Issue by mattoa9** [bitgapp/eqMac#237]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Impossible to adjust volume in app

**Steps to Reproduce**
1. Open Eq Mac
2. Set max volume on system with F11-F22 keys
3. Set Volume in-app with sliders or knobs
4. See error, volume doesn't change If i move the slider from 0 to 100%

**Expected behaviour**
When I use wireless headphones I want to set volume between 0% to 100%, but it changes only when I set the slider in the "boost zone". I want to set volume in the 0-100% zone.

**Setup information:**
 - Audio device used for playback: Mi True Wireless 2
 - Audio transmission interface: Bluetooth
 - macOS Version: 10.13.6
 - eqMac Version: 0.0.1
 - eqMac UI Version: 0.0.4

**Comment by nodeful** [comment]
Thanks for taking the effort to follow the Template. I will look into this one of the evenings this week.

**Comment by nodeful** [comment]
I couldn't replicate the issue on my end :(

**Comment by nodeful** [comment]
Closing as haven't had any feedback from the author.
If you feel like this is still an issue feel free to reopen with extra feedback
