### ISSUE TITLE
Gain slider not showing value loaded from preset

### ISSUE THREAD

**Issue by jakobmaul** [bitgapp/eqMac#238]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Gain slider is not set to saved value when loading a preset (it seems to be applied to the audio however).

**Steps to Reproduce**
1. Create a preset and adjust gain
2. save preset
3. change gain to any value (the more extrem the better you'll hear, that the value is applied)
4. load preset

**Expected behaviour**
Gain slider is set to the loaded value.

**Actual behaviour**
The gain slider remains on the value it was before.

**Setup information:**
- OPPO HA-2
- Bluetooth
- mac OS 10.15.4
- UI Version 0.0.4

**Screenshots or Console.app logs**
N/A

**Additional information**

**Comment by jesseleite** [comment]
I just noticed this as well!

**Comment by nodeful** [comment]
Do you mean the Global Gain slider? Or any of the frequency bands? I have noticed it happening only to the Global Gain slider

**Comment by jesseleite** [comment]
Only the global gain slider, the horizontal one.  The frequency bands seem fine to me.

**Comment by nodeful** [comment]
Yeah, that's an easy fix. Expect an update soon

**Comment by nodeful** [comment]
Fixed in 5668c15a2c137517b39b3208cad00577c7c5963b
Pushed a new UI update with version 0.0.5
The UI should update after 2 restarts of eqMac.
Thanks for reporting this.
