### ISSUE TITLE
why on the earth ui is served from internet?!

### ISSUE THREAD

**Issue by aol-nnov** [bitgapp/eqMac#239]
Hello, dear author!

Your program is definitely neat and perform better than competitors in some aspects

BUT

why on the earth ui is served from the internet?! https://ui-v000.eqmac.app (which resolves to cloudflare) and here we go, oh my. I can't say a word, how I'm surprised by that move.

**Comment by nodeful** [comment]
Because i can deploy over the air updates and bug fixes without doing a whole native update.
The UI is cached with service workers so works offline as well. Try to turn your internet off and the website should still load. Also the UI is shipped with the app in case user open eqMac for the first time without internet.

So what's your problem with that?

**Comment by aol-nnov** [comment]
> So what's your problem with that?

Literally, my equalizer is tracking me and uploading (unknown portions of) data to servers. :)

At least, you could make that clear to users, IMHO.

Other than that, I do not have problem with it. Keep it up!

**Comment by nodeful** [comment]
How is it unknown if you can see exactly what I'm sending to Google Analytics here:
[/ui/src/app/services/analytics.service.ts](https://github.com/bitgapp/eqMac/blob/master/ui/src/app/services/analytics.service.ts)
How would a non Web based UI stop me from sending any data back to servers?

**Comment by nodeful** [comment]
Why was this labeled with a bug label @aol-nnov ?

**Comment by nodeful** [comment]
These types of questions should be discusses in our [Discord server](https://discord.gg/BA22ceW). GitHub is for actual problems, not a place to express any random thoughts.

**Comment by aol-nnov** [comment]
> Why was this labeled with a bug label 

Cuz you made some issue templates, obviously! :)

This is a privacy concern, not a feature request.
