### ISSUE TITLE
Bug: "Replace knobs with sliders" checkbox is not saved during app restarts

### ISSUE THREAD

**Issue by aol-nnov** [bitgapp/eqMac#240]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
"Replace knobs with sliders" checkbox is not saved during app restarts

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. launch eqMac
2. Click on settings icon
3. tick the "Replace knobs with sliders" checkbox
4. observe ui change
5. exit app and lauch again
6. observe knobs instead of sliders
7. go to settings and find"Replace knobs with sliders" checkbox unchecked

**Expected behaviour**
ui is started with sliders instead of knobs

**Setup information:**
 - Audio device used for playback: external headphones
 - Audio transmission interface:  3.5mm Jack
 - macOS Version: 10.15.4
 - eqMac Version [e.g. 0.0.1]
 - eqMac UI Version [e.g. 0.0.4]

**Comment by nodeful** [comment]
Thanks for reporting this.
I have looked into it and unfortunately it won't be trivial to fix. I can't fix it in a UI update, I will have to ship the fix in a full native update.
The fix should be shipped in eqMac v0.0.2

**Comment by nodeful** [comment]
That is now fixed in the latest update v0.1.0
Please download it from https://eqmac.app or GitHub or update directly from the App itself.
Closing this issues, if you are still having problems then please reopen. 
Thanks

**Comment by aol-nnov** [comment]
I can confirm, the issue is now resolved.
