### ISSUE TITLE
eq mac on mac catalina

### ISSUE THREAD

**Issue by davelite73** [bitgapp/eqMac#243]
I just installed the new version because I was having problems with my mac not seeing my JBL Pulse 3 bluetooth speaker in the sound preferences and the speaker would only connect for 5 seconds then disconnect.  After uninstalling eqmac the speaker now connects again and is playing fine.  Odd part. when I installed the lastest version of eqmac, the "Output" choice at the bottom of the UI did not identify my JBL Pulse, only internal speaker and another smaller BT speaker that I had connected.. And then the mac os would not let me choose to output to my JBL in sound preferences.. Some weirdness going on and not sure how to proceed other than not to use eqmac as it seems to be the stem of the problem.  Thoughts?

**Comment by nodeful** [comment]
Ignoring because bug report template has not been followed.
