### ISSUE TITLE
Bug: volume eqMac changed after reboot Mac

### ISSUE THREAD

**Issue by erwinxxx** [bitgapp/eqMac#244]
I have my volume at 50% but sometimes after a reboot my volume is lower again. I must turn up my volume again. It don't remember the right setting. The other settings like the self made and saved preset is still the same, only the volume changing sometimes. Can you fix this?

**Comment by bhushan-n** [comment]
After waking up from sleep my Macbook has no audio then when I restart eqMac after quitting audio restores

**Comment by erwinxxx** [comment]
No, I don't have my mac in a sleep modus, I'm closedown it totally. And restart it after I needed it.

**Comment by nodeful** [comment]
Ignoring because Bug issue template has not been followed
