### ISSUE TITLE
Bug: The app worked fine for a minute then the audio slowly became a buzzing/warbling sound that replaced the playing audio

### ISSUE THREAD

**Issue by kesarion** [bitgapp/eqMac#245]
**Disclaimer**
- [x] I have checked for a similar issue and made sure it hasn't been reported before.

**Describe the bug**
The app worked fine for a minute then the audio slowly became buzzing/warbling sound that replaced the playing audio. Restarting the app didn't help. Restarting the Mac didn't help either. It starts out OK, then goes out of sync with a buzzing/warbling sound. At least, it sounds as if it's going out of sync somehow, since the audio slowly fades while the buzzing gets louder.

**Steps to reproduce**
1. Start eqMac
2. Play something with audio
3. Wait a minute

**Expected behaviour**
A clear and crisp sound.

**Setup information**
 - Audio device used for playback: LG display with built in speakers
 - Audio transmission interface: Display Port
 - macOS Version: 10.14.6
 - eqMac Version: 0.0.1

**Additional information**
It was great for about 30 seconds, just what I was looking for, a way to control the volume from the keyboard, since MacOS doesn't allow it for certain devices, the way Windows does. I sure hope this can be fixed.

**Comment by nodeful** [comment]
How is this not a duplicate of #224 ?

**Comment by kesarion** [comment]
@nodeful Reading it in detail, it could be, especially because of that desync/drift behaviour. There are many issues, so I skimmed through the ones I found relevant, I probably missed it because I was looking for more specific terms. If you're already aware of this issue then we can close this one.

**Comment by nodeful** [comment]
Thank you
