### ISSUE TITLE
Bug: volume changed after reboot Mac sometimes

### ISSUE THREAD

**Issue by erwinxxx** [bitgapp/eqMac#246]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
I have my volume at 50% but sometimes after a reboot my volume is lower again. I must turn up my volume again. It don't remember the right setting. The other settings like the self made and saved preset is still the same, only the volume changing sometimes. Can you fix this?

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):

**Expected behaviour**

**Setup information:**

    Audio device used for playback: external headphones
    Audio transmission interface: 3.5mm Jack
    macOS Version: 10.15.4
    eqMac Version [e.g. 0.0.1]
    eqMac UI Version [e.g. 0.0.4]

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by nodeful** [comment]
closing in favour of #248
