### ISSUE TITLE
Enhancement: Improve Volume handling

### ISSUE THREAD

**Issue by nodeful** [bitgapp/eqMac#248]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+enhancement%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are certain your issue is not related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
Users are experiencing volume behaviour inconsistency as mentioned in #111 and #246 
Need to stay as close to native volume behaviour of macOS

**Comment by Intenditore** [comment]
+
Just wanted to open the issue on the same topic. This is worth fixing

**Comment by nodeful** [comment]
This issue should be resolved in [v0.3.1](https://github.com/bitgapp/eqMac/releases/tag/v0.3.1).
Please update the app and let me know if this issue is still relevant. Thank you

**Comment by Intenditore** [comment]
Sorry to say, there are some problems. I updated, it worked ok but than I tried to switch the device (not sure which name there was) and the program halted. Sound became completely off. I started again, it said you need to reinstall the driver. It failed. Than I tried to go to sound settings (as no sound devices show up in menu at all) and Settings app crashed. It does it every time I go to sound settings.
No I'm without speakers at all 🙄
