### ISSUE TITLE
Bug: Graphical userinterface is all messed up in MacOSX-10.12.5

### ISSUE THREAD

**Issue by Snakehater** [bitgapp/eqMac#251]
![image](https://user-images.githubusercontent.com/46170264/80278455-9fd78580-86f6-11ea-85f1-93e4332698ac.png)
First of all you can see knob of bass not rotating around the right axis. Second of all the rest of buttons don't work, you can't change to advanced equalizer nor any other and buttons like select output won't work. The entire GUI seems to not work at all.

EDIT:
I also find all of the three knobs doing the same, not the ones above. Also, uninstalling is not working either as the buttons either is not working or not showing.

**Comment by nodeful** [comment]
If you want this issue to be opened you need to follow Bug report issue template.
