### ISSUE TITLE
Feature: Implement Expert Equalizer with unlimited bands

### ISSUE THREAD

**Issue by nodeful** [bitgapp/eqMac#252]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
The old eqMac2 had 31 Band EQ mode.
The new eqMac needs to have an Expert EQ mode with following features:
 - Unlimited amount of EQ bands
 - Q factor as mentioned here: #167 
 - Spectrum Analyser
 - Interactive adjustments (Dragging, scrolling to widen the bands etc.)

**User flow & interface:**
Most likely the UI will have a Spectrum Analyzer on the top, with the graph also showing your current settings as a bezier curve line.
On the bottom you will be able to add any amount of bands or select a preset to save time with setup.
Something that looks like this, but better:
![image](https://user-images.githubusercontent.com/8472525/80281421-f5b22a80-8702-11ea-9690-3b2ec503b574.png)

This will be a Pro feature that will be paid to support eqMac development and maintainabilty.

**Comment by mmitchellg5** [comment]
Looking forward to this! Take my money!

**Comment by ppamorim** [comment]
Please add support to this, I will love to EQ manually the things!

**Comment by EveryDayISeeMyDream** [comment]
@nodeful Do you have any news on this? Would be great to see a much more fine eq here.

**Comment by nodeful** [comment]
I'm currently balls deep into this feature, sorry for the profanity 😄 
Here's a sneak peak:
https://user-images.githubusercontent.com/8472525/110254093-4f77b800-7f96-11eb-8189-da16f06bcccb.mp4
What do you guys think? Any suggestions?
I'm thinking in the future to make the Window resizable so we can place the Filter controls vertically.
Currently working on integrating https://github.com/jaakkopasanen/AutoEq into this as well.

**Comment by EveryDayISeeMyDream** [comment]
Why does it changes colors when dragging it from low to high frequencies (from red to green and blue)?

For me personally it would be great when I can also adjust the band type (peak or low/high shelf) For this I would make the slider smaller and put a small dropdown behind the frequency.
Also maybe a small "dot" marking the point, where I can drag the band up would be nice. Could appear at hovering over the spectrum.

Making the window bigger for having the band settings vertically would go a bit away from the small tool up to a heavier looking UI. I would keep it as simple as possible with the UI you still have. For better UX the band list could scroll to the band you are graggin up in the spectrum, so that you have your changes more exactly without scrolling the list. Makes more sense, the more bands you set up.

Hope this feedback helps you. For any questions, feel free to ask! :)

**Comment by nodeful** [comment]
@EveryDayISeeMyDream thanks for the message.
The colours are there to distinct the bands from each other and also for aesthetics, might give users the ability to change the colour for every band manually in the future.
In terms of Filter type i.e. Low/High Shelf etc. I do have plans adding those in the future as well, I just haven't figured out the Maths for that yet and I want to push the Expert EQ feature as quick as I can, would take me another couple of weeks to figure this out. I think majority of people will be using just Peaking filters hence why I focused on those first!
I actually had dots on the peaks already, but didn't like the look, although I might consider adding them when you are hovering a specific band, again probably in a subsequent update after I release the main sauce.
In terms of making the UI bigger I didn't say that you would be forced to do that, it would be just an option for people that don't need the compactness. I personally also like the smallest UI possible :)
Yeap, scrolling the UI to the band you're currently adjusting will be there for sure, just haven't come round to implement that yet.

Thanks again for the tips

**Comment by poxin13** [comment]
Looking forward to this, especially if there is a way to import REW filters directly, as mentioned above, that would be killer.

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Expert EQ with Unlimited Bands is implemented, however no support for Low/High Shelf and RAW Import.
I will create two separate issues for those, if I forget within a couple days please create the Issue for me.
Thanks again.

Roman
