### ISSUE TITLE
Bug: Cannot get eqMac started | MacOS 10.14.6

### ISSUE THREAD

**Issue by neonbaer** [bitgapp/eqMac#254]
****
I installed eqMac properly (driver got installed and microphone-usage was checked in Security Preference Pane) but after restarting my Macbook, eqMac didn't start automatically- which I checked in the eqMac settings. I tried starting it manually but it didn't work. When I check activity monitor I can see the app showing up but it disappears after a couple of seconds. I can select eqMac as my output device but there is no sound audible.
I tried to reinstall it a couple of times but the issue remains.

****
1. Go to Applications Folder
2. Open up eqMac
3. App shows up in activity Monitor then disappears
4. App won't open or show icon in Status Bar

****
App opens up and show icon in status bar

****
 - Zoom F8n
 - USB, coreAudio
 - macOS 10.14.6
 - eqMac v0.0.1

**Comment by nodeful** [comment]
As per issue Bug template you need to provide a log from the `Console.app`. From that you will probably figure out that this is related to #223 .
If not then you can post the log here.
Closing until proper information is provided.
