### ISSUE TITLE
Trying to uninstall eqmac removed all audio devices.

### ISSUE THREAD

**Issue by GmbWtv** [bitgapp/eqMac#259]
I installed eqmac but it would always crash after trying to open it up. I did install the drivers it required for the first boot up but the app always crashed so i tried just throwing it in the trash but eqmac still lingered on my audio devices so i installed it again a ran the uninstall_driver.sh found in the apps resources with the terminal. That still didnt do it so i tried running the executable file eqmac under the MacOS and thats when i noticed all my audio devices were gone. If you all have any pointers it'd be much appreciated because im slightly concerned i'll have to do a full reset over a random app i installed. 

![Screenshot 2020-04-29 at 15 59 52](https://user-images.githubusercontent.com/45470911/80611422-7e4a0700-8a32-11ea-9d11-6aa248689e3d.png)

**Comment by GmbWtv** [comment]
After restarting all the devices came back but i'd still like to know how to remove eqmac from my audio devices.

**Comment by HamdanFadh** [comment]
I've same issue with you for new release. You can just run this command in terminal

`sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/ && launchctl kickstart -k system/com.apple.audio.coreaudiod &>/dev/null`

**Comment by nodeful** [comment]
No reason to create an issue on GitHub regarding this. Can be resolved in our Discord: https://discord.eqmac.app

**Comment by nodeful** [comment]
The uninstall script should work just fine as long as you don't have Audio playing, if you did then a restart should help.

**Comment by nodeful** [comment]
Also the answer could be found in the FAQ: https://eqmac.app/faq
