### ISSUE TITLE
Bug: You can't mute with the mute button, only by lowering volume

### ISSUE THREAD

**Issue by mausv** [bitgapp/eqMac#260]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
If you try to mute the audio by the mute button, the audio is still there. You need to lower the volume to get it to mute.

**Steps to Reproduce**
1. Play something.
2. Hit mute (the sound's still there).
3. Lower the volume until you get it to 0.

**Expected behaviour**
The mute button should lower the volume to 0.

**Setup information:**
- macOS 10.15.4
- eqMac 0.1.1

**Comment by nodeful** [comment]
For me the volume mute works as intended. 
The steps to reproduce doesn't really make sense...
What do you mean "Lower the volume until you get it to 0." - when you mute the sounds and then press Volume Up/Down that unmutes, which is the native behaviour of macOS.
The PR you've added is clearly broken as there is no Application.toggleMute() function anymore. You haven't even spent the time to open Xcode to test.

**Comment by psd-coder** [comment]
I have the same behaviour as described in the issue.

```
What do you mean "Lower the volume until you get it to 0." - when you mute the sounds and then press Volume Up/Down that unmutes, which is the native behaviour of macOS.
```
@nodeful The problem is that mute button DO NOT MUTE sound itself. It keeps playing
