### ISSUE TITLE
Bug: Update to latest version 0.1.1 dumped all saved profiles

### ISSUE THREAD

**Issue by larimer** [bitgapp/eqMac#263]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Updating the app to the current version (0.1.1) seems to have dumped all my saved profiles. The only available profile post-update is "Flat."

**Steps to Reproduce**
1. Run the previous version -- I assume it was 0.1.0.
2. Create and save a custom profile.
3. Update the app to version 0.1.1.
4. The saved profile has been disappeared.

**Expected behavior**
The saved profile should survive the update process.

**Setup information:**
 - macOS Version: [e.g. 10.15.4]
 - eqMac Version [e.g. 0.1.1]
 - eqMac UI Version [e.g. 0.1.0]

**Comment by nodeful** [comment]
I couldn't replicate the issue you are describing, all my presets are there the same way as before the update :(

**Comment by nodeful** [comment]
Closing due to stale issue, if anyone is still having issue please post more information and I will reinvestigate.
