### ISSUE TITLE
Bug: Mute does not work when selecting my monitor (Dell U2720Q) as the sound device

### ISSUE THREAD

**Issue by Wysie** [bitgapp/eqMac#264]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When using my MacBook's internal speakers as the device, the Vol Up, Vol Down and Mute buttons on the keyboard all work as intended.

However, when using my monitor as the device, Vol Up and Vol Down works, but Mute does nothing (even though the Mute overlay shows up, sound still keeps playing).

**Expected behaviour**
Volume should get muted/unmuted when the Mute button is pressed.

**Setup information:**
 - Audio device used for playback: Dell U2720Q
 - Audio transmission interface: 3.5mm Jack
 - macOS Version: 10.15.4
 - eqMac Version 0.1.1
 - eqMac UI Version 0.1.0

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by alexandrerochasalles** [comment]
The same occurs to me, when using my monitor as audio playback device.

Setup information:

Audio device used for playback: LG 29WK500-P
Audio transmission interface: 3.5mm Jack
macOS Version: 10.15.4
eqMac Version 0.1.1
eqMac UI Version 0.1.0

**Comment by nodeful** [comment]
Yeah, but without eqMac running it also doesn't work 😄 
So are you expecting eqMac to virtually put the volume to 0?

**Comment by alexandrerochasalles** [comment]
> Yeah, but without eqMac running it also doesn't work 😄
> So are you expecting eqMac to virtually put the volume to 0?

without eqMac running MacBook doesn't control volume at all, but with eqMac it does increase and decrease(even to 0) the volume, but directly thru the mute button it doesn't work.

That's the thing.

**Comment by nodeful** [comment]
Yeah, so it's not a bug, it's a feature request then :) Should be out today

**Comment by nodeful** [comment]
Implemented in release v0.2.0
Please download from [website](https://eqmac.app), [GitHub release](https://github.com/bitgapp/eqMac/releases/tag/v0.2.0) or update from within the app directly :)

**Comment by alexandrerochasalles** [comment]
> Implemented in release v0.2.0
> Please download from [website](https://eqmac.app), [GitHub release](https://github.com/bitgapp/eqMac/releases/tag/v0.2.0) or update from within the app directly :)

Perfectly done!!
And popover mode possibility, dropping out of the icon, instead of the window with the X button is perfect!!

**Comment by Wysie** [comment]
Thank you! Sorry it should be a feature not a big as you have said.
