### ISSUE TITLE
Feature: Adjust Output Sample Rate

### ISSUE THREAD

**Issue by cgatesman** [bitgapp/eqMac#265]
It would be nice to have control over the output sample rate rather than having to open the Audio MIDI Setup app to change it.

**Comment by nodeful** [comment]
I don't feel like it's a useful feature if you can do it through Audio MIDI Setup app. Why put in a lot of work into a feature to cut on just 1 step that 99% of users won't touch. However, I think eqMac would actually crash right now if you try to change sample rate mid playback, so it should handle that. But that's a different issue
