### ISSUE TITLE
Bug: cannot uninstall eqmac2 audio output (MacOS Catalina)

### ISSUE THREAD

**Issue by xdebbie** [bitgapp/eqMac#266]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
App won't open. I suspect there is no support for Catalina, and I cannot remove the eqmac2 audio device output/input no matter what. I have uninstalled and reinstalled multiple times but it does not work. The app crashes on start. How can I remove the audio device output/input directly from the terminal?

**Setup information:**
 - Audio device used for playback: Sony WH-1000XM3
 - Audio transmission interface: 3.5mm jack
 - macOS Version: 10.15.3
 - eqMac Version: 2.2

**Screenshots or Console.app logs**
![Screenshot](https://i.ibb.co/fQ4jggR/Screenshot-2020-05-06-at-14-26-59.png)

**Comment by nodeful** [comment]
https://eqmac.app/faq

**Comment by xdebbie** [comment]
Thank you for the answer but I have read the FAQ already and also tried running the code on the terminal, unsuccessfully. Will keep trying other means.

**Comment by nodeful** [comment]
https://github.com/bitgapp/eqMac/blob/master/native/app/Source/Scripts/uninstall_driver.sh

**Comment by nodeful** [comment]
oh sorry I thought you are talking about the new eqMac...

**Comment by nodeful** [comment]
See #247

**Comment by xdebbie** [comment]
Thank you! The code below works well, once the .kext files were gone the audio output has vanished as well. 

`sudo reboot
(Press Cmd + R during boot)
(Select "Teminal" from the top menu "Utilities")
csrutil disable
reboot
(in Teminal:)
sudo rm -rf /System/Volumes/Data/Library/Extensions/eqMac2Driver.kext
sudo rm -rf /Library/StagedExtensions/Library/Extensions/eqMac2Driver.kext
reboot
(Press Cmd + R during boot)
(Select "Teminal" from the top menu "Utilities")
csrutil enable
reboot`

**Comment by xdebbie** [comment]
Thank you! The code below works well, once the .kext files were gone the audio output has vanished as well.

`
sudo reboot 
(Press Cmd + R during boot) 
(Select "Teminal" from the top menu "Utilities") 
csrutil disable 
reboot 
(in Teminal:) 
sudo rm -rf /System/Volumes/Data/Library/Extensions/eqMac2Driver.kext 
sudo rm -rf /Library/StagedExtensions/Library/Extensions/eqMac2Driver.kext 
reboot 
(Press Cmd + R during boot) 
(Select "Teminal" from the top menu "Utilities") 
csrutil enable 
reboot`

**Comment by xdebbie** [comment]
Thank you! The code below works well, once the .kext files were gone the audio output has vanished as well.

```
sudo reboot 
(Press Cmd + R during boot) 
(Select "Teminal" from the top menu "Utilities") 
csrutil disable 
reboot 
(in Teminal:) 
sudo rm -rf /System/Volumes/Data/Library/Extensions/eqMac2Driver.kext 
sudo rm -rf /Library/StagedExtensions/Library/Extensions/eqMac2Driver.kext 
reboot 
(Press Cmd + R during boot) 
(Select "Teminal" from the top menu "Utilities") 
csrutil enable 
reboot
```
