### ISSUE TITLE
Bug: eqMac will sometimes force media to play very quickly after waking from sleep

### ISSUE THREAD

**Issue by anthne** [bitgapp/eqMac#268]
**Describe the bug**
When waking my Mac from sleep, eqMac will sometimes make media play several times its normal speed until it is restarted. This includes audio, video, and gifs.

**Steps to Reproduce**
1. Put the computer to sleep
2. Wake computer from sleep
3. Sometimes play media and wonder why a 30 minute video finishes in about a second.

**Expected behaviour**
eqMac to not mess with the playback speed.

**Setup information:**
 - Audio device used for playback: External Speakers
 - Audio transmission interface: Digital Out
 - Mac Model: Mac Pro 2010 running latest firmware (144.0.0.0.0) and using OpenCore
 - macOS Version: 10.15.4
 - eqMac Version 0.1.1

**Additional information**
This problem might be related to the dated hardware, and/or the use of OpenCore.

**Comment by nodeful** [comment]
I've tried to replicate the issue a bunch of times, but couldn't make it happen for me. I'm not familiar with OpenCore, what is it?

**Comment by anthne** [comment]
[OpenCore](https://github.com/acidanthera/OpenCorePkg) is a bootloader that is used to make old Macs able to get the latest OS updates.

**Comment by andreami96** [comment]
The same happens on my MacBook Pro 15" Mid 2015 with Catalina 10.15.6.

I experienced it on Safari and was forced to switch to Firefox where the bug doesn't appear.

**Comment by kshitijdeota** [comment]
[Here](https://youtu.be/-ZO8c0bG-ZQ) is a screen recording of the issue that I was able to catch right on time. Playback goes erratic all of a sudden, sound just stops, no hissing or even white noise then as soon as we quit eqMac and refresh the browser things return back to normal right away.

**Comment by jono-hayward** [comment]
Just chiming in with a +1 as I'm experiencing this as well on my 2019 15" MBP running Big Sur (11.2.1). It seems to affect all system video, no matter if you're in QuickTime, Safari, Twitter/Tweetbot etc. 

Screen recording attached. You'll notice the video plays at normal speed immediately upon quitting eqMac 

https://user-images.githubusercontent.com/659408/110057292-770f2a80-7db4-11eb-815b-89f81cbda5fa.mov

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by nodeful** [comment]
Can anyone please confirm that this is still an issue with the newest version of eqMac?
There's been a lot of changes and fixes since this issue was created!
Otherwise will be closing this issue within the next week :)
