### ISSUE TITLE
Bug: No Aggregate devices in list of output devices.

### ISSUE THREAD

**Issue by legendaryaman** [bitgapp/eqMac#270]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Bug Description**
Unable to switch to Aggregate devices in eqMac. If I try to switch from Sound Preferences, eqMac crashes after 2-3 clicks. When I restart eqMac it switches to Aggregate device but it does not show up in "Select output list". 

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Go to 'eqMac'
2. Click on 'Select Output'
3. No Aggregate/Multi-Output devices found in the list.

**Expected behaviour**
eqMac should display a list of all Aggregate and Multi-Output devices.

**Setup information:**
 - Audio device used for playback: [G560 Gaming speakers]
 - Audio transmission interface: [USB Audio]
 - macOS Version: [10.15.4]
 - eqMac Version [e.g. 0.0.1] 
 - eqMac UI Version [e.g. 0.0.4] 

**Screenshots or Console.app logs**
<img width="1037" alt="Screen Shot 2020-05-12 at 7 47 22 PM" src="https://user-images.githubusercontent.com/3285444/81703997-f250ca00-948a-11ea-98f8-90db26235d92.png">

<img width="500" alt="Screen Shot 2020-05-12 at 10 04 25 PM" src="https://user-images.githubusercontent.com/3285444/81720847-9727d300-949c-11ea-96bd-bb3f0d652e34.png">

**Comment by nodeful** [comment]
I've managed to replicate the issue, and it's an easy fix. Will be pushed in the next update. Thanks for reporting

**Comment by nodeful** [comment]
This issue should be resolved in [v0.3.1](https://github.com/bitgapp/eqMac/releases/tag/v0.3.1).
Please update the app and let me know if this issue is still relevant. Thank you
