### ISSUE TITLE
Bug: eqMac window does not reopen after removing from Menu Bar, I can't control the equaliser anymore.

### ISSUE THREAD

**Issue by danialazlee** [bitgapp/eqMac#271]
Description:
I recently updated eqMac to its latest version. While looking through the recent facelift, I accidentally removed the app from the menu bar. Now when I reopen the app, eqMac window doesn't pop up anywhere anymore. I can't control the equaliser.

Steps:
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Update to the latest version of eqMac
2. Change display settings from 'Menu Bar' to 'Dock'
3. Window will disappear even if you restart the app

**Comment by luccamarqueti** [comment]
Having the same problem. Have you managed to solve it yet?

**Comment by danialazlee** [comment]
Nope, I have also tried uninstalling the drivers and the app but neither has worked.

**Comment by MichielTG** [comment]
Same problem here

**Comment by samwise-nl** [comment]
Also having this issue

**Comment by eduardorha** [comment]
Same problem. ¿Any solution?

**Comment by MrEessa** [comment]
Likewise, same issue. The app works but I can't access the window now.

**Comment by nodeful** [comment]
I've just pushed an over the air update to UI v1.0.1 which should fix the issue. No need to redownload eqMac, just restart it a few times and it should be fixed. 
Thanks for reporting :)
