### ISSUE TITLE
Crash when removing headphone jack

### ISSUE THREAD

**Issue by ppamorim** [bitgapp/eqMac#277]
**Describe the bug**
I simply removed my headphone and plugged my external speaker and this crash happened.

<img width="1002" alt="Screenshot 2020-05-21 at 14 22 14" src="https://user-images.githubusercontent.com/5521682/82563274-aaa6fe00-9b6e-11ea-8b2b-737abd38a4b7.png">

Full log: https://gist.github.com/ppamorim/5c769bd361a85b1ee232d8f6713ea539

**Steps to Reproduce**
Not sure, happened randomly when unplugging the jack.

**Expected behaviour**
Do not crash when removing the jack.

**Setup information:**
 - Audio device used for playback: Sony WH1000MX3
 - Audio transmission interface: 3.5mm Jack
 - macOS Version:10.15.4
 - eqMac Version: 0.2.0
 - eqMac UI Version: 1.0.0

**Comment by nodeful** [comment]
Did you see #227 ?
This is a duplicate

**Comment by ppamorim** [comment]
No I didn't, the title is not easy to understand.
