### ISSUE TITLE
Had to close Spotify to install driver

### ISSUE THREAD

**Issue by GumbyTheGreen1** [bitgapp/eqMac#278]
When I was installing eqMac, I had Spotify open and paused. The installer just said to make sure my music was paused, but the installation of the driver failed (and the message that says to either try again or quit appeared). So I closed Spotify; then I hit "Try Again" and it worked.

**Comment by nodeful** [comment]
So what can I do about it? The alternative is to force people to restart their mac after installing eqMac

**Comment by nodeful** [comment]
https://github.com/bitgapp/eqMac/commit/5b1ae04be9944e341329cdf716e443c82fd8272e
This is the most I can do for now.
