### ISSUE TITLE
audio with DP connection no microphone jack audio on MacMini  OS Mojave

### ISSUE THREAD

**Issue by DrBob-W** [bitgapp/eqMac#279]
eqMac app will not play thru 3.5mm audio jack on 2018 MacMini (Mac OS: Mojave)  nor use MacMini's internal speakers.  It will however play through a Dell Display with a DP attached hub.

I've tried re-booting computer, changing input to original input then back to eqMac.  Still sound only comes from the Dell Display.

![Screen Shot 2020-05-23 at 3 47 50 PM](https://user-images.githubusercontent.com/65833105/82741952-eaa3e780-9d0c-11ea-9dd1-ada9027a0bbc.jpg)

**Comment by nodeful** [comment]
Probably related to #257 
Try and play with the Sample Rate in Audio MIDI Setup.app
