### ISSUE TITLE
Bug: eqMac stops playing audio when volume is set to 0%

### ISSUE THREAD

**Issue by badprogramshere** [bitgapp/eqMac#280]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Whenever the audio is muted, eqMac stops playing audio even after the volume is increased, and has to restart.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Open eqMac
2. Play audio
3. Change the volume to 0% using the keyboard, or the sound menubar item
4. Increase the volume again. There should be no sound

**Expected behaviour**
Audio should play as normal after the volume is changed

**Setup information:**
 - Audio device used for playback: Samsung in-box earphones (although this is also found with Beats EP headphones)
 - Audio transmission interface: 3.5mm Headphone Jack
 - macOS Version: 10.14.6
 - eqMac Version 0.2.0

**Screenshots or Console.app logs**
Console logs: https://pastebin.com/9kEvJwMQ

**Additional information**
Sometimes, eqMac won't play audio even after restarting the app, and I have to reboot the computer to get it to work again.

**Comment by nodeful** [comment]
Thanks for reporting this, I managed to replicate the issue. The solution for now is to hit Volume Down button a couple times and then Volume Up. Or also just hit Mute button twice.
I will fix this in the next update

**Comment by badprogramshere** [comment]
Alright, thanks!

**Comment by nodeful** [comment]
Should be fixed in the latest release
