### ISSUE TITLE
Fan full throttle when eqMac is activated

### ISSUE THREAD

**Issue by Citi53hn** [bitgapp/eqMac#282]
I am getting the issue that when I turn on eqMac my fans start to run a 100% aprox. 6000rpm.  This happens whenever I use eqMac.  the computer can be idle and will begin at 25c and when I turn on eqMac it raises my cpu temp to around 50c however, the fans starts to run at full speed as soon as I turn on eqMac.  I usually have to put the macbook to sleep and let it sit for a few minutes and then get back on.  once that happens everything seems to work fine.  I am also having the issue that i cannot change the audio source from system preferences.  i will choose internal macbook speakers for example and the eqMac will not release control.  I have to turn off eqMac in order to get this to switch source.  this is intermittent, does not happen all the time.

i have a 2018 macbook pro 15" A1990
2.6ghz  6 core i7
Raedon Pro Vega 20 4gb graphic card
16gb ram

**Comment by nodeful** [comment]
You didn't follow the bug issue template.
eqMac uses about 3-5% CPU usage on my 2 core CPU which is much better than any other alternative on the market.
![image](https://user-images.githubusercontent.com/8472525/82798959-2b1c7600-9e71-11ea-8ee2-ee4bcfac9d19.png)
There's still a little bit of performance I can squeeze out eventually but that's not a priority at the moment. 

In terms of eqMac switching the audio device back to eqMac, this is intended as eqMac needs the driver audio device to be selected for it to work. When you select any other device eqMac with build a processing pipeline and start playing audio through your selected device.
