### ISSUE TITLE
eqMac Beta v0.2.0 can't minimise back to tray

### ISSUE THREAD

**Issue by MariuzM** [bitgapp/eqMac#283]
When clicking minimise before .2 update it use to close the window and only display in system tray, now it minimises as window.

**Comment by nodeful** [comment]
now the X button closes the window and the "-" button minimizes the window to the dock. This is in line with Apple's User Interface Guidelines. Most other apps behave this way and if they are not, they should. No need to create a GitHub issue for this discussion, we have a discord server for discussing such things: https://discord.eqmac.app
