### ISSUE TITLE
Enhancement: Change volume via native MacOS interface

### ISSUE THREAD

**Issue by eyalroth** [bitgapp/eqMac#287]
I can't tell if this is a bug or a missing feature, as this is the first time I'm using the app.

**Description:**
Changing the volume via the MacOS interface -- either with the slider in the menu bar or with the keyboard shortcuts -- doesn't affect the volume of the app.

This is quite uncomfortable as I'm used to change the volume quite often.

**Comment by nodeful** [comment]
This is supposed to work, changing the volume anywhere is supposed to sync with eqMac. 
You haven't followed GitHub issue template and the guidelines setup with those. So I'm closing this issue. If you want to discuss it further with me please contact me on http://discord.eqmac.app

**Comment by davyjones321** [comment]
Same problem with me. Why arent they responding ?
