### ISSUE TITLE
Bug: No sound on High Sierra

### ISSUE THREAD

**Issue by Rinblackbird** [bitgapp/eqMac#290]
**Describe the bug**
After opening the app on mac running High Sierra there is no sound output.

**Comment by nodeful** [comment]
#257

**Comment by Rinblackbird** [comment]
These seem to be slightly different issues, that is, the same issue on different Mac versions. I wasn't sure if that matters or not though.

**Comment by nodeful** [comment]
I'm not sure if it matters or not, you haven't followed the Issue template so I don't have other details that I need to debug a problem, I'm closing issues like that to minimise the issue noice in the repository
