### ISSUE TITLE
Enhancement: Launch silently on startup

### ISSUE THREAD

**Issue by melvinbeemer** [bitgapp/eqMac#293]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
When launch on start-up is on, I would like for the app to launch silently. Meaning the app would not show it's window at all and just launch in the background. I think this is especially useful in status bar only mode where accessing the app is rarely the first thing you want to touch and the window goes away anyway after any other interaction. So it's better for users to not show the window at all in the first place.

**User flow & interface:**
There are a few ways this could be implemented:
1. Launch it in the background only on startup (it makes sense to show the window when launching it manually) by default
2. Or add an extra toggle in the preferences to enable "silent startup"

**Comment by nodeful** [comment]
From this:
https://github.com/bitgapp/eqMac/blob/master/native/app/Source/Application.swift#L84-L86
Should already be the case, I guess there's a bug?

**Comment by melvinbeemer** [comment]
As far as I can see it's just checking for first launch there. I'd like for the UI to be hidden on system startup (which is also first launch).

**Comment by nodeful** [comment]
This issue should be resolved in [v0.3.1](https://github.com/bitgapp/eqMac/releases/tag/v0.3.1).
Please update the app and let me know if this issue is still relevant. Thank you
