### ISSUE TITLE
Music transitioned to cracks and hissing noises

### ISSUE THREAD

**Issue by Xardas220** [bitgapp/eqMac#294]
**Describe the bug**
It does it's job for 20-30 minutes - then the sound starts to crackle goes further more crackle until there are only cracks and hisses and so no music to listen to. From music to only hisses and cracks are about 20 seconds. It's a a smooth transition. Is there a buffer that's not cleared?
-> Quit and start again brings it back to life.
**Setup information:**
 - Selfmade Hackintosh (Gigabyte Aorus Pro, AMD 3700X, AMD 5700XT)
 - External DAC with headphone amplifier connected via USB, so there cannot be a problem with the system itself because USB
 - macOS Version: 10.15.5
 - eqMac Version: 0.2.0

**Screenshots or Console.app logs**
There's no anormal activity there. I compared the console activities when it was working and when it starts crackling.

**Comment by nodeful** [comment]
duplicate
