### ISSUE TITLE
Bug: No sound for external head phones

### ISSUE THREAD

**Issue by sisyphosloughs** [bitgapp/eqMac#296]
There is no sound output from my external wired headphones (Panasonic rp-hde5m). Internal Mac speaker, and my Audioengine 2+ speaker are fine.

**Steps to Reproduce**
1. Plug in the headphone speakers into the MacBook
2. Start eqMac
3. Chose external headphone
4. Optonal: Click on "Reset Playback"

**Expected behaviour**
Sound output

**Setup information:**
 - Audio device used for playback: anasonic rp-hde5m
 - Audio transmission interface: 3.5mm Jack
 - macOS Version: macOS 10.15.4 (19E287)
 - eqMac Version: 0.2
 - eqMac UI Version: 1.0.1

**Screenshots or Console.app logs**
standard	17:30:17.960747+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:30:17.961926+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:30:17.961985+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:30:17.971574+0200	eqMac	0x10e5085e0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:17.972846+0200	eqMac	0x10e508730 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:17.973027+0200	eqMac	0x10e508760 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:17.973138+0200	eqMac	0x10e5085e0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:17.974499+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:30:17.974544+0200	eqMac	0x10e508730 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:17.974579+0200	eqMac	0x10e508760 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:24.289823+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:30:24.291410+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:30:24.291486+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:30:24.295217+0200	eqMac	0x10e5087b0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:24.296353+0200	eqMac	0x10e508900 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:24.296612+0200	eqMac	0x10e508930 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:24.296713+0200	eqMac	0x10e5087b0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:24.298652+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:30:24.298697+0200	eqMac	0x10e508900 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:24.298731+0200	eqMac	0x10e508930 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:34.423211+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:30:34.424392+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:30:34.424508+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:30:34.427819+0200	eqMac	0x10e508970 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:34.430054+0200	eqMac	0x10e508ac0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:34.430269+0200	eqMac	0x10e508af0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:34.430447+0200	eqMac	0x10e508970 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:34.433341+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:30:34.433511+0200	eqMac	0x10e508ac0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:34.433581+0200	eqMac	0x10e508af0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:44.534492+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:30:44.535150+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:30:44.535196+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:30:44.536990+0200	eqMac	0x10e508b30 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:44.539619+0200	eqMac	0x10e508c80 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:44.539889+0200	eqMac	0x10e508cb0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:44.539968+0200	eqMac	0x10e508b30 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:44.541362+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:30:44.541414+0200	eqMac	0x10e508c80 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:44.541445+0200	eqMac	0x10e508cb0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:55.422781+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:30:55.424092+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:30:55.424165+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:30:55.427680+0200	eqMac	0x10e508cf0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:55.431571+0200	eqMac	0x10e5fcd40 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:55.431734+0200	eqMac	0x10e5fcd70 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:55.431771+0200	eqMac	0x10e508cf0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:55.431792+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:30:55.433166+0200	eqMac	0x10e5fcd40 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:30:55.433202+0200	eqMac	0x10e5fcd70 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:31:04.291115+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:31:04.292083+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:31:04.292172+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:31:04.294294+0200	eqMac	0x10e5fcdc0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:31:04.295397+0200	eqMac	0x10e5fcf10 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:31:04.295629+0200	eqMac	0x10e5fcf40 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:31:04.295723+0200	eqMac	0x10e5fcdc0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:31:04.297363+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:31:04.297404+0200	eqMac	0x10e5fcf10 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:31:04.297436+0200	eqMac	0x10e5fcf40 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:31:08.531631+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:31:08.532495+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:31:08.532543+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::willPerformClientRedirectForFrame: frameID = 13
standard	17:31:08.536031+0200	eqMac	0x10e5fcf80 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:31:08.537200+0200	eqMac	0x10e5fc9d0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:31:08.537426+0200	eqMac	0x10e5fca00 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:31:08.537462+0200	eqMac	0x10e5fcf80 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:31:08.538767+0200	eqMac	0x7fdfc9097820 - [pageProxyID=10, webPageID=11, PID=3934] WebPageProxy::didCancelClientRedirectForFrame: frameID = 13
standard	17:31:08.538892+0200	eqMac	0x10e5fc9d0 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'
standard	17:31:08.538985+0200	eqMac	0x10e5fca00 - [PID=0, throttler=0x10e5ebd98] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInMainFrameScriptWorld'

**Comment by virtustilus** [comment]
Can be related to #257 
Will test it today on MacBook Pro 16.

**Comment by ediblemanager** [comment]
Can confirm external output has no sound when using eqMac. MBP 2018, 10.14.6.

**Comment by nodeful** [comment]
Most likely related to #257 
Please download this release:
https://github.com/bitgapp/eqMac/releases/tag/v0.2.2
and report back if the issue is still not resolved for you

**Comment by sisyphosloughs** [comment]
I can confirm, version 0.2.2 works fine with my head phones.
