### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by tommybds** [bitgapp/eqMac#3]
Hello, due to multiples cut during music playback, I tested to uninstall eqmac but the UI don't let me do it :)

On Catalina macbook pro 2015
![image](https://user-images.githubusercontent.com/5949831/72059077-948c5580-32d1-11ea-87c0-a82d08b17760.png)

**Comment by nodeful** [comment]
Hmm I never saw this issue. Seems like your UI is guffy in other ways as well.
Can you go to this link **in Safari**: https://google.com/search?q=what%27s+my+user+agent
And tell me what User Agent do you have. Cheers

**Comment by tommybds** [comment]
Hello, 
Here it is : 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15`

**Comment by nodeful** [comment]
This bug is related to #13 as it's a UI rendering issue. Please refer there for future updates.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
