### ISSUE TITLE
Bug: Sound won't round using External Headphones (via physical audio port)

### ISSUE THREAD

**Issue by AcidSlide** [bitgapp/eqMac#303]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
The equalizer works perfectly via the mbp speakers, but when connecting a headphone through the audio jack, no sound comes out to the external speaker/headphones.

I've tried switching between audio devices while eqMac is running but every time the external headphones is selected no sound is being generated.

Killing/quiting eqMac restores the sound back to the external headphones.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Run eqMac
2. Play any music/audio
3. Plug an external headphone/speaker
4. Try switching between built-in and external
5. See screenshot for error every time trying to switch to external headphones/speakers

**Expected behaviour**
Sound should still be routed properly using external audio via the audio jack/port.

**Setup information:**
 - Macbook Pro Speaker and a external headphone and external speaker
 - Built-in speaker and 3.5mm audio jack
 - macOS Version: 10.15.5
 - eqMac Version 0.2.0
 - eqMac UI Version 1.0.1

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac`
![image](https://user-images.githubusercontent.com/6833047/84581211-5c091e80-ae11-11ea-91ea-34350fac910b.png)
 

**Additional information**

**Comment by virtustilus** [comment]
This was already fixed in 0.2.2

**Comment by AcidSlide** [comment]
> This was already fixed in 0.2.2

Is there a DMG available already? On the official site, the download version is still at 0.2.0.

**Comment by AcidSlide** [comment]
> > This was already fixed in 0.2.2
> 
> Is there a DMG available already? On the official site, the download version is still at 0.2.0.

never mind.. found the release folder.. testing now

**Comment by AcidSlide** [comment]
> > > This was already fixed in 0.2.2
> > 
> > 
> > Is there a DMG available already? On the official site, the download version is still at 0.2.0.
> 
> never mind.. found the release folder.. testing now

Verifying.. working in 0.2.2.. hope it doesn't crash as I've seen some has been mentioning crashes
