### ISSUE TITLE
Bug: eqMac will not load after update June 2020

### ISSUE THREAD

**Issue by arthurfrisch** [bitgapp/eqMac#306]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- 

- [X] [x]

 I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
I was prompted for a version update a few days ago. Ever since, eqMac hangs on loading - I see window with spinning wheel. I have re-installed same issue.

**Steps to Reproduce**
1. Open eqMac

**Setup information:**
 - Audio device used for playback: Macbook
 - Audio transmission interface: 3.5mm Jack
 - macOS Version: 10.15.4 (19E287)
 - eqMac Version: latest
 - eqMac UI Version: latest

**Comment by nodeful** [comment]
Duplicate

**Comment by arthurfrisch** [comment]
Duplicabe to which issue? @nodeful has there been a solution published? Thank you.
