### ISSUE TITLE
Feature: add option to disable Volume Boost

### ISSUE THREAD

**Issue by krupenja** [bitgapp/eqMac#307]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
I would like to have an option to disable Volume Boost — at the moment there is no such option.

**User flow & interface:**
I think this option can be added as an extra checkbox in Settings view.

**Comment by nodeful** [comment]
There's no boost below 100%, software boosting starts over 100% Volume
