### ISSUE TITLE
Bug: Crash when changing audio output (Catalina)

### ISSUE THREAD

**Issue by Maci68** [bitgapp/eqMac#308]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When changing the audio output, eqMac sometimes (it's not often) crashes silently. Maybe verry similar bug as on HighSierra. [Crash when changing audio output (HighSierra) #297](https://github.com/bitgapp/eqMac/issues/297)

**Additional information**
Tested on MacPro 2013, 64GB RAM, internal audio output, DualHead display via displayport, Catalina 10.15.5, eqMac version 0.2.0

**Comment by nodeful** [comment]
Yes the same issue
