### ISSUE TITLE
eqMac set itself as the audio output source when the app wasn't running

### ISSUE THREAD

**Issue by gagank1** [bitgapp/eqMac#31]
eqMac was not running, but no audio would play from my computer. I went into Audio MIDI Setup on a hunch and somehow the selected source was eqMac. I opened eqMac and quit it, and it disappeared. This was not happening yesterday, and I haven't run eqMac since my last listening session, so it somehow spontaneously set itself as the source while not running since my last listening session.

**Comment by nodeful** [comment]
Ah yes I know how that is happening. When you restart your Mac the device goes active at first. If you dont run eqMac on startup thats a problem. I just never restart my Mac so never came across this

**Comment by nodeful** [comment]
Will fix in the next update

**Comment by gagank1** [comment]
Makes sense, my computer had restarted after updating to 10.15.4.

**Comment by connorkutz** [comment]
@nodeful Just wondering if you were planning on open sourcing this. I'm interested in branching this to work on some issues / bugs in my spare time.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
