### ISSUE TITLE
Bug: Multiple monitor if turn off the one monitor (Catalina)

### ISSUE THREAD

**Issue by Maci68** [bitgapp/eqMac#310]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
I use a multi monitor set and if I turn off one of the monitors, the eqMac always switches the audio output to the active (on) monitor. I have displayport monitors with audio, but I don't use them to listen to audio. eqMac doesn't remember my original settings (for example audio line). If I switch the audio output back, everything is fine. Even the eqMac will not crash.

**Additional information**
Tested on MacPro 2013, 64GB RAM, internal audio output, DualHead display via displayport, Catalina 10.15.5, eqMac version 0.2.0

**Comment by nodeful** [comment]
This issue should be resolved in [v0.3.1](https://github.com/bitgapp/eqMac/releases/tag/v0.3.1).
Please update the app and let me know if this issue is still relevant. Thank you
