### ISSUE TITLE
Bug: Upon startup/boot no sound/audio coming out

### ISSUE THREAD

**Issue by AcidSlide** [bitgapp/eqMac#311]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
This might be related to the sleep issue #309 (not sure really)

Upon newly start or reboot of macos, no sound coming out. After checking, eqMac is selected even if eqMac is not running.  I had to manually change to "MacBook Pro Speaker" to get the sounds back.  Then I have to run eqMac then quit for it to be removed in the audio output.

I'll update this after I do another reboot for the screenshots.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Reboot MBP (Note: eqMac is not running, not set to auto launch on startup)
2. Run any apps with sounds or audio, or best open a movie and play it
3. No sounds
4. Change output manually to "MacBook Pro Speakers" (eqMac is selected even if it is not started)
5. Yey! Sound is back.
6. Run eqMac
7. Exit eqMac
8. eqMac removed from audio devices

**Expected behaviour**
eqMac should not be enabled or selected upon startup, especially the "Launch from startup" is not selected or enabled.

**Setup information:**
 - MacBook Pro Speakers
 - Audio transmission interface: Built-n
 - macOS Version: Catalina 10.15.5
 - eqMac Version 0.2.2
 - eqMac UI Version 1.0.1

**Screenshots or Console.app logs**
I will updated this after I do a full restart for the screenshots.

**Additional information**
No other informations for now.

**Comment by AcidSlide** [comment]
I haven't fully reproduced the issue, but prior to creating the issue ticket, I experienced this twice already.

So far, I was only able to reproduce the "eqMac" device is active (but not selected) even if "eqMac" was not set to launch at startup.

The only way to disable the "eqMac" audio devices was running eqMac itself the quitting it.

<img width="704" alt="issue_311_after_restart_001" src="https://user-images.githubusercontent.com/6833047/85115541-6e8aba00-b24e-11ea-82f0-7f13f5cc9978.png">

**Comment by nodeful** [comment]
This issue should be resolved in [v0.3.1](https://github.com/bitgapp/eqMac/releases/tag/v0.3.1).
Please update the app and the driver when launching and let me know if this issue is still relevant. Thank you
