### ISSUE TITLE
Output Select Shortcuts

### ISSUE THREAD

**Issue by Powemi** [bitgapp/eqMac#313]
**Description:**
Quick output selections/changes

**User flow & interface:**
Global shortcut key to bring up list of output devices with options next to each for quickly changing. 

**
The program Ears but implemented within EqMac to still be able to use the EqMac functions for sound.

**Comment by nodeful** [comment]
Sorry but I'm not currently interested in implementing this feature, too much work for very little benefit. Sorry once again

**Comment by GabrielVinicios** [comment]
Shortcuts for change automatically the output device would be great! 

Would it be very complicated to implement a shortcut where the each press change automatically the output device? SoundSwitch (https://soundswitch.aaflalo.me), that is Windows only, works this way. It would be amazing!
