### ISSUE TITLE
eqMac Won't load Properly

### ISSUE THREAD

**Issue by Ashteroide** [bitgapp/eqMac#314]
**Describe the bug**
A constant loading that won't go away on both v0.2.2 and v0.3.0

**Steps to Reproduce**
Download eqMac.dmg
Open dmg and install eqMac
Open eqMac
The app then opens but doesn't show a UI until you open the app again

**Expected behaviour**
Open eqMac and load UI

**Setup information:**
Any audio device
MacOS 10.15.2
v0.3.0 & v0.2.2

![Screen Shot 2020-06-22 at 2 26 30 pm](https://user-images.githubusercontent.com/56657815/85248639-c4e93a00-b494-11ea-8921-d2db835e3e82.png)

**Comment by oddharsh** [comment]
I am also getting this issue with 0.3.0, though 0.2.2 worked as expected for me

**Comment by t0mn** [comment]
Same here

**Comment by Ashteroide** [comment]
I uninstalled 0.2.2 to install 0.3 which then both broke

**Comment by sakwads** [comment]
I am also experiencing the Loading issue. It just displays the spinner but nothing loads

**Comment by t0mn** [comment]
Also tried uninstalling 0.3, kext driver & cache, reinstalled 0.2.2 and exactly the same problem.  Nothing is working for eqMac.

**Comment by nodeful** [comment]
Yeah something is wrong again.... pain in the ass.
For me eqMac doesn't work without internet access, with internet everything works fine. I'll fix soon but for the moment please enable internet access to the app for it to work. Also please follow issue #284
