### ISSUE TITLE
Bug: starting eqMac prompts about an update while on latest version

### ISSUE THREAD

**Issue by erikhuizinga** [bitgapp/eqMac#316]
**Disclaimer:** 

- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**

The update dialog prompts to install an update while on the latest (v0.3.0) version).

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Launch eqMac v0.2.x
1. See update prompt
1. Install update through prompt
1. Launch eqMac v0.3.0
1. BUG! See update prompt again?! **Notice in the screenshot below that the prompt says that 'v0.3.0' is available and that I'm on 'v0.3'. This string difference is possibly the cause of the bug.**

**Expected behaviour**

I don't see an update prompt when on the latest stable version.

**Setup information:**
 - macOS Version: 10.14.6 (18G5033)

**Screenshots or Console.app logs**

![image](https://user-images.githubusercontent.com/19374736/85258304-90ab5480-b467-11ea-8875-2fc4f57c12fc.png)

**Comment by conceptomes** [comment]
hi,
I just had the same issue in Catalina 10.15.3
I installed the update and now when I try to launch eqMac nothing happens :(.

**Comment by nodeful** [comment]
This should not be fixed, no need to update anything, was just a caching issue on the server. Thanks for reporting

**Comment by nodeful** [comment]
@conceptomes what you said is not related to this issue
