### ISSUE TITLE
Bug: eqMac audio driver is still enabled even after quitting eqMac

### ISSUE THREAD

**Issue by AcidSlide** [bitgapp/eqMac#317]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Even after quitting eqMac 0.3.0 and 0.3.1, eqMac is still in the Audio device list.
![image](https://user-images.githubusercontent.com/6833047/85286313-fa0d8080-b4c4-11ea-86f3-96b6aa617a25.png)

This didn't happen with 0.2.0 and 0.2.2. If you quit eqMac it also removes the eqMac audio in the audio list.

Image below when eqMac is running, which is correct.
![image](https://user-images.githubusercontent.com/6833047/85286528-66887f80-b4c5-11ea-9ec3-30f78b71775e.png)

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Run eqMac.
2. Then quit eqMac.
3. Click the volume icon.
4. You will see eqMac is still listed.

**Expected behaviour**
eqMac audio should not be active if eqMac is not running.

**Setup information:**
 - Audio device used for playback: MacBook Pro Speaker
 - Audio transmission interface: Built-in speaker
 - macOS Version: Catalina 10.5.5
 - eqMac Version 0.3.1 (and 0.3.0)
 - eqMac UI Version 1.2.0
 - eqMac Driver Version 1.0.0

**Screenshots or Console.app logs**
![image](https://user-images.githubusercontent.com/6833047/85286313-fa0d8080-b4c4-11ea-86f3-96b6aa617a25.png)

**Additional information**
No additional information.

**Comment by nodeful** [comment]
Try restarting you Mac and try again

**Comment by AcidSlide** [comment]
> Try restarting you Mac and try again

Just did that now, full shutdown then turn back on and it's still there.
![image](https://user-images.githubusercontent.com/6833047/85287374-be73b600-b4c6-11ea-82d9-0ff425ffdab0.png)

This used to work with 0.2.2.
1. Run eqMac
2. Quit eqMac
3. eqMac audio gone from audio list

But now, even after go through those steps, eqMac is still in the audio list.

**Comment by nodeful** [comment]
Seems like you still running Driver version 1.0. Go to app settings and Reinstall Driver.

**Comment by AcidSlide** [comment]
> Seems like you still running Driver version 1.0. Go to app settings and Reinstall Driver.

Unable to update the driver, see below

First attempt...
![image](https://user-images.githubusercontent.com/6833047/85288876-17444e00-b4c9-11ea-93c4-07c697660f24.png)

Failed and I thought the app got stuck only noticed there was a notification because of the bouncing icon during the 2nd and 3rd attempt, NOTE: the notif screen was somehow hidden in my screens, only showed after clicking the bouncing icon)
![image](https://user-images.githubusercontent.com/6833047/85289009-55da0880-b4c9-11ea-9a8b-92199cf1f25d.png)
![image](https://user-images.githubusercontent.com/6833047/85289026-5bcfe980-b4c9-11ea-9135-7d20bb609483.png)
![image](https://user-images.githubusercontent.com/6833047/85289044-62f6f780-b4c9-11ea-87e9-304b5c540da1.png)


Second attempt, i didn't do any screenshots..

Third attempt...
![image](https://user-images.githubusercontent.com/6833047/85289121-80c45c80-b4c9-11ea-94fa-a8e915ef6ae2.png)
![image](https://user-images.githubusercontent.com/6833047/85289136-8457e380-b4c9-11ea-9f41-3b359f3c97be.png)
![image](https://user-images.githubusercontent.com/6833047/85289139-87eb6a80-b4c9-11ea-8ae6-51410ae8e13d.png)

**Comment by AcidSlide** [comment]
I actually tried a fourth attempt.. still failed

**Comment by AcidSlide** [comment]
I'll try now from a full shutdown since eqMac is not showing in the audio list

**Comment by AcidSlide** [comment]
After a full shutdown and boot, I was able to update the drivers with no errors.. but....... a new issue popped up.. which is not related to this problem.. ahahaha

![image](https://user-images.githubusercontent.com/6833047/85290435-963a8600-b4cb-11ea-9df0-27145b6759c1.png)

This was the problem..
![image](https://user-images.githubusercontent.com/6833047/85290484-a7839280-b4cb-11ea-9395-0c036b78b515.png)
That happened after plugging my external hub (multi port usb-c hub) which my external monitor is connected.

**Comment by AcidSlide** [comment]
I think this can be closed, but just in case others might find the installation issue useful.

**Comment by nodeful** [comment]
Thanks for your findings, if anyone asks about these problems in the future I will send them to this issue
