### ISSUE TITLE
Bug: eqMac crashes when a usb-c hub was plugged in

### ISSUE THREAD

**Issue by AcidSlide** [bitgapp/eqMac#318]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
I'm not sure if this or was related to #297 

While the eqMac was running and the interface was open, I plugged my USB-C hub (with HDMI output) and eqMac crashed immediately.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Run eqMac
2. Open the eqMac interface
3. Plug the multi-port usb-c hub with external display support (vga and hdmi), secondary display is connected in the HDMI
4. eqMac crashes immediately

**Expected behaviour**
eqMac won't be affected by external devices with audio devices.

**Setup information:**
 - Audio device used for playback: MacBook Pro Speaker
 - Audio transmission interface: Built-in speaker
 - macOS Version: Catalina 10.15.5
 - eqMac Version 0.3.1
 - eqMac UI Version 1.2.0 (Remote)
 - eqMac Driver Version 1.1.0

**Screenshots or Console.app logs**
![image](https://user-images.githubusercontent.com/6833047/85291464-1a413d80-b4cd-11ea-816a-3fe46937500b.png)

Below is a partial crash log of Apple...
```
Process:               eqMac [702]
Path:                  /Applications/eqMac.app/Contents/MacOS/eqMac
Identifier:            com.bitgapp.eqmac
Version:               v0.3.1 (0.3.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           eqMac [702]
User ID:               501

Date/Time:             2020-06-22 20:55:03.484 +0800
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Bridge OS Version:     4.5 (17P5300)
Anonymous UUID:        50--------- <<-- removed for security reasons


Time Awake Since Boot: 170 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (CFGetTypeID(r) == CGRegionGetTypeID()), function assert_check_region_without_null_check, file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreGraphics/CoreGraphics-1355.17/CoreGraphics/Regions/CGRegion.c, line 37.
```

**Additional information**
This is my usb-c hub: [https://www.ugreen.com/products/9-in-1-hdmi-ethernet-usb-c-hub](https://www.ugreen.com/products/9-in-1-hdmi-ethernet-usb-c-hub)

**Comment by nodeful** [comment]
Please try the latest version v0.3.2

**Comment by AcidSlide** [comment]
> Please try the latest version v0.3.2

Yup, looks like it doesn't happen with v0.3.2 anymore. Just that now I can't use my earphones :( ahahaha.. anyway, closing this.  Thanks @nodeful
