### ISSUE TITLE
Bug: eqMac won't open at all

### ISSUE THREAD

**Issue by MonkeyFeeder** [bitgapp/eqMac#324]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
I downloaded the application this morning, and got it to work. Paused me music, shut my laptop, got back home, watched Netflix, and wanted to listen to more music, now it won't open at all. I tried to force quit the app in the Activity monitor, and open it again, it appears for literally a fraction of second, not giving me time to read anything. If I launch the app another time ( after the first try and the short appearance ), it opens up a black window which keeps on loading forever, never showing me the UI. I tried to reinstall, but it's not solving the issue.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Launch the app once, pay attention to the screen
2. The App should appear in the activity monitor, but not have any active window in the dock or anything ( not even a dot under the icon )
3. Launch the app another time, window should appear but won't display any UI

**Expected behaviour**

**Setup information:**
 - Audio device used for playback: Bose Soundlink 2 when listening to music, MBP 16" when watching Netflix
 - Audio transmission interface: Bluetooth with the Soundlink 2
 - macOS Version: 10.15.5
 - eqMac Version Can't know since application won't open, but downloaded on the 06/25/2020. File information shows v0.3.1 though
 - eqMac UI Version [e.g. 0.0.4] **(if UI related issue)**

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by nodeful** [comment]
Without a crash log can't help much sorry

**Comment by MonkeyFeeder** [comment]
Alright, where can I see the logs of the app ?
Thanks !
