### ISSUE TITLE
Bug: No sound after waking or logging in (Catalina)

### ISSUE THREAD

**Issue by Maci68** [bitgapp/eqMac#329]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
no sound is heard after waking up or logging in. The audio device is set up correctly. When I click to increase or decrease the volume in the eqMac control panel, the sound is activated

**Additional information**
Used on MacPro 2013 (Model 2018), Catalina 10.15.5, eqMac UI 1.21, app. 0.3.1, Driver 1.0.0

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Sorry for taking so long. 
So you are saying that as soon as you change the volume the sound start playing?

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by nodeful** [comment]
I think this issue has been resolved for a while now, so I'll be closing this issue unless suggested otherwise. Thank you
