### ISSUE TITLE
Bug: No sound is heard after changing the audio output (Catalina)

### ISSUE THREAD

**Issue by Maci68** [bitgapp/eqMac#331]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
No sound is heard after changing the audio output

**Steps to Reproduce**
Change audio output

**Additional information**
Tested on MacPro 2013 (model 2018), 64GB RAM, Dual DisplayPort Monitors, Catalina 10.15.5, eqMac 0.3.1

**Comment by AcidSlide** [comment]
Hi @Maci68 you didn't follow the prescribed format to submit issues.  It's hard to determine what is your issue and if this is related to other issues you left out some needed information.

Anyway...

Have you tried 0.3.2? What is the audio output you are using? Switching from which output to what output?

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Sorry for taking so long.
Seems like this issue is related to other "no sound" issues like #326
Closing this one unless you advice otherwise
