### ISSUE TITLE
Bug: Not Starting on macOS Big Sur

### ISSUE THREAD

**Issue by chrisspiegl** [bitgapp/eqMac#335]
**Disclaimer**

I am aware that I am running a beta version of macOS, I just thought I'd report this so that it can be fixed ideally soon, but for the upcoming release at all. Especially since nowadays Apple is releasing public betas and those are available like 3 months before the public release and it would be too bad if eqMac would not work till Sept/Oct.

**Describe the bug**

When installing eqMac on macOS 11.0 Big Sur Beta 1 and 2, the program does work sometimes (weirdly enough) but then other times it does not start at all. The console prints the following when trying to launch via terminal:

<details>
<summary><b>$/Applications/eqMac.app/Contents/MacOS/eqMac</b></summary>

```
2020-07-08 10:17:41.901 eqMac[8116:132180] Sentry Started -- Version: 4.5.0
eqMac (Source/Application.swift:184) Setting up Audio Engine
Error: 2003332927 -> /Users/romanskisils/Programming/Bitgapp/eqmac/native/app/Source/Audio/Sources/System/Driver.swift:123
ERROR: SentryCrashMachineContext.c (232): void sentrycrashmc_resumeEnvironment(): thread_resume (0000d807): (os/kern) object terminated
[1]    8116 segmentation fault  /Applications/eqMac.app/Contents/MacOS/eqMac
```

</details>

Manually installing the driver anew, prints:

<details>
<summary><b>$ sudo /Applications/eqMac.app/Contents/Resources/install_driver.sh</b></summary>

```
Device not ready yet, waiting...
Device not ready yet, waiting...
Device not ready yet, waiting...
Device not ready yet, waiting...
ERROR: Device did not become active
```

</details>

Another weird thing about this all: the driver is actually running and is visible in the Activity Monitor as a Core Audio Driver process.

**Steps to Reproduce**

Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Install and Open on Big Sur
2. Sometimes it works, sometimes it does not.
3. Restarted macOS sometimes it let's eqMac launch, sometimes it does not?

**Expected behaviour**

eqMac should just start every time and work?

**Setup information:**

 - Audio device used for playback: LG Ultrawide monitor (USB-C conencted), Internal Speakers, Headphone Jack connected headphones. Problem is visible without and with devices connected.
 - Audio transmission interface: USB-C to Ultrawide
 - macOS Version: 11.0 beta
 - eqMac Version: v0.3.2
 - eqMac UI Version: v1.1.1

**Comment by nodeful** [comment]
If it works sometimes then has nothing to do with Big Sur and is probably related to other issues

**Comment by chrisspiegl** [comment]
Interesting point, I am going to keep my eyes open for any new release on here and will try everything to see once it goes back to work. And I will also try to provide more feedback if I find any more details.

**Comment by oddharsh** [comment]
I've also had this issue, albeit more consistently, on both betas thus far.

**Comment by enaluz** [comment]
Also have had this issue, consistently on Big Sur 11.0 Beta 4 (20A5343i).

**Comment by brainkilla-X** [comment]
> Also have had this issue, consistently on Big Sur 11.0 Beta 4 (20A5343i).

Same here, the terminal output reads:

`020-08-12 11:34:38.555 eqMac[9390:466999] Sentry Started -- Version: 4.5.0
eqMac (Source/Application.swift:184) Setting up Audio Engine
Error: 2003332927 ->  /Users/romanskisils/Programming/Bitgapp/eqmac/native/app/Source/Audio/Sources/System/Driver.swift:123

ERROR: SentryCrashCPU.c (58): _Bool sentrycrashcpu_i_fillState(const thread_t, const thread_state_t, const thread_state_flavor_t, const mach_msg_type_number_t): thread_get_state: (ipc/send) invalid destination port
ERROR: SentryCrashCPU.c (58): _Bool sentrycrashcpu_i_fillState(const thread_t, const thread_state_t, const thread_state_flavor_t, const mach_msg_type_number_t): thread_get_state: (ipc/send) invalid destination port
ERROR: SentryCrashMachineContext.c (232): void sentrycrashmc_resumeEnvironment(): thread_resume (0001860b): (ipc/send) invalid destination port
Segmentation fault: 11
logout`

**Comment by DiegoGiovany** [comment]
same here...

**Comment by doppelpunkt89** [comment]
I have the same issue. Would be great to know if there is anything we can do about it. I really enjoyed the app in the past and would like to use it with Big Sur as well.

**Comment by hnizam** [comment]
Just update Big Sur, audio sounded garbled when using eqMac. stopping (quitting) eqmac, restores the audio back to normal but without the eqmac equalizer setting. 
Please help to rectify.

**Comment by geochronology** [comment]
I recently installed Big Sur 11.0.1 and I'm experiencing the same issue.

**Comment by philuxx** [comment]
Killing the `coreaudiod` process seems to always work for me when I have eqMac issues. The process respawns automatically.

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
I have experienced some intermittent issues on my Big Sur machine as well during development so will be looking into it in the next coming days.
This issue will be the main one that I will referring duplicate issues too.

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by chrisspiegl** [comment]
Update from my side: I am currently not using eqMac and will not be able to provide testing. But I hope others in this thread will 👍.

**Comment by nodeful** [comment]
Thanks for the update @chrisspiegl and sorry to see you go. Hope to win you back again some day 😄 
Can anyone else please let me know if this specific bug is still an issue?

**Comment by nodeful** [comment]
I think this issue has been resolved for a while now, so I'll be closing this issue unless suggested otherwise. Thank you
