### ISSUE TITLE
Bug: Loud popping when accessing Firefox's about:support

### ISSUE THREAD

**Issue by advicepyro** [bitgapp/eqMac#336]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When eqMac is running, opening the Firefox page `about:support` produces two LOUD popping noises. This does not happen if eqMac is closed.
Not a super critical bug as this page is not a frequently accessed one.

**Steps to Reproduce**
1. Have eqMac open and enabled
2. Possibly adjust EQ settings: I have everything flat except for 32 and 64 Hz at +11 dB each
3. In Firefox 79.0 beta, navigate to `about:support` (but take your headphones off first 😜)

**Setup information:**
 - Audio device used for playback: Wired MPOW gaming headset
 - Audio transmission interface: 3.5 mm jack
 - Hardware: MacBook Pro (2017, 2 Thunderbolt ports)
 - macOS Version: 10.15.5
 - eqMac Version: 0.3.2
 - eqMac Driver Version: 1.1.1

**Comment by nodeful** [comment]
I was never able to replicate this issue, I've tried many times over and over and never saw it. Sorry if it's still an issue for you but there isn't much I can do to fix it without a contribution from someone in the open source community. I will be closing this issue for now for upkeep purposes but let me know if you think this issue should still say opened
