### ISSUE TITLE
Bug: (Driver?) Issues when using other apps that interfere with audio I/O

### ISSUE THREAD

**Issue by erikhuizinga** [bitgapp/eqMac#337]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

#41, #129, #185, #291 seem related.

**Describe the bug**

EqMac works fine for me, except when using other apps that interfere with audio I/O / devices / ???

**Steps to Reproduce**

Two symptoms of the issue. These might be two separate issues.

Issue with Android emulator:

1. Start eqMac
1. Play music
1. (ensure all is well)
1. Start an Android emulator
1. Notice that when the emulator is started, sound loops the last 200 ms (or so) forever, instead of continuing normal undisrupted playback.

Issue with (Philips) Hue Sync:

1. Start Hue Sync
1. Enable 'Use audio' setting in Hue Sync
1. Start light sync
1. Start eqMac
1. Driver install fails (see numerous other issues)
1. (Hue Sync also doesn't work properly anymore. I assume that both apps do something with audio I/O and undo each others changes).

**Expected behaviour**

The ability to start other audio I/O applications without eqMac or the other applications stopping working.

**Setup information:**

 - Audio device used for playback: headphones
 - Audio transmission interface: jack port of MBP
 - macOS Version: 10.14.6 (18G5033)
 - eqMac Version 0.3.2
 - eqMac UI Version: 1.2.1 (Remote)

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by superjeng1** [comment]
Hi, it has been a long time since you posted this issue and I think this bug has been fixed. If you are still observing this issue, you are more than welcome to reopen it.
