### ISSUE TITLE
Many buttons not responsive; can't switch out of Basic mode; MID and TREBLE dials disappear when turned

### ISSUE THREAD

**Issue by ghost** [bitgapp/eqMac#340]
Just installed, and having a lot of GUI issues. All these buttons and other elements are totally unresponsive:

- Green triangle next to "Basic Equalizer"; can't switch to Advanced Mode.
- Either the + or - buttons.
- The switch above the - button.
- The Select Output menu. I would imagine I could choose between my internal speakers and BlueTooth speaker, but there are no options or response to clicking the menu.

In addition, the MID and TREBLE dials disappear when I turn them, though if I can guess where to click, I can still turn them. The BASS dial does not have this problem.

Using Mac OS 10.12.6 on iMac (21.5-inch, Mid 2011). Thank you for any help!
![Screen Shot 2020-07-18 at 7 08 50 PM](https://user-images.githubusercontent.com/42849345/87863561-27194b80-c92a-11ea-97a1-f8af7d988e40.png)

**Comment by shubham1g5** [comment]
+1 facing the same exact issue as well with mac OS 10.12.6

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
I have now managed to install Virtual Machines of macOS 10.10 and 10.12 and experienced your problem. 
This is to do with a very outdated WebKit version shipped with your OS version.
Unfortunately not a trivial fix, especially on 10.10 but I think should make it work on 10.12.
Another option for you guys is to update to macOS 10.14 or newer. If you Mac is very old you might be able to use: http://dosdude1.com/software.html

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by nodeful** [comment]
This has been resolved a while ago, closing issue
