### ISSUE TITLE
Bug: Volume control disappears when running app on MacOS 10.14.3

### ISSUE THREAD

**Issue by kristianpresnal** [bitgapp/eqMac#341]
Bug:
Basically, whenever I use the app, I can't control the computer's volume level. The touch bar volume slider stops working. I can mute, but that's it. The volume tool in the app itself doesn't work either.

Obviously, I should be able to change the computer volume without this issue. I don't really know anything about software engineering and such, so I'm afraid I can't give much detail on the specifics.

**Setup information:**
 - Audio device used for playback: Sony WH-1000XM2 Headphones
 - Audio transmission interface: Bluetooth
 - macOS Version: 10.14.3 
 - eqMac Version 0.3.2
 - eqMac UI Version 1.2.1

I tried re-downloading the app, but that didn't help.

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago. 
Closing for now, any new issues with eqMac should be submitted through the website.
