### ISSUE TITLE
Bug: The sound sizzle

### ISSUE THREAD

**Issue by Firecowbruh** [bitgapp/eqMac#345]
Sometimes the sound start to sizzle since I've installed eqMac, and that's very annoying. I'm using a 2019 15" macbook pro, I already tried to restart my mac, reinstall eqMac and his drivers but nothing changed.

**Comment by FCCTech** [comment]
I have the same issue.  Typically, I get the "sizzle" sound when there are multiple applications that may be trying to use the Mac audio system (Skype, Teams, Zoom, system sounds, etc.).  Usually, I can eliminate the 'sizzle' by switching to another output device (internal speakers or headphone port), but sometimes when I try to switch eqMac will crash resulting in a continuous audio loop that can only be eliminated by restarting.

**Comment by erwinxxx** [comment]
Still this issue even under 0.3.2. and update the audio driver.

**Comment by MetroMayhem** [comment]
Seeing this issue, 16" MacBook Pro on Catalina 10.15.7, version 0.3.6, driver version 1.2 while playing Spotify.

**Comment by rririanto** [comment]
I also experience this while upgrading to the new version eqMac Beta v0.3.7 with Big Sur OS. I even try to use reset playback but it doesn't work. I can only solve it by restarting the mac which is not a good solution. Here's the sound I attached
[Voice 094.m4a.zip](https://github.com/bitgapp/eqMac/files/6112572/Voice.094.m4a.zip)

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by sporkisfaster** [comment]
@nodeful Issue still persists. Force quitting/restarting the Core Audio Driver fixes it.

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
