### ISSUE TITLE
Totally uninstall EqMac? Install EqMac2

### ISSUE THREAD

**Issue by erwinxxx** [bitgapp/eqMac#348]
I want totally uninstall EqMac. I know how I do this with the terminal command and sudo rm but if I do this there are still files left behind as I look at my app Find Any File, also I can't delete. So how can I delete all the files from EqMac?
I wanna install EqMac2 again. Someone knows where I can find this older version?

**Comment by mgutierrezz** [comment]
I use this app called app cleaner, it does a pretty good job removing hidden files
[AppCleaner](https://freemacsoft.net/appcleaner/)

**Comment by erwinxxx** [comment]
Ok, thanks. And where can I find the older EqMac2 installer?

**Comment by erwinxxx** [comment]
I found the EqMac2 installer but it don't work after installing the audio driver. The icon leaves my systemtray and it don't work. Try to reinstall EqMac and it works from stretch so with install the drivers and also made a new preset. Hope this helps for my problems with EqMac.

**Comment by mgutierrezz** [comment]
My EqMac2 wouldnt work either when i tried to reinstall, what you need todo is uninstall everything, restart, install eqmac2 and restart one more time

**Comment by erwinxxx** [comment]
I deinstall everything, EqMac first and than install EqMac2 but after a restart again the message for install drivers, fill in my password from my Mac but crashed after that and it's not working.

**Comment by nodeful** [comment]
I have added instructions on the new website's FAQ on how to uninstall the new eqMac: https://eqmac.app#uninstall
And here's the binary for the latest version of the old eqMac2 if you still need it: https://github.com/bitgapp/eqMac/releases/tag/V0.0.0
