### ISSUE TITLE
Not starting on Mac 10.15.6

### ISSUE THREAD

**Issue by dynamitechetan** [bitgapp/eqMac#349]
**Describe the bug**

```
2020-07-31 20:51:05.653 eqMac[27621:4647110] Sentry Started -- Version: 4.5.0
eqMac (Source/Application.swift:184) Setting up Audio Engine
Error: 2003332927 ->  /Users/romanskisils/Programming/Bitgapp/eqmac/native/app/Source/Audio/Sources/System/Driver.swift:123

ERROR: SentryCrashMachineContext.c (232): void sentrycrashmc_resumeEnvironment(): thread_resume (0000da07): (os/kern) object terminated
[1]    27621 segmentation fault  /Volumes/eqMac/eqMac.app/Contents/MacOS/eqMac
```
**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Download latest app
2. open the app

**Expected behaviour**
Should start eqMac

**Setup information:**
 - Audio device used for playback:  Macbook speaker 
 - macOS Version: [e.g. 10.15]
 - eqMac Version Latest
 - eqMac UI Version [e.g. 0.0.4] **(if UI related issue)**

**Comment by EstebanVargas10** [comment]
Same here :( 

![image](https://user-images.githubusercontent.com/12404128/89137482-80ba7200-d4f5-11ea-9535-56ba9c885df3.png)

**Comment by florent-haffner** [comment]
Same here, without the error pannel :'(

Other similar issue : https://github.com/bitgapp/eqMac/issues/356

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
This issue will be related to #328 
Driver API is not registering for some reason. Please refer to that issue from now on.
