### ISSUE TITLE
Bug: Audio Driver starts to crackle after approximately 45 Minutes

### ISSUE THREAD

**Issue by mwansing** [bitgapp/eqMac#353]
**Description**
After about 45 minutes, the Driver starts to crackle. I have to change audiosource or reset playback to go back to normal.

**Steps to Reproduce**
eg. Listen to music for 45 Minutes

**Setup information:**
 - Audio device used for playback: External headphones and USB C Audio out (both crackle)
 - Audio transmission interface: 3.5mm Jack, USB c
 - macOS Version: 10.15.5
 - eqMac Version : v0.3.2

**Additional information**
On my previous MacBook I used eqmac2 without any problems (mac OS 10.14) but I cant seem to make any eqMac Version work flawlessly now

**Comment by Xardas220** [comment]
I have the same problem. The longterm fadein-crackle problem is gone. But there is a second problem with crackling so as you described it. There are after some time little crackle. Like viny-crackling and not specific to bass, midds or highs. It's random after some time. Reset playback fixes the problem for some time before it comes back.

Audio device used for playback: External USB Dac + Amplifier
macOS Version: 10.15.6
eqMac Version : v0.3.2 (cleaninstall after update to 10.15.6)

**Comment by cg-admin** [comment]
same issue expect its about every 15-30 seconds

**Comment by Reiszecke** [comment]
Following. Would love to take care of this but I have only worked so much with real time audio processing.

To me it sounds like the CPU can't satisfy the audio buffer in time. Finding out as to why that is is one thing, but increasing the buffer size may already reduce the frequency of this issue happening. I'm unable to locate any buffer size selector in the UI, is there one?

**Comment by Reiszecke** [comment]
No need to say sorry, your app already helped me so much as-is. I love improvements but you already made me a happier person with the previous versions

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by benj-o** [comment]
Congratulations on 1.0

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
