### ISSUE TITLE
Bug: Balance Level doesn't work

### ISSUE THREAD

**Issue by howtobanana** [bitgapp/eqMac#354]
**Description**
After changing the balance in the eq settings to (example 60% left) I can not go back to the stock settings with 100% on both, left and right.

I tried to uninstall the driver inclusive the app and reinstalling it. Even with App cleaner wehere it should delete all related files it doesn't fix the issue. After every reinstallation I have the exact same settings (in my case 60% left) as before.

**Setup information**
Audio transmission interface: Digital Output
macOS Version: 10.14.6
eqMac Version : v0.3.2

**Comment by nodeful** [comment]
This should be fixed now. Over the air update, so no update of eqMac required
