### ISSUE TITLE
Feature request: Spectrum analyzer

### ISSUE THREAD

**Issue by PaulGrill** [bitgapp/eqMac#364]
Dear developer team!

First of all thank you for the massively helpful application! I love eqMac to death!
I just want to come up with a feature request: Is it possible to implement a spectrum analyzer? That would help to find frequencies that have to be EQed. 

Thank you so much and keep up the good work!

BR
Paul

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
I have already implemented this feature and it should be shipped in v1.0.0 under the Expert EQ, so keep an eye out for in the next couple weeks.

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Spectrum Analyzer is implemented as part of the Expert Equalizer
Thanks again.

Roman
