### ISSUE TITLE
Bug: Drivers not installing and audio not going through

### ISSUE THREAD

**Issue by Tabyoshi** [bitgapp/eqMac#365]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Whenever I try and install/reinstall the audio driver it fails/crashes the application

**Expected behaviour**
the driver would install normally

**Setup information:**
 - Audio device used for playback: [Pair of cheaper headphones I got a while ago]
 - Audio transmission interface: [3.5mm Jack]
 - macOS Version: [e.g. 10.15.5]
 - eqMac Version [0.3.2] **(if audio related issue)**
 - eqMac UI Version [e.g. 0.0.4] **(if UI related issue)**

**Comment by tcz305** [comment]
yes it has, a few posts below

https://github.com/bitgapp/eqMac/issues/356
