### ISSUE TITLE
Feature: Seperate selection for Audio Input and Output

### ISSUE THREAD

**Issue by dc10023** [bitgapp/eqMac#366]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
Currently you a single Audio to connect for both mic/input and speaker/output. So if I select an source that only has speaker and no mic (for example Monitor with build in speakers but no microphone), I lose microphone capability. It would be nice to be able to select one source for speakers and another for microphone. 

**User flow & interface:**
Need a separate input box for Input/Mic below Output/Speaker drop down box.

**Comment by nodeful** [comment]
Just go to system preferences > Audio > Input and select your preferred microphone. eqMac doesn't force you to have a certain input device selected.
