### ISSUE TITLE
Bug: Undefined audio output

### ISSUE THREAD

**Issue by KasparRosin** [bitgapp/eqMac#367]
Recently a undefined output has shown up in my output dropdown that is overlapped with label (CADefaultDeviceAggregate-54109-4). Upon choosing the option, the app craches. There have been other instances when 
the app has crashed randomly when switching outputs, but not sure whether those are related to this issue.

**Setup information:**
 - macOS Version: 10.14.6
 - eqMac UI Version: 1.2.1
 - eqMac App Version: 0.3.2
 - eqMac Driver Version: 1.1.1

![Screenshot 2020-09-19 at 15 02 31](https://user-images.githubusercontent.com/33309407/93666833-d5a44e80-fa89-11ea-813a-4672946e8503.png)
![Screenshot 2020-09-19 at 15 14 37](https://user-images.githubusercontent.com/33309407/93666943-e2757200-fa8a-11ea-93d3-2d6dc5c8a056.png)

**Comment by nodeful** [comment]
This should now be fixed. No update of eqMac required

**Comment by KasparRosin** [comment]
Thank you!
