### ISSUE TITLE
Bug: Missing askpass.sh when running build.sh?

### ISSUE THREAD

**Issue by Takuro-Ito** [bitgapp/eqMac#368]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
I can't build `Driver-Debug` _Target_ successfully.
When I build `Driver-Debug` _Target_ in Xcode, the following error is output.
```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
```
I guess missing `askpass.sh` file causes this build error.
Could you include `askpass.sh` to this repository so everyone can build & run.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Follow [this](https://github.com/bitgapp/eqMac#building-and-running-the-app) instruction in README.md.
2. Open `eqMac.xcworkspace`
3. Fix location to `Scripts/build.sh` in Xcode as xcodeproj points different location.
3. Change `Team` in _Signing & Capability_, if necessary.
4. Select `Driver-Debug` _Target_.
5. Hit Command+B (Build).
6. You see build error.

**Expected behaviour**
Success to build.

**Setup information:**
 - macOS Version: 10.15.6
- Xcode Version: Version 12.0 (12A7209)

**Screenshots or Console.app logs**
<img width="1777" alt="image" src="https://user-images.githubusercontent.com/12025248/93714448-9f57f380-fb9d-11ea-8da8-6017db4ec852.png">

**Comment by nodeful** [comment]
The askpass is meant for running a sudo command during the Debug process. This is needed to install the driver in the right location. If you want to just build the driver use the Release Scheme. If you really want to run it in Debug then please create a `~/askpass.sh` file yourself. It should look like this:
```
#!/bin/bash
echo YOUR_SUDO_PASSWORD
```

**Comment by Takuro-Ito** [comment]
Creating `~/askpass.sh` and changing `sudo` to `sudo --askpass` (or `sudo -A`) solved this issue.

<details>
<summary>build.sh</summary>

```sh
#!/bin/sh
# Type a script or drag a script file from your workspace to insert its path.
if [ "${CONFIGURATION}" = "Release" ]; then
    cp -r "$BUILT_PRODUCTS_DIR/$FULL_PRODUCT_NAME" "$SRCROOT/../app/Embedded/"
fi

if [ "${CONFIGURATION}" = "Debug" ]; then
    export SUDO_ASKPASS=~/askpass.sh
    # Uninstall any new driver leftovers
    sudo --askpass rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/
    # Install the new driver
    sudo cp -f -r "$BUILT_PRODUCTS_DIR/$FULL_PRODUCT_NAME" /Library/Audio/Plug-Ins/HAL/
    # Restart CoreAudio
    sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod
fi
```
</details>

Just to be sure, how do you run without `-A` option for `sudo` with `$ASK_PASS` on your machine? 
Thanks!
