### ISSUE TITLE
Sometimes a short distortion in the sound

### ISSUE THREAD

**Issue by erwinxxx** [bitgapp/eqMac#369]
Sometimes I have a little distortion in the sound for 2/3 seconds and than it's back to normal. What's that and how can I fix this or is this a bug?

UI version 1.2.1. Version: 0.3.2. Driver version 1.1.1.

**Comment by erwinxxx** [comment]
Nobody have a fix for this? It's annoying.

**Comment by kshitijdeota** [comment]
This issue is same as  #345
