### ISSUE TITLE
Bug: eqMac2 Will not Install from Download on Catalina 10.15.6

### ISSUE THREAD

**Issue by kkathman** [bitgapp/eqMac#370]
Upon downloading the package (eqMac2.dmg) the installation informs of the need to install a driver, then asks permission to allow the local password to be entered. However, when this is done, the dialog goes away and there is no installation done. Subsequent attempts to run the installer proceed with the same steps as if a brand new install.  Attempted to uninstall and re-install with no resolution.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Download the current version at the source site.
2. Run the DMG file
3. When prompted, move the app to Applications
4. Launch the app in Applications
5. Click to run the program
6. When prompted, enter system password to allow install of driver.

Note that here, the dialog goes away and any subsequent attempts to launch the .app will begin the install process again.

**Expected behaviour**
Expected the driver to be installed, and the program to execute and run.

**Setup information:**
 - Audio device used for playback: Mac Speakers
 - Audio transmission interface: Internal standard
 - macOS Version: 10.15.6
 - eqMac Version: Unknown as the program never loaded
 - eqMac UI Version: Unknown as the program never loaded
Assume most recent version based on the green DOWNLOAD bar.

**Comment by virtustilus** [comment]
@kkathman Hello! Please, don't try to use "eqMac2" on Catalina or any next MacOS releases, as it's very old project and won't work. Use last versions: eqMac 0.3.2 or wait for eqMac 0.3.4
