### ISSUE TITLE
Bug: spinning ball in menu bar when launching with BackgroundMusic already running

### ISSUE THREAD

**Issue by hoondi** [bitgapp/eqMac#371]
[BackgroundMusic](https://github.com/kyleneideck/BackgroundMusic) enables me to manually control audio levels of every running process as well as set left and right balance of every process.

When I launch eqMac after BackgroundMusic is already running, I get spinning ball in menubar and eqMac's menu never responds.
Not hard to get around, but figured I'd let you guys know.

Just so you know:
I'll often have 3 zoom meetings going on at once(supporting people during university exam sessions), and use BackgroundMusic to put meeting 1 in left ear only, meeting 2 in right ear and the third meeting at 60% volume in both ears. Madness, but it works.

macOS 10.15.6 (19G2021)
MacPro 6,1

Regards,

**Comment by nodeful** [comment]
BackgroundMusic and eqMac are based on the same driver codebase provided by Apple. I don't think they can work together in unison at all and I don't plan to try support that. The plan is to have the app volume mixer feature in eqMac at some point.
