### ISSUE TITLE
macOS 10.15.7: Driver failed to activate

### ISSUE THREAD

**Issue by EstebanVargas10** [bitgapp/eqMac#374]
![image](https://user-images.githubusercontent.com/12404128/94375255-a2883d80-00cf-11eb-9b1b-b128f25f7fb0.png)

**Comment by ninjit** [comment]
Just started seeing the same error

**Comment by ninjit** [comment]
Was able to fix by following instructions in this issue #372

**Comment by EstebanVargas10** [comment]
Thanks @ninjit 
Worked for me.

**Comment by nodeful** [comment]
Have you guys tried v0.3.6? Closing issue for now until further info.
