### ISSUE TITLE
Incorrect uninstallation instructions on the website's FAQ

### ISSUE THREAD

**Issue by claudio-silva** [bitgapp/eqMac#375]
On the website's FAQ, on "*Question: How do I uninstall eqMac?*", the answer currently says:
```
sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/ && launchctl kickstart -k system/com.apple.audio.coreaudiod &>/dev/null
```
The second command (`launchctl`) is incorrectly called without `sudo` and it **will fail**, but as the output is suppressed (via `>/dev/null`), the user cannot see that it fails.

Solution:

`sudo` must be prepended to `launchctl`.
Furthermore, the output supression is not needed, as the `launchctl` produces no output, so it should be removed, because it may deceive the user, making him/her believe the command succeeded, when it may fail for some reason (it happened to me).

Please change the line to:
```
sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/ && sudo launchctl kickstart -k system/com.apple.audio.coreaudiod
```

**Comment by claudio-silva** [comment]
Also, should the uninstallation steps include this?
```
sudo /Applications/eqMac.app/Contents/Resources/uninstall_driver.sh
```
As seen on #372

It seems the FAQ's uninstallation command does not remove the driver; for if I run this command afterwards, it runs, and says "Device removed".

Also, the uninstallation instructions do not mention dragging the app to the trash can. Perhaps a `rm -rf /Applications/eqMac.app` should be included?

**Comment by erwinxxx** [comment]
I also can't full uninstall EqMac with the app AppCleaner. When I looking for left behind files in the Find Any File app I still see files when I search for 'EqMac'. How I get rid of these files? I can't remove them when I try it to move them immediatly or move it to the trashcan. How is that possible?

**Comment by nodeful** [comment]
I have completely revamped the site now for release of v1.0.0 and here's the url for the updated FAQ: https://eqmac.app#uninstall
