### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by plimitone** [bitgapp/eqMac#376]
**Describe the bug**
eqMac crashes when starting the application

**Steps to Reproduce**
1. Double click the eqMac icon in the dock

**Expected behaviour**
eqMac should start without an error and be ready for use

**Setup information:**
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro10,1
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  Boot ROM Version:	262.0.0.0.0

**Screenshots or Console.app logs**
crashlog is attached

**Additional information**
This was occurring last week but I dismissed it as a eqMac issue because I was in the process of installing an overdue MacOS update. However today the crash upon startup has been consistent.
[crashlog-10-3-20.txt](https://github.com/bitgapp/eqMac/files/5322198/crashlog-10-3-20.txt)

**Comment by snooz3r** [comment]
same issue and I can't get it to run anymore

**Comment by ssent1** [comment]
# eqMac always hangs on startup

![eqMac always hangs on startup](https://i.imgur.com/q32dslC.png)
This is all I see. That's it. Just a white window.

![eqMac - right-click >> Reload](https://i.imgur.com/1E0PWDv.png)
When I right-click, it displays a dialogue box that says, **Reload**. In **Activity Monitor**, I can see eqMac responding to the right-click. But, it returns to the same white window.

Despite, the eqMac window partially loading, it neither displays any **Menu Bar** info nor does it appear in the **Application Switcher**.

![eqMac in Mission Control](https://i.imgur.com/ulC2SaN.png)
It makes an appearance in **Mission Control**.

![eqMac in Activity Monitor](https://i.imgur.com/ssfAbZr.png)
eqMac shows up in the Activity Monitor — temporarily.

## Hardware

| item             | value                                |
| :--------------- | :----------------------------------- |
| Operating System | macOS **Mojave**                     |
| Version          | 10.14.6 (18G6042)                    |
| Model Name       | iMac Retina 5K, 27-inch, Mid 2015    |
| Model Identifier | iMac15,1                             |
| Processor        | 3.3 GHz Intel Core i5                |
| Memory           | 24 GB 1600 MHz DDR3 (2×8 GB, 2×4 GB) |
| memory_Type      | 1600 MHz DDR3                        |
| Graphics         | AMD Radeon R9 M290 2048 MB           |

## Console Log >> Errors and Faults

[eqMac-Console_Log_Errors_Faults.log](https://github.com/bitgapp/eqMac/files/5656280/eqMac-Console_Log_Errors_Faults.log)

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
@plimitone this issue is related to #328, #339, #349, #356
@ssent1 your issue is related to #346 
Will be closing this issue, please refer to the issues I've mentioned

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Thanks again.

Roman
