### ISSUE TITLE
Bug : Not workin with Big Sur Beta 9 

### ISSUE THREAD

**Issue by TurannUl** [bitgapp/eqMac#377]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [ ] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):

**Expected behaviour**

**Setup information:**
 - Audio device used for playback: [eg AirPods or Macbook speaker or Bose QC32] 
 - Audio transmission interface: [eq HDMI or Bluetooth or 3.5mm Jack] Usb Headphones
 - macOS Version: [e.g. 10.15] 11.0 b9
 - eqMac Version [e.g. 0.0.1] **(if audio related issue)** Not workin
 - eqMac UI Version [e.g. 0.0.4] **(if UI related issue)** -
[EQMac Bug Reporting.zip](https://github.com/bitgapp/eqMac/files/5322497/EQMac.Bug.Reporting.zip)

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 
I added all details
**Additional information**
Incompatible with 11.0 Beta (20A5384c), microphone access not requested, Cannot start later

**Comment by TurannUl** [comment]
label:fix

**Comment by TurannUl** [comment]
@nodeful

**Comment by sunchensheng** [comment]
ME too！！

**Comment by TurannUl** [comment]
Driver now works 👍 , cannot give microphone access still not working :(

**Comment by nodeful** [comment]
Have you tried latest v0.3.6 version?

**Comment by TurannUl** [comment]
> Have you tried latest v0.3.6 version?

Sorry for late reply Updated App works,Driver too but cannot give microphone access Added Screenshot

**Comment by TurannUl** [comment]
![Uploading Ekran Resmi 2020-10-30 02.32.53.png…]()

**Comment by TurannUl** [comment]
label:support

**Comment by TurannUl** [comment]
Priority:medium

**Comment by TurannUl** [comment]
Works with Big Sur RC Thanks for Support Issue Closed
