### ISSUE TITLE
Bug: I can't go from "basic equalizer" to advanced.

### ISSUE THREAD

**Issue by Damiortiz** [bitgapp/eqMac#383]
hello, good day. 
I can't go from "basic equalizer" to advanced. I can't change the audio output either. And the menu looks like the screenshot I'm taking. 
I have MacOs Sierra 10.12.6
Thank you very much.

![Captura de pantalla 2020-10-12 a la(s) 21 31 16](https://user-images.githubusercontent.com/57038552/95802039-b5eff700-0cd2-11eb-99b8-55079fc1f5fd.png)

**Comment by nodeful** [comment]
It's a common issue with older version of macOS.
Is the UI still broken if you open https://ui-v1.eqmac.app/ with Safari browser?

**Comment by Damiortiz** [comment]
> It's a common issue with older version of macOS.
> Is the UI still broken if you open https://ui-v1.eqmac.app/ with Safari browser?

Hello! No, it doesn't work.

**Comment by nodeful** [comment]
@Damiortiz can you please try opening eqMac again to see if it works now?

**Comment by Damiortiz** [comment]
> @Damiortiz can you please try opening eqMac again to see if it works now?

Now it works, it even looks like it should. When I switch to advanced equalizer it closes only after 2 seconds. (Sorry my bad English)

**Comment by nodeful** [comment]
So issue closed then

**Comment by Damiortiz** [comment]
thank you very much!
