### ISSUE TITLE
eqmac not loading since recent changes

### ISSUE THREAD

**Issue by elf10** [bitgapp/eqMac#385]
Since your most recent changes several days ago, app does not work in catalina 10.15.7.  It opens and then immediately closes. I have never had this problem before now. I have completely deleted the program and downloaded the new version and the problem is still happening.  This is happening on two different devices an iMac and a MacBook Pro.  It is exactly the same problem on both.

**Comment by nodeful** [comment]
I need logs and more information in general. Please follow the Bug Issue template. This issue will be closed until further information is provided.
