### ISSUE TITLE
Music blanks, eqMac & Background Music crashes when used with Background Music (system wide per app volume control)

### ISSUE THREAD

**Issue by caesarsamsi** [bitgapp/eqMac#387]
**Bug info**
Sound on Mac Pro is lost when Background Music is installed

**Steps to Reproduce**

	1. MacOS High Sierra, latest updates as of 10/19/2020
	2. Install Spotify. Verify that music plays through internal speaker or headphone jack
	3. Install eqMac and launch. 
		a. eqMac launches behind Finder
		b. Music is switched from headphone jack to eqMac (as expected).
		c. Music is played at very low volume (unexpected)
			i. Main Mac volume is at 50%
		d. Switch foreground app to eqMac
		e. eqMac button (middle left) switches from black red to green black
		f. Music is played at very low volume, even if eqMac volume was set to higher volume before relaunch
	4. Install Bacground Music (https://github.com/kyleneideck/BackgroundMusic)
		a. Music blanks out twice during installation but comes back
		b. Background Music is auto launched by installation (I can see its double off center circle icon on the menu bar). Verify music still plays.
		c. eqMac crashes (not stopped manually, the Ignore, Reopen, blargh dialog is shown).
		d. Clicking on Mac's volume menu icon shows Background Music is selected as Output Device
	5. Relaunch eqMac, it launches in the background, menu icon shows, music blanks out
		a. Click on eqMac menu icon, eqMac goes foreground, switch moves from red to green.
		b. Music blanks out. I have to click on eqMac's volume slider left and right to get music going again.
		c. Output Device is now eqMac (NOTE: eqMac overrides Device Output setting which was Background Music before. This is unexpected).
	6. Tried to set Output Device back to Background Music (I like it because it lets me set different volumes for different apps).
		a. Music blanks out
		b. Output Device is still eqMac (unexpected)
		c. Background Music has crashed silently (menu icon gone, app is no longer in Activity Monitor Process Name list, so gone gone, really).
	7. Click on eqMac menu icon, still no music
		a. Tried clicking on volume slider as before, it behaves
		b. Tried clicking on Output Device, eqMac unresponsive, menu icon is there, beach ball when hovered. Command Tab shows eqMac, but can't switch to app.
	8. Activity Monitor shows eqMac and eqMac Web Content not responding. Others are responding
	9. Killed eqMac, everything killed.
	10. Still no sound
	11. Relaunch eqMac, still no sound
	12. Click on menu item, eqMac goes foreground but switch is now red, then turns green.
	13. Same trick as before clicking on volume slider brings music back.
	14. Background Music is still listed as Mac Output Device option. It is not listed in eqMac.
	15. Interestingly enough clicking on Reset Playback stutters music then kills it completely. Same trick as before (#13) brings music back.

I know a little about audio/video. Processing them usually follows a flow with filters chained one to the other linearly.

So you have Input Filter (pick a source to use) -> Filter 1 (say passes high frequencies) -> Filter 2 (say increases volume) -> Output Filter (pick a music playback to use)

Here's where it gets interesting:
	1. eqMac seem to insert itself as the last filter in the chain. From the eqMac's Output Device list, it really seems to be the last (after Output Filter) as only some select Output Devices are shown. These are gone:
		a. Background Music (I use this to set different volumes for different apps).
		b. SoundFlower (I use these to record screen captures)
	2. When it inserts itself in/out it doesn't do so cleanly, it just drops the music on the floor instead of buffering it _before_ the switch is made, and playing the music _from_ the buffer while the switch is made.

Please make eqMac behave with Background Music. Better if you fix the filter chain behaviour.

It's got bugs but for the most part it works just fine. Except for the bugs with Background Music.

Here is their source code again: https://github.com/kyleneideck/BackgroundMusic

You really don't want me to muck in yours or theirs … https://github.com/bitgapp/eqMac

**Expected Behavior**
Music plays smoothly.
Apps don't crash (see repro on where crashes occur).

**Setup information:**
 - Audio device used for playback: Plain old Headphone 3.5mm jack into an external bookshelf amplified speaker (Bose something something)
 - Audio transmission interface: 3.5mm jack
 - macOS Version: High Sierra 10.13.6
 - eqMac Version: Driver  1.1.1
 - eqMac UI Version: UI 1.2.2
 - eqMac App: 0.3.2

**Screenshots or Console.app logs**
Sorry … didn't think to do this

**Additional information**
Just make it work with Background Music and announce it when you do (I've no idea where to sign up for notification: cmsamsi@hotmail.com)

**Comment by GarageMan** [comment]
I would kindly ask the developers to enable that solution.
Both applications are great, but not working together.

With regards

.:. lutz

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
This issue is a tricky one because both apps use practically the same driver and same approach of grabbing system audio. eqMac needs to allow using BackgroundMusic as the Output Device. I will try to play around with it and see what I can do, but no promises. In the future I'm planning to implement a Volume Mixer inside eqMac, but not sure when that's going to happen

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago plus eqMac now has its own Volume Mixer.
I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
