### ISSUE TITLE
Crash When Opening (Catalina 10.15.6)

### ISSUE THREAD

**Issue by plimitone** [bitgapp/eqMac#393]
**Describe the bug**
MacEq crashes immediately upon startup

**Steps to Reproduce**
Steps to reproduce:
1. Double click the MacEq icon to start

**Expected behaviour**
MacEq should start and be ready to use without any errors

**Setup information:**
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro10,1
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  Boot ROM Version:	262.0.0.0.0
  SMC Version (system):	2.3f36

MacEq version = 0.3.2

**Screenshots or Console.app logs**
crash log attached
[MacEQCrash-10-24-2020.txt](https://github.com/bitgapp/eqMac/files/5433801/MacEQCrash-10-24-2020.txt)

**Additional information**

**Comment by BuonOmo** [comment]
I'm not sure what is meant by _crash_ here, but I may have the same issue:
<img width="629" alt="Screenshot 2021-01-03 at 01 21 22" src="https://user-images.githubusercontent.com/11378424/103469208-189ce000-4d62-11eb-9eb1-b4d4c533c7f0.png">

And looking a bit more in depth I could see that it was in deed not installed. Shall I open a new issue or is this the same bug ?

Unfortunately my knowledge of Mac applications or swift is way too insufficient for me to tackle such an issue by myself

**Comment by nodeful** [comment]
This issue is related to these: #328, #339, #349, #356, #376, #393
@BuonOmo your issues is related to these: #291, #325, #327, #330

**Comment by BuonOmo** [comment]
@nodeful Don't know if it might help with your triage, I've updated eqMaq, it now works. (thanks for the work!)
