### ISSUE TITLE
Feature request: add "donate" button

### ISSUE THREAD

**Issue by berlingozzo** [bitgapp/eqMac#398]
This may be the first time one ever asks for this feature. But I'm a fun of free software, and, when this provides value to me, I'd like to have a way to reward the author(s). 
Please add a donate button somewhere so people like me can donate to this project.
If you think I'm too kind, look at my other open issue :)

**Comment by nodeful** [comment]
I'm working on having extra paid cool features in eqMac soon. If you'd like to support my effort in the future you will be able to contribute by purchasing those "Pro" features :) Thank you

**Comment by nodeful** [comment]
eqMac Pro has now been released: https://eqmac.app
Thank you for your support!
