### ISSUE TITLE
Data privacy: elaborate on what data is collected, where it is stored, who the Data Controller and Processors are (compliant to GDPR)

### ISSUE THREAD

**Issue by berlingozzo** [bitgapp/eqMac#399]
You mention in the LICENSE that you may collect usage and personal data. However you don't specify which data you collect, where it is stored, who the Data Controller and Data Processor are.
Please issue a GDPR compliant statement about this.

**Comment by nodeful** [comment]
Yeap, I do need to be more clear on that. But I didn't mention anywhere that I am collecting any data either. Just FYI I don't collect ANY personal information at all. Just anonymous statistics about macOS version and country of the user, but is in no way tracable back to the user. There are no accounts to create, I don't collect emails or anything, even though I probably should :)

**Comment by berlingozzo** [comment]
hi, thanks for your response. What you write here conflicts with this screenshot from your T&Cs.
Can you please clarify? perhaps I'm missing something? :) thanks
<img width="845" alt="image" src="https://user-images.githubusercontent.com/5732826/97453928-1c5d5200-192e-11eb-8312-663d1fd76892.png">

**Comment by nodeful** [comment]
Meh, common I just slapped a general T&C template from some website that covers my ass in every case. I'm just a one man doing this project + some contributions from the community, I don't have the resources to hire a lawyer to assemble a tailored T&C for me, nor do I have the time to cherry pick points myself :) The app is free and open-source. Anyone can remove or add anything, then build it from Source locally and run it if not happy with the pre-built distribution. The T&C's will be updated when the time will be right. Building the product - priority number one

**Comment by berlingozzo** [comment]
Works well enough as a clarification to me :)
thanks

**Comment by nodeful** [comment]
I have since updated the T&C's, Privacy Policy and EULA. However please read this to understand the current state of this issue: https://eqmac.app/#privacy-concerns

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
