### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by sathio** [bitgapp/eqMac#4]
It seems that it adds up to half a second lag between video and audio. very noticeable when watching a youtube video

**Comment by nodeful** [comment]
In my initial post I've mentioned that I am aware of that.
The naming for this issue is insufficient I will close this issue

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
