### ISSUE TITLE
Bug: Reset playback button changes volume (to about 50%)

### ISSUE THREAD

**Issue by erikhuizinga** [bitgapp/eqMac#402]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**

The 'Reset playback' feature (button in bottom-left corner) changes the output volume to about (I guess) 50%.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Start eqMac, play some music, set volume to lower than 50%.
2. Click on 'Reset playback' (button in bottom-left corner)
3. Notice that, after the reset, the volume _increases_ a bit to, I would guess, 50%.

Now, when changing the volume (e.g. increasing it), then notice that it goes back to the previous lower volume (which is then increased, effectively lowering the volume if it was well below 50% before).

**Expected behaviour**

Either:

- Resetting the playback doesn't change the volume.
- The Reset playback feature is not necessary in the first place.

**Setup information:**
 - Audio device used for playback: analog headphones
 - Audio transmission interface: 3.5mm Jack
 - macOS Version: 10.14.6 (18G6032)
 - eqMac Version: 0.3.6
 - eqMac UI Version 1.2.2 (Remote)
 - Driver version: 1.2

**Screenshots or Console.app logs**

N/A

**Additional information**

N/A

**Comment by mafroew** [comment]
I notice the same thing when selecting a different (or the same) output device - seems to do the same thing as pressing the 'reset playback' button

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by erikhuizinga** [comment]
Seems fixed in v1.0.0. Thank you.

I noticed that when Boost is enabled, increasing volume beyond the middle (normally that's 100%), e.g. 5% boost, then the volume actually decreases w.r.t. the 0% boost (100% normal volume).

Because I don't use boost, I won't open an issue for this problem unrelated to the current issue.
