### ISSUE TITLE
Bug: eqMac crashes with Zoom running simultaneously causing all connected audio/video devices to reset

### ISSUE THREAD

**Issue by bhedavivek** [bitgapp/eqMac#406]
**Describe the bug**
With Zoom running, eqMac consistently crashes causing all connected audio/video devices to crash. Attached crash reports collected from console.app

**Expected behaviour**
eqMac should not crash?

**System Information**
![image](https://user-images.githubusercontent.com/12003668/97911600-5f3d7200-1d00-11eb-8030-7da63f9cb0b5.png)

**Crash Reports**
[eqMac-crash-report-1.txt](https://github.com/bitgapp/eqMac/files/5477577/eqMac-crash-report-1.txt)
[eqMac-crash-report-2.txt](https://github.com/bitgapp/eqMac/files/5477578/eqMac-crash-report-2.txt)

**Comment by SanjayVyas** [comment]
+1
It not only crashes but leaves the audio in an inconsistent state when I have to reboot the mac. Had to uninstall eqMac because I cannot conduct/attend sessions on Zoom.

**Comment by TideGear** [comment]
It doesn't crash on my wife's mid 2011 Macbook Air, but it fails to boost the audio of Zoom at all.
