### ISSUE TITLE
Bug: Balance feature not working. 

### ISSUE THREAD

**Issue by jadouth** [bitgapp/eqMac#407]
When using eqMac's balance feature it does not produce audio when I pan to the left channel on either side. 
When fading to the right channel both speakers emit audio - not just the right channel. So, the balance feature is now just a null volume knob. 

Steps to reproduce the behaviour):
1. Go to 'module'
2. Click on 'balance'
3. Scroll down to 'left and right'

I expect to be able to balance my speakers left and right to adjust audio on my computer.

Setup information:
 - Audio device used for playback: iMac (Retina 5K, 27-inch, Mid 2015) 
 - Audio transmission interface: USB Nobsound® Amplifier with TDL Speakers
 - macOS Version: 10.15.7 (19H2)
 - eqMac Version: 0.3.6
 - eqMac UI Version: 1.2.2(Remote)

**Comment by Reiszecke** [comment]
It's supposedly fixed #363 but it doesn't work for me either.

**Comment by jadouth** [comment]
It seems to work on my iMac internal speakers - but not when plug in an external USB device.

**Comment by henriw1410** [comment]
jadouth, I have the same issue. Also using external usb audio card. Balance works well when sound sent to internal system / headphones etc.  Everything works perfect except for stereo balance.

**Comment by wouzer** [comment]
Same here. Doesn't work on Focusrite Scarlett 2i2. When shifting to the left, the volume minimize to 0 for both left and right channel. When shift to the right, nothing really happens. 
EqMac version: UI Version 1.22.(Remote) Appversoin 0.3.7. Driver versoin 1.2

![image](https://user-images.githubusercontent.com/43588045/111909726-bbf6ba80-8a5e-11eb-95b6-338b4c1c91c5.png)

**Comment by pjpmarques** [comment]
Same issue here. Using an external DAC through USB.

**Comment by oliverlambson** [comment]
Also having the same issue

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
Guys could you please post a screenshot of your preferred device selected in the `Audio MIDI Setup.app` like so:
![image](https://user-images.githubusercontent.com/8472525/120399305-6420dd80-c344-11eb-8115-fe129c3ea667.png)
I would like to see how many channels your device is running and how do they look :) 
Thanks

**Comment by dpolivaev** [comment]
<img width="763" alt="Screenshot 2021-06-04 at 23 52 33" src="https://user-images.githubusercontent.com/1558052/120866364-0f71a280-c590-11eb-9f4a-8a0e4ea863d5.png">
as requested, same issue here

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by dpolivaev** [comment]
Many thanks, the balance works fine now (Big Sur 11.4, mac mini m1)

**Comment by henriw1410** [comment]
Hello dear,
The balance control works perfectly now!
Thank you so much for your input!
Henri 


 iPh

**Comment by dpolivaev** [comment]
And the boost works as well!

**Comment by nodeful** [comment]
Thank you for confirming :) Will be closing this issue then
