### ISSUE TITLE
Bug: When unplugging headphones from Macbook, eqMac detects the change, reverts to internal speakers but no sound.

### ISSUE THREAD

**Issue by mafroew** [bitgapp/eqMac#408]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Unplugging headphones causes audio to stop until output is manually selected

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. eqMac detects headphones being plugged in and the selection changes from the display port audio to headphone audio (speaker in my monitor)
2. unplugging headphones, the selector changes to internal speakers (it has detected the headphones are unplugged).
3. there is no sound until I select an audio source from the drop down list (I can select either internal speakers or display port and it is fine.

**Expected behaviour**
When I unplug the headphones it goes back to the output that was selected prior to plugging them in and sound works.

**Setup information:**
 - Audio device used for playback: Dell U3818dw (monitor speaker), audio technica ATH-ANC33iS (Headphones), MacBook Pro (Retina, 13-inch, Early 2015) (laptop)
 - Audio transmission interface: monitor speaker - display port, headphones - 3.5mm, laptop - internal speakers
 - macOS Version: 10.15.7
 - eqMac Version: 0.3.6
 - eqMac UI Version: 1.2.2

**Screenshots or Console.app logs**
Prior to plugging in headphones
![image](https://user-images.githubusercontent.com/23118120/98327658-2d9e1100-2048-11eb-9173-918241c32aae.png)

After plugging in headphones
![image](https://user-images.githubusercontent.com/23118120/98327698-44446800-2048-11eb-82cf-c574e3f45766.png)

After unplugging headphones (no sound)
![image](https://user-images.githubusercontent.com/23118120/98327720-57573800-2048-11eb-87bc-b0b4e47b23ee.png)

Selecting any option will play audio as expected from the selected device
![image](https://user-images.githubusercontent.com/23118120/98327758-6dfd8f00-2048-11eb-9042-a311be17ec0f.png)

**Additional information**
None

**Comment by badprogramshere** [comment]
This also happens to me on 10.14.6, and it also happens when changing from Internal Speakers to Headphones. The solution I found, aside from re-opening the app, is to create a Multi-Output Device in Audio MIDI Setup, add 'Built-In Output', switch to the device in eqMac, and switch back to the Internal Speakers.

**Comment by mafroew** [comment]
@badprogramshere 
Thanks, your workaround - https://github.com/bitgapp/eqMac/issues/408#issuecomment-723544466 - took me a few times and actually running through it to understand. Is the reason for the multi-output device due to the fact that you  don't have a different output device to select? Whereas I have the monitor speaker (display port audio device).

Simpler solution might be 'reset playback' button (if you haven't already), works for me (for internal speakers/headphones only)

![image](https://user-images.githubusercontent.com/23118120/98615445-c4234880-234e-11eb-9fa0-38cec48fccfe.png)

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
