### ISSUE TITLE
Bug: Serious memory leak!

### ISSUE THREAD

**Issue by claudio-silva** [bitgapp/eqMac#411]
**Describe the bug**
When I'm running the eqMac desktop program, it's memory consumption slowly increases as time passes by.
After  a few hours, it can reach as much as **700Mb** (see the screenshot below), and I believe it will continue to increase.
I notice this because my system becomes increasingly sluggish, and starts swapping data to/from the swap file, because of the lack of free RAM (not totally eqMac's fault, of course, as I usually have a lot of programs opened). 

**Steps to Reproduce**
1. Start eqMac
2. Start Activity Monitor and open the Memory tab
3. Locate the eqMac process
4. Stand by and watch, as memory very, very slowly increases
5. Note that sometimes it also decreases, and oscillates, but it will slowly increase the baseline.
6. After a few hours it will be BIG

If I close the program and reopen it, it starts again at aprox. 30Mb, but it will soon start growing again.

**Expected behaviour**
I don't need an equalizer to eat up all my RAM ;-)

**Setup information:**
 - Audio device used for playback: default
 - Audio transmission interface: none
 - macOS Version: MacOS Catalina 10.5.7
 - eqMac Version: 0.3.6
 - eqMac UI Version: 1.2.2

**Screenshots or Console.app logs**
![Screen Capture on 2020-11-13, at 10 52 22](https://user-images.githubusercontent.com/1999803/99065489-5faaf800-259f-11eb-8d29-73b723d872f7.png)

**Comment by nodeful** [comment]
Interesting observation
![image](https://user-images.githubusercontent.com/8472525/99067266-119fef80-25b3-11eb-94ac-35f70da61027.png)
For me eqMac has been open for the past 8 hours
I will keep monitoring it

**Comment by BenRacicot** [comment]
I believe I can confirm this. eqMac gets an indefinite spinner after running for a bit.

MacBook Pro (15-inch, 2016) Catalina 10.15.7 
2.9 GHz Quad-Core Intel Core i7
Radeon Pro 460 4 GB
Intel HD Graphics 530 1536 MB

**Comment by nodeful** [comment]
The spinner could be related to a crash due to some other reason, not necessarily a memory leak :)

@BenRacicot It's a native app with Web UI, so kinda a bootleg Electron in Swift instead of Node.js 😄

**Comment by tcz305** [comment]
I think I can also confirm this. Same setup as OP. Not as bad as 700mb but after 6 hours at 107, went from 93mb about 30 minutes prior, still rising.

**Comment by karmarube** [comment]
Just came here to say the same thing. I opened up the interface to adjust the volume boost slider and it was super sluggish. Opened up Activity monitor and eqMac was using 1.GB of memory! I've had the app open for several days, if not weeks (since last reboot). I quit the app and reopened and it's now using a more reasonable 34.2MB.

**Comment by jfgodin** [comment]
I have encountered the same problem. After a couple of weeks it was up to 10GB!

MacOS 10.15.7
Mac Mini 2018
Core i7 with 32GB RAM

**Comment by austinbutler** [comment]
Currently at ~600MB for me.

**Comment by DesmondKong** [comment]
Same here. Just hit 700MB+.
eqMac v0.3.6 on macOS Catalina with 16GB RAM.

**Comment by nodeful** [comment]
Took me 3 days of bashing my head against the wall but I think I found the culprit of this issue. Should be fixed in v1.0 that's coming shortly

**Comment by BenRacicot** [comment]
@nodeful What on earth was it?! Thank you for seeing this through though.

**Comment by nodeful** [comment]
@BenRacicot  It was caused by doing too much in the Output Render callback here: https://github.com/bitgapp/eqMac/blob/bb15c079eb11e3106fc0be7be14823341520e169/native/app/Source/Audio/Outputs/Output.swift#L42
There'a whole PID Controller calculation happening many times per second. This function should ideally have as little logic as possible, especially referencing Swift objects. I moved the calculation on a background thread.

**Comment by nodeful** [comment]
![image](https://user-images.githubusercontent.com/8472525/121366989-992fc000-c942-11eb-8db6-068edbaa7bf1.png)
After 40 minutes 47MB RAM Usage, same as it started at

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by claudio-silva** [comment]
Memory consumption has been stable.
Thank you very much for taking this issue seriously.

By the way, version 1.0 is amazing! :-)

**Comment by retorquere** [comment]
For me it was using 700MB after running a few days,
