### ISSUE TITLE
Bug: eqMac 2 crashes when used with external audio interface

### ISSUE THREAD

**Issue by Troubadixderdritte** [bitgapp/eqMac#412]
I tried several times to reinstall the program but it crashes the moment I connect my interface. Strange enough I used the old eqMac-app for some time with the same interface (Audient iD14) without any problems.
MacBook Pro 2018 i5 16 G RAM macOS 10.15.7

**Comment by stevietmoney** [comment]
The same behavior happens when switching from my AirPods to my Focusrite 2i4 interface.  I don't think switching is the issue, but it just plain out doesn't work with the usb interface.

**Comment by nodeful** [comment]
eqMac2 is an outdated and not supported application at this point. Please use the new app. Thanks
