### ISSUE TITLE
Looking for testers: How eqMac works on M1 chip with Rosetta and build an ARM universal build

### ISSUE THREAD

**Issue by nodeful** [bitgapp/eqMac#413]
As people are now getting access to an M1 Macs, would be great if someone would test how eqMac works without any updated to the binary with Rosetta translation. Also I already managed to do a build with Universal binary, I will post it in this issue soon. If anyone has got an M1 Mac and is willing to do some beta testing please make yourself known in this issue! Thank you!

**Comment by freak969** [comment]
Any updates on this? I wanna buy an M1 but I wanna know if EqMac works already on this machine?

**Comment by nodeful** [comment]
Had no responses from anyone yet. Trying to source a M1 16GB RAM machine but they are not easily available yet :( Don't want to go for the 8GB RAM model

**Comment by nodeful** [comment]
But there shouldn't be any dramatic differences. I was already able to build a Universal Binary for the Driver and the App itself, will release it this weekend. Kinda scary that people base their decision to buy a new machine on wether eqMac will work on it or not 😄 but it should be pretty safe to buy I think

**Comment by wildpa** [comment]
I do have an M1 MacBook Air, just installed eqMac and it seems to work.
During installation it asked me to restart Audio or the whole Mac, when I selected to restart the Mac, the Mac restarted and the driver was not installed. Driver installation works only when selecting to restart Audio only.
What i noticed in a few minutes: balance control does not work right, when going to left, it gets louder until like 80% for the right channel, then it gets less loud until its silent when 100% left 0% right. When going to the right it just lowers the volume until its silent when set to 100% right 0%left.

Sorry, English is not my first language, so im not sure if I worded that in a understandable way.

**Comment by nodeful** [comment]
@wildpa I've made a build for M1 chip, could you try it out?
https://github.com/bitgapp/eqMac/releases/tag/v0.3.7
Before you run the installer. Could you please delete this file on your system:
`/Library/Audio/Plug-Ins/HAL/eqMac.driver`. This is so that the installer would install the new M1 native version of the driver. You can do this by running this command in Terminal.app:
`sudo rf -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver`

**Comment by artyvasiuk** [comment]
I am awaiting my M1 Mac delivery by Dec 8. Will help when I have it in hands. Meanwhile you may consider my help with Intel if needed.

**Comment by wildpa** [comment]
The installer ran fine, EQ works as before, but it looks like its still intel.
<img width="812" alt="Bildschirmfoto 2020-11-30 um 10 44 20" src="https://user-images.githubusercontent.com/55982083/100600880-2e9e2780-3302-11eb-9b4b-57844a7f9d46.png">

**Comment by nodeful** [comment]
@wildpa thanks, sorry I think I messed up. What version does the app says it's running?

**Comment by artyvasiuk** [comment]
I checked. It says 0.3.6

**Comment by nodeful** [comment]
Sorry lads, clearly made a mistake here. I'll reupload the v0.3.7 and will let you know

**Comment by oinkbark** [comment]
I downloaded the pkg from the 0.3.7 release tag and it runs fine for me on 16GB RAM m1 mac mini.

0.3.6 from the website would not even run.

**Comment by nodeful** [comment]
Guys I have reuploaded the correct version here:
https://github.com/bitgapp/eqMac/releases/tag/v0.3.7
Please try again and report back on how it went 😄 
I appreciate your help and patience

**Comment by artyvasiuk** [comment]
Just tried 0.3.7 on Intel MacBook Air - works fine here. Mind the balance issue mentioned by @wildpa above. No special steps to reproduce - simply try making Left only signal :)

**Comment by nodeful** [comment]
@artyvasiuk is that the M1 Chip or Intel?

**Comment by artyvasiuk** [comment]
@nodeful Intel.

**Comment by nodeful** [comment]
Huh weird, what type of output device used?

**Comment by artyvasiuk** [comment]
Are you referring to balance issue or something else? 

Output device setting in the eqMac itself? Any device has balance issue - speakers and external headphones.

**Comment by nodeful** [comment]
I'm referring to the balance issue that is not reproducable on my end. eqMac is always the output device, I meant the device that the final Audio is being routed to

**Comment by artyvasiuk** [comment]
@nodeful Then yes, it's External headphones and same for Macbook Air Speakers. Maybe you need to try it as clean install? Let me know if you need a video or smth. Right channel 100% - 0% works as a volume (from regular to nothing). Left channel 100%-0% - no effect.

**Comment by Chunguska** [comment]
M1 mac mini user here. Made an account so I could jump in here. I've been struggling with the eqMac app using rosetta. It seems to be going out of phase or something after a few hours, it "detunes".

Video of the detuning issue:
https://youtu.be/bjZKdGw4Ik0

**I downloaded v0.3.7 and I'm testing it now. I'll be listening to spotify all day today so I'll report back here if the detuning issue arises again with v0.3.7.**

_Observed Improvements:
-It installed much quicker and more smoothly(no restart/just works).
-Volume control using MX Master side wheel is no longer glitchy.
-Sound level indicator LED on my micca OriGen g2 DAC properly responds now._

**Comment by nodeful** [comment]
@Chunguska great observations. Haven't thought about tuning eqMac like that 😮  I can code, but clearly I can't audio.
I will make v0.3.7 the latest release then now.

**Comment by gapton** [comment]
If I choose restart the machine the installation fails. M1 Macbook Air with 16GB ram here. OSX 11.1 
![image](https://user-images.githubusercontent.com/637259/104808390-d2935200-5820-11eb-9c5f-4e679baa412d.png)
However after reading the above and choosing restart the audio, the installation worked. The first launch after success installation crashed the App and I was stuck with a grey blank App. I force quit it and launch it again and everything is working. Checked System Monitor and saw its running in Apple mode.

Hope the above helps.

**Comment by nintendork07** [comment]
Hello, on my M1 Macbook Air, the sound stops working when waking the laptop from hibernation/sleep. There is no sound at all until I wait a minute or mess with the sound input settings. 

Also for installation, it fails if I select restart mac, it only successfully installs if I select restart audio instead.

**Comment by FraSa67** [comment]
Running on MacMini M1 OS X 11.2 - Installation was flawless and as expected. First start of the app was a bit strange (no app window, forcing the app windows up shows an empty white box), after second try everything seems to work fine. I wish for a rather esoteric feature: using an iPhone as calibration mike to baseline any speaker (a bit like SONOS does it) - Great Job, thanks a bunch for this smart piece of software. Would gladly pay a few bucks to keep this going ! :)

**Comment by xXorAa** [comment]
Installed the v3.7 Beta on M1 MBP and application seems functional. I did see the white window problem noted above, had to quit and restart then it started to function normally.

**Comment by josuemedi** [comment]
Hello, I am trying to install bur it gives me this error.
<img width="286" alt="Captura de Pantalla 2021-02-17 a la(s) 1 29 23 a  m" src="https://user-images.githubusercontent.com/79190205/108171414-177d0380-70c1-11eb-8182-7680fdd78287.png">

**Comment by antonkudin** [comment]
Installing was weird, at first it rebooted, failed. After reinstalling it complained it started with a blank window, muted all audio. After closing the window and restarting, it started fine, seem to be working. Pan slider doesn't work correctly: -100 - 0 is just volume and 0 - +100 doesn't affect sound at all. Somehow setting pan slider in the middle lowers volume?

**Comment by bernardkkt** [comment]
Installer still requires Rosetta 2 to be installed. Someone mentioned that the ```Distribution``` file needs to be updated:
> https://developer.apple.com/forums/thread/667672?answerId=648995022#648995022
