### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by squadgazzz** [bitgapp/eqMac#416]
UI version: 1.2.2
App version: 0.3.6
Driver version: 1.2
Big Sur MacOS

Settings -> Uninstall eqMac -> admin password -> "Uninstalling eqMac..." window hangs forever. Rebooting doesn't help.
If the app removed via Trash bin, eqMac is still in the output device settings.

**Comment by oddharsh** [comment]
same issue applies for me as well

**Comment by laurastreetradio** [comment]
Same issue here.

**Comment by TomaszG** [comment]
Can you share any uninstall script or an alternative way to uninstall eqMac? I wanted to try it, however, it's messing with my audio and I started to experience network issues (not sure if it's related to eqMac, I just want to check it).

**Comment by smolar** [comment]
Hi,
I had the same issue as all of us - eqmac (0.3.6) doesn't work (crash after launch) on Big Sur, so I wanted to delete it completely. When application has been uninstalled, `ps aux | grep coreaudiod` still showing eqmac plugin `Core Audio Driver (eqMac.driver)`.
In my case removing files helped: `rm -rf /Library/Audio/Plug-Ins/HAL/`
`sudo pkill -9 coreaudiod` for restart.

Hope that will be useful

**Comment by squadgazzz** [comment]
> Hi,
> I had the same issue as all of us - eqmac (0.3.6) doesn't work (crash after launch) on Big Sur, so I wanted to delete it completely. When application has been uninstalled, `ps aux | grep coreaudiod` still showing eqmac plugin `Core Audio Driver (eqMac.driver)`.
> In my case removing files helped: `rm -rf /Library/Audio/Plug-Ins/HAL/*`
> `sudo pkill -9 coreaudiod` for restart.
> 
> Hope that will be useful

Thanks that's worked for me too. But I'm not sure you have to remove all the data inside `/Library/Audio/Plug-Ins/HAL/*`. I have some other drivers inside. I've removed `/Library/Audio/Plug-Ins/HAL/eqMac.driver` only.

**Comment by smolar** [comment]
> > Hi,
> > I had the same issue as all of us - eqmac (0.3.6) doesn't work (crash after launch) on Big Sur, so I wanted to delete it completely. When application has been uninstalled, `ps aux | grep coreaudiod` still showing eqmac plugin `Core Audio Driver (eqMac.driver)`.
> > In my case removing files helped: `rm -rf /Library/Audio/Plug-Ins/HAL/*`
> > `sudo pkill -9 coreaudiod` for restart.
> > Hope that will be useful
> 
> Thanks that's worked for me too. But I'm not sure you have to remove all from `/Library/Audio/Plug-Ins/HAL/*`. I have some other drivers inside. I've removed `/Library/Audio/Plug-Ins/HAL/eqMac.driver` only.

Fair point, I had nothing else in this directory and didn't think about it. Thanks

**Comment by anderssmedman** [comment]
I had no option to uninstall eqMac (the minus was grayed in Audio Devices and the app couldnt even start). Tried a lot of tips but no success.

 I opened Finder in / and searched for eqMac, sent everything in result to Bin except one .kext that could not be removed and that was the one in Library/StagedExtenstions/Library/Extensions/ so I ran

```sudo kextcache --prune-staging```

It was now removed from my finder search result list, emptied the Bin and restarted the machine. Now the eqMac drivers was removed from Audio Devices list, no logs, no apps re-appered when I searched for eqMac.

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, eqMac doesn't bundle an uninstaller anymore, instead people are guided to the Uninstall instructions here: https://eqmac.app/#uninstall

I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
