### ISSUE TITLE
Feature: Implement delete preset so users can easily manage/remove presets 

### ISSUE THREAD

**Issue by seanyu4296** [bitgapp/eqMac#418]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
Implement a delete preset. I'm not sure though if i am missing something, but I couldn't find how to delete a preset
![Screen Shot 2020-11-24 at 2 36 54 PM](https://user-images.githubusercontent.com/11349232/100057736-01b1c680-2e63-11eb-9430-81a8d7c587f8.png)

**Comment by nodeful** [comment]
Flat and Manual are default presets and can't be deleted. To delete your Video Call presets just select them and then press the [ - ] button on the left. Case closed

**Comment by seanyu4296** [comment]
oh got it! Thanks so much! I was doing right click on the preset and was looking for a delete option.
