### ISSUE TITLE
Bug: Impossible to launch the app when do not disturb is on

### ISSUE THREAD

**Issue by Andres-Rivas** [bitgapp/eqMac#421]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Today I closed eqmac and couldn't open it again (it stayed on the blank screen with the spinner loading endlessly), after completely deleting and reinstalling 2 times  I remembered do not disturb was on, I terminated the stuck eqmac process, disabled do not disturb and tried launching again, it launched normally.

I came to the solution checking on the console and finding a log that reads "Delayed update because do not disturb is on" from eqmac process when the app tries launching, then it logs "LSExceptions shared instance invalidated for timeout". 

When killing the process and restarting with DND off it starts fine every time.

**Steps to Reproduce**
- Close eqmac
- Turn do not disturb on from the control center
- Try to open eqmac and it won't open, you can check the logs on console

*To open again you have to kill the process from activity monitor, disable DND, launch the app and only then can you re enable DND.

**Expected behaviour**
- The app should launch normaly even with do not disturb on

**Setup information:**
 - macOS Version: 10.15.6
 - eqMac Version: 0.3.6
 - eqMac UI Version: 1.2.2

**Comment by allanleonardjr** [comment]
Experiencing the exact same issue. Turning off my DND before I launch it works, THANKS!!!

**Comment by brross** [comment]
+1 this issue

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
