### ISSUE TITLE
Enhancement: Group user presets above default presets

### ISSUE THREAD

**Issue by shape55** [bitgapp/eqMac#424]
**Disclaimer:** 
- [x] I have checked for a similar enhancement and didn't see it previously requested in the search results for "user presets" & "default presets".

**Description:**
Please separate user presets from default presets, primarily so that customized user presets can be accessed more quickly.

**User flow & interface:**
Ideally, they should be grouped above default presets w/ something like a horizontal line separator between them that spans across the entire preset window.  Since the commonly used "Flat" can be reproduced by using the bypass EQ button, this is probably also better grouped below user presets in its own section w/ Manual:

User Preset 1
User Preset 2
      -------------
Manual
Flat
      -------------
Acoustic
Bass Booster
etc.

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
I like this suggestion, will look into it! Thanks

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Comment by shape55** [comment]
Hi, yes, I saw that this was added a while ago.  Thank you very much! :slightly_smiling_face:
