### ISSUE TITLE
Bug: App stops responding after opening a closed laptop/waking up from hibernation

### ISSUE THREAD

**Issue by TheBananaCam** [bitgapp/eqMac#426]
**Describe the bug**
eQMac fails to respond after laptop is closed and enters hibernation. App needs to be closed via Activity Monitor and restarted.

**Steps to Reproduce**
1. Close lid of laptop
2. Laptop enters hibernation mode
3. Open laptop lid

**Expected behaviour**
Application should continue to be response upon waking up

**Setup information:**
 - Audio device used for playback: [aiaiai tma-2]
 - Audio transmission interface: 3.5mm Jack
 - macOS Version: 10.15.7
 - eqMac Version 0.3.7
 - eqMac UI Version 1.2.2

**Additional information**
Laptop is setup with 2 additional monitors via lighting bolt cables.

The generally happens when I come back in to the office the next day. Laptop is closed around 4pm and reopened at 9am.

**Comment by nintendork07** [comment]
Same issue with M1 Macbook Air

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
