### ISSUE TITLE
Feature: Add a disable button for Volume Boost

### ISSUE THREAD

**Issue by hayduas** [bitgapp/eqMac#427]
**Description:**
Volume Boost is turned on when a user presses the volume up button and reaching the OS max. When it is turned on, distortion may be added to the sound. 

**User flow & interface:**
A "Disable Volume Boost" button should be added to settings, if a user wishes to avoid this issue.

**Comment by andresilva-cc** [comment]
I just discovered that eqMac is doing this and I really wish there was a disable button for this.

**Comment by mwhrtin** [comment]
Agreed, I want to be able to disable the volume boost. 

The built-in macOS volume indicator does not take the volume boost into account, so "100%" isn't the maximum possible volume with eqMac, it's possible to increase the volume beyond it. So the volume boost breaks the visual indicator.

**Comment by 1ennard** [comment]
Yes I also want this feature. If you are in boost mode you noticeably lose audio quality.

**Comment by nodeful** [comment]
Hey 👋🏻 
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
Yes the boost only activates if you go beyond 100% volume. 
What if I add an additional Boost HUD to the native macOS Volume HUD to indicate that you went beyond 100%?
Would you still need the option to disable going into Boost regardless?

**Comment by 1ennard** [comment]
> Hey 👋🏻
> I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
> Yes the boost only activates if you go beyond 100% volume.
> What if I add an additional Boost HUD to the native macOS Volume HUD to indicate that you went beyond 100%?
> Would you still need the option to disable going into Boost regardless?

I think the Boost HUD would be nice but you lose audio quality so I would prefer diable it completely.
Thanks for your effort!

**Comment by nodeful** [comment]
> 
> I think the Boost HUD would be nice but you lose audio quality so I would prefer diable it completely.
> Thanks for your effort!

You dont lose audio quality if you dont go beyond 100% volume a.k.a. don't go into Boost territory. The Boost gain is not applied below 100% volume

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
This has been implemented now. So will be closing the issue
Thanks again.

Roman
