### ISSUE TITLE
Audio output switched to default Mac speakers when connected to external display after wakeup from sleep

### ISSUE THREAD

**Issue by MurrayStudio** [bitgapp/eqMac#428]
Every time I wakeup the mac from sleep, the default audio output is the mac mini speakers instead of the TV I was previously connected to prior to sleeping. I have to manually switch output in the app until it resets again after the next sleep. 

I'm on the EqMac latest release with the latest BigSur (11.1) with an M1 Mac Mini.

**Comment by kylehase** [comment]
I can confirm the same on MPB 16" (2019) using a HP Z27 display over Thunderbolt 3. Additionally, when this happens, the app often crashes when attempting to switch back from internal speakers to the display output.

**Comment by cqst** [comment]
same issue on mba M1 connected to external monitor
emac 0.3.7

**Comment by WeiChihChern** [comment]
Same issue here. M1 mini, eqMac 0.3.7.

**Comment by nodeful** [comment]
Related to #408

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, there's now a Output Device priority in the Output Settings.
I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Comment by adamdexter** [comment]
Thought I don't use EQ Mac, I made a fix with Claude Code for this bug on my Mac Mini and if folks still have this issue, this script worked for me: https://github.com/adamdexter/stickyAudio/tree/main

**Comment by ryanaltvater** [comment]
Thanks @adamdexter for the script. I'll definitely check it out. I'm still experiencing this issue on app v1.8.12.

**Comment by adamdexter** [comment]
@ryanaltvater any luck with my script? I just updated the script with some fixes to make the check/fall-back more robust and some additional commands, easier install, and shortcut toolbox for pausing if manual override is needed. lmk!

**Comment by ryanaltvater** [comment]
Apologies, but I didn’t even get around to testing it. Eventually, I ended up moving away from eqMac for SoundSource. 1000x better, and allows for device ordering. I don’t experience this issue at all with SoundSource, after waking from sleep. SS runs through my preferred device order until it finds the first one that’s active. MB speakers are last on the priority list and so it never is a problem.

Thanks though!
