### ISSUE TITLE
Feature: Implement results from AutoEq 

### ISSUE THREAD

**Issue by hpl002** [bitgapp/eqMac#432]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
Incorporate seamless integration to [AutoEq ](https://github.com/jaakkopasanen/AutoEq)
To my surprise i could not find any mention in any closed or open issue of the AutoEq project.

This project and AutoEq seem like a match made to be.

Excerpt from AutoEq:
> AutoEQ is a project for equalizing headphone frequency responses automatically and it achieves this by parsing frequency response measurements and producing equalization settings which correct the headphone to a neutral sound. This project currently has over 2500 headphones covered in the results folder. See Usage for instructions how to use the results with different equalizer softwares and Results section for details about parameters and how the results were obtained.

AutoEq has a slight mention of eqMac in their usage section. However, the user has to do quite a bit of work in order to actually first translate the values pertaining to their chosen audio listening device, and then integrate these generated values into some new or existing preset in eqMac. I believe this can be made a whole lot simpler, and that this is something that every user would want.

**In the end, we just want better sounding headphones. This would certainly help us get a whole lot closer..**
> I can imagine that the settings from AutoEq would serve as a good starting point for further tweaking and adjustment.

**User flow & interface:**

The settings could be offered as default presets or added to the presets menu via some other interaction.

**Comment by variousred** [comment]
Love this idea

**Comment by nodeful** [comment]
This has been implemented and will be available from v1.0.0
https://user-images.githubusercontent.com/8472525/120506972-1604ec00-c3cf-11eb-9a51-db3a7899a46c.mp4

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Thanks again.

Roman
