### ISSUE TITLE
Bug: App stops responding after laptop sleep mode

### ISSUE THREAD

**Issue by LeoNiemi** [bitgapp/eqMac#433]
eQMac fails to respond after laptop is closed and enters hibernation. App icon is visible in the status bar but cursor turns into a spinning pinwheel. App also does not show up in Task Manager and needs to be closed via Activity Monitor and restarted.

Setup information:

Audio device used for playback: Scarlett 2i2 USB
Audio transmission interface: USB
macOS Version: 10.15.1
eqMac Version 0.3.7
eqMac UI Version 1.2.2
Driver version 1.2

**Comment by cqst** [comment]
same issue with macOS 11.1 on mba M1
and it doesn't keep the latest selected output device, always back to integrated mba speakers

**Comment by edwards-chris** [comment]
I have the exact same issue on Mac Version: 10.15.7.
eqMac Version 0.3.7
eqMac UI Version 1.2.2
Driver version 1.2

**Comment by TheBananaCam** [comment]
Also have this issue.

macOS Version: 10.15.7
eqMac Version 0.3.7
eqMac UI Version 1.2.2

**Comment by nintendork07** [comment]
Same issue with M1 Macbook Air

macOS Version: 11.1
eqMac Version 0.3.7
eqMac UI Version 1.2.2

**Comment by mr-mmmmore** [comment]
Same, also with a **Scarlet sound interface** (solo 3rd gen).

macOs: 10.14.6
eqMac: 0.3.7
eqMac UI: 1.2.2
Driver: 1.2

**Comment by FraSa67** [comment]
MacOs 11.2/M1 -  after hibernate eqMac is gone entirely and needs to be restartet; also output settings are reset (this might be an issues of BigSur/M1 which is terrible faulty overall

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by perryloh** [comment]
Hi @nodeful 

This issue is still occurring for me with the latest.
macOs: 10.15.7
eqMac: 1.1.0
eqMac UI: 1.5.7
Driver: 1.2.3

**Comment by LeeBinder** [comment]
Issue persist, unfortunately:

Mac: Intel
macOS: 10.14.6
eqMac: 1.1.0
eqMac UI: 1.6.3
Driver: 1.2.3

**Comment by gitnik** [comment]
Any way we can help in providing more debug data? :)

**Comment by gitnik** [comment]
No longer happening to me with the following versions

Mac: M1
macOS: 11.4
eqMac: 1.2.0
eqMac UI: 2.1.1 (Remote)
Driver: 1.2.3

**Comment by talentrydev** [comment]
Sorry, still happening

**Comment by gitnik** [comment]
Sorry, still happening

**Comment by LeoNiemi** [comment]
Just letting you know that this problem has stopped appearing at some point during the Fall 2021. Running OSX 11.3.1, app version 1.3.1. Huge thanks for the creator!

**Comment by eparisis** [comment]
Hi there, the issue still exists and is very consistent. Every time my mac goes to sleep it completely freezes and has to be closed through activity monitor. macOS Monterey 12.4 MacBook Air M1 2020

**Comment by fdenofa** [comment]
Issue is very consistent for me as well. 12.4 M1 Pro. Let me know if I can help, thanks!

**Comment by justinfx** [comment]
This is happening to me, every time my laptop wakes from sleep.
macOS Monterey 12.4
M1 Max
App: v1.5.1
Driver: v2.1.0
UI: v4.0.3

Pretty surprising this ticket has been open for 1.5 years. The bug makes the app mostly unusable. Hope to see a fix soon! I have not purchased the Pro yet as I have only started using this for 1 week.

**Comment by fdenofa** [comment]
> This is happening to me, every time my laptop wakes from sleep. macOS Monterey 12.4 M1 Max App: v1.5.1 Driver: v2.1.0 UI: v4.0.3
> 
> Pretty surprising this ticket has been open for 1.5 years. The bug makes the app mostly unusable. Hope to see a fix soon! I have not purchased the Pro yet as I have only started using this for 1 week.

This has been happening less and less for me for some reason? As suggested above, when it does happen, you can open Activity Monitor to kill it manually and then reopen.  It's annoying but maybe better than it not working? MAYBE?

**Comment by justinfx** [comment]
> when it does happen, you can open Activity Monitor to kill it manually and then reopen. It's annoying but maybe better than it not working? MAYBE?

Like I said I have only been using it a week so I cant gauge any long term behaviour. But it happens every time I sleep the laptop. And its not just that I have to kill and restart eqMac, but I also have to restart a few other apps. Microsoft Teams wont pick up the virtual audio device again without a restart. And Spotify stops responding until force restart. Its not a minor issue.

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
