### ISSUE TITLE
with EQMac blocked via outbound firewall, app does not work

### ISSUE THREAD

**Issue by zaphodd** [bitgapp/eqMac#437]
I know there's a similar bug elsewhere about the UI being dragged from the internet.

i will not allow EQMac or other such local apps access the internet.
On Catalina, the app appears to install, okay but i have a privacy concern.
If i start the latest EQMac app with my outbound firewall disabled - or if internet is not available, 
the app appears with a broken UI, just a blank white space as the remote UI skin is not loaded.

On Mojave, i can *usually* let the remote UI load by one time opening the firewall for a second or two until the UI is downloaded, and then blocking the app, and re-starting EQMac as if Mojave is caching the UI and Catalina isn't.
I guess this maybe is to do with the Catalina disc volume permissions perhaps.

Please can EQMac be made to work with all files locally ?

**Comment by nodeful** [comment]
It does work with no internet at all. The UI loads from local files if there's no access to the web.

**Comment by zaphodd** [comment]
Hi
Thanks for the reply.
It does not work for me :(
I even did a full OS re-install of Mojave 10.14.6 and i either get a blank white UI
or the big 'EQMac quit unexpectedly' dialogue with loads of debug info in.

It's a totally fresh install of Fresh Mojave from the App store.

EVERY TIME - if i disable my firewall, Then start EQMac - it all loads, UI and helper app & works perfectly.
if i disallow EQMac to connect outside, every single time i get blank UI.  

I've been using computers since the early 80s and i was coding in 6502a assembler, so I'm pretty well aware
of how to use and correctly install a clean OS on my rMBP.  the OS is stock &  updated with no weird kernel 
modules etc.

I tried High Sierra,  the experience was the same, again, the UI only populated when web was accessible :(

I would not waste your time if was a *nix newbie or using a Hackintosh or weird hardware or whatever.
i can send you the dump if needed.
Thanks

**Comment by 4fthawaiian** [comment]
yeah, I'm on a corporate machine with enforced incoming FW, and I'm completely unable to use the app

having to pull a UI down from the internet is a pretty silly requirement for an audio eq

**Comment by zaphodd** [comment]
**STILL not working when firewalled off.**

<img width="608" alt="Screenshot 2021-03-14 at 18 22 48" src="https://user-images.githubusercontent.com/17805128/111079568-72542000-84f2-11eb-9838-d7f92fde64db.png">

I agree with the above comment 12th Feb.. having to pull the UI off the web is ridiculous and
likely could be a potential security issue too.
every time, Mojave. Fresh Install. UI is a plain white box unless allowed internet access, which isn't going to happen.

On Catalina, the driver completely fails to load and has never worked on *any* of my 3 Macs.

I'm rating this as unuseable, because of the ongoing breakage of the app.
I'm so disappointed, as I'm a electronic musician and bass guitarist and enjoy audio a great deal,
but on my 3 Macs, a Macbook Pro 15 retina, a Macbook Air 13 and iMac 24" this app fails, always.
the UI should be in the code already. until it is, i cant use it. Sorry, I like the concept.

**Comment by nodeful** [comment]
Guys the UI should load fine without internet, it's shipped with the app. It will only load the UI from the web if it can access it. Tens of thousands of people use eqMac every day and it works fine with and without internet. There is just some specific issue with your setup, we can get to the bottom of this I'm sure. Please run Console.app and filter the system log by "eqMac" and run the app, post yiur logs here. Also please make sure to use the latest version that you can download from the website.
On a side note, I went with a Web UI because it would take me twice as long to develop the UI in Swift... I'm the only one working on the app and for me using the Web technologies for UI is a massive time saver. There are no security implications to that at all as I know what I'm doing when it come to Web :)

**Comment by nodeful** [comment]
I'm going to close this issue as it's related to #346 
As I mentioned there is not requirement for the internet by design, but there's just some bug that I think I've fixed in v1.0.0 that's coming soon.

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman
