### ISSUE TITLE
Bug: eqMac UI not shown on status bar and the sound produced heavily jaggy on older El Capitan machine

### ISSUE THREAD

**Issue by febrifahmi** [bitgapp/eqMac#439]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
After successful fresh install and reboot on old 10.11.6 El Capitan machine, eqMac UI content is not shown properly on status bar when started. Moreover when playing streaming video from YouTube and streaming music from Spotify the output sound produced heavily jaggy (also tested by playing local mp3 files using iTunes). Tested both with internal/system speaker and bluetooth headset (JBL T450BT).

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Fresh install the application.
2. Open Launchpad and start the application.
3. Play local mp3 files using iTunes/play music stream from Spotify/play YouTube videos while the eqMac app active on status bar.
4. Click the eqMac icon on the status bar and the UI content in not shown properly.
5. Here is [the screenshot of the bug](https://drive.google.com/file/d/1lM2fKBzRhym4iVgCTg2BL1g9WRzmNCJz/view?usp=sharing)
6. Here is [output sound sample of the bug](https://drive.google.com/file/d/1fXf1N7bCTCzVc3rCmqLZzIApTBGQRdMH/view?usp=sharing)

**Expected behaviour**
eqMac UI shown properly and clear output sound on El Capitan.

**Setup information:**
 - Audio device used for playback: internal speaker, JBL T450BT bluetooth headset
 - Audio transmission interface: internal (for internal speaker) and Bluetooth
 - macOS Version: 10.11.6 on MacBook Pro (13-inch, Mid 2009)
 - eqMac Version [eqMac Beta v0.3.7](https://github.com/bitgapp/eqMac/releases/tag/v0.3.7) **(if audio related issue)**
 - eqMac UI Version [eqMac Beta v0.3.7](https://github.com/bitgapp/eqMac/releases/tag/v0.3.7) **(if UI related issue)**

**Screenshots or Console.app logs**
See [screenshot of the console log here.](https://drive.google.com/file/d/1bdzZQ25RgXBuIU67xHDBng4biBWWXy_5/view?usp=sharing)

**Comment by Vengeance1020** [comment]
Also having this issue on El Capitan. This seems like a graphics issue (much like how Google Chrome will have issues on el cap and will refuse hardware rendering on some devices). Does your system have an nvidia gpu? Mine does, older macbookpro

macOS video driver and nvidia web drivers both have this issue, seems like an el cap issue

I think this app should have the option to software render its ui elements if they are hardware accelerated in the first place

Of course this is a guess based on El Caps notorious history with certain GPU apps (particularly electron apps), it might not apply to this particular app but its a start

I just tried to see if its possible to start the app without giving it access to the GPU drivers and that didn't seem to work, but I'll leave [what I found](https://gist.github.com/marpontes/23cec835ac161d8d66c4c65e0c283434) here just in case

heres hoping this can be fixed, for now the older eqmac2 software does work on el cap so I will be using that

**Comment by febrifahmi** [comment]
Yes, my machine has Nvidia GPU.. 

> heres hoping this can be fixed, for now the older eqmac2 software does work on el cap so I will be using that

Which version exactly does work with El Capitan?

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
The UI rendering issue is related to #340 and happens because macOS 10.12 and older WebKit framework shipped with the OS... Regarding Audio issues can't comment at this stage as I don't have macOS device to test on. Sorry

**Comment by nodeful** [comment]
Thanks for being patient with me.
Unfortunately, I have to let you know that eqMac has stopped support for macOS 10.11 and lower due to inability to make the UI work on outdated WebKit version. For context, it's like building a WebSite to run on Internet Explorer 9."
It was a tough decision because about 3% of eqMac's users run 10.11 or lower but I had to make this sacrifice to move the project forward.
Maybe some day I'll get to the bottom of this and will remove this restriction. I apologise for the inconvenience.  

Roman
