### ISSUE TITLE
Bug: volume slider is only 0% or 100% (or boost)

### ISSUE THREAD

**Issue by FernandoMiguel** [bitgapp/eqMac#448]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When controlling the volume with the app or system slider, nothing changes unless it goes all the way down (where it mutes). 
anything above  zero, is the same volume all the way to 100%
if i goes past 100% (boost) it does increase a bit too.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. set volume to zero
2. increase 25%

**Expected behaviour**
to exist a valid scale of the volume across the spectrum

**Setup information:**
 - Audio device used for playback: Samsung Buds live
 - Audio transmission interface: Bluetooth
 - macOS Version: 10.15.7 (19H512)
 - eqMac Version: 0.3.7
 - eqMac Driver: 1.2
 - eqMac UI Version: 1.2.2

**Comment by mkantzer** [comment]
If you open the app and use the advanced EQ and change the "global" level, does THAT change it? (I think i'm trying to do the same thing as you: get audio control of a device that macOS wasn't previously allowing me to control from the computer)

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
