### ISSUE TITLE
Not working with Audirvana?

### ISSUE THREAD

**Issue by Joan-Felip** [bitgapp/eqMac#451]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+enhancement%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are certain your issue is not related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
I've got a iMac 27 inches (end of 2013) with macOS High Sierra 10.13.6 and a Musical Fidelity V-DAC. eqMac (UI Version 1.2.2, App Version 0.3.7, Driver Version 1.2) works perfectely with iTunes but doesn't with Audirvana 3.5.43, a very good digital audio playback software. Is it a limitation of the software or a bug? (I tried eqMac 2 but nothing works at all).

**Comment by Joan-Felip** [comment]
I've got a iMac 27 inches (end of 2013) with macOS High Sierra 10.13.6 and a Musical Fidelity V-DAC. eqMac (UI Version 1.2.2, App Version 0.3.7, Driver Version 1.2) works perfectely with iTunes but doesn't with Audirvana 3.5.43, a very good digital audio playback software. Is it a limitation of the software or a bug? (I tried eqMac 2 but nothing works at all).

**Comment by nodeful** [comment]
Please check in Audirvana settings that it uses The Default System Output device or is explicitly set to eqMac

**Comment by eelpout** [comment]
Yeah, I'm having problems with Audirvana Studio and eqMac too. the weirdest one is occasionally, tracks will play at half speed when eqMac is selected as the source. I can't seem to reliably reproduce it though.

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
