### ISSUE TITLE
Feature: Implement 16Hz Slider so users can manage lower freqs

### ISSUE THREAD

**Issue by sandinak** [bitgapp/eqMac#452]
**Disclaimer:** .
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
Right now the lowest slider is 32Hz .. which is fine for Rock and other styles that don't use subsonics much .. but EDM and alot of the recent Pop are starting to use em ( Halsey - Graveyard .. good example ) .. i'd like to be able to manage those separately from the lower end if possible so the Subwoofers aren't overwhelmed with them etc.. 

**User flow & interface:**
I think just adding the slider for that space .. or including this in the proposed "Advanced Mode" would be great.  

I may take a stab at this myself ( I am a coder ;)

**Comment by nodeful** [comment]
With eqMac v1.0 that's coming in the next couple of weeks there will be Expert EQ where you'll be able to precisely control any frequency down to 10Hz, so keep an eye out

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
With Expert EQ you can control frequencies down to 10Hz
Thanks again.

Roman
