### ISSUE TITLE
Please signpost the need to reinstall after major OS upgrades

### ISSUE THREAD

**Issue by boxabirds** [bitgapp/eqMac#453]
I've been really enjoying eqMac and it went completely bonkers (just pure static) after upgrading to Big Sur 11.1. I downloaded eqMac and reinstalled and restarted it and it was back happy as larry. 

It'd be cool if the app could detect major OS changes and prompt to be reinstalled or something so the experience for a user is really smooth…

**Comment by nodeful** [comment]
Yes probably would be good to add to the FAQ.
Although I think a reinstall is an overkill, sometimes Apple just does something crazy but a `sudo killall coreaudiod` should do the trick in most cases.

**Comment by nodeful** [comment]
For now put this instruction into the FAQ: https://eqmac.app/#issues-after-macos-update
