### ISSUE TITLE
Pitch speed

### ISSUE THREAD

**Issue by jazzkid74** [bitgapp/eqMac#455]
Playing music from Music music changed speed and pitch throughout a song.

**Comment by qwertyuu** [comment]
YOU TOO? It's been driving me crazy. I used a video of 420hz test just to be sure I was not going mad in the brain. Plz fix! I love eqmac but I fear I'll start seeing monkeys soon!

**Comment by mr-mmmmore** [comment]
This issue is already described in #423, please upvote it.

**Comment by nodeful** [comment]
Yeap Duplicate of #401 and #423 
Please refer to those, closing this one
