### ISSUE TITLE
Bug: White window on BigSur

### ISSUE THREAD

**Issue by gbasile** [bitgapp/eqMac#465]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
**When** I open the app
**Then** a black windows appear
**And** when I tap on the windows
**Then** the windows controls disappear (red/yello/green circles)
**And** the windows goes white

| On load  | After tapping |
| ------------- | ------------- |
| ![screenshot 2021-03-01 at 02 13 17](https://user-images.githubusercontent.com/797790/109440822-c6133380-7a33-11eb-8bc1-84e65aa5f8d7.png)| ![screenshot 2021-03-01 at 02 13 19](https://user-images.githubusercontent.com/797790/109440827-cc091480-7a33-11eb-8609-f171967bb2ac.png) |

**Steps to Reproduce**
On Every app launch

**Expected behaviour**
App should load

**Setup information:**
 - Audio device used for playback U-Phoria UMC22
 - Audio transmission interface:USB
 - macOS Version: 11.2.2 
 - eqMac Version 0.3.7

**Screenshots or Console.app logs**

```
eqMac[1007]: getattrlist failed for /Library/GPUBundles/AMDRadeonX6000GLDriver.bundle/Contents/MacOS/ATIRadeonX6000SCLib.dylib: #2: No such file or directory
eqMac[1007]: getattrlist failed for /System/Library/Extensions/AMDRadeonX6000GLDriver.bundle/Contents/MacOS/ATIRadeonX6000SCLib.dylib: #2: No such file or directory
eqMac[1007]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
```
**Additional information**
Might be related to this: 

```
New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker
cache of all system-provided libraries. As part of this change, copies of dynamic
libraries are no longer present on the filesystem. Code that attempts to check
for dynamic library presence by looking for a file at a path or enumerating a
directory will fail. Instead, check for library presence by attempting to dlopen()
the path, which will correctly check for the library in the cache. (62986286)
```

[Source](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes)

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
Probably nothing to do with Frameworks/Libraries, just a bug preventing the UI from loading when mac is offline or there's an outgoing firewall setup on your Mac. Related to #346, #437. Should be fixed in v1.0 that's coming in the next couple of weeks.

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by gbasile** [comment]
Great work! Is working now on my machine 🥳

**Comment by nodeful** [comment]
Awesome. Thanks for confirming!
I will close this issue, please let me know if this problem is still a problem in the future :)
