### ISSUE TITLE
Bug: Crash when switching to aggregate audio device

### ISSUE THREAD

**Issue by fecundf** [bitgapp/eqMac#467]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
before installing eqMac I created an Aggregate Audio device via the Mac's pre-installed "Audio Midi Setup"- the device is the "Built-in Output" and the "DisplayPort". The allows me to use both my Macs speakers and the external display's speakers.

I then installed eqmac, and saw that it works individually with "Built-in Output" or the "DisplayPort", one-at-a-time, but as soon as I click the aggregated device in the drop-down, eqmac crashes. I get the following report-
<img width="404" alt="image" src="https://user-images.githubusercontent.com/317592/109895232-df4af880-7c5c-11eb-98db-4c552af6190e.png">

**Setup information:**
 - Audio device used for playback: Aggregate device:  "Built-in Output" + "DisplayPort"
 - Audio transmission interface: USB-C cable for DP + Mac Built-In
 - macOS Version: 11.2.2
 - eqMac Version 0.3.7

**Problem Reporter logs**
800+ lines so go here: https://gist.github.com/fecundf/49e0624a071a72ee76b0b079f9efee7b

**Comment by fecundf** [comment]
The crash looks similar to the first half #270 though that was resolved

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by fecundf** [comment]
Yes Aggregate Device is working under eqMac 1.3.2 – thanks much! Sorry it took a while to get back to this.
