### ISSUE TITLE
Crash: Output to audio interface (Audient iD4)

### ISSUE THREAD

**Issue by pashashocky** [bitgapp/eqMac#468]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
eqMac crashes when output is a USB audio interface

**Steps to Reproduce**
I use an audient iD4, and i haven't been able to play anything to it thorugh eqMac

**Expected behaviour**
Output sound switches to play through my audient iD4

**Setup information:**
 - Audio device used for playback: Audient iD4
 - Audio transmission interface: USB 3.0 or USB-C
 - macOS Version: 11.2.2 (20D80)
 - eqMac Version: latest v0.3.7

**Additional information**
Happy to do a debugging session with someone, everything else works 'nearly perfectly'.

**Comment by KONSTANTINDEV1** [comment]
Having this issue too my usb scarlet interface once selecting the output on eqmac

**Comment by pashashocky** [comment]
Great that it's not just me, would love for this to be fixed as I simply got too used how awesome eqMac is!

**Comment by jaszopa** [comment]
+1 App is unusable for me. It installs ok on M1 MBP 13", and recognizes the iD22 but  attempting to switch to it causes the app to crash.

**Comment by jasperdunn** [comment]
Having this issue when selecting my Focusrite Clarett interface.

**Comment by pashashocky** [comment]
Hey @nodeful - would be great to hear your thoughts on whether this is a relatively easy or complicated fix? Can we help out in any way?

**Comment by nodeful** [comment]
Haven't looked into this (and most issues tbh) at all in the last couple months. Been focusing on developing some paid features for eqMac to make it a more sustainable project. I will be triaging all issues very soon! Sorry for the delays

**Comment by nodeful** [comment]
Would be great to get a crash report and a screenshot from Audio MIDI Setup.app with your device selected (so I can see what kind of channels/sample rates your device is running)

**Comment by pashashocky** [comment]
Here you go Sir! @nodeful  - thank you!

![Screenshot 2021-03-24 at 22 10 30](https://user-images.githubusercontent.com/673857/112390282-f32ecb00-8ced-11eb-9c81-2830a0001093.png)

[eqMac_2021-03-24-220757_OBEY-LAP.txt - changed extension from .crash](https://github.com/bitgapp/eqMac/files/6200767/eqMac_2021-03-24-220757_OBEY-LAP.txt)

**Comment by nodeful** [comment]
Hmm seems to be that there are no Output channels at all 🤔

**Comment by nodeful** [comment]
Or no says 4 channels. Wilk take a look more thoroughly when I get a chance

**Comment by pashashocky** [comment]
> Or no says 4 channels. Wilk take a look more thoroughly when I get a chance

Thank you! Would really appreciate this being fixed!

**Comment by pashashocky** [comment]
@nodeful - any luck? let me know if you want to get online sometime to debug together? Thank you :)

**Comment by jbgbrt** [comment]
It crashes also for me with MOTU M4. I have their drivers installed as well.
Attached the crash log.
[MOTU M4 crash.txt](https://github.com/bitgapp/eqMac/files/6370800/MOTU.M4.crash.txt)

**Comment by nodeful** [comment]
I am triaging & trying to fix all open issues before release of eqMac v1.0.0. Excuse the wait.
Could be related to #352 or #431 
From the screenshot you posted seems like all channels don't have any software volume controls, including Master channel.
Could be related to that, but to debug I would need to get some USB Audio device with hardware volume control 🤔

**Comment by pashashocky** [comment]
@nodeful Happy to jump on a zoom call with you and do a debugging session if you want.

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by pashashocky** [comment]
It works for me! You are the boss! Thank you so much! 
Unrelated issue to this, but at least i know you'll see it - noticing that overdoing the gain at around 64Hz starts to significantly degrade the quality of sound. It's not a massive problem for me, possibly it's just that audio...

**Comment by jasperdunn** [comment]
Fantastic work Roman, I'll definitely consider upgrading to pro, it seems
very stable so far. Small feature request here, can we have the ability to
double click the volume to reset it to 100? Or enter in values manually?

**Comment by nodeful** [comment]
Thank you guys :) Glad to provide the service.
@pashashocky Regarding the quality degradation, usually decreasing the global gain and increasing the Overall Volume to compensate helps! 
Regarding Atmos and generally 5.1 surround sound setups for now it's not possible, would have to do a complete driver rewrite to support that, but it might come in the future!
@jasperdunn Regarding double clicking to reset volume to 100%, I'm afraid someone might missclick and go from 5% volume straight to a 100 :D that would not be a pleasant experience. Maybe going from over 100% (so like when you apply boost) down to 100% would be better.

**Comment by domoritz** [comment]
I am still seeing crashes with the Motu M2. I just sent a crash report via the app. @jbgbrt are you seeing this problem as well? Version 1.2.0 and driver 1.2.3 on M1 MacBook Pro.

**Comment by fredhohman** [comment]
I am also seeing crashes with my Motu M4. If I switch to another audio output the app loads, but then within the app when I selected the USB M4 output it crashes. Happy to provide more details.

**Comment by MUWalter** [comment]
> I am still seeing crashes with the Motu M2. I just sent a crash report via the app. @jbgbrt are you seeing this problem as well? Version 1.2.0 and driver 1.2.3 on M1 MacBook Pro.

I am also seeing chrashes with my Motu M2.

**Comment by Gantzed** [comment]
I have had the same issue and solved it by rolling back the Motu driver. However, now I am on Monterey and somewhere after 12.1 it broke. And now I am struggling to load any other driver besides 89383. I deleted the older ones as I did before, but cannot seem to get the Motu installer to install anything older.

**Comment by MUWalter** [comment]
> I have had the same issue and solved it by rolling back the Motu driver. However, now I am on Monterey and somewhere after 12.1 it broke. And now I am struggling to load any other driver besides 89383. I deleted the older ones as I did before, but cannot seem to get the Motu installer to install anything older.

which driver version did you get back to?

**Comment by Gantzed** [comment]
As it stands, and after talking with Motu, only the latest driver will install on Monterey. Perhaps an absolute fact now that I am on 12.1. I still think I got an older driver on 12 but I can no longer check. However, if you remove the extension from the application folder, it works fine. 
You will lose loop back and some latency will be added, but I’m fine with that. If I’m recording I wouldn’t use a downstream eq and the latency is a non issue for 99% of human ears.

**Comment by nodeful** [comment]
Hey guys, sorry for the lack of updates,
About a month ago I was having a conversation with s man named Daniel (not sure if one of you guys is him) over email about the MOTU M2 device he was having troubles with together with eqMac.  He said he rolled back the MOTU driver back to v2.0.87935 and everything worked fine from there on. As I grasped this driver version is not working on Monterey, but the one of Monterey somehow makes eqMac crash... So not sure what to do, I don't have a MOTU device to test with but I will gladly accept Crash Reports from latest eqMac version so I can look into it more thoroughly.
By the way this issue is related to Audient iD4 which seems to have been fixed now, but somehow transformed into conversation about Motu.
So to not annoy people with email notifications that were here only for the iD4 I've created a separate issue just for the MOTU devices:
#612
Please refer to that issue from here on out about the MOTU devices and also post the Crash Reports there.
I will be closing this issue unless someone tells me that there's still an issue with any kind of Audient device.
