### ISSUE TITLE
AMD Hackintosh compatibility

### ISSUE THREAD

**Issue by Entwolker** [bitgapp/eqMac#471]
Just tried eqMac on my AMD Ryzen Hackintosh to enhance my microphone quality but it crashes so I wondered if the eqMac driver is incompatible with my CPU.

Hackintosh:
* AMD Ryzen 5 2600,
* macOS 10.15.6 & OpenCore Bootloader

**Comment by nodeful** [comment]
I have an Intel Hackintosh based on OpenCore and eqMac runs fine, so probably related to some differences in instruction sets 🤔 What Hackintosh software are you using? Crash log?

**Comment by Entwolker** [comment]
Crashed after selecting eqMac as microphone in discord. [Crash log](https://pastebin.com/sL2mAELB)

**Comment by nodeful** [comment]
Why do you want to select eqMac as microphone in Discord?

**Comment by nodeful** [comment]
Yes currently eqMac is meant to Equalize the System Audio, but equalizing Input devices is coming soon
