### ISSUE TITLE
Mute Not Working

### ISSUE THREAD

**Issue by seanbusse** [bitgapp/eqMac#474]
Hi there,
I have noticed that the keyboard buttons for volume up and down work very well although I would like to see the option to turn off boost. The bug is the mute button. When it is pressed, the on-screen display says that volume is muted but audio still passes. It would be great for the mute to work in the same fashion as the volume up and down. But great app. Solved my problems with having to use audio over HDMI and keep keyboard audio control.

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by psd-coder** [comment]
I have v1.0.0 installed from the Brew and issue still present, yes

**Comment by psd-coder** [comment]
Hm! Seems the reason was in conflicting with MonitorControl.app. I have closed it and all start work perfectly!

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
