### ISSUE TITLE
Searching for the Old Version of eqMac

### ISSUE THREAD

**Issue by mjo-unknown** [bitgapp/eqMac#477]
Hi Romans

I am looking for now several days through all the world wide web, to find somewhere the old version of your eqMac. I installed it once on a MacBook of my girlfriend, and it worked very well - not perfect, some bugs but restarting the tool made it working again.

Since then, many things changed, as well your eqMac. As I can see, it become a really great an mighty app, which is all over the web very appreciated. Somewhere i read from a user, why "they" (you) don't put the app on Apple's AppStore. He wrote, that he trusts just applications from there, but that he would pay for sure 1 or 2 Euros / Dollars for a working tool like that - so the creator could get something back for his efforts. I guess maybe apple doesn't want any equalizer in his store or that there are for sure reasons - but just in case you did not had this idea before - I also think that this app is easily worth 1 to 2 €/$. :-)

Something else has changed since then - as I have a new Mac for working, I took the old iMac in my private room, as it still works perfect for surfing or enjoying music, movies and so on. So I would like to install eqMac, but this iMac works on OS X 10.9.5 - I didn't update it deliberately, so it works smoother. But for this reason I'm looking for this old version of your app, which absolutely worked fine enough for me and my girlfriend these times. Today she is my ex-girlfriend and we lost contactasdf, why I could not even ask her to check on her old macbook.

I hope you can help me by sending me a link where I can download it or if you could upload it somewhere and send me the download-link. You can - if you wish - also send it directly by email to me: "marc (point) bhg (at) gmail (point) com". I looking forward to your response, so that I soon can listen to my music or enjoy my movies with more sound power / better feeling sound.

Many thanks to you for your effort, to create such a great piece of work! I really like your app, as everything with sound is better with it. :-) My best wishes and regards to you and hope to read from you soon.
-Marc

**Comment by scaszoo** [comment]
@mjo-unknown 
Have you tried checking the releases? :)

https://github.com/bitgapp/eqMac/releases/tag/V0.0.0 which would be "Old eqMac2 - Build 2.2", the one you might be looking for?

**Comment by nodeful** [comment]
Thank you @mjo-unknown 
The app is not on the AppStore because Apple doesn't allow installing of Audio Drivers for the app to work, but there's a work around that I will be working on at some point. Anyway scaszoo left you a link to the latest eqMac2 Release if you want to keep using that
