### ISSUE TITLE
Bug: YouTube freezes (Chrome unresponsive tab) when trying to start a video with eqMac

### ISSUE THREAD

**Issue by boxabirds** [bitgapp/eqMac#478]
**Steps to Reproduce**
1. Go to any YouTube video
2. Try to play it. It hangs
3. I quit eqMac, it plays immediately. 

**Expected behaviour**
It plays. 

**Setup information:**
 - Audio device used for playback: Yamaha AG-06
 - Audio transmission interface: Phono jack to active speakers coming from AG-06
 - macOS Version: 11.2.3 (20D91)
 - eqMac Version 0.3.7

**Screenshots or Console.app logs**

When I tried to load any YouTube video, I watched the `system log` in `Console.app`: 

```
ar 21 21:10:10 VM843 Google Chrome Helper[55474]: Libnotify: notify_register_coalesced_registration failed with code 9 on line 2835
Mar 21 21:10:37 VM843 Google Chrome Helper[55648]: Libnotify: notify_register_coalesced_registration failed with code 9 on line 2835
Mar 21 21:11:37 VM843 Google Chrome Helper[55648]: Libnotify: notify_register_coalesced_registration failed with code 9 on line 2835
Mar 21 21:11:38 VM843 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0B000000-0200-0000-0000-000000000000[55862]): Service exited due to SIGKILL | sent by mds[86]
Mar 21 21:11:38 VM843 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.06000000-0200-0000-0000-000000000000[55980]): Service exited due to SIGKILL | sent by mds[86]
Mar 21 21:11:38 VM843 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.01000000-0400-0000-0000-000000000000[55978]): Service exited due to SIGKILL | sent by mds[86]
Mar 21 21:11:49 VM843 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.08000000-0700-0000-0000-000000000000[56008]): Service exited due to SIGKILL | sent by mds[86]
Mar 21 21:12:12 VM843 Google Chrome Helper[55474]: Libnotify: notify_register_coalesced_registration failed with code 9 on line 2835
```

Then I clicked "Exit Page":

<img width="950" alt="Screenshot 2021-03-21 at 21 12 19" src="https://user-images.githubusercontent.com/147305/111921017-3c7ee080-8a8a-11eb-8e71-c2c19d8c0af5.png">

```
Mar 21 21:12:26 VM843 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.03000000-0600-0000-0000-000000000000[55977]): Service exited due to SIGKILL | sent by mds[86]
Mar 21 21:12:26 VM843 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0D000000-0100-0000-0000-000000000000[55979]): Service exited due to SIGKILL | sent by mds[86]
Mar 21 21:12:26 VM843 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0E000000-0500-0000-0000-000000000000[55976]): Service exited due to SIGKILL | sent by mds[86]
Mar 21 21:12:26 VM843 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.07000000-0000-0000-0000-000000000000[55975]): Service exited due to SIGKILL | sent by mds[86]
Mar 21 21:12:26 VM843 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.09000000-0100-0000-0000-000000000000[56035]): Service exited due to SIGKILL | sent by mds[86]
Mar 21 21:12:26 VM843 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0B000000-0300-0000-0000-000000000000[56033]): Service exited due to SIGKILL | sent by mds[86]
Mar 21 21:12:26 VM843 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.01000000-0500-0000-0000-000000000000[56036]): Service exited due to SIGKILL | sent by mds[86]
Mar 21 21:12:37 VM843 Google Chrome Helper[55648]: Libnotify: notify_register_coalesced_registration failed with code 9 on line 2835
```

**Related info**
* Spotify plays with what I believe is a "buffer underflow": static / distortion repeatedly cycling in every few seconds. I've had this problem with eqMac on and off ever since the beginning. 
* Problem still happens with Incognito mode.

**Comment by boxabirds** [comment]
Any updates on this?

**Comment by boxabirds** [comment]
Oh well @nodeful I was a sponsor but cancelled as I'm pretty disappointed that this is being ignored.

**Comment by nodeful** [comment]
it is not ignored I just don't have the time to reply to every issue as I spend every minute that I have to develop eqMac Pro at the moment. All bugs like this will be triaged and fixed once eqMac will start to generate revenue with the Pro version. Please reopen this issue so I can keep track in the future. No need to be a sponsor to show you support, but I am grateful for your contributions 🙇🏻‍♂️  Sorry for any inconvenience you've experienced, just a lone man running this thing here with a load of issues in real life.

**Comment by nodeful** [comment]
Could possibly be related to #268 or #373 Please refer to those from now on
