### ISSUE TITLE
Bug: Support HiRes source for HDMI output

### ISSUE THREAD

**Issue by prietales** [bitgapp/eqMac#482]
**Describe the bug**
The default frequency of the eqMac input and output in the audio and midi settings is always 48000 Hz. When I try to change it to 96000 Hz to listen to HiRes music the audio freezes.

**Steps to Reproduce**
1) Open eqMac.
2) Open VLC or Amazon Music HD or Tidal.
3) Open Audio/Midi settings set external device to 96 Khz / 24 bit.
3) Open Audio/Midi settings and try to set more than 48000 Hz, for example 96000Hz to eqMac input/output.

**Expected behaviour**
Frequencies greater than 48000 Hz should be selectable or should be adjusted automatically depending on the source.

**Setup information:**
Macbook 12" 2017
Audio device: HDMI output on LG TV
macOS Version: 11.2.2
eqMac Version: latest v0.3.7

**Code**

It seems that the current sample rate of the device is not being obtained and it is set to 48000 by default. (Please test it with a HDMI output.

```
private static func matchDriverSampleRateToOutput () {
    let outputSampleRate = selectedDevice.actualSampleRate()!
```

I changed the default value from 48_000 to 96_000 and built the app with Xcode and its working.

Thanks.

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by prietales** [comment]
Hi,

It's working now. The audio does not freeze and the app does not crash when I select the HDMI output of the TV. I can reproduce without problem at 96Khz.

Thanks!

**Comment by nodeful** [comment]
Awesome, your welcome 😇 Thanks for giving eqMac a chance. Will be closing this issue then
