### ISSUE TITLE
Bug: volume drop

### ISSUE THREAD

**Issue by ctbk** [bitgapp/eqMac#484]
Wen eqMac is running, as soon as I adjust the volume (in any way) the volume drops significantly: the same volume level (for example, 32%) has a quieter output. When eqMac is turned off, the volume level returns to normal.

**Steps to Reproduce**
1. Adjust the volume to your liking;
2. Turn on eqMac;
3. Increase/Decrease the volume by any amount and then restore the previous level;
4. You will hear a clear drop in the volume;
5. You can adjust the volume again, but it will be quieter than it should;
5. Shut down eqMac;
6. Volume gets back to normal;

**Expected behaviour**

**Setup information:**
 - Audio device used for playback: Headphones;
 - Audio transmission interface: 3.5mm jack;
 - macOS Version: 11.2.3
 - eqMac Version: 0.3.7
 - eqMac UI Version: 1.2.2

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
