### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by lauren7ino** [bitgapp/eqMac#486]
Hi
Greetings from Portugal. English is not my native language.
First of all, congratulations for this excellent software!
I notice that eqMac uses between 2% and 5% of CPU, the whole time, even when no audio being played.
Can you improve on that? Not good for laptop battery.
Thanks 
(MacBookPro9,1, macOS Catalina (latest))

**Comment by Coobers** [comment]
On modern systems, usage is most often shown per core. So this means it's 2-5% of 1 core usage. 
Music samples are CPU intensive tasks (relatively to your expectations), so use at this level is perfectly normal.
If you care about your CPU usage, it's better to use your phone. They have dedicated circuits designed to playback samples, thus reducing power usage.

**Comment by nodeful** [comment]
yeah there's something that can be done to decrease CPU usage. Currently eqMac processes audio even if there is no audio. I will look into stopping processing when there's no audio. Will keep you posted

**Comment by JonDum** [comment]
@nodeful That would be amazing! As it is now, eqMac sits at a constant 8-10% CPU on my i9 MBP resulting in even worse than the normally abysmal battery life. I think it may be keeping the cpu in a higher power state.

Perhaps as a temporary workaround there's a way to turn off the processing when the eqMac.app is not running? It seems like the driver is always processing even if the app is not running.

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, eqMac now stops any audio processing if no audio is playing.
I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Comment by dverzolla** [comment]
This app is amazing. but... 

In my macbook air M1, it uses 6% of CPU.
High energy impact.

Would be really nice if something could be optimized to not use so much CPU.
