### ISSUE TITLE
Bug: I uninstalled a long time ago. mac freezeing needing hard reboot

### ISSUE THREAD

**Issue by azreal1983** [bitgapp/eqMac#489]
My macbook pro is freezing ever so often
Process:               com.apple.audio.Core-Audio-Driver-Service [253]
..

Thread 2 Crashed:: Dispatch queue: com.apple.NSXPCConnection.user.anonymous.216

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff2044eeba semaphore_wait_trap + 10
1   com.bitgapp.eqmac.driver      	0x00000001053313a8 EQM_TaskQueue::WorkerThreadProc(unsigned int, unsigned int, TAtomicStack<EQM_TaskQueue::EQM_Task>*, TAtomicStack2<EQM_TaskQueue::EQM_Task>*, std::__1::function<bool (EQM_TaskQueue::EQM_Task*)>) + 72
2   com.bitgapp.eqmac.driver      	0x0000000105330a66 EQM_TaskQueue::RealTimeThreadProc(void*) + 86
3   com.bitgapp.eqmac.driver      	0x000000010533921b CAPThread::Entry(CAPThread*) + 123
4   libsystem_pthread.dylib       	0x00007fff20483950 _pthread_start + 224
5   libsystem_pthread.dylib       	0x00007fff2047f47b thread_start + 15

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff2044eeba semaphore_wait_trap + 10
1   com.bitgapp.eqmac.driver      	0x00000001053313a8 EQM_TaskQueue::WorkerThreadProc(unsigned int, unsigned int, TAtomicStack<EQM_TaskQueue::EQM_Task>*, TAtomicStack2<EQM_TaskQueue::EQM_Task>*, std::__1::function<bool (EQM_TaskQueue::EQM_Task*)>) + 72
2   com.bitgapp.eqmac.driver      	0x0000000105330b7a EQM_TaskQueue::NonRealTimeThreadProc(void*) + 90
3   com.bitgapp.eqmac.driver      	0x000000010533921b CAPThread::Entry(CAPThread*) + 123
4   libsystem_pthread.dylib       	0x00007fff20483950 _pthread_start + 224
5   libsystem_pthread.dylib       	0x00007fff2047f47b thread_start + 15

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff2044eeba semaphore_wait_trap + 10
1   com.bitgapp.eqmac.driver      	0x00000001053313a8 EQM_TaskQueue::WorkerThreadProc(unsigned int, unsigned int, TAtomicStack<EQM_TaskQueue::EQM_Task>*, TAtomicStack2<EQM_TaskQueue::EQM_Task>*, std::__1::function<bool (EQM_TaskQueue::EQM_Task*)>) + 72
2   com.bitgapp.eqmac.driver      	0x0000000105330a66 EQM_TaskQueue::RealTimeThreadProc(void*) + 86
3   com.bitgapp.eqmac.driver      	0x000000010533921b CAPThread::Entry(CAPThread*) + 123
4   libsystem_pthread.dylib       	0x00007fff20483950 _pthread_start + 224
5   libsystem_pthread.dylib       	0x00007fff2047f47b thread_start + 15

Thread 7:
0   libsystem_kernel.dylib        	0x00007fff2044eeba semaphore_wait_trap + 10
1   com.bitgapp.eqmac.driver      	0x00000001053313a8 EQM_TaskQueue::WorkerThreadProc(unsigned int, unsigned int, TAtomicStack<EQM_TaskQueue::EQM_Task>*, TAtomicStack2<EQM_TaskQueue::EQM_Task>*, std::__1::function<bool (EQM_TaskQueue::EQM_Task*)>) + 72
2   com.bitgapp.eqmac
.driver      	0x0000000105330b7a EQM_TaskQueue::NonRealTimeThreadProc(void*) + 90
3   com.bitgapp.eqmac.driver      	0x000000010533921b CAPThread::Entry(CAPThread*) + 123
4   libsystem_pthread.dylib       	0x00007fff20483950 _pthread_start + 224
5   libsystem_pthread.dylib       	0x00007fff2047f47b thread_start + 15

I thought I uninstalled this.

How do I get rid of these threads

**Comment by nodeful** [comment]
```
sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/
sudo killall coreaudiod
```
Make sure to close all audio playing application before you do this
