### ISSUE TITLE
Kind of bug: getting eqMac 2.2 going on 11.2.3

### ISSUE THREAD

**Issue by timremple** [bitgapp/eqMac#490]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Got eqMac 2.2 -- UI 1.2.2, App 0.3.7, Driver 1.2 -- installed on Mac OS X 11.2.3 with some struggle.

**Steps to Make It Work**
Things to do / know:
1. Make sure you allow eMac access to the Microphone; if disabled, things do not go well
2. You will likely need to click Allow re. eqMac in System Preferences . Security & Privacy . General -- you may have to do this multiple times, or after first reboot, till the Allow "sticks"
3. It can also be handy, perhaps even necessary, to install eqMac, then, manually, do a: `sudo launchctl kickstart -k system/com.apple.audio.coreaudiod &>/dev/null`
4. Then reboot, and thing should work

**Expected behavior**
This works trivially and there is nothing the user needs to do besides run the pkg installer.

**Notes**
Hope this helps folks install eqMac on Mac 11.  I *LOVE* eqMac; the best equalizer I've found for Mac OS x!

**Comment by nodeful** [comment]
eqMac 2.2 is a 3 year old version of eqMac and is not supported anymore, it doesn't have UI version nor does it use the HAL driver, it uses Kernel Extension Driver. Not sure what exactly are you talking about, sorry :( 
Please elaborate, but for now closing the issue
