### ISSUE TITLE
When selecting "multi-output device" eqMac freezes

### ISSUE THREAD

**Issue by sfguy83** [bitgapp/eqMac#491]
**Describe the bug**
I have 2 external HP monitors plugged into my Macbook Pro.  I'm trying to sync the volume on both monitors.  I created a Multi-Output Device in Audio MIDI.  But when I go to select this profile in eqMac it freezes the eqMac app.   

**Steps to Reproduce**
1. Go to "eqMac" in the menu bar app
2. Click on "Multi-Output Device" from drop down
3. See error

**Expected behaviour**
I would like to get sound out of both monitors (1 & 2).

**Setup information:**
 - Audio device used for playback: two HP monitors, and my Macbook Pro
 - Audio transmission interface: DisplayPort - direct connectors from each monitor to my Macbook Pro
 - macOS Version: 10.15.7
 - eqMac Version: 0.3.7
 - eqMac UI Version: unknown

**Screenshots or Console.app logs**
n/a

**Additional information**
n/a

**Comment by ngeorger** [comment]
Hi!
I have a similar issue when I try to select a 4 channel output device connected via USB, even if i try any conf. availible from  Audio MIDI.
The device is a Behringer BCD 3000 (oldie but works like a charm)

**Comment by nodeful** [comment]
No crash report?

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
