### ISSUE TITLE
Tip: How to get even frequency response on bad speakers

### ISSUE THREAD

**Issue by serif** [bitgapp/eqMac#494]
I just wanted to share this tip.

With terrible speakers, like the internal speakers on my ancient MacBook Pro 2012, start by trying to get a flat response. That means subjectively hearing equal volume for tones in each band. I used this site to generate tones: https://www.szynalski.com/tone-generator/

I started at 125 Hz, then hit the [x2] button to skip directly to 250 Hz, 500 Hz, 1 kHz, 2 kHz, etc., and the [x1/2] to skip backwards, incrementally adjusting the sliders in eqMac until the volume of each tone seemed as equal as possible. Those [x2] and [x1/2] buttons make it really easy to focus on the right frequencies.

On poor speakers, you may find lower frequencies inaudible no matter what, so cutting those bands can decrease distortion.

That's it.

I'm attaching what that looks like on the terrible internal speakers of my MacBook Pro 2012. This might look like too extreme of an adjustment, but these speakers really are that bad.

![Screen Shot 2021-05-13 at 3 03 44 PM](https://user-images.githubusercontent.com/62613995/118174136-73bf9d00-b3fc-11eb-9f57-c8a8896fbddd.png)

**Comment by serif** [comment]
Actual feature enhancement suggestion:

Turn the band labels (... 250, 500, 1K ...) into clickable buttons that generate tones at those frequencies

**Comment by nodeful** [comment]
Hey thanks for sharing this. But this is not really an Issue so I think it should live here: https://github.com/bitgapp/eqMac/discussions
I will close this issue but feel free to repost it there
