### ISSUE TITLE
Typo in the word "acoustic"

### ISSUE THREAD

**Issue by ztcollazo** [bitgapp/eqMac#500]
In the file [native/app/Source/Audio/Effects/Equalizers/Advanced/AdvancedEqualizerDefaultPresets.swift](https://github.com/bitgapp/eqMac/blob/master/native/app/Source/Audio/Effects/Equalizers/Advanced/AdvancedEqualizerDefaultPresets.swift), there is a typo here:
```swift
let ADVANCED_EQUALIZER_DEFAULT_PRESETS: [String : [Double]] = [
  "Flat": Array(repeating: 0, count: 10),
  "Accoustic": [
    -8.3,
    9.8,
    -15.68,
    2.1,
    18.22,
    3.5,
    7,
    8.2,
    7.1,
    4.3
  ],
...
```
Did you mean "Acoustic?"

**Comment by nodeful** [comment]
Yeap: 01920115847e603be84255fc5f8d9b2d27b7bb3a
Thanks for that
