### ISSUE TITLE
Add ability to update and replace existing presets.

### ISSUE THREAD

**Issue by ztcollazo** [bitgapp/eqMac#502]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

When I edited one of my own presets, I tried to resave it, but it created a duplicate preset instead. Is it possible to change this so that it will overwrite the previous preset when I save a duplicate preset? 
<img width="394" alt="Screen Shot 2021-05-28 at 11 32 52 AM" src="https://user-images.githubusercontent.com/59693490/120008057-94652680-bfa8-11eb-94c7-ec4174adc596.png">

**Comment by nodeful** [comment]
This has been implemented in this commit: c592c894a32c9518f59325082b25a6eba30e606e
3 months ago 😆 
But I dont think I updated the UI version yet, so it didn't make it to the app yet.
Will try to do so today.
