### ISSUE TITLE
Bug: Boost volume lower than 100% normal [1.0.0]

### ISSUE THREAD

**Issue by byytelope** [bitgapp/eqMac#510]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Boosting volume anywhere from 1% to ~17% drops volume to lower than 100% non-boosted volume.

**Steps to Reproduce**
1. Increase volume to 100% without boost.
2. Boost volume by pressing the volume up key.

**Expected behaviour**
Volume should be louder than 100% from >1% boost.

**Setup information:**
 - Audio device used for playback: MacBook Air M1 speakers and USB headphone
 - Audio transmission interface: Default speakers/USB
 - macOS Version: 11.4
 - eqMac Version: 1.0.0
 - eqMac Driver Version: 1.2.1

**Additional information**
Did not happen before 1.0.0 update.

**Comment by nodeful** [comment]
Thanks for reporting this, I was able to replicate and now looking into the issue

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
