### ISSUE TITLE
Bug: application crashes after M1 goes to sleep

### ISSUE THREAD

**Issue by ilinkmike** [bitgapp/eqMac#515]
After the Mac goes to sleep, EQ Mac pro will no longer be open (assume crash) on reawakening 

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Open EQ Mac
2. Switch audio output from External Headphones to DELL U3818DW
3. Allow mac to go to sleep
4. Awaken Mac

**Expected behaviour**
EQ Mac should have remained open and DELL U3818DW still selected.

**Setup information:**
 - Audio device used for playback: DELL U3818DW monitor speakers
 - Audio transmission interface: HDMI
 - macOS Version: 11.4
 - eqMac Version [e.g. 0.0.1] 1.0.0 Driver 1.2.1
 - eqMac UI Version [e.g. 0.0.4] 1.3.3

**Additional information**
Can also be reproduced just by forcing the mac to sleep and then reawakening .

**Comment by tcz305** [comment]
This is also happening with me.
Nothing related to external speakers ...the app just closes whenever the computer sleeps.
iMac 11.2.3.
New bug since version 1.0.0

**Comment by simonmcl** [comment]
ditto, keep joining meetings after lunch and find the audio is not working

**Comment by V0LARE** [comment]
same here is there any fix for this?
i already turned sleep mode off just to listen music
Mac Mini 2020 M1 11.2

**Comment by ilinkmike** [comment]
Interestingly I may have stumbled across a fix (well more like a work around). I switched the cable running from the Mini to the Dell Monitor from HDMI to HDMI to a USB C (Thunderbolt 3) to DCC (Displayport Cable Compatible) and the app now performs as it should.

The system can sleep and then wake while remaining with the correct output source selected. The app also has not crashed after a week with the cable in place (which it did crash frequently prior to that) and what I believe may have been a memory leak (likely a symptom of the crashing) has also gone away.

So this may resolve the issue for other users (try switching your cables out as I have done) but it doesn't resolve the issue for the developers, but at least it's a clue for them.

**Comment by buxxb** [comment]
It is crashing after sleep. I have a 2017 MacBook running Catalina.

**Comment by hoofdletterj** [comment]
Similar issue here, although a bit simpler: 

Sound output stops after resuming from sleep on Macbook Air M1

eqMac app doesn't crash per se, but remains responsive and accessible. Only no sound can be heard. When the eqMac app is closed, regular sound output resumes. Relaunching the app works as predicted, where regular sound output gets filtered through the eqMac audio driver again. This behaviour was tested with several apps that output audio.

Macbook Air M1 - no external hardware / peripherals
macOS 11.4 (20F71)
eqMac version 1.1.0
driver version 1.2.3
UI version 1.5.6

**Comment by whatstheporpoise** [comment]
Same issue with output to USB DAC. iMac always wakes from sleep with no audio being passed to any device and eqMac in a crashed state. After force quitting and relaunching, eqMac selects internal speakers instead of the USB device used before the crash.

iMac 20,1 (Intel)
macOS 10.15.7
eqMac 1.2.0
driver 1.2.3
UI 2.1.1

**Comment by Cyberdroid1** [comment]
Been crashing for me too. When the output is set to a bluetooth speaker, the app will crash when waking from sleep. But, when the output is set to internal speakers, it will not crash.

MacbookPro9,2
macOS 10.12.6
App version 1.2.0
Driver 1.2.3
UI 2.1.1

**Comment by hoofdletterj** [comment]
> Similar issue here, although a bit simpler:
> 
> Sound output stops after resuming from sleep on Macbook Air M1
> 
> eqMac app doesn't crash per se, but remains responsive and accessible. Only no sound can be heard. When the eqMac app is closed, regular sound output resumes. Relaunching the app works as predicted, where regular sound output gets filtered through the eqMac audio driver again. This behaviour was tested with several apps that output audio.
> 
> Macbook Air M1 - no external hardware / peripherals
> macOS 11.4 (20F71)
> eqMac version 1.1.0
> driver version 1.2.3
> UI version 1.5.6

My issues instantly disappeared with updating to v1.2.0, thanks!

**Comment by JacqsLabz** [comment]
I think I'm having the same problem. I'm using a macbook. Every time I close it, whenever I open it again, eqMac has stopped responding and I have to force quit then reopen it to get my sound back. Every single time. I use this macbook for fun, and frequently close it when I get up to do something like change out the washer, grab a snack, refill my water bottle, take care of my dog, clean for a few minutes, etc etc etc. So I'm needing to force quit & restart eqMac many many times a day (on my days off work that is). Honestly I'm finding it to be super annoying. 

MacBook Air (13-inch, 2017)
no headphones, external speakers, etc - just using the built in speakers only
MacOS Monterey 12.0.1
eqMac app v1.4.6
driver v2.0.5
IU v3.2.4 (Remote)

**Comment by larruda** [comment]
SUPER annoying

**Comment by chetth** [comment]
My Mac mini M1 (Monterey 12.4) frequently crashes even whether it is in sleep mode or not. It happens when there is no sound device is used.

**Comment by Gandalf286** [comment]
same/similar issue here. switching to/from clamshell mode causes eqMac to crash. Have also noticed that when I have this running, my teams/slack calls don't have audio. Also crashed on wake from sleep.

**Comment by krazykriskomar** [comment]
So this bug is not only in the bug list at least 3 times (bug # 682, 515 and 670), but it's got to be **_the most debilitating bug_** in this program, basically making it unusable. Also, I seen multiple people state that they want to BUY this program and can't or will not due to this bug. Why has there been no response or traction from the developer on this?

**Comment by nodeful** [comment]
Hey everyone, 
I'm super sorry for the lack of communication from my end, the last 5 months have been pretty rough for me but I pulled through.
I have been working on an update for a while that addresses the issue you're all experiencing. 
I had to completely rewrite the Core of the app to use a more older version of Audio API's that Apple has.
The newer AVAudioEngine API that Apple has been pushing down developers throats ended up being a massive problem for eqMac and my productivity.
Hopefully this is all behind us now and I'll be able to release updates more often and better as I have more control over the Audio Pipeline!
Please check out a Pre-Release of v1.5.0 that you can download here: https://github.com/bitgapp/eqMac/releases/tag/v1.5.0
Or just Enable "Beta Program" in eqMacs Settings!
Please let me know how it goes!

Kind Regards,
Roman - Founder of eqMac

**Comment by panckreous** [comment]
Hey Roman, welcome back! Glad you made it through

**Comment by justinfx** [comment]
Hi. I've been running beta v1.6.1 and have been noticing that while the app isnt sitting in the tray with a spinning crashing icon when hovered... its actually fully quit now when I wake my M1 from sleep. It doesn't report that it crashed. It is just gone and I have to launch it again. Anyone seeing that behaviour now?

**Comment by anorudes** [comment]
I confirm. App stopped working and crashes after launch on M1. Reinstall didn't help

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Comment by kadumedim** [comment]
Happening on my M2 air.
