### ISSUE TITLE
Bug: "invalid bandwith parameter" for AutoEq preset

### ISSUE THREAD

**Issue by alex-boswell** [bitgapp/eqMac#517]
**Describe the bug**
When selecting the Audio-Technica m50x headphone preset in expert mode (non-specific earpads), I get the error message "invalid bandwith parameter, must be a Double between 0.05 and 5.00."

Additionally, I get the same error message when changing any bandwith manually after setting the preset, using either the slider or the numerical entry.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Go to expert mode.
2. Select the Audio-Technica m50x headphone preset, with the non-specific earpads option.
3. The error will appear in a red box. It appears again when the Q parameter is adjusted for any band.

**Expected behaviour**
No error message, and the preset should be implemented as in the data provided by the AutoEq project.

**Setup information:**
 - eqMac Version 1.0.0
 - eqMac UI Version 1.3.0

**Comment by nodeful** [comment]
Thanks for posting this issue!
I've investigated and found that AutoEQ sometimes uses Q Factor as low as 0.09 (6.97 Octaves) in case of your headphones:
https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Audio-Technica%20ATH-M50x
eqMac only supports bandwidth with Q Factor of 0.182 (or 5 Octaves) as the lowest. It's a limit that Apple enforces for now...
Maybe one day when I'll write our own EQ Unit this limit will be lifted.
For now though I have made a change to clamp the values that are outside eqMac's limits to those limits. This change makes some AutoEQ presets not be exactly what they should be, but the difference should be minimal and at least you can now select them. 
This update is an over the air update with UI Version 1.3.5, so if you restart eqMac and see that version you should be able to select your preset now. 
Please let me know how it goes and what you think of this solution in general and consider closing the issue if you are satisfied!

**Comment by alex-boswell** [comment]
Thank you! I appreciate the quick response and agree your change is a good solution, so I am closing the issue.

Best wishes, and thanks for the excellent software.
