### ISSUE TITLE
Ok this project is going pro, time to fork this shit

### ISSUE THREAD

**Issue by peterdowns-cmccd** [bitgapp/eqMac#518]
Ok this project is going pro, time to fork this shit

**Comment by nodeful** [comment]
The part that is free will always stay open source and will be improved. Also all the future Free features will be open sourced as well. I will also release signed builds of just the Open Source code for people to download, without the Pro features, just need to figure out the infrastructure. Feel free to fork and change as you'd like! But remember you can't use "eqMac" brand to distribute your copies.
