### ISSUE TITLE
Bug: Flaky music output through external DAC (Qobuz)

### ISSUE THREAD

**Issue by BendeguzBe** [bitgapp/eqMac#520]
**Describe the bug**
Using Qobuz as the source and playing High-Res or "CD-Quality" files through an external DAC eqMac doesn't play Music reliably. Using eqMAC as the Audiooutput in Qobuz it regularly stops playing any audio even it the track itself keeps playing in Qobuz.
I don't think that it is an issue of Qobuz, because the audio starts playing again as soon as a change the Audiooutput to another Output.

To resolve the issue I have to change the Audiooutput in eaMac to another Output and then change it back to the DAC again. This fix only resolves the issue for 1 song. As soon as the next song gets played I have to do the whole dance again ;)

**Setup information:**
 - Audio device used for playback: Xduoo XD05+ DAC/AMP
 - Audio transmission interface: USB-C IN
 - macOS Version: 11.4
 - eqMac Version: 1.0.0; Driver 1.2.1
 - eqMac UI Version: 1.3.4

**Screenshots or Console.app logs**
Jun 26 12:50:29 Mac-mini-von-Benaja eqMac[762]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
Jul  2 18:25:09 Mac-mini-von-Benaja com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100005.Aqua): Could not import service from caller: caller = otherbsd.395, service = com.bitgapp.eqmac-LaunchAtLoginHelper, error = 119: Service is disabled
Jul  3 14:10:40 Mac-mini-von-Benaja com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100005.Aqua): Could not import service from caller: caller = otherbsd.414, service = com.bitgapp.eqmac-LaunchAtLoginHelper, error = 119: Service is disabled
Jul  3 14:21:44 Mac-mini-von-Benaja eqMac[1438]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
Jul  3 15:11:38 Mac-mini-von-Benaja com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.bitgapp.eqmac.14082771.14082778(501)> [1649]
Jul  3 15:11:40 Mac-mini-von-Benaja eqMac[2164]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
Jul  3 16:02:22 Mac-mini-von-Benaja com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.bitgapp.eqmac.14082771.14082778(501)> [1649]
Jul  3 16:02:25 Mac-mini-von-Benaja eqMac[2816]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
Jul  3 16:04:06 Mac-mini-von-Benaja com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.bitgapp.eqmac.14082771.14082778(501)> [1649]
Jul  3 16:04:09 Mac-mini-von-Benaja eqMac[2841]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
Jul  3 17:01:02 Mac-mini-von-Benaja com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.bitgapp.eqmac.14082771.14082778(501)> [1649]
Jul  3 17:01:04 Mac-mini-von-Benaja eqMac[3468]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory

**Comment by momaek** [comment]
I have the same problem, do you have any idea

**Comment by jackofallstudios** [comment]
I have the same problem. I cannot continue my subscription until this issue is resolved. I use Qobuz exclusively and EQMac works 20% of the time and I have to keep adjusting the volume to flip back and forth between Bifrost 2 and Bifrost 2 with eq mac output only for it to maybe work (20% of the time). This is exhausting and not worth the trouble. I can't get my gaming PC to not produce audible noise (even with idefender, ipurifier, isilencer, and unison usb, galvanic isolation dac) so I need to use my Mac Mini and if this app were to become usable with Qobuz, then that would be a game-changer for me.

**Comment by pattont** [comment]
I think the issue occurs when the resolution changes. If you stay with one album all the same resolution does it still happen? I posted about this in another thread, but it looks like whenever the Qobuz switches the "Output Format in MacOS's Audio Midi Setup" eqMac goes all buggy with the audio. Switching devices fixes it like it refreshes it in eqMac somehow and it's resolved. 

The same thing happens with Apple Music using the free app LosslessSwitcher (which Qobuz does automatically). 

Given that this post is from 2021 and now it's 2023 and the issue still exists I am nervous that it's gonna get fixed.

**Comment by nodeful** [comment]
This issue was one of my main focuses on the latest update that I just released to Beta testers:
https://github.com/bitgapp/eqMac/releases/tag/v1.7.4

Can you try out this release and let me know if the issue with Sample Rate switching performs well now :)

Thank you!

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed now, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
