### ISSUE TITLE
Bug: Music gets slowed down

### ISSUE THREAD

**Issue by BendeguzBe** [bitgapp/eqMac#521]
**Describe the bug**
From time to time when playing music from Qobuz through eqMac (using an external DAC) the track gets slowed down. So the music sounds a lot deeper like being in slow-motion.

I don't think it's an issue of the DAC, because I only experiment this behavior using eqMAC.

**Setup information:**
 - Audio device used for playback: Xduoo XD05+ DAC/AMP
 - Audio transmission interface: USB-C IN
 - macOS Version: 11.4
 - eqMac Version: 1.0.0; Driver 1.2.1
 - eqMac UI Version: 1.3.4

**Comment by nodeful** [comment]
Thanks for the report, but probably relates to #401 and #423 so please refer to those in the future.
