### ISSUE TITLE
Bug: Sometimes becomes an echo cave

### ISSUE THREAD

**Issue by Reiszecke** [bitgapp/eqMac#523]
**Disclaimer:** 
Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

First of all, congrats to 1.0 and your step to self-employment, you deserve it!

**Describe the bug**
What made me update was a recent occurrence of eq mac <1.0 instead of doing what it's supposed to do, simply playing a mess of distorted audio with repeating bits of continuous bits that sounded like buffer frames in length. I could recreate how it sounded like in Ableton Live if it helped you.

Now after updating to 1.0 I did not have this issue again - however I did experience something very similar - watching something on Prime Video and hitting the mute button on my keyboard while video was still playing did in fact mute the audio, it did however cause a repeated distorted echo/delay of the last bit that was playing. The echo occurred like 2-4 times a second. During composing this issue here, I later clicked "play" again and the problem was gone.

**Setup information:**
 - Audio device used for playback: External headphones
 - Audio transmission interface: AUX jack on the Mac
 - macOS Version: 11.4
 - eqMac Version: 1.0.0

**Additional information**
Since """upgrading""" from Air to Pro I have always experienced all sorts of things that made me restart CoreAudio or the whole device, Apple quality really did go downhill in the past years which is why I'm not sure if this is in fact caused by eqMac but in case someone else experiences this, maybe we are onto something here.

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
