### ISSUE TITLE
Bug: Expert mode displays curves with a narrower bandwidth than what is entered.

### ISSUE THREAD

**Issue by rjbunge99** [bitgapp/eqMac#524]
Expert mode displays curves with a narrower bandwidth than what is entered.

Entering a boost or cut with a bandwidth of 3 octaves displays a curve with a bandwidth of about 2 octaves. The true bandwidth seems to be roughly 50% wider than the value entered.

Verify this for yourself by comparing the eqMac display to any other parametric EQ with the same values entered.

I'm not certain whether the changes to audio reflect the displayed curves or the true values entered.
 - macOS 10.15.7
 - eqMac Version 1.0.0
 - eqMac UI Version 1.4.0

**Comment by nodeful** [comment]
I'm investigating this now, seems like you are correct but it seems to be more of a problem on higher bandwidths, 1 octave looks very Similar to a lot of EQ plugins, but as you go higher it starts to be more incorrect.
The visual doesn't affect the sound in any way btw, so 3 Octaves will be 3 real octaves, as long as Apple got their maths correct

**Comment by nodeful** [comment]
New curve for Peaking filter:

![image](https://user-images.githubusercontent.com/8472525/125533572-e9afc33c-80d0-4adc-b957-6ce06d681554.png)


New curve for High/Low shelf:

![image](https://user-images.githubusercontent.com/8472525/125533606-0f041e3b-8d84-495d-bd0d-0a6edbf1ff6f.png)

This was released as part of Over the Air UI update v1.5.2. Refresh eqMac a you should see the new curve shapes.
Thanks for reporting this.

**Comment by rjbunge99** [comment]
Looks good now. Thanks for looking into it.
