### ISSUE TITLE
Window keeps popping up after sleep + not consistent sound volume control.

### ISSUE THREAD

**Issue by buxxb** [bitgapp/eqMac#526]
Every time I open my computer after sleeping, the eqmac window pops up in the centre of the screen. WHY? It doesn't even remember the last place I put it on the screen. It doesn't matter if I have the desktop or menubar preference. It doesn't;t matter if I hide or close the window before closing the computer and later opening it again. 

There is something else. Despite increasing volume to  200%, the sound volume in sound only still thinks I am using the normal 100%, so the added 100% is not recognised by the sound volume. So, if I start from 200% and go to 100% using the sound volume on the keyboard, the pop flicks back to 100% UNTIL I reach where the normal 100% is for the computer. It would help if the system volume control was calibrated to the full 200% I set eqmac to.

I appreciate this is free, but with issues like this, why would I buy it?

Something to look at ...

**Comment by tcz305** [comment]
issues already previously noted and we are all waiting for fixes, ....if you had read previous posts.
as for threatening not to buy it i doubt the dev would purposefuly leave bugs wether it was free or paid.

**Comment by nodeful** [comment]
> issues already previously noted and we are all waiting for fixes, ....if you had read previous posts.
> as for threatening not to buy it i doubt the dev would purposefuly leave bugs wether it was free or paid.


Could not have said it better. I'm more frustrated by bugs than any of my users. Fix coming today/tomorrow. Closing this as duplicate
