### ISSUE TITLE
No playback on bluetooth

### ISSUE THREAD

**Issue by thomasgordon** [bitgapp/eqMac#528]
plays through my laptop speakers fine but when i swap onto my bluetooth headphones there is no playback whatsoever, and it occasionally crashes

macOS: 11.2.2
app version: 1.1.0
UI version: 1.5.1

**Comment by nodeful** [comment]
Hey why did you close the issue? Did you figure something out?

**Comment by thomasgordon** [comment]
apologies, i am an idiot and didn’t do sufficient troubleshooting before submitting the issue. managed to fix it by turning everything on and off several times so i’m guessing it is just an issue with my laptop
