### ISSUE TITLE
Typos in system message

### ISSUE THREAD

**Issue by qwertyuu** [bitgapp/eqMac#530]
https://github.com/bitgapp/eqMac/blob/349187df4c74e1296b1a175142531054c993211d/native/app/Source/Application.swift#L99
https://github.com/bitgapp/eqMac/blob/349187df4c74e1296b1a175142531054c993211d/native/app/Source/Application.swift#L100

Both use the word "corrently" instead of "currently"

**Comment by nodeful** [comment]
Aw yes my sausage fingers at it again. Thank you! fixed on a separate branch.
