### ISSUE TITLE
Sound control only registers to 100% despite boost set to 200%

### ISSUE THREAD

**Issue by XY43137** [bitgapp/eqMac#533]
I hope this makes sense. 

On increaing the volume using keystrokes, the sound pop-up only registers to the mac's 100% volume when in boost mode. So increasing or decreasing volume in boost shows on the mac as always full volume. The sound feedback doesn't scale to the full 100% boost. This also means that I can't use the sound menubar slider to increase volume in the boost mode. I can only use keystrokes. In essence, the mac doesn't recognise that the volume has increased to the 200%. It just seeds the 100%. I can use the boost volume, but there is no visual feedback to tell you that boost is on. 

Make sense? Just turn on boost, increase the volume using the sound up on the keyboard past the 100% that the mac sees, and you will see what happens. The second 100% that epmac boosts sound to is always just full volume to the mac.

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!

**Comment by XY43137** [comment]
Jesus, when did I write that? Way passed this now.

Thx. Bye.
Kind regards,

------------------------------
   F R E D E R I C K   M A L O U F
   X Y
   P O   B O X   7 4 3 4      B O N D I   B E A C H   N S W   2 0 2 6     A
U S T R A L I A
+ 6 1   4 0 3   9 9 3   6 9 9
------------------------------
How would I define myself? That’s like asking the definition of infinity …
