### ISSUE TITLE
Spatial Audio is not working

### ISSUE THREAD

**Issue by SJang1** [bitgapp/eqMac#534]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Spatial Audio is not working, and midi shows eqmac as stereo, not for Spatial Audio

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Try Pro Feautures.
2. Try to listen to Spatial Audio music.
3. It doesn't use Spatial Audio, plays as stereo.

**Expected behaviour**
It should play as Spatial Audio

**Setup information:**
 - Audio device used for playback: Airpods Pro
 - Audio transmission interface: Bluetooth
 -  - macOS Version: 12.0 21A5268h
 - eqMac Version 1.1.0 / driver 1.2.3
 - eqMac UI Version 1.5.3

**Screenshots or Console.app logs**
<img width="763" alt="스크린샷 2021-07-14 오후 10 30 59" src="https://user-images.githubusercontent.com/29011440/125630603-3c1c3aab-dded-4347-9532-e97ecf85913d.png">

**Additional information**

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
Spatial Audio in eqMac doesn't mean Surround Audio which is what I think you are referring to.
I'm working on adding Surround Audio to eqMac in the next update (if you have Surround Audio equipment)
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
