### ISSUE TITLE
New Random crashes while in use since 1.1.0

### ISSUE THREAD

**Issue by tcz305** [bitgapp/eqMac#535]
seems possibly similar to https://github.com/bitgapp/eqMac/issues/513

**Describe the bug**
since 1.1.0 the app now randomly and frequent crashes while in use, ass opposed to only after going to sleep etc.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. launch app
2. play any audio
3. sometimes the audio will go off or flicker on and off
4. if you open the sound control panel you can see the audio output flicking between internal speakers and eqmac
5. the app will eventually crash and quit

**Expected behaviour**
this should not happen, the app should stay open

**Setup information:**
 - Audio device used for playback: [internal speakers]
 - Audio transmission interface: [bluetooth]
 - macOS Version: [e.g. 11.2.3]
 - eqMac Version 1.1.0

**Screenshots or Console.app logs**
crash report attached ( i think that's the right one from one of the crashes)
[crash report.txt](https://github.com/bitgapp/eqMac/files/6831471/crash.report.txt)

**Comment by buxxb** [comment]
It is crashing after sleep. I have a 2017 MacBook running Catalina.

**Comment by LeeBinder** [comment]
For me, the latest eqmac only crashes after wake from sleep. Intel Mac, macOS Mojave 10.14.6. No crashes with the old version.

**Comment by tcz305** [comment]
this seems to have been fixed since 1.2.0 so i'm going to close this thread
