### ISSUE TITLE
Bug: Sliding volume from macOS status bar volume control causes volume jitter

### ISSUE THREAD

**Issue by salieri** [bitgapp/eqMac#536]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Sliding volume from macOS status bar volume control causes volume jitter

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Assuming you've checked System Preferences > Sound > Show volume in menu bar
1. Click sound icon in macOS status bar to reveal the volume control
1. Drag the "thumb" of the slider to a new spot (just clicking to change volume isn't enough; gotta do mouse down, slide, mouse up)
1. Volume begins to jitter 

Jitter can be stopped by changing the volume from eqMac.

**Expected behaviour**
Jitter should not occur

**Setup information:**
 - Audio device used for playback: internal iMac speakers
 - Audio transmission interface: n/a
 - macOS Version: 11.4
 - eqMac Version 1.1.0
 - eqMac UI Version 1.5.7

**Comment by nodeful** [comment]
By any chance on a Hackintosh?

**Comment by nodeful** [comment]
Aw sorry iMac, didn't read

**Comment by salieri** [comment]
Yeah, it's an Intel iMac Pro 2017 if that's any help.

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
