### ISSUE TITLE
Restart audio service when the computer wakes @ MacOS 11.4

### ISSUE THREAD

**Issue by amiltonjr** [bitgapp/eqMac#537]
Everytime the computer wakes, the app crashes and outputs no sound. What I do to fix it is run a bash script that restarts the audio service and then restarts eqMac. The code is the following:

```
restartaudio() {
	echo "Restarting audio service..."
	sudo nohup pkill -9 eqMac >/dev/null 2>&1
	wait
	sudo nohup pkill -9 coreaudiod >/dev/null 2>&1
	wait
	echo "Done!"
	echo "Opening eqMac..."
	nohup open -n /Applications/eqMac.app >/dev/null 2>&1
	wait
	sleep 6
	osascript -e 'set ovol to output volume of (get volume settings)' >/dev/null 2>&1
	echo "Done!"
}
```

I hope it helps the development team to fix it soon.

**Comment by LeeBinder** [comment]
Thank you. Same here on an Intel Mac still running macOS Mojave 10.14.6. Would be great if this bug can get solved 👍

**Comment by PeterFalken** [comment]
Same here, waking up from sleep no sound afterwards - Intel Mac running macOS 11.5.2.
Must hit volume keys for eqMac to start working again.

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
