### ISSUE TITLE
Bug: Selecting "Advanced" presets mode does not allow scrolling or selecting preset via up/down keys

### ISSUE THREAD

**Issue by naipaulojar** [bitgapp/eqMac#538]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Selecting the "Advanced Mode", a number of presets are available. More are available than fit in the visible window. Only the ones that are visible are selectable via the point-and-select via the mouse. Once I was able to scroll via mouse, but never again.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Go Equalizer "Advanced" Mode
2. Click on 'up/down' arrows and a list of presets are visible, more exist
3. Scrolling is not supported within the presets window
4. Using the Up/Down keyboard arrows does not scroll within the list of presets
5. Page-Up or Page-Down does not scroll within the list of presets

**Expected behaviour**
Within the list of "Advanced" Presets, I would be able to select a value via the following keyboard selectors:-
1. Click on Mouse, to select a visible preset option
2. Starting from the selected preset, the up/down keys should allow the user to select the new desired preset
3. Moving from the last visible preset, the non-visible options should be visible. The visible window should be a movable window for presets. At the moment, non-visible presets in the window are not selectable.

**Setup information:**
 - Audio device used for playback: [Any]
 - Audio transmission interface: [Any]
 - macOS Version: [10.15.17]
 - eqMac Version [1.1.0] 
 - eqMac UI Version [1.5.10]

**Screenshots or Console.app logs**
![Unable_to_scroll_below](https://user-images.githubusercontent.com/33267717/126640951-09e5c24c-6a3d-4517-ace9-147a685a35aa.jpg)

**Additional information**
The very first time I opened the Presets, there was only 1 item.
On closing and re-opening I found the list of presets

**Comment by naipaulojar** [comment]
This is an Intel MacBook Pro 2019

**Comment by nodeful** [comment]
Thank you for the detailed report and I'm sorry it took me so long to respond.
I'm cleaning up issues now that have been stale for a while.
Even though I agree that generally using arrow keys should be supported the intended way is to use Mouse wheel or two finger scroll on the Touchpad, there's also a scrolling bar to the right.
![image](https://user-images.githubusercontent.com/8472525/218612308-54570e0a-ad84-4e18-8aac-30ed6517c06e.png)
Closing this issue for now for upkeep, but will try to improve the experience maybe in a future update.
