### ISSUE TITLE
Bug: Kernel task spike

### ISSUE THREAD

**Issue by mamarkg** [bitgapp/eqMac#540]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
with the new version, i've been experiencing a spike in kernel task. it's usually 7-9% on my end. but when using eqmac, it spikes up to 400+%. No other apps opened, just spotify and eqmac

**Steps to Reproduce**
opening eqmac

**Expected behaviour**
runs smoothly without spiking kernel task

**Setup information:**
 - Audio device used for playback: logitech z333 on USB sound card
 - Audio transmission interface: USB sound card to USB C
 - macOS Version: 11.4
 - eqMac Version] 1.10
 - eqMac UI Version 1.6.2

**Screenshots or Console.app logs**
--

**Additional information**
sometimes, it works normally. most of the time it spikes up my kernel task.

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, or maybe it wasn't related to eqMac at all, I had Macbook where the Kernel task would run at 100% for no reason, with no software running at all.
I encourage people to try v1.7 by download it from the website: https://eqmac.app/
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
