### ISSUE TITLE
Bug: eqMac Web Content high CPU Usage

### ISSUE THREAD

**Issue by Bijan91** [bitgapp/eqMac#542]
Dear developer, I'm using the Pro-version of eqMac for the first time now on my MacBook Pro 16" (i7).
With the App open and listening to music, I recognized a very high CPU usage of "eqMac Web Content" of around 87%.

After reboot and reinstall it's unfortunately the same, so I switched back to eqMac2 (which I still love).

Setup information:
 - Audio device used for playback: Universal Bluetooth Receiver
 - Audio transmission interface: Bluetooth or 3.5mm
 - macOS Version: 10.15.7
 - eqMac Version: 1.1.0
 - eqMac UI Version: 1.6.3

<img width="959" alt="Bildschirmfoto 2021-07-31 um 16 54 36" src="https://user-images.githubusercontent.com/83472743/127744245-670aa93c-8928-4c87-ae72-273fbd5a588b.png">

Thank you for caring!

Edit 1: Same happens on a MacBook Air 2013 running MacOS Mojave.
Edit 2: CPU-Usage increases even more, if the actual preset is turned off (so the signal bypasses the eq).

**Comment by nodeful** [comment]
I'm completely aware of this and in the update v1.2.0 that I'm releasing today most of the performance issues were addressed. However, drawing out the Spectrum Analyzer in the Web UI is very resource heavy and I think I've done everything I could (in update v1.2.0) to optimise it's performance, I think we're hitting some Web Limits at this point. Switching the Spectrum Analyzer off in the Expert EQ settings should improve the performance. Sorry that you've encountered this problem, hope you will believe that I'm trying my best 😅

**Comment by Bijan91** [comment]
Don' be sorry! I'm just happy that there is no problem with my hardware or OS. Thank you very much for caring Roman. Don't hurry too much, your wonderful EQ is definitely worth waiting for🙌🏼

**Comment by nodeful** [comment]
> Don' be sorry! I'm just happy that there is no problem with my hardware or OS. Thank you very much for caring Roman. Don't hurry too much, your wonderful EQ is definitely worth waiting for🙌🏼
> 
> Edit 1: Installed Version 1.2.0 with recent Web-UI. Better overall performance and improved look and feel of the UI - thanks for that! It still needs a lot of CPU but only if the window is open. When I close it while EQ is still active, cpu usage drops near zero. Maybe you could add a switch in the next update, which could en- or disable the spectrum analyser manually.


But you can disable the Spectrum Analyser since v1.0.0
It's in the settings of Expert EQ. 
Sorry I may have totally missed the point. Are you using the ExpertEQ when the CPU usage is high? Or is it high during other EQ types?

**Comment by Bijan91** [comment]
I'm such a moron! Didn't see the option man. So thanks again, everythings working perfectly now. Probs to you, cheers!

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app/
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
