### ISSUE TITLE
Bug: Pan knob must be tweaked upon app launch else the pan setting is not regarded

### ISSUE THREAD

**Issue by benj-o** [bitgapp/eqMac#547]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
An existing panning setting is not regarded upon opening eqmac, until you touch the rotary control.

**Steps to Reproduce**
1. Open eqmac interface, tweak pan setting and quit eqmac.
2. Open eqmac.
3. Audio is not panned even though the pan knob is in the previously set position.

**Expected behaviour**
Audio to be panned as the knob shows.

**Setup information:**
 - Audio device used for playback: External headphones
 - Audio transmission interface: 3.5mm Jack
 - macOS Version: 11.5
 - eqMac Version 1.2.0, driver version 1.2.3
 - eqMac UI Version 2.0.0 local

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app/
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
