### ISSUE TITLE
Bug: Audio output defaults back to internal speakers when moving from expert to advanced equalizer 

### ISSUE THREAD

**Issue by Lunas12** [bitgapp/eqMac#549]
When i switch from the advanced to expert equalizer and vice versa the audio output switches back to the internal speakers despite having bluetooth headphones connected

**Comment by nodeful** [comment]
Yeap I noticed that as well. Will be fixed in next update. Thanks for reporting

**Comment by superjeng1** [comment]
Hi, I am closing this issue since this bug is fixed. Feel free to reopen it if this is not the case.
