### ISSUE TITLE
Bug: 1.2.0 update crackles and repeats .5 sec audio every 5-8 seconds

### ISSUE THREAD

**Issue by sandinak** [bitgapp/eqMac#554]
**Disclaimer:** 
- [x] I have checked for a similar issue and am sure it hasn't been reported before.

**Describe the bug**
When playing music .. the system will "Crackle" and then repeats about .5 of a second and continues to stream.  This happens every 5-8 seconds of any playback. ( Web, Hermes or Music ).  I also note it seems to be buffering ALOT of audio as when I hit stop it has to take a second or two before the music cuts out. 

**Steps to Reproduce**
Steps to reproduce the behavior (feel free to change the placeholder as you need):
1. Updated this morning to current 
2. Lost my presets .. so was base configuration ( no eq ) 
3. play anything 
4. hear repeats

**Expected behavior**
Music Stream should be consistent 

**Setup information:**
 - Audio device used for playback: External Speakers 
 - Audio transmission interface: 3.5mm back
 - macOS Version: 11.5.2
 - eqMac Version 1.2.0 
 - eqMac UI Version 2.1.1
 - eqmac Driver Version: 1.2.3
 - iMac 2020 27" 3.8GhHz 8 core i7 with 128GB memory. 

**Screenshots or Console.app logs**
Nothing in the logs.  

**Additional information**

**Comment by superjeng1** [comment]
I am closing this since this issue has been pretty old. Feel free to reopen it if you are still having this issue. Note that, there is a pretty long standing bug where if the memory (RAM) usage is too high, macOS's audio output would be inconsistent, and that bug would happen even without eqMac.
