### ISSUE TITLE
Bug: Distortion at high gain (over 5 to 10 db)

### ISSUE THREAD

**Issue by randcraw** [bitgapp/eqMac#556]
Whenever I turn up equalization gain over 10 db, I consistently get a lot of distortion.  This happens at lower gains sometimes (as little as 5 db) and is clearly audible in good headphones as well as good external speakers that should not distort at these volume gain levels.

If I keep all the EQ below 5 db, eqMac sounds great.  Thanks again for the recent improvements.  I want to point out this is **_not_** a severe bug, but something that could benefit from explanation or optimization.

In the basic interface, distortion seems to begin at:
- the bass rotary 'knob': 5 to 10 db
- the midrange knob:  5 to 10 db
- the treble knob does not obviously distort at any gain level

In the advanced slider interface, the distortion is clearly audible at:
- 32: +17 db
- 64: +10 db
- 128: +9 db
- 250: +8 db
- 500: +16 db
- 1K:  +13 db
I'm not sure about distortion at higher frequencies.  My ears may are no longer young and not be sensitive at this range.

I used a 'master' source from Tidal to get a clean input signal.  I used music, not test tones.

I'm using eqMac 1.20, an AudioQuest Dragonfly Red USB DAC, and a 2018 Macbook pro running Big Sur 11.5.2.  The MIDI settings are 88,200 for all audio interfaces.  Headphones are Denon AHD-2000, speakers AudioEngine 5+.

**Comment by whatstheporpoise** [comment]
Use the Global gain to attenuate equal to the largest boost you have set on any one band to ensure no distortion will occur. Increasing the gain on a digital signal is bound to create distortion eventually and I would not consider this a bug.

**Comment by nodeful** [comment]
Yes this is not a bug but a limit of protocol/encoding of data that is outside of my control, as @whatstheporpoise said lower the global gain as much as the highest gain you have on a band and compensate with volume
