### ISSUE TITLE
Bug: Hiding either of Volume or Balance hides both from the UI

### ISSUE THREAD

**Issue by Cyberdroid1** [bitgapp/eqMac#560]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When using the "Show/Hide Features" and hiding either of Volume or Balance, it hides both of them.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Open eqmac settings
2. Click on Show/Hide Features
3. Untick **either** Volume **or** Balance
4. Come back to flyout and notice that both of the elements have hidden.

**Expected behaviour**
Only one of them should be hidden.

**Setup information:**
 - Audio device used for playback: Internal speakers
 - Audio transmission interface: idk, maybe system?
 - macOS Version: 10.12.6
 - eqMac Version 1.2.0
 - eqMac UI Version 2.1.1

**Screenshots or Console.app logs**

![image](https://user-images.githubusercontent.com/51435948/132227874-b37f16ea-7e2c-44e5-a2e3-d77cedecbe51.png)

![image](https://user-images.githubusercontent.com/51435948/132227918-c9dfb505-756e-4b05-9d4c-005ab835512a.png)

**Comment by nodeful** [comment]
Thanks for reporting this and sorry for not replying in time, this bug has been fixed for a while now.
Closing this issue
