### ISSUE TITLE
several .dmg installers on this site come up as 'corrupted'

### ISSUE THREAD

**Issue by kalamalka** [bitgapp/eqMac#562]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Various DMG downloaded form this site files will not open. There are warnings on most older versions that say the image is corrupt. 

**Steps to Reproduce**

1. Go to https://github.com/bitgapp/eqMac/releases/tag/v0.3.0
2. Download .dmg file
3.Observe pop op window with description of error. 

**Expected behaviour**
Installer window should appear. 

**Setup information:**
 - Audio device used for playback: N/A
 - Audio transmission interface:  N/A
 - macOS Version: 10.9.5
  - eqMac Version [e.g. 0.0.1] **(if audio related issue)**
 - eqMac UI Version [e.g. 0.0.4] N/A

**Screenshots or Console.app logs**
N/A 

**Additional information**
Could anyone confirm that these older installers are working? Also, I need to find something that works on 10.9.5. 
Thanks in advance!

**Comment by superjeng1** [comment]
This is Apple's GateKeeper blocking the .dmg files. The versions you mentioned is really old and it is not really feasible to go back and re-sign every package we released, so I would close this issue as won't fix. However, there is a way to bypass this, please just right click and select "Open" from the context menu, this would change the options the message presents to you to include "Open".
