### ISSUE TITLE
Feature: Implement Light mode for the UI

### ISSUE THREAD

**Issue by Cyberdroid1** [bitgapp/eqMac#563]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
Add an option to change the UI to follow Light theme, Dark theme, or the System theme.

**User flow & interface:**
It can be added as a row of button just like how the "Status Icon Type" is done.

**Comment by nodeful** [comment]
I've implemented Light/Dark theme with a little bit of a redesign. Should be available in app version v1.3.0 and higher if you have OTA Updates enabled.
![image](https://user-images.githubusercontent.com/8472525/149200591-03abba15-6190-413a-aa82-422ca6e4541a.png)
![image](https://user-images.githubusercontent.com/8472525/149200620-9b00116b-e3d5-4017-b3b1-cc7f2f1ace3d.png)
