### ISSUE TITLE
Does the pro version have a live Visualizer?

### ISSUE THREAD

**Issue by Onyx808** [bitgapp/eqMac#564]
Hi, looking at the home page it looks like it has a visualizer?
![image](https://user-images.githubusercontent.com/987993/134087865-55223674-2a1b-400f-b35e-456077c171de.png)

**Comment by nodeful** [comment]
It does have a live Spectrum Analyzer. Please try the Trial mode (click the Pro button in eqMac top bar) and test it out before committing to the Pro Subscription. You can trial for 5 minutes with a 1 minute timeout unlimited amount of times

**Comment by tempusthales** [comment]
Those color bands you see, is not a visualizer like you are thinking, its just a type of "slider" to configure the EQ.  The two "visualizers" are a traditional peak bar, and the sound lines...

![eqMac_peakbars](https://user-images.githubusercontent.com/2447303/134257707-d65e39a9-7cb0-4755-a238-5637f24956f1.gif)

![lineEQ](https://user-images.githubusercontent.com/2447303/134257861-ea02ac5c-2e13-4808-930e-42b0a50ba6f6.gif)

I haven't figured out how to remove the color "sliders"...

**Comment by Onyx808** [comment]
Is there any Docs?

**Comment by nodeful** [comment]
@Onyx808 there's no Documentation currently, but I'm working on it as well as video showcase/tutorial of eqMac.
The original question has been answered, so closing the issue. Thank you
