### ISSUE TITLE
Feature: Implement X so users can do Y (REPLACE THIS)

### ISSUE THREAD

**Issue by tempusthales** [bitgapp/eqMac#568]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
In the Equalizer section with the Sliders, there is an option in Advanced, that you can use some Color shades to control the EQ.  The sit on top of whatever visualization is playing and makes it difficult to see the viziualization, once you are done manipulating them.  It would be nice, if there was a way to turn them on and off.  See example of what I mean below, its outlined by a horrible red line of my own creation ;)

![Outline](https://user-images.githubusercontent.com/2447303/134260465-165e859e-bf44-4e3b-8242-0c78a222431b.png)

![lineEQ](https://user-images.githubusercontent.com/2447303/134260492-689e8737-bb81-4dc7-b1de-997267760b05.gif)

**User flow & interface:**
A very small icon about the size, of the Eye icon used to minimize the section, in the same shade and wavy pattern would help, if you click it once, it goes grey and turns it off, if clicked again, it turns lightly colored and turns it on again. 

![eqMac_example_1](https://user-images.githubusercontent.com/2447303/134262012-de844cf0-57a9-412e-95f6-cd8119d51156.png)

![eqMac_example_2](https://user-images.githubusercontent.com/2447303/134262024-41202dbc-dee8-472e-83fa-c07e494c9e3c.png)

Or even a little button that you flip on and off would help. If there is no room, in the front interface, then a checkup box when you click the EQ Gear Menu would also work.

![eqMac_example_3](https://user-images.githubusercontent.com/2447303/134262380-ce992292-f6b6-4b8d-bd68-a186910ef68c.png)

Thanks!

**Comment by nodeful** [comment]
This has now been implemented in the latest UI update in the Expert EQ settings, we discussed it on Discord :) Please next time the Title of the issue need to be replaced from the Template. Closing this issue.
