### ISSUE TITLE
eqMac preventing sleep (Monterey - 12.0 Beta 21A5543b)

### ISSUE THREAD

**Issue by Lapin** [bitgapp/eqMac#574]
Hey, 

I'm not sure if this was reported before but I've just noticed eqMac is preventing my mac going to sleep

<img width="1054" alt="Screenshot 2021-10-11 at 14 56 56" src="https://user-images.githubusercontent.com/1576470/136802949-142bd097-b7ac-49d1-bb22-9b9e73b66e5f.png">

If so, please feel free to discard this ticket and sorry!

**Comment by hexeric** [comment]
yes, seems like because it is using audio IN/OUT systems and stops sleep on some machines. it works on macbook when you close the lid unless you have an external display.

**Comment by rivanovs** [comment]
Same on macOS Big Sur 11.6.1 (20G224).
I'm running a MacBook Pro (16-inch, 2019) with an external DELL U2518D monitor connected over a Type C-HDMI dongle, and I have speakers connected to the monitor.
I'm using eqMac for the sole purpose of controlling the volume of the external speakers. It does the job with two caveats:
1. It prevents MacBook from going to sleep
2. After restarting the MacBook, despite the fact, that eqMac shows the same volume level as before restart (30%), the actual volume is at 100% until you change it. As soon as I change it, the new volume is applied. To work around this I had to create an Automator app, that starts at user login, then waits for 30 seconds (to give time for everything including eqMac to start), then changes volume to 10%, and then - to the preferred 30%.

**Comment by hexeric** [comment]
i changed to the free 'speakeramp' on appstore for this reason and all is good now (eqMac also crashes for me on Monterey around sleep and has a strange ground crackling noise).

**Comment by rivanovs** [comment]
I have also tried SoundFlower - it works, but with its own caveats. It too prevents sleep, and after ~30 minutes of playback the sound becomes choppy and robotic, so I have to select a different output and switch back to the monitor.

MonitorControl works great for brightness control, but it does not change sound volume in my case. The HUD does appear when I change it, but the actual volume stays the same (at max level).

I have just installed SpeakerAmp - looking good so far. It can even switch outputs when I unplug/replug the monitor, and Activity Monitor says it does not prevent sleep. So far so good.

**Comment by nodeful** [comment]
![image](https://user-images.githubusercontent.com/8472525/146656357-d06d1b3a-3aa6-4bc4-b95e-98dddf810c5e.png)
I finally figured this one out, will be fixed in the next update that's coming next week.
Sorry for the delay, I will let you know when the update is available.

**Comment by nodeful** [comment]
I've just release a new PRE-Release v1.4.0 build that should solve this issue.
I'm looking for people to beta test this build.
You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.4.0 (eqMac.pkg)
Could you please try it out and report if this issue still persists or if there's any other issues.
Thank you! And sorry for the wait 🙏🏻

**Comment by tootlezz** [comment]
I was having this problem since installing eqMac on my iMac with Monterey, but after the update it goes to sleep normally.

**Comment by gradha** [comment]
> Could you please try it out and report if this issue still persists or if there's any other issues.

[v1.4.3](https://github.com/bitgapp/eqMac/releases/tag/v1.4.3) seems to allow sleep on my macmini.

**Comment by claudiombsilva** [comment]
Version 1.4.4 solves the problem on a MacBook Air M1. 👍

**Comment by mwansing** [comment]
> Version 1.4.4 solves the problem on a MacBook Air M1 with macOS Monterey. 👍

thx for the tip. switched to beta for this, was stuck on 1.3.6. also the annoying orange dot finally gone <3

**Comment by superjeng1** [comment]
Hi, since this issue is solved, I would go ahead and close this issue.
