### ISSUE TITLE
Bug: Having issues with sound from Google Chrome

### ISSUE THREAD

**Issue by jpricesmith** [bitgapp/eqMac#575]
When using Chrome audio is coming through very choppy. Found this issue when playing a YouTube video and thought the video was having a hard time buffering. It is now affecting all audio out of Chrome.  When I disable eqMac the audio quality returns to normal. Not sure what is causing the issue.

**Comment by superjeng1** [comment]
I am closing this since this issue has been pretty old. Feel free to reopen it if you are still having this issue. Note that, there is a pretty long standing bug where if the memory (RAM) usage is too high, macOS's audio output would be inconsistent, and that bug would happen even without eqMac.
