### ISSUE TITLE
No sound output (v1.3.0, Big Sur, Macbook Pro 16-inch, 2019)

### ISSUE THREAD

**Issue by tabell** [bitgapp/eqMac#576]
Things I have tried:
- Open GarageBand and set input to eqMac (Scarlett 2i2)
- Open Zoom and go to test audio settings
- Set eqMac output to other devices (MacBook Pro Speakers)
- Go into MIDI settings and set all devices to 44100 Hz
- Tried putting eqMac into bypass mode
- Press "reset playback" button in eqMac
- Restart eqMac
- Restart MacOS

**Comment by superjeng1** [comment]
Hi, I am closing this bug just based on the age of this issue, if this issue persists for you, please reopen this issue and I would be glad to help you out.

**Comment by tabell** [comment]
I don't use eqMac anymore so no idea if this was ever fixed
