### ISSUE TITLE
Bug: Privacy help comes up under the privacy window

### ISSUE THREAD

**Issue by gsgf** [bitgapp/eqMac#581]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] Yes, I have checked for a similar issue and sure it hasn't been reported before. (searching for "privacy" or "question mark" did not show up any relevant bugs)

**Describe the bug**
At first start right after installing eqMac, a Privacy dialog appears. When you click on the question mark button at the end of the checkbox descriptions (Send Anonymoous Analytics data), the explanation dialog comes up behind the Privacy dialog box so you can not read the whole text.

**Steps to Reproduce**
fresh install the app and launch it. Privacy dialog appears. Press any of the two question mark buttons.

**Expected behaviour**
The box of the clarifying text comes up in front of the Privacy dialog and you can read it.

**Setup information:**
 - Audio device used for playback: Macbook speaker (not applicable)
 - Audio transmission interface: not applicable
 - macOS Version: 11.6.1
 - eqMac Version 1.3.1 **(if audio related issue)**
 - driver version: 1.3.2
 - eqMac UI Version 3.0.6 **(if UI related issue)**

**Screenshots or Console.app logs**
Not applicable. 

**Additional information**

<img width="446" alt="Screenshot 2021-10-29 at 20 22 43" src="https://user-images.githubusercontent.com/25801881/139492282-0e1d41a2-1218-400b-bba6-c4725c0471aa.png">

**Comment by nodeful** [comment]
Thanks for reporting this. Will fix ASAP

**Comment by nodeful** [comment]
This has been fixed now. Thanks again
