### ISSUE TITLE
Feature: Update icon when using headphones

### ISSUE THREAD

**Issue by adeonir** [bitgapp/eqMac#584]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
It would be nice to have the icon changed when using headphones like the system.

**User flow & interface:**
When you connect an headphone, the icon changes:

Without `eqMac`:

<img width="320" alt="Screen Shot 2021-11-04 at 15 53 59" src="https://user-images.githubusercontent.com/3428733/140402271-3cdb94c9-4fb8-4f7b-970b-dfcf02e0b78e.png">

---

With `eqMac`:

<img width="321" alt="Screen Shot 2021-11-04 at 15 53 38" src="https://user-images.githubusercontent.com/3428733/140402288-0a721d8c-6fd8-4f8c-8cca-ddc6d49ffb6a.png">

**Comment by superjeng1** [comment]
Hi, I don't think it is possible to change the icon of the virtual device, however we are planning on a solution where a virtual device is no longer needed. I am closing this issue since this is not possible.
