### ISSUE TITLE
Bug: Volume stays stuck at 28% when Surface Headphones 2 are connected.

### ISSUE THREAD

**Issue by ScottC2001** [bitgapp/eqMac#585]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and made sure it hasn't been reported before.

**Describe the bug**
Once I connect my bluetooth headphones (Surface Headphones 2), the volume drops to 28% and will not change. Any method I use to change the volume, from the media keys on my keyboard to the dial on the headphones, raises the volume only to immediately reduce back to 28%, as reported by eqMac's interface. Once I get the volume past 50% it seems fine but anything lower than 50% it starts reducing back to 28% again. If you fight with it long enough, it starts oscillating the volume between two different values? Not really sure how to describe that.

**Steps to Reproduce**
1. Boot up MacBook Pro, login, eqMac launches at login.
2. eqMac's output device is set to "Internal Speakers" by default; set volume to anything (for this example I set it to 72%).
2. Turn on Surface Headphones 2, they automatically pair with my MacBook.
3. Once eqMac reads the new audio device, it switches to Surface Headphones as output and the volume starts dropping to 28%. 

**Expected behaviour**
Expected behavior is connecting bluetooth headphones and being able to control the volume normally. 

**Setup information:**
 - Audio device used for playback: Microsoft Surface Headphones 2
 - Audio transmission interface: Bluetooth
 - macOS Version: Monterey 12.0.1
 - eqMac App Version: 1.3.1
 - eqMac Driver Version: 1.3.2
 - eqMac UI Version: 3.0.6 (Local)

**Screenshots or Console.app logs**
Screen recording demonstrating bug:
https://user-images.githubusercontent.com/40281573/140448280-9bf77fc1-9068-462a-a99f-b874866e0001.mp4

Console logs that occurred during screen recording:
default	22:27:17.455379-0400	CAReportingService	    CAReportingService.mm:466   sessions for client 181 : (
    "reporterID=777389080581,serviceName=audiodeviceusage,ownerPid=181,clientProcessName=(null),HostApplicationDisplayID=com.apple.loginwindow,started=1,singleMessageSession=0",
    "reporterID=777389080577,serviceName=audiodeviceusage,ownerPid=181,clientProcessName=(null),HostApplicationDisplayID=com.bitgapp.eqmac,started=1,singleMessageSession=0",
    "reporterID=777389080580,serviceName=audiodeviceusage,ownerPid=181,clientProcessName=(null),HostApplicationDisplayID=com.bitgapp.eqmac,started=1,singleMessageSession=0",
    "reporterID=777389080582,serviceName=audiodeviceusage,ownerPid=181,clientProcessName=(null),HostApplicationDisplayID=com.apple.loginwindow,started=0,singleMessageSession=0",
    "reporterID=777389080578,serviceName=audiodeviceusage,ownerPid=181,clientProcessName=(null),HostApplicationDisplayID=com.bitgapp.eqmac,started=0,singleMessageSession=0"
)

default	22:27:17.455637-0400	CAReportingService	    CAReportingService.mm:601   3 active reporting session(s) (
    "reporterID=777389080581,serviceName=audiodeviceusage,ownerPid=181,clientProcessName=(null),HostApplicationDisplayID=com.apple.loginwindow,started=1,singleMessageSession=0",
    "reporterID=777389080577,serviceName=audiodeviceusage,ownerPid=181,clientProcessName=(null),HostApplicationDisplayID=com.bitgapp.eqmac,started=1,singleMessageSession=0",
    "reporterID=777389080580,serviceName=audiodeviceusage,ownerPid=181,clientProcessName=(null),HostApplicationDisplayID=com.bitgapp.eqmac,started=1,singleMessageSession=0"
)

default	22:27:19.361224-0400	eqMac	0x7fe3c981cc20 - [pageProxyID=5, webPageID=6, PID=572] WebPageProxy::willPerformClientRedirectForFrame: frameID=15

default	22:27:19.361573-0400	eqMac	0x7fe3c981cc20 - [pageProxyID=5, webPageID=6, PID=572] WebPageProxy::decidePolicyForNavigationAction: frameID=15, navigationID=0

default	22:27:19.362332-0400	eqMac	0x7fe3c981cc20 - [pageProxyID=5, webPageID=6, PID=572] WebPageProxy::decidePolicyForNavigationAction: listener called: frameID=15, navigationID=1131, policyAction=2, safeBrowsingWarning=0, isAppBoundDomain=0

default	22:27:19.362370-0400	eqMac	0x7fe3c981cc20 - [pageProxyID=5, webPageID=6, PID=572] WebPageProxy::receivedNavigationPolicyDecision: frameID=15, navigationID=1131, policyAction=2

default	22:27:19.388030-0400	eqMac	0x7fe3c981cc20 - [pageProxyID=5, webPageID=6, PID=572] WebPageProxy::didCancelClientRedirectForFrame: frameID=15

default	22:27:21.323896-0400	eqMac	0x7fe3c981cc20 - [pageProxyID=5, webPageID=6, PID=572] WebPageProxy::willPerformClientRedirectForFrame: frameID=15

default	22:27:21.363848-0400	eqMac	0x7fe3c981cc20 - [pageProxyID=5, webPageID=6, PID=572] WebPageProxy::decidePolicyForNavigationAction: frameID=15, navigationID=0

default	22:27:21.364042-0400	eqMac	0x7fe3c981cc20 - [pageProxyID=5, webPageID=6, PID=572] WebPageProxy::decidePolicyForNavigationAction: listener called: frameID=15, navigationID=1132, policyAction=2, safeBrowsingWarning=0, isAppBoundDomain=0

default	22:27:21.364065-0400	eqMac	0x7fe3c981cc20 - [pageProxyID=5, webPageID=6, PID=572] WebPageProxy::receivedNavigationPolicyDecision: frameID=15, navigationID=1132, policyAction=2

default	22:27:21.378037-0400	eqMac	0x7fe3c981cc20 - [pageProxyID=5, webPageID=6, PID=572] WebPageProxy::didCancelClientRedirectForFrame: frameID=15

**Additional information**
I was experiencing this issue for a while up until I factory reset my MacBook last week. I didn't experience this issue again until tonight, however, simply deleting and reinstalling eqMac does not fix the problem. Other troubleshooting steps included unpairing and repairing the Surface Headphones, toggling MacBook bluetooth, rebooting the system, and factory reseting the headphones.

**Comment by ScottC2001** [comment]
After further review it appears my problem is similar to the one posted in https://github.com/bitgapp/eqMac/issues/583. I'll keep my post up for now as it contains more details and logs, but if you'd like me to delete this I will.

**Comment by nodeful** [comment]
Thanks for reporting this, I'll investigate for the next update. Keep this issue up, it's fine

**Comment by sebastian-norero-cardenas** [comment]
I have exactly the same problem with my Sony WH-1000XM4 via Bluetooth. I am using a MacBook Pro (13-inch, 2019) with macOS Version: Monterey 12.0.1

**Comment by smit1625** [comment]
I'm also having this exact problem with a JBL Charge 5 connected via Bluetooth to my Macbook Pro (16-inch, 2019) with Monterey 12.0.1.

**Comment by frosas** [comment]
Same here. I tried playing on my MBA 2020 running Monterey through a couple of Bluetooth devices and the volume "snaps" to certain values:

0%, 5% and 10% → 0%
20% → 20%
25% → 25%
30%, 35%, 40% → 28%
45% → 44%
50% → 50%
55% → 54%
60% → 59%
65% → 65%
70% → 69%
70%, 75%, 80% → 69%
85% → 84%
90% → 90%
95% → 94% or 95%
100% → 100%

No issues when playing through the laptop speakers or using the mini-jack port.

**Comment by Durocks** [comment]
Exact same issue here. Macbook Pro 2018 Intel i5 16GB RAM.

**Comment by dom-will** [comment]
^ Exact same issue here. Including the machine: Macbook Pro 2018 Intel i5 16GB RAM.

**Comment by nodeful** [comment]
Should be fixed by 9d0cfd25a429f7087e7dbb6e516b54f15ccf50c4
Will be releasing a minor update v1.3.2 with just this fix shortly.
Sorry for the inconvenience everyone, Apple has changed something about their SDK's in Monterey which caused Volume Change events fired 10 times instead of 1 specifically for Bluetooth devices 😕

**Comment by nodeful** [comment]
Hey again, could you please download the pre-release eqMac.pkg v1.3.2 from here: https://github.com/bitgapp/eqMac/releases/tag/v1.3.2
Alternatively you can enable Beta Program in eqMac settings and press "Check for Updates".
And let me know if that fixed the issue for you.
Thank you!

**Comment by sebastian-norero-cardenas** [comment]
> Hey again, could you please download the pre-release eqMac.pkg v1.3.2 from here: https://github.com/bitgapp/eqMac/releases/tag/v1.3.2
> Alternatively you can enable Beta Program in eqMac settings and press "Check for Updates".
> And let me know if that fixed the issue for you.
> Thank you!

So far so good. The update has fixed the problem for me (Sony WH-1000XM4 via Bluetooth using a MacBook Pro (13-inch, 2019) with macOS Version: Monterey 12.0.1)
Thank you very much.

**Comment by nodeful** [comment]
Ok I guess it's mostly fixed, still plenty of work to do with volume handling though, somehow it's the most complex part of the app due to having to override a lot of OS events which macOS doesn't like. Build v1.3.2 is now public and I will be closing this issue, thank you everyone for contributing your time to this!
