### ISSUE TITLE
Bug: crashes when M1 Mac enters sleep or wakes up (Monterey)

### ISSUE THREAD

**Issue by hexeric** [bitgapp/eqMac#586]
MBP 16" M1 pro with Monterey
EQ crashes randomly, mostly around sleep changes

**Comment by Stex** [comment]
I experience the same behaviour on MacOS 12.0.1 with an M1 Max, it happens every time I put the Macbook to sleep over night and turn off the external power.

When I wake it up again the next morning, eqMac is simply not running any more without any indication of what happened.

I turned on crash reports for now, hopefully something valuable gets send out.

**Comment by dwellerstein** [comment]
Same issue for me.  M1 Monterey 12.0.1.

**Comment by talios** [comment]
I have a similar issue on an Intel Mac running Monterey - after wakeup - eqMac is just beachballing.

**Comment by aamkye** [comment]
Have the same issue on Intel macMini running Monterey.

**Comment by superjeng1** [comment]
I am closing this issue since this is a pretty old issue and the stability of the app has increased these days. If you are still experiencing this issue, feel free to comment here.
