### ISSUE TITLE
strange low-frequency crackling noise when using on monterey

### ISSUE THREAD

**Issue by hexeric** [bitgapp/eqMac#587]
whnever the app is running and using the virtual output you gear low-frequency rattling and crackling on m1 pro macbook 16" with monteres

**Comment by nodeful** [comment]
I only have the M1 Air from 2020 and I don't experience such issue and lately haven't heard people reporting such issues.
Please let me know what kind of Audio device are you using? A screenshot of your device selected in AudioMIDISetup.app would be great. Also let me know if you have some kind of heavy load happening from other apps when this happens. Thanks

**Comment by jorneilander** [comment]
I can somewhat confirm this behaviour, I've had it happen to me twice in a period of about two weeks. M1 Pro Macbook Pro 16". 

It happened the last time when opening the Macbook from sleep, so no heavy loads at the time. It's still on 12.0 so 12.1 might solve this issue. I'll keep a lookout for circumstances should it happen again.

**Comment by pikerflinn** [comment]
Ditto here, 15" MB Pro with 12.1 installed, eqMac Pro 1.4. Connected to a Fiio K3 DAC at the time. The sounds are somewhat intermittent, i.e. they only last for about 2-3 seconds, then disappear. I'll monitor this again and report back if it repeats. I haven't fiddled with the settings in the midi setup at all, just using the default.

**Comment by jorneilander** [comment]
I've had the issue twice today, after opening the laptop from sleep. This time it was _stuck_ in this mode, where I have to click `Macbook Pro Speakers` for it to automagically revert to `Macbook Pro Speakers (eqMac)` and work perfectly fine. 

<img width="305" alt="image" src="https://user-images.githubusercontent.com/22998183/148935382-89271ecf-2cf6-4c72-9661-bbf90e550ef1.png">

What I did notice is that any short sound, like a `ding`, will take several seconds with pauses of silence in between playing the (scrambled) sound. 

OS X: `12.1 (21C52)`
eqMac: `1.3.2`

**Comment by trulyarya** [comment]
I can also confirm that I sometimes have some crackling, echoing distorted gain glitch. The glitchy noise either goes away on its own or I have to restart eqMac myself. I also do feel like this has happened in the past few weeks more often. I have not been using the app for more than a few months though.

Here's the system I'm using. I use external 2.1 Logitech Speakers.

<img width="228" alt="Screen Shot 2022-02-05 at 19 04 19" src="https://user-images.githubusercontent.com/99092685/152653622-0aa88b0f-bea3-42c4-8366-8cd553b81fc5.png">
<img width="887" alt="Screen Shot 2022-02-05 at 19 10 54" src="https://user-images.githubusercontent.com/99092685/152653664-da0754fb-e723-401c-afd2-1977fd525c27.png">

**Comment by superjeng1** [comment]
I am closing this since this issue has been pretty old. Feel free to reopen it if you are still having this issue. Note that, there is a pretty long standing bug where if the memory (RAM) usage is too high, macOS's audio output would be inconsistent, and that bug would happen even without eqMac.
