### ISSUE TITLE
Problem using eqMac on small screen

### ISSUE THREAD

**Issue by frandrewpastore** [bitgapp/eqMac#589]
Hi there
Am new to eq and received a recommendation to try you out - have Audeze headphones and the settings feature is fantastic...
Issue:
Am partially sighted so use the laptop screen pretty zoomed in so I can reed... There dose not seem to be any way to scroll down the eqMac interface when it is overlapping the bottom of the screen - have to go into display - get a bigger screen size and then go back... This means in my normal screen I cannot make incremental changes to the sliders the controls below...
Hope this makes sense...
Loving the product....
Andrew

**Comment by nodeful** [comment]
Hey Andrew,
Thanks for your report.
Did you notice there's a UI Scale setting in the settings of eqMac?
![image](https://user-images.githubusercontent.com/8472525/140805542-45e159a1-16e2-4121-b3bc-92a4880997a0.png)
Just pull that top slider to the left and it will decrease the size of the UI.
Let me know how it goes

**Comment by frandrewpastore** [comment]
Hi Roman
That is awesome… Many thanks….

God Bless
Fr Andrew Pastore SI
St Vincent de Paul
40 Newbrook Road
Over Hulton, Bolton BL5 1ER

Tel: 01204 436702

Web: www.stvincentbolton.org
Facebook: stvincentbolton
Twitter: stvincentsbol1

**Comment by frandrewpastore** [comment]
Hi Roman
sJut to let you know
An issue comes when you shrink the UI by the way you showed me...
When I make the UI smaller by dragging to the left...
When I attempt to add a Headphone EQ Profile from AutoEQ - that window ends up very close to the bottom and you can only see 2 lines in the selection window - again - enlarged the display - enlarged emac - then AutoEQ pop up window appears more to the centre of the UI and you can use the pop up lists with was….

God Bless
Fr Andrew Pastore SI
St Vincent de PaulAn
40 Newbrook Road
Over Hulton, Bolton BL5 1ER

Tel: 01204 436702

Web: www.stvincentbolton.org
Facebook: stvincentbolton
Twitter: stvincentsbol1

**Comment by nodeful** [comment]
This should have been fixed now with an OTA (over the air update) if you have those enabled in the Settings. All the UI elements scale with the setting that is set properly. Thanks for letting me know. Please don't reply to this message over email as it's duplicated on GitHub and is public so contains your email footer signature with you phone number and address (I've deleted those now from public view, so don't worry). Closing issue
