### ISSUE TITLE
Feature: Implement built-in "Ballast" to the source code so users can avoid sound balance drifting

### ISSUE THREAD

**Issue by mustevenplay** [bitgapp/eqMac#591]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
[Ballast](https://github.com/jamsinclair/ballast) is an open-source tool, a workaround for the known issue on Mac OS that makes the sound balance (LR) drift from it's original position (which is too annoying sometimes). They say it has something to do with CPU overload, but I've noticed that there are many things that trigger it, but nothing concise or definite either.

**User flow & interface:**
I'm thinking, maybe adding an enable/disable button in the main interface, or maybe the settings menu.

**Additional info:**
In the [Ballast](https://github.com/jamsinclair/ballast) github page, they advice to make use of [Balance Lock](https://www.tunabellysoftware.com/balance_lock) instead, but its source code doesn't seem to be public, but if [_eqMac_](https://github.com/bitgapp/eqMac) could have that option built-in, omg, that would really be **AMAZING**.

When you guys fix the volume knob issue, I'm DEFINITELY going to get a subscription, and recommend it to everyone!!
I love the app. :)

**Comment by nodeful** [comment]
Thanks for this suggestion, never had this happen to me and wasn't even aware of such problem and the solutions on the market, I don't even need the source code it would be super trivial to add to eqMac. Will add this feature in an upcoming update.
Thanks again!

**Comment by superjeng1** [comment]
Hi, this feature was already added into eqMac, so I am closing the issue now. Please reopen this issue if you are still having this issue.
