### ISSUE TITLE
Bug: Volume slider erratic when using Logitech mouse wheel to control volume.

### ISSUE THREAD

**Issue by htjunkie** [bitgapp/eqMac#593]
**Describe the bug**
I have assigned volume control to the lateral wheel of my Logitech MX Master 3 mouse (connected via Bluetooth). I also use the volume control wheel on the crown of my Logitech Craft keyboard (over Bluetooth as well). In both cases, when I try to adjust the volume of eqMac with those Logitech peripherals, the volume starts jumping between 2 values, instead of locking onto a volume value. 

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Make sure the sound goes through eqMac
2. Open the eqMac screen so you can see the volume slider or knobs.
3. Change volume up and down with the mouse lateral wheel or with the crown on the keyboard
4. Volume doesn't settle on one value and bounces up and down

**Expected behaviour**
Volume should not bounce up and down. 

**Setup information:**
 - Audio device used for playback: HK Soundsticks III (wired)
 - Audio transmission interface: Laptop > External monitor with USB-C/Thunderbolt > Soundsticks via 3.5mm audio
 - macOS Version: 11.6.1
 - eqMac Version: 1.3.1
 - eqMac UI Version: 3.0.5
**Screenshots or Console.app logs**
Here's me trying to adjust the volume. At first by dragging the slider: no problem. After that I am using the wheel on my mouse. It shows how it sometimes gets stuck between 2 values and oscillates between the two. https://www.screencast.com/t/3lO3RMpx

**Comment by nodeful** [comment]
Thanks for reporting this. I can't replicate this but I think it could be related to the same issue as reported in #583 and #585 although those issues were connected with Bluetooth. I think patch v1.3.2 that I will release tomorrow will solve this issue for you. I'll keep you updated. Thanks again

**Comment by nodeful** [comment]
Hey again, could you please download the pre-release eqMac.pkg v1.3.2 from here: https://github.com/bitgapp/eqMac/releases/tag/v1.3.2
Alternatively you can enable Beta Program in eqMac settings and press "Check for Updates".
And let me know if that fixed the issue for you.
Thank you!

**Comment by htjunkie** [comment]
I just installed the new version and it looks like it worked! Thank you so much for being so responsive and fixing it!

**Comment by nodeful** [comment]
No problem, glad it helped you! Stay tuned for more updates :)

**Comment by notaLonelyDay** [comment]
@nodeful 
The same problem, 
ventura 13.4
mx master 3
audient id4 mkii

eqmac 1.7.10
driver 2.4.3
ui 4.6.6

**Comment by notaLonelyDay** [comment]
Fixed after reboot
