### ISSUE TITLE
Bug: Can't adjust volume 

### ISSUE THREAD

**Issue by BigTimeStats** [bitgapp/eqMac#595]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Cannot adjust volume with mac keys

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Connect BT headphones
2. Adjust volume up on mac
3. Notice that the Mac visualizations shows the volume adjust input but the volume doesn't go up

**Expected behaviour**
Volume adjusts

**Setup information:**
 - Audio device used for playback: [eg AirPods or Macbook speaker or Bose QC32]
 - Audio transmission interface: [eq HDMI or Bluetooth or 3.5mm Jack]
 - macOS Version: 12.0.1
 - eqMac Version 1.2.0
 - eqMac UI Version 2.1.1

**Screenshots or Console.app logs**
In the video, I'm only pushing up on the volume

https://user-images.githubusercontent.com/29850965/142478642-8bba7e81-432c-493e-8d33-d374439949de.mov

**Additional information**

**Comment by nodeful** [comment]
Duplicate
