### ISSUE TITLE
Bug: Global Volume on AutoEq Presets Ignored

### ISSUE THREAD

**Issue by wzhorton** [bitgapp/eqMac#596]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When importing an EQ preset from AutoEQ, the global adjustment (which is important to avoid clipping) is ignored. Although the value displayed is correct, eqMac is actually using a global adjustment of 0. This can be seen by switching to another profile and then back to the preset where the displayed global adjustment is now 0.

**Steps to Reproduce**
Steps to reproduce the behavior (feel free to change the placeholder as you need):
1. Go to expert equalizer and click on AutoEQ to import a profile
2. Go to (for example) AKG > K240 > K240 Studio and click "Select this Preset"
3. Observe that the global adjustment is displayed as -6.6dB in this example.
4. Begin playing music and note the volume.
5. Using the preset dropdown menu change the EQ profile to something else, such as flat (still on expert window)
6. Now using that same dropdown menu, change the EQ profile back to the newly created "AKG K240 Studio" preset
7. Notice that the displayed global adjustment is now 0dB
8. Note that the volume is the same as in step 4

**Expected behaviour**
Expected global volume adjustment to be remembered after switching back to an already imported preset, not for it to revert to zero. Also expected a global adjustment of 0dB to be louder than an adjustment of -6.6dB, rather than the same.

**Setup information:**
 - Audio device used for playback: Macbook Pro headphone jack > JDS Atom Amp > AKG K240 Studio headphones
 - Audio transmission interface: 3.5mm Jack
 - macOS Version: 11.6.1
 - eqMac Version: 1.3.1 (Driver version 1.3.2)
 - eqMac UI Version: 3.1.0

**Additional information**
The problem is not persistent. After switching back to the imported preset (where it shows a global adjustment of zero), if I then change the global adjustment and save it as a new preset, it will correctly remember it. The issue only appears as soon as it has been imported from AutoEQ, as if the display is updated with the correct value, but the underlying EQ program isn't.

**Comment by nodeful** [comment]
Thanks for letting me know, will look into this ASAP

**Comment by nodeful** [comment]
That should now be fixed in the latest Over the Air (OTA) update, if you have those enabled you should see UI Version 3.1.1 which includes the fix. Sorry for the wait and thank you for reporting this again!
