### ISSUE TITLE
Keeps losing sound randomly

### ISSUE THREAD

**Issue by Breaking-Craft** [bitgapp/eqMac#599]
I use this software alot its really god i want to purchase it but i find it keeps randomly cutting out

it will just mute my audio and i have to shut off eqmac and turn it back on and then it works again. Im on a mac mini m1 big su 11.6 very new to mac os and desktop computers in general 
**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. install and reinstall app 20 times
2.  restart mac 5 times
3. eqmac 2
4.  remove eqmac 2 and cry

**Expected behaviour**
If i have to fork over cash to get it to stop cutting out just say so

**Setup information:**
 - Audio device used for playback:mac mini plugged into 3.5mm splitter to 2 subwoofers and 2 studio monitors
 - Audio transmission interface: [hdmi signal going to smart tv audio should be restricted to 3.5 jack though i have 2 external headphones selections and one says eqmac and the other doesnt
 - macOS Version: [e.g. 11.6 big sur
 - eqMac Version latest install

hope i did this correctly not used to asking devs for help but this really is a nice lil app

**Comment by superjeng1** [comment]
Hi, I am closing this issue based on the age of it, and I believe this might already be fixed. If this is not the case, please reopen this issue and reach out, thanks!
