### ISSUE TITLE
Saving Presets: Unable to Name

### ISSUE THREAD

**Issue by Sciman3** [bitgapp/eqMac#6]
When trying to save an EQ preset, the text box in the dialog that pops up for a name isn't big enough to click on and enter a name.

<img width="160" alt="Screenshot 2020-01-10 16 12 30" src="https://user-images.githubusercontent.com/1441963/72186811-13fa5180-33c4-11ea-9593-1a1ef7f50235.png">

Thank you for all the hard work on this rewritten version!!

**Comment by nodeful** [comment]
Thanks for reporting this. I've deployed an over the air UI update. Please restart the app and check again if you still have the problem.

**Comment by Sciman3** [comment]
That seems to have fixed it! Thanks! 😃

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
