### ISSUE TITLE
Bug: When plugging in a new audio device, the app crashes

### ISSUE THREAD

**Issue by andrew-jolley** [bitgapp/eqMac#603]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When I plug in a new audio device (e.g. headphones) sometimes the app crashes. 

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Plug in a new audio device
2. Try to open eqMac from the Menu Bar
3. The app (should) crash

**Expected behaviour**
The app to open

**Setup information:**
 - Audio device used for playback: MacBook Speaker
 - Audio transmission interface: In-built speakers
 - macOS Version: macOS 12.0.1
 - eqMac Version 1.3.2
 - eqMac UI Version N/A

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by nodeful** [comment]
Thanks for reporting this but I need a Crash Report (as a text file) to be able to understand what is going on precisely.
