### ISSUE TITLE
Crackling sound with YT Music and browsing with Chrome

### ISSUE THREAD

**Issue by nanoverse1** [bitgapp/eqMac#606]
Using YT Music stream in chrome tab.
Go to for example reddit and sound crackles.
Using Advanced EQ, External Headphones

Mac OS 11.6
Latest Chrome.
Version 96.0.4664.55 (Official Build) (x86_64)

**Comment by superjeng1** [comment]
Hi, I could not reproduce this issue on the latest version of eqMac, so I am closing this issue now. If this still happens to you, please reopen this issue and comment on the details. Thanks!
