### ISSUE TITLE
Bass levels are too harsh (regardless of MIDI balance)

### ISSUE THREAD

**Issue by ddrt** [bitgapp/eqMac#608]
I have played this song over 1k times https://open.spotify.com/track/7xbV9wF8FcmBq4KNG2gZOY?si=ec03743319ff4e3a

However I've never had an issue until the recent update of EQ mac. There are issues with the sound driver or (hopefully not) this was something intentional to drive us to premium balancing. I really hope not.
![Screen Shot 2021-12-14 at 23 32 09 PM](https://user-images.githubusercontent.com/1043575/146135596-74f81c99-1c51-4351-af64-9ce5379d8f98.png)

**Comment by ddrt** [comment]
Bass is way to harsh, it blows out the sound. I'm on Bayerdynamic DT 770 Pro 32 Ohm with the following setup
![Screen Shot 2021-12-14 at 23 34 52 PM](https://user-images.githubusercontent.com/1043575/146135745-c3667836-7ea4-4564-a682-b9fa21efda9e.png)
![Screen Shot 2021-12-14 at 23 34 50 PM](https://user-images.githubusercontent.com/1043575/146135748-5cb0c805-e82d-4871-a30f-68fb269c387a.png)

**Comment by ddrt** [comment]
Even turning them down below 0 it's still too harsh. This is freaking horrible. It sounds awful!

**Comment by nodeful** [comment]
I would nevwr decrease the quality of sound for free features lol. Something wrong with the way your specific setup works, the core code of the EQ and audio pipeline hasn't changed for a while, it will in the upcoming update, but it's not live yet. I recommend trying to swith your headphones to a higher sampling rate, maybe 48kHz and using the global gain to make sure the sound doesnt clip. Then increase the volume to compensate for the lost volume from the global gain

**Comment by superjeng1** [comment]
@ddrt Hi, looks like your EQ profile results in a overall positive gain. You should set global gain to the negative of the highest filter. In newer eqMac versions, just check the "Auto" checkbox next to the global gain slider. I am closing this issue for now, if you have further question regarding this, feel free to reopen this and reach out, thanks!
