### ISSUE TITLE
Feature: Per device configuration

### ISSUE THREAD

**Issue by Doridian** [bitgapp/eqMac#611]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
Allow "pairing" a preset (either just EQ or entire app) with a certain device.
So if I switch to my speakers it uses one EQ, and if I switch to my headphones it switches to another (like the AutoEQ profile, for example)

**User flow & interface:**
Could be implemented like a settings menu, where you can view profiles (like you can see EQ profiles) and select "automatically apply when sound device X is selected"

**Comment by nodeful** [comment]
Sorry even though I appreciate you suggesting this you haven't checked for the same feature being requested on many occasions, mainly this one #231 
I will close this issue please refer to the issue mentioned for further updates

**Comment by Doridian** [comment]
@nodeful Sorry about that, I did a search, but that issue is quite old so I must've missed it in all the other issues matching the search terms I tried. Sorry again.

**Comment by nodeful** [comment]
I understand, it's no worries :)
