### ISSUE TITLE
When I press column up, it does not increment the volume

### ISSUE THREAD

**Issue by augmentedstartups** [bitgapp/eqMac#614]
Volume button on MacBook does not increase the the volume of eq App. Down volume works.

**Comment by LAJW** [comment]
Similar problems here: Pre release 1.4.3. Bluetooth headphones. Volume up/down stops working after a while/disconnecting peripherals/screen/sleep.

**Comment by maren04** [comment]
Similar problems here. While using bluetooth devices like my Sennheiser HD 4.50BTNC my volume control is very buggy. If I press volume up it beeps about 1-10 times and then goes back, while turning down it beeps a bit less and then works. When adjusting the volume too many times in short succession the app crashes. This happens both when adjusting through the app's interface and the touch bar.

**Comment by superjeng1** [comment]
Hi, I am closing this issue due to the age of it, and the belief of this should be fixed. If you are still having this issue, please reopen this issue and let us know, thanks!
