### ISSUE TITLE
Bug: Crash when connecting Bose AE2 Headphones with latest 1.4.0 on Monterey

### ISSUE THREAD

**Issue by danielletx** [bitgapp/eqMac#616]
not really anything more to this issue except the title, which says it all.  never did manage to connect.

**Comment by nodeful** [comment]
I would need a crash report

**Comment by nodeful** [comment]
Can you please try this release: https://github.com/bitgapp/eqMac/releases/tag/v1.4.3
If the issue still persists please send me a Crash Report if you can, I will look into it further.
