### ISSUE TITLE
Close, Minimize & Popover Mode buttons do not work until you give the app focus

### ISSUE THREAD

**Issue by cgatesman** [bitgapp/eqMac#620]
If you have focus on some other application then try to click on the Close, Minimize or Popover Mode buttons at the top left of the app, they do nothing.  You have to click elsewhere on the eqMac application to give it focus, first, before these buttons work.  This is not normal behavior for buttons like these in macOS.  They should function even when the application does not have focus.  This problem is even more prominent when using the "Always on top" feature.

**Comment by nodeful** [comment]
Thank you for creating this issue. I've been experiencing this myself for ages but wasn't able to find a fix, a lot of Web based UI apps suffer from this issue, for example Discord. I will try to fix this in an upcoming update.

**Comment by nodeful** [comment]
I advise to try out this release candidate v1.4.4 and see if it improves your experience:
https://github.com/bitgapp/eqMac/releases/tag/v1.4.4 (eqMac.pkg)

**Comment by cgatesman** [comment]
> I advise to try out this release candidate v1.4.4 and see if it improves your experience:

Nice work!  Thanks! 👍

**Comment by superjeng1** [comment]
I can confirm that this issue has been fixed, so I would go ahead and close it now.
