### ISSUE TITLE
Bug: Sound disappears

### ISSUE THREAD

**Issue by kopyl** [bitgapp/eqMac#622]
**Describe the bug**
Sometimes I face the issue when a sound disappears altogether until I "force quit" Core Audio Driver (eqMac.driver).

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Do nothing. I don't know what exactly has caused it. Maybe a Zoom call, not sure.

**Setup information:**
 - Audio device used for playback: [MacBook Pro Speakers]
 - macOS Version: [12.1]
 - eqMac Version [1.3.2]

**Additional information**
And I just noticed that in [sound settings](https://imgur.com/a/7b20te9) all the audio sources disappeared except MacBook Pro Speakers. The only thing which fixed it was to "force quit" Core Audio Driver (eqMac.driver). After I force-quit it, all the rest audio sources appeared, but the "eqMac" output source was selected. After switching back to MacBook Pro Speakers the audio got fixed.

**Comment by nodeful** [comment]
I advise to try out this release candidate v1.4.4 and see if it improves your experience:
https://github.com/bitgapp/eqMac/releases/tag/v1.4.4 (eqMac.pkg)

**Comment by superjeng1** [comment]
Hi, I am closing this bug due to the age of it, if this issue still happens to you, please reopen this issue, thanks!
