### ISSUE TITLE
Bug: "The eqMac Audio Driver is not installed" window pops up

### ISSUE THREAD

**Issue by kopyl** [bitgapp/eqMac#625]
**Describe the bug**

I sometimes get this window when I launch eqMac app with the title: "The eqMac Audio Driver is not installed" and description
For unknown reason the Audio Driver needed for eqMac to work currently is not installed. Try restarting your computer and run eqMac again. In that doesn't work, try re-installing eqMac from our website.

Please fix it ASAP since it's the most critical bug. I'm not a fan of restarting my mac. Macs should never be restarted.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):

Do nothing. I don't know what exactly has caused it.
Setup information:

**Audio device used for playback**: [MacBook Pro Speakers]
**macOS Version**: [12.1]
**eqMac Version**: [1.3.2]

**Additional information**
I'm having this issue on 2 macs, 2 chips, and 2 OS versions – meaning it's present everywhere.

**Comment by nodeful** [comment]
I advise to try out this release candidate v1.4.4 and see if it improves your experience:
https://github.com/bitgapp/eqMac/releases/tag/v1.4.4 (eqMac.pkg)

**Comment by kopyl** [comment]
@nodeful is it still relevant?

**Comment by rafazafar** [comment]
Im still having this issue on latest Monterey 12.3. A restart of macos will get it working again . A few sleep/wakes later and the same driver error appears agian.

**Comment by superjeng1** [comment]
Might be related to this #780

**Comment by superjeng1** [comment]
Hi, I am closing this issue in favor of issue #780. If this is a mistake, please reopen this issue or comment. Thanks
