### ISSUE TITLE
Bug: Spatial audio issues when switching EQ mode

### ISSUE THREAD

**Issue by nikolaydyankov** [bitgapp/eqMac#628]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When I have a spatial audio env selected, when I start switching EQ modes (basic to advanced) the audio gets really messed up, like I'm in a very large echoing hall. To fix it I have to change the spatial environment, then change it back to my original one - small room.

**Steps to Reproduce**
Have spatial audio enabled, then switch from Basic to Advanced EQ. Also happens when the PC goes to sleep and then I wake it up.

**Setup information:**
 - Audio device used for playback: Yamaha HS8
 - Audio transmission interface: M-AUDIO AIR 192/4
 - macOS Version: 12.1
 - eqMac Version: 1.4.3
 - eqMac UI Version: 3.2.3

**Comment by nodeful** [comment]
Thanks for reporting this!
I advise to try out this release candidate v1.4.4 and see if it improves your experience:
https://github.com/bitgapp/eqMac/releases/tag/v1.4.4 (eqMac.pkg)

**Comment by superjeng1** [comment]
Hi, I am closing this issue due to the age of it and the belief of this bug has been fixed. If you are still experiencing this bug, feel free to reopen this issue and reach out.
