### ISSUE TITLE
Bug: EqMac crashes when accepting a Facetime or Facetime audio call on Desktop.

### ISSUE THREAD

**Issue by abelardoriojas** [bitgapp/eqMac#633]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
As simple as it sounds. When someone calls me, either from their phone or through facetime, the call will fail and EqMac will crash.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Have a friend call you
2. Pick up the call on your Mac
3. Observe, as it will crash.

**Expected behaviour**
It should just work!

**Setup information:**
 - Audio device used for playback: Koss Porta Pro headphones
 - Audio transmission interface: 3.5mm jack
 - macOS Version: 12.1 monterrey
 - eqMac Version 1.3.2

**Comment by jfranconi** [comment]
I can confirm this issue impacts me too - 12.2 Monterey and eqMac 1.4.4 too (latest build preview).

**Comment by jfranconi** [comment]
Any word if this was fixed in 1.4.5? I dont see it mentioned and didnt re-install yet as I having this constantly crash my audio. Thanks!

**Comment by carlosromanxyz** [comment]
Same here, issues on incoming calls #647 and #648

**Comment by luiscarlospando** [comment]
Apparently this issue still exists even in v1.5.1 beta. The person on the other end won't be able to hear me until I quit eqMac.
