### ISSUE TITLE
Selected audio output not highlighted

### ISSUE THREAD

**Issue by jericodelfinado** [bitgapp/eqMac#635]
Selected audio output is not highlighted on the menu bar.

<img width="341" alt="image" src="https://user-images.githubusercontent.com/6530419/151599458-0814bef3-c952-4d79-afe8-d2e800f98bb9.png">

App: v1.4.1
Driver: v2.0.1
UI: v3.2.4

macOS: 12.1

**Comment by nodeful** [comment]
This is intended behaviour because eqMac has to switch the output to the driver to capture the system audio and the driver is not listed as an output device anymore to help with other bugs that were happening specifically with AirPods

**Comment by nodeful** [comment]
You can always check for the selected Output device in eqMac.
The only way around this is to develop the Capture driver as a System/Kernel Extension which would require 2 Mac restarts during installation and a complicated manual extension approval process to the user

**Comment by Garylum** [comment]
Is this behaviour supposed to happen with 1.3.2 as well?
 I'm using EQmac to control HDMI volume  specifically for a zoom room . I am running 1.3.2 and Monterey 12.3.1    For some reason I no longer see eqmac as an option in sound output.  If I choose an output in EQmac, it changes the OS sound output to what I chose in eqmac.  It seems like I no longer have volume control for HDMI
