### ISSUE TITLE
Bug: Check for Updates reports v.1.3.2 as the newest version available

### ISSUE THREAD

**Issue by MrGcGamer** [bitgapp/eqMac#638]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
"Check for Updates" reports v.1.3.2 as the newest version available although I already manually installed 1.4.5

**Steps to Reproduce**
This only happens on my machine running Mojave.
On my Big Sur machine updates are working just fine and the newest version is reported correctly.

**Expected behaviour**
Properly inform me of an update.

**Setup information:**
 - macOS Version: 10.14.6

**Comment by nodeful** [comment]
v1.4.5 is only available as a download from the website or if you have Beta Program selected in eqMac's settings.
There are still some issues I need to resolve before pushing the update to everyone.

**Comment by MrGcGamer** [comment]
ohh true... didn't notice I had the beta switch enabled in my Big Sur machine
