### ISSUE TITLE
eqMac Audio Device not showing in sound menu

### ISSUE THREAD

**Issue by andrew-jolley** [bitgapp/eqMac#639]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When I install v1.4.5 and restart the audio and my MacBook, in the 'Sound' menu, the eqMac devices don't show up

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Install eqMac v1.4.5
2. Restart Mac
3. The eqMac devices don't show up in the audio menus

**Expected behaviour**
I expect the 'MacBook Pro Speakers (eqMac)' to show (or necessary speaker device)

**Setup information:**
 - Audio device used for playback: External headphones, built-in speakers
 - Audio transmission interface: 3.5mm jack
 - macOS Version: macOS 12.2
 - eqMac Version v1.4.5
 - eqMac UI Version v3.2.4 (not sure whether UI or not)

**Screenshots or Console.app logs**
<img width="346" alt="Screenshot 2022-02-02 at 19 31 10" src="https://user-images.githubusercontent.com/64013644/152223733-b87d5260-9fd3-424e-af7b-39191b8e98e2.png">

**Additional information**
The problem does not occur when v1.4.5 is removed, and v1.3.2 is re-installed

**Comment by nodeful** [comment]
This is intended behaviour as I explained in #635 
<img width="953" alt="image" src="https://user-images.githubusercontent.com/8472525/152260923-93c449cf-e8a5-446c-b97c-54ccddb51f17.png">
