### ISSUE TITLE
Bug: Random crashes on macOS 12.1

### ISSUE THREAD

**Issue by robopuff** [bitgapp/eqMac#640]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and am sure it hasn't been reported before.
    - There is a similar issue there but I do not use MOTU drivers

**Describe the bug**
The application randomly crashes without changes in devices or outputs.
It is happening with and without DAC connected. It's crashing quite often actually and it's mildly infuriating

**Setup information:**
 - macOS Version: 12.1
 - eqMac Version 1.4.5

**Screenshots or Console.app logs**

* v1.4.5 https://gist.github.com/robopuff/43f24994230e5343f3c8147160bc794a
* v1.4.6 https://gist.github.com/robopuff/924274294b7f78432f3a9af8392a0780

**Comment by julio-cavallari** [comment]
Same here, the app crashes whenever I disconnect my bluetooth headset, and sometimes also out of the blue, for no reason, it just crashes

**Comment by robopuff** [comment]
Now additionally whenever I get back, after locking the screen, it's froze with beach ball spinning :/

**Comment by nodeful** [comment]
Hey everyone, I am aware of the issue and for the last month I've been rewriting the core of the app to make sure these discrepancies never happen again, or at least it will be easier to fix. The update is almost ready and should be available soon.
For now I recommend trying out an older version of eqMac: https://github.com/bitgapp/eqMac/releases/tag/v1.3.2
This version has other issues but should make the issue you're experiencing better. Sorry for the inconvenience and for the wait

**Comment by superjeng1** [comment]
Hi, I am closing this due to the age of this issue, and I believe this has been fixed. If you are still experiencing this issue, feel free to reopen this.
