### ISSUE TITLE
Bug: School iT blocking gui

### ISSUE THREAD

**Issue by aestavan** [bitgapp/eqMac#642]
My school iT block literally everything but google. When i load eq mac I get the no permission popup. Could you get around this?
<img width="1512" alt="Screen Shot 2022-02-07 at 1 11 22 pm" src="https://user-images.githubusercontent.com/60243214/152714473-ea07c58f-f054-46af-b3c8-9da9f20edcac.png">

**Comment by superjeng1** [comment]
Hi, this is related to #578, and the workaround currently is to uncheck the "OTA Updates" box in settings.
