### ISSUE TITLE
Bug: missing model from autoEq list

### ISSUE THREAD

**Issue by zanza00** [bitgapp/eqMac#651]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Missing AutoEq for KZ zsn pro X

**Steps to Reproduce**
1. open autoEq db
2. search for `KZ ZSN`
3. only original and pro are selectable

**Expected behaviour**
Able to select the X model

**Screenshots or Console.app logs**
![image](https://user-images.githubusercontent.com/3732011/154500156-2ddfe3a3-a6e8-40ae-a58f-3a906d19c70a.png)

in the list there is

![image](https://user-images.githubusercontent.com/3732011/154500657-70044a0b-7af7-4648-bad3-50c10efe34af.png)

here is the entry in the database
https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/KZ%20ZSN%20Pro%20X

**Comment by marier-nico** [comment]
I'm facing this issue as well, I think it would be nice to be able to import AutoEQ profiles manually, that way it wouldn't be as important for the database to always be up to date

**Comment by nodeful** [comment]
I treat every space in the name of the preset as a new level.
If you press on KZ ZSN Pro you will see the preset for Pro (general) and X:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/8472525/184736262-9e7604f2-054e-4652-82ce-c56c68be4041.png">
