### ISSUE TITLE
Improvement: Save EQ by device

### ISSUE THREAD

**Issue by marcusmota1986** [bitgapp/eqMac#653]
Hi, when I'm using EQMac pro, I usually change from time to time between my headphone dac/amp to my speakers, but the Equalizer preset is completely different from one to another.

My improvement request would be to save the EQ by device, not a global when, so this way I don't have to keep changing device and also resetting all my EQs.

Thanks and keep up the good work.

**Comment by talios** [comment]
Oh yes make this so! This would be great.

**Comment by jameshobden** [comment]
🎯 Definitely need this please - I'm always switching between two devices.

**Comment by marnovo** [comment]
Same here. I have literally >10 input/output devices, a few of them frequently used (video calls, music listening, notifications, virtual output…) and it's painful to be changing eq profiles by hand N times a day, every single time another device is active, and often feeling something is "off" and realizing you're now using device XYZ with the previous ABC eq profile. I have been asking the folks from SourceSource for this for _years_… now with the close feature parity between both, eqMac more reliable/stable, that would make it a key reason for me to change to eqMac.

**Comment by marnovo** [comment]
By the way this is related to/duplicated in all these tickets (and maybe more):
- https://github.com/bitgapp/eqMac/issues/553
- https://github.com/bitgapp/eqMac/issues/231
- https://github.com/bitgapp/eqMac/issues/611

**Comment by Corican** [comment]
I also want this feature.

**Comment by mattpnolan** [comment]
+1 :)

**Comment by Peam269** [comment]
+1 for me too!

**Comment by superjeng1** [comment]
This is already possible with the use of "Super Preset" feature! With it, it allows you to make eqMac auto switch eqMac settings when different device is selected. Please do check it out. I am closing this issue since the requested feature has been added, if I missed anything, feel free to reopen this issue.
