### ISSUE TITLE
Bug: Switching between different speaker / headphone will caused the app not responding

### ISSUE THREAD

**Issue by zhenghaoweii** [bitgapp/eqMac#654]
I was planning to purchase pro subscription, but end up canceled because of this issues.

overall the app is very good!

**Comment by devo-t** [comment]
same . M1. crashes 2-3x daily. switching audio device is sure to do it but also happens randomly when I am way - come back to the unexpectedly quit message.

**Comment by medi74** [comment]
I love the app but on my M1 it's very unstable. I've tried to reproduce the crashes on my Mac Mini but with no success.
I'm more then happy to help to find the issue so just let me know if there is something I can do.
Attached my bug report log
[bug report.pdf](https://github.com/bitgapp/eqMac/files/8268848/bug.report.pdf)
.

**Comment by sergiothoumi** [comment]
Same, Intel Macbook Air (late 2019) running the last operating system. It happens everytime.

**Comment by maren04** [comment]
Same, Intel Macbook Pro (2020). Crashes almost every time I switch devices both when I had Big Sur and now with Monterey OS.

**Comment by sergiothoumi** [comment]
For more info, if I have my earphones, open the app, and listen to music, then remove my earphones, the app starts not responding. Something I noticed is that even when I force quit the app I still don't get audio coming out of my speakers, for this to be fixed I have to 1. quit the video or song I am playing, 2. use the "sudo pkill coreaudiod"  command 3. play the video or song again. I am not sure how much this extra info can help the developer but it definitely messes with the audio of the macbook.

**Comment by tw3nty5ix** [comment]
same issue here! love the app, i have the pro version but i'm now wondering if i should pause my sub until this gets ironed out. every time i switch devices (including when i first open the app) it freezes and i have to force quit over and over again until it decides to work. mac mini 2012, catalina 10.15.7

**Comment by therealenky** [comment]
same issue here, MacBook Pro (early 2015), Monterey 12.3. this seems like the best eq i can get on mac, but keeps crashing every time i switched devices. almost unusable, but I still use it bcs i need the EQ :(

**Comment by eesqueda01** [comment]
Same here, doesn't matter if I'm using my MacBook Retina 13" 2013, 15" 2015 or Air M1 2020.

**Comment by panzerfahrer** [comment]
I experience freezes as soon as returning from standby. Killing eqMac usually helps. Sometimes I also need to kill the audio driver to get the app back to operating.

MacBook Pro (16 Zoll, 2019), Intel, macOS 11.6

**Comment by marceloformentao-hotmart** [comment]
Macbook Pro 2019 Intel with the same issues, most of the time freezes and stop responding after switching audio devices.

**Comment by jacobhill247** [comment]
Mac Mini M1 on 12.2 Monterey with the same issues. Love the app but this is a huge pain.  Switching devices or after sleep the program is usually unresponsive. Have to kill it and then hope it will work properly. Have the pro version and may cancel like some above until this is ironed out.

**Comment by djoca** [comment]
I'm also having this issue. Sad to see there's no update on this bug until now.

MacBook Pro (16-inch, 2019)
macOS Catalina 10.15.7

**Comment by CrazyAZ** [comment]
I am also experiencing this issue. Everything else about this app has been great, but I use it on a laptop and it is very frustrating to have the app crash every time I need to unplug from my dock. Would really love to see this ironed out.

MacBook Pro (16-inch, 2019)
MacOS Big Sur 11.6.5

**Comment by mattpnolan** [comment]
I'm having the same issue.

MacOS Monterey 12.3.1
MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)

I use an external DAC connected via USB. eqMac freezes if I plug in my Mac to the hub with my DAC or unplug the DAC from my Mac.

**Comment by jaboolean** [comment]
Same issue, but for me eqMac freezes and requires a force close, then when reopened works until I disconnect the DAC again. Also a Pro user here
MacBook Pro 2018, Monterey 12.3.1

**Comment by pidds** [comment]
Same problem - Mac Mini M1 running 12.3.1

**Comment by raymondxcho** [comment]
Same thing on my 2015 MBP. I use a Scarlett interface and whenever I wake up my laptop, it defaults to internal speakers. I have to change the output to my interface every time and most times, the app will crash. If developer can confirm this is fixed or will be fixed, I will subscribe to pro version.

**Comment by doseofding** [comment]
I am also having this issue with the 2021 MacBook Pro.

**Comment by SteveKVT** [comment]
Same on iMac running Monterey.  Love the functionality when it works but wondering whether it's worth the subscription

**Comment by Quorthom** [comment]
same... :c

**Comment by derekleverenz** [comment]
I have this same issue on a 15" 2019 MBP (osx 10.15.7), its not exclusive to M1. I have two audio devices i use frequently so this renders it largely unusable :( I think i will cancel pro for now, but ill keep an eye on this

**Comment by mattpnolan** [comment]
It's definitely been established this is not exclusive to M1 :) The OP didn't mention M1 and many comments are of non-M1 users.

I have gotten used to keeping the icon in the dock and force quitting each time I disconnect from a DAC, but I'm looking forward to not having to do that any longer :D

**Comment by pidds** [comment]
I reverted back to eqMac v1.3.2 which "fixed" the Bluetooth problem.

**Comment by nodeful** [comment]
Hey everyone, 
I'm super sorry for the lack of communication from my end, the last 5 months have been pretty rough for me but I pulled through.
I have been working on an update for a while that addresses the issue you're all experiencing. 
I had to completely rewrite the Core of the app to use a more older version of Audio API's that Apple has.
The newer AVAudioEngine API that Apple has been pushing down developers throats ended up being a massive problem for eqMac and my productivity.
Hopefully this is all behind us now and I'll be able to release updates more often and better as I have more control over the Audio Pipeline!
Please check out a Pre-Release of v1.5.0 that you can download here: https://github.com/bitgapp/eqMac/releases/tag/v1.5.0
Or just Enable "Beta Program" in eqMacs Settings!
Please let me know how it goes!

Kind Regards,
Roman - Founder of eqMac

**Comment by talios** [comment]
@nodeful Sorry to hear you've had a rough time lately - but glad to see moved it thru whatever it was.

Great to see life in eqMac as well - so far 1.5 has been running smoothly (nicely timed with updated Oratory 1990 measurements and presets coming out today - so manually updated my EQ and whoah - so good.

Hopefully Apple don't drop support of those older Audio APIs in the upcoming OS release!

**Comment by nodeful** [comment]
@talios @medi74 Thanks guys :) 
Don't worry I'm mostly fine, I just take on too much responsibilities in my life and can't get anything done in time.
Overpromised and underdelivered. But slowly and surely I'm getting out of the mess I created and starting to get things in order. 
Don't worry the project will never die as long as people are using it, this is currently my main source of income and I don't take it for granted. I'm still working on this whole thing by myself and it takes time to develop a stable product. We'll get there!

**Comment by medi74** [comment]
BTW, even with 1.5 still crash.  I don't know if this a new issue or an old one. If necessary I'll open a new ticket.
 I'm attaching the full error report.
[eqmac error report.txt](https://github.com/bitgapp/eqMac/files/9154458/eqmac.error.report.txt)

**Comment by nodeful** [comment]
@medi74 I've taken a look at the report and it seems like it would be a easy crash to fix, but unfortunately the report is too tangled in Libraries that don't provide an easy to read Stack Trace. Did you do anything specific before the crash occurred?

**Comment by medi74** [comment]
@nodeful I'm not able to reproduce the issue. I was away from the mac for 2 hours and then when I came back I've seen the Crash popup. I'll try to observe during the next day if I can provide you some more information or if I'm able to reproduce the crash.

**Comment by seyerian** [comment]
Issue is fixed for me by opting into Beta in the app, without system restart.

Thank you so much @nodeful! Hope you are well.

**Comment by zhenghaoweii** [comment]
Thanks so much! @nodeful
