### ISSUE TITLE
Bug: shutdown went wrong when using eqmac 1.4.6 (

### ISSUE THREAD

**Issue by mariposalinda** [bitgapp/eqMac#657]
Mac mini m1
Latest Monterey
Everytime i shut down my computer it hangs and asks me to force quit eqmac in order for my computer to shutdown. It is very annoying :(

Otherwise it works great

Thank you

**Comment by mikperk** [comment]
Same here.

**Comment by chrishill-github** [comment]
Same here.  2021 Macbook M1 Pro, Monterey 12.2.1 (21D62)

**Comment by seanmuth** [comment]
Here's a coredump of a recent eqmac crash on my M1 MBP Monterey 12.3.1. Opening System Preferences > Security & Privacy > Accessibility, then Click the Lock to Make Changes, and eqMac will crash, and need to be force-quit from activity monitor. 

Let me know if I can provide any other helpful info.

https://gist.github.com/seanmuth/bb01266625ddec90f0b423a7922a25f7

**Comment by iRuvie** [comment]
me too

**Comment by Quorthom** [comment]
it always happen 🌵 :/

MacBook Pro (13-inch, Mid 2012)
