### ISSUE TITLE
Using Reset Playback Freezes the Program

### ISSUE THREAD

**Issue by sflory94566** [bitgapp/eqMac#662]
**Describe the bug**

Reset playback freezes the system

**Steps to Reproduce**

1. Go to Reset Playback on the bottom right of the control panel
2. Click on the icon and the system hangs...
3. Note: In both Expert mode and Advanced mode

**Expected behaviour**
Reset all the slide controls back to "zero" in order to start again

**Setup information:**
 - Audio device used for playback: Macbook speakers
 - Audio transmission interface: 
 - macOS Version: 12.2.1
 - eqMac Version: Appv1.4.6 with Driver v2.0.5
 - eqMac UI Version: v3.2.4

**Screenshots or Console.app logs**
Error file attached

**Additional information**
[log file 031822.txt](https://github.com/bitgapp/eqMac/files/8307490/log.file.031822.txt)

**Comment by superjeng1** [comment]
Hi, the reset button is for resetting the output not the sliders. And yes, it shouldn't crash the program. This is not reproducible on the latest version of eqMac for me so I am closing this issue now, if you are still encountering this bug, feel free to reopen it and comment on the details. Thanks!
