### ISSUE TITLE
Didn't work after upgrade MacOs to monterey (Air M1)

### ISSUE THREAD

**Issue by iampick** [bitgapp/eqMac#663]
- Can not click on the section Spatial / Equalizer
- At the sound icon (mac icon) doesn't show eqMac
- uninstall / install the problem was not gone.
![Screenshot at Mar 30 16-54-23](https://user-images.githubusercontent.com/7637063/160804584-7bc6e70d-150c-4eaa-881b-aa49299ada0e.png)

**Comment by themo1e** [comment]
I fine with monteray, execute all programs you want to use eq mac for first (for me traktor and OBS).
then you will see the device name (eq mac mini speakers EQMAC! not cor audio. the app does crash if u open an app assigned to another audio device.

**Comment by superjeng1** [comment]
Hi, I am closing this issue due to the age and under the assumption of this should already been fixed. If you find it otherwise, please reopen this issue and comment on here.
