### ISSUE TITLE
Bug: X went wrong when using Y (REPLACE THIS)

### ISSUE THREAD

**Issue by juliankauai** [bitgapp/eqMac#666]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**

installed eqmac 1.4.6 on mac mini using mac os 12.3.1. it didn't work well for me. i followed the uninstall directions and used the terminal command and dragged eqmac to the trash. restarted and found it had removed all audio input drivers in sys preferences.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):

installed eqmac 1.4.6 on mac mini using mac os 12.3.1. it didn't work well for me. i followed the uninstall directions and used the terminal command and dragged eqmac to the trash. restarted and found it had removed all audio input drivers in sys preferences.

**Expected behaviour**

expected to get back to regular sound settings. which i'm familiar with.

**Setup information:**

installed eqmac 1.4.6 on mac mini using mac os 12.3.1. it didn't work well for me. i followed the uninstall directions and used the terminal command and dragged eqmac to the trash. restarted and found it had removed all audio input drivers in sys preferences.

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

<img width="646" alt="image" src="https://user-images.githubusercontent.com/1791443/163667006-ac780b45-194d-4524-81fb-dff03a43dc90.png">

**Additional information**

i have sound work to do all weekend. if there is some way you can get back to me with a fix it would be appreciated.
thanks
julian

**Comment by superjeng1** [comment]
Hi, the command can not remove any real devices, only virtual devices can be "deleted". If a real device isn't showing up, it is macOS not detecting it. I am closing this issue due to the age and the assumption of you had solved it somehow, but if that is not the case, feel free to reopen this issue and comment, we would try to help you out.
