### ISSUE TITLE
The apps stop working when back from sleep

### ISSUE THREAD

**Issue by Aprilx85** [bitgapp/eqMac#668]
The eqMac Stop working every time when back from sleep on macbook pro 2018 
and the sound wont hear ,i have to stop the eqMac process on Activities Monitor and reopen it the it's working

**Comment by fsboehme** [comment]
Yep – this happens to me _all. the. time_. Multiple times per day. Please look into this!

**Comment by nickbalch** [comment]
Confirmed - same for me.   I use eqmac for a set of speakers connected to a USB-c docking station.  It seems to crash when I undock (and therefore the USB audio device is not available)

**Comment by ariisenberg** [comment]
Same. Ditto to happening all the time.

**Comment by deftdawg** [comment]
My WindowServer crashes when my machine wakes up, but the eqMac app is still running in the background.

Can you guys try opening a terminal, checking if the process is still running, then kill it and restart.

```sh
ps -ef | grep -i eqMac | grep -v grep
```
If you see something like this
```
  202 26768     1   0 Fri11PM ??         0:59.48 Core Audio Driver (eqMac.driver)
  501 39516     1   0 10:25PM ??         0:06.15 /Applications/eqMac.app/Contents/MacOS/eqMac
```
Then run
```sh
killall eqMac
```
And then restart the `eqMac` app from the `Applications` folder.

**Comment by superjeng1** [comment]
Hi all, the newer versions of eqMac has fixed a lot of sleep issues, please try them out and see how it goes. If you are still encountering this bug, please reopen this issue and comment some further details here, thanks!
