### ISSUE TITLE
Bug: When double clicking EQ slider - curve does not reset.

### ISSUE THREAD

**Issue by AdrianLevy7** [bitgapp/eqMac#669]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug:**
Double clicking the EQ slider correctly resets the slider but not the white EQ curve. The wave form correctly updates though.

**Steps to Reproduce**
1.  Go to Equaliser: Advanced.
2. Ensure that  the green switch is enabled for the feature.
3. Set the slider to a setting (eg. lower it).
4. Double click the slider handle.
5. The slider handle resets but not the EQ curve displayed.  

**Expected behaviour**
The white EQ curve should reset to the zero level in the display window.

**Setup information:**
 - Audio device used for playback: Steinberg UR22C
 - Audio transmission interface: USB C Thunderbolt 3
 - macOS Version: Monterey 12.3.1
 - eqMac Version: There is no about box.
 - eqMac UI Version: There is no about box.

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by superjeng1** [comment]
Hi, I don't see what you mean by the curve, maybe it was removed in the newer versions. And when I did your steps provided, it works as expected, so I am closing this issue, however if this is still a problem, please reopen it and comment to let us know more detail on this, thanks!
