### ISSUE TITLE
Quits for no reason

### ISSUE THREAD

**Issue by jfraden** [bitgapp/eqMac#675]
The app, while working fine as expected, suddenly quits every 5-15 min for no apparent reason, even if the computer is not in use. 
Computer MacMini, chip M1, OS: macOS Monterey. After restarting the app, it works fine for a while, then quits again.

**Comment by superjeng1** [comment]
Hi, I am closing this issue due to the age, and the belief of this might already been fixed, if you still have this issue, please reach out by reopening this issue and commenting.
