### ISSUE TITLE
Enhancement: Make Mixer Items Moveable and Hideable So Users can Order the items and Trim the list down

### ISSUE THREAD

**Issue by mattpnolan** [bitgapp/eqMac#677]
**Description:**
As a user, my list of items in the Mixer is too large to manage, and there are many apps/programs in the list that I will never need to or want to control.

![Screen Shot 2022-05-26 at 11 18 59 AM](https://user-images.githubusercontent.com/25890321/170519648-11a072fe-69cf-441e-8fe1-4a69d9deb3fc.png)

Therefore, I would like to be able to hide certain apps or programs from the list and/or at least be able to order them so that I don't have to scroll to find the apps I want to control. For example, Zoom is always at the end of the list for me, and I have to scroll the list in order to see Zoom.

**User flow & interface:**
Ideally, to order the items, the user could drag the items to order them. In regards to hiding or unhiding apps/programs, I believe that would have to be an additional section in the Settings that would dynamically show all the apps/programs detected and allow the user to check or uncheck a "visibility" option.

**Comment by superjeng1** [comment]
Hi, this is already possible, please navigate to the settings icon next to the "App Mixer" title and deselect the apps you don't need or reorder them.

**Comment by mattpnolan** [comment]
Thank you. I just saw this was added, but I forgot to come back and close this ticket. I'm not sure when it was added, but I only saw it 2 weeks ago. :P
