### ISSUE TITLE
Enhancement: Support all AutoEq presets

### ISSUE THREAD

**Issue by omcnoe** [bitgapp/eqMac#679]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
Current set of AutoEq presets is very limited, results for many common models are missing. Is there a reason why this feature can't simply allow you to select any presets from the AutoEq repository?
It is also important to be able to select between different authors for the same model of headphone - sometimes one authors preset is much better.

I just want to be able to select any preset from the AutoEq repository without having to manually type all the values across.

**Comment by Salzian** [comment]
Bump for visibility

I'm about to receive Pixel Buds Pro. They got added about 3 weeks ago to the AutoEQ repository. Does eqMac only support a subset of earphones, or is the catalog outdated? When can we expect new models to be added?

**Comment by superjeng1** [comment]
Hi, I think the list is pretty complete, and Google Pixel Buds Pro as mention by @Salzian is included in there too. So I am closing this issue for now, if there is any other thing missing, please feel free to comment and reopen this issue.
