### ISSUE TITLE
Bluetooth Ear Buds causes eqmac to stop responding 

### ISSUE THREAD

**Issue by gworley** [bitgapp/eqMac#684]
I have two different pair of ear buds and both cause eqmac to stop responding.

**Comment by jaydsmith** [comment]
+1

**Comment by komw** [comment]
+1

**Comment by superjeng1** [comment]
Hi, Is this still happening? I have several models of AirPods and they all work fine. As this issue is quite old, I would close it for now. If this bug still happens to you, please reopen this issue and comment, I would be here to help.
