### ISSUE TITLE
major issue: crashing when reverting from airpods to system audio

### ISSUE THREAD

**Issue by jaydsmith** [bitgapp/eqMac#685]
crashing instantly

**Comment by komw** [comment]
The same with non Apple bluetooth headphones.

**Comment by pidds** [comment]
Seems to occur whenever you ad or remove a bluetooth device as your active audio.

**Comment by superjeng1** [comment]
Hi, Is this still happening? I have several models of AirPods and they all work fine. As this issue is quite old, I would close it for now. If this bug still happens to you, please reopen this issue and comment, I would be here to help.
