### ISSUE TITLE
Bug: unresponsive under Ventura

### ISSUE THREAD

**Issue by hstriepe** [bitgapp/eqMac#686]
eqmac becomes unresponsive under Ventura
**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Boot ventura
2. Load emac
3. Enable key control
4. Works great for a bit
5. Stops changing volumes with keys
6. Wheel of death with cursor over menu bar icon
7. Hangs on restart

**Expected behaviour**
It just works under Monterey

**Setup information:**
 - HDMI and other speakers
 - macOS Version: [13beta]
 - eqMac Version [1.4.6, driver 2.0.5]
 - eqMac UI Version [3.2.4]

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**
[eqMac_2022-06-11-092942_Neptune.sin.txt](https://github.com/bitgapp/eqMac/files/8884693/eqMac_2022-06-11-092942_Neptune.sin.txt)

**Comment by superjeng1** [comment]
Hi all, I am closing this issue since the latest versions are way more stable now, if there is any other related issue, please browse for a similar open issue and comment on it. If there are none, please create a new one. Thanks!
