### ISSUE TITLE
Bug: Volume control of bluetooth speaker does not work

### ISSUE THREAD

**Issue by BennyAvelin** [bitgapp/eqMac#687]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [v] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
After starting eqMac the volume control of my bluetooth speaker stops working. i.e. any change in volume does not reflect any change at the speaker.

**Steps to Reproduce**
1. Play music on a bluetooth speaker then start eqMac.
2. Try changing the volume of the speaker, nothing happens unless you go to 0 in which case it actually goes silent.

**Expected behaviour**
The volume on the speaker should change when I change the system volume as is normal without eqMac.

**Setup information:**
 - Audio device used for playback: Linocell portable bluetooth speaker
 - Audio transmission interface: Bluetooth
 - macOS Version: 11.6.2
 - eqMac Version [1.4.6, driver 2.0.5] **(if audio related issue)**
 - eqMac UI Version [e.g. 0.0.4] **(if UI related issue)**

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by superjeng1** [comment]
Hi, Can you verify that this is still the case with the latest version of eqMac? A lot of issue has been fixed since then. Please reopen the issue if this is still the case for you.
