### ISSUE TITLE
when using YouTube, audio distorts

### ISSUE THREAD

**Issue by ghost** [bitgapp/eqMac#689]
I am on a M1 Pro 2021 MacBook Pro 16 in. when using YouTube (I am unsure of what other sites or apps may have this issue, but YouTube seems to be the only culprit, as something like Apple Music for example or another video streaming website does not have this problem

the problem is simple; the audio occasionally warps in pitch by about 1 semitone about every 1 - 1.5 seconds. makes it annoying to use while using YouTube. that'll be about it, thank you

**Comment by superjeng1** [comment]
Hi, the issue mentioned seemed like an sample rate issue, but I cannot reproduce the issue on my Mac. A lot of issue has been fixed since you opened your issue. Please reopen the issue if this is still the case for you.
