### ISSUE TITLE
Bug: Audio Driver is not installed

### ISSUE THREAD

**Issue by joldwg** [bitgapp/eqMac#691]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
At some random point a few days ago the problem just appeared and i can't get it to work again.
The problem has already been reported long ago but the "solving" hasn't solved my problem.
Restarting my mac and trying at least 10 times hasn't helped.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Just trying to install or open 

**Expected behaviour**
I just want to use it T_T

**Setup information:**
 - Audio device used for playback: anything
 - Audio transmission interface: anything
 - macOS Version: 12.4
 - eqMac Version: newest one available from the website or mail
 - eqMac UI Version: newest one available from the website or mail

**Screenshots or Console.app logs**
![Screen Shot 2022-06-23 at 7 39 13 PM](https://user-images.githubusercontent.com/93392322/175362917-9201cc11-d5bf-4346-bb97-7635e1e1d525.png)

**Comment by superjeng1** [comment]
Hi, I think this issue has been resolved. However there is another issue now with the newer versions which is really close in wording to this issue. Check it out here #780
