### ISSUE TITLE
Hang

### ISSUE THREAD

**Issue by elmansyah** [bitgapp/eqMac#693]
Currently my eqMac running in mac OS Monterey, the app always hanged, always request force quit.

**Comment by TripleNL** [comment]
Same issue here, when system needs a reboot or shutdown, EqMacs hangs the reboot or shutdown
Apple Mini Mac M1 16Gb

**Comment by elmansyah** [comment]
Okay Bro, solved in v1.3.2. Btw, I can't upgrade to new one version? I should be in v1.3.2 always?
I think this can make reference for you to fixing this issue in the new version.

Let us know if it's fixed in the new version.

Thanks Bro.

**Comment by superjeng1** [comment]
Hi all, I am closing this issue since the latest versions are way more stable now, if there is any other related issue, please browse for a similar open issue and comment on it. If there are none, please create a new one. Thanks!
