### ISSUE TITLE
Bug: X went wrong when using Y (REPLACE THIS)

### ISSUE THREAD

**Issue by fastzombies** [bitgapp/eqMac#695]
**Disclaimer:** 
Searching the open issues for "license" does not return anything similar.

**Describe the bug**
License will not sync.

**Steps to Reproduce**
This is not reproducable.

**Expected behaviour**
License auto-syncs every month.

**Setup information:**
 - Audio device used for playback: Macbook speaker, A1407 Display audio, Logitech G533 headset.
 - Audio transmission interface: Thunderbolt, USB.
 - macOS Version: 11.6.3
 - eqMac Version v1.3.2
 - eqMac UI Version v3.2.4

**Screenshots or Console.app logs**
Apps seems to indicate license is current but not syncing.
![image](https://user-images.githubusercontent.com/18073500/178791305-677cdc14-ed0c-4251-adf2-c4407dc75fdc.png)

**Additional information**
Tried direct email but haven't heard back in a while.

**Comment by fastzombies** [comment]
Checking on my account, this is what I see:
![image](https://user-images.githubusercontent.com/18073500/178796522-93536290-f8d1-4371-98c7-d74e8fbbf6f4.png)

But when I go to manage subscription I have already paid for July 2022:
![image](https://user-images.githubusercontent.com/18073500/178796830-68b14d89-746a-4b4c-b8a4-a0ee913f5820.png)

So I don't understand the disconnect.  Please advise.

**Comment by nodeful** [comment]
Have you tried restarting the app or Unchecking and Checking the "Auto Manage" checkbox?
I had a couple emails about this problem and restarting the app always helped so far.
I wasn't able to reproduce the issue on my machine and I spent a whole day looking into the code to find the issue culprit but no success so far.
By the way, for future reference, the best way to get help regarding anything "Pro" related is to email me on contact@eqmac.app

**Comment by fastzombies** [comment]
I thought I had tried close/open, but I tried it again and now it had sync'd.  Thanks for the tip.  I had emailed but hadn't heard in a few days and thought I would try here in case someone else knew about it.

Issue closed.
