### ISSUE TITLE
eqMac 1.5.0 weird audio hang issues

### ISSUE THREAD

**Issue by Doridian** [bitgapp/eqMac#698]
While 1.5.0 did successfully fix any type of full-on hang (where eqMac has to be force quit and restarted), it seems to have changed them rather than fix.

As in, quite often now when I as much as stop a YouTube video (and thus I am no longer listening to any audio), and then resume the video, eqMac lags for a couple seconds and I hear no audio at all, until it eventually fixes itself and I can hear audio again.

If this only happened on longer pauses, sure, no worries.

But this happens sometimes even when I just press "next song" in Spotify. If there is as much as the smallest period of no audio, it can happen.

Very, very rarely eqMac fixes itself into turning my audio into chipmunk noises as well, or other distortion. Usually this fixes itself within a couple seconds. Once, however, the only way to fix it was to keep pausing and re-playing music until eqMac hung and fixed itself.

**Comment by nodeful** [comment]
Thanks for the report, I have experienced this as well but very very rarely and it's hard to replicate, but I will keep trying.

**Comment by superjeng1** [comment]
Hi, Just checking in, is this still an issue for you?

**Comment by superjeng1** [comment]
I am closing this issue since I am not hearing back from you. If you are still having this issue, you are welcome to reopen and comment on it.
