### ISSUE TITLE
Silent crashed with v1.5.0

### ISSUE THREAD

**Issue by bouscram** [bitgapp/eqMac#699]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before (for this version at least)

**Describe the bug**
Sometimes eqMac silently crashes (without any notice)

**Steps to Reproduce**
I have not really identified if it is at wake-up or in other circumstances, so no steps to reproduce. I'll add a comment if I can be more specific

**Expected behaviour**
Not crashing

**Setup information:**
 - Audio device used for playback: LG monitor through HDMI connection
 - Audio transmission interface: HDMI
 - macOS Version: 12.5 (M1 Mac Mini)
 - eqMac Version: 1.5.0 
 - eqMac UI Version: 4.0.1

**Comment by nodeful** [comment]
Do you have any recent crash logs related to eqMac in Console.app?

**Comment by bouscram** [comment]
Hi Roman. No, there is nothing. Since I opened the issue, it happened once more, I think after a wakeup, but it's far from being systematic. Right now for instance it didn't happen.

**Comment by bouscram** [comment]
Hi. Same behaviour with version 1.5.1. I notice most silent crashes at wakeup, but I'm pretty sure it happens also in other circumstances.

**Comment by aldaw** [comment]
You could go CMD + Space and then look for console.app.
Then go to crash reports, look for eqMac and copy past it here.
<img width="1149" alt="Bildschirmfoto 2022-08-06 um 22 21 32" src="https://user-images.githubusercontent.com/16668679/183265014-ff9650c8-b7ca-4097-a507-2b0358d3968d.png">

Same here: https://github.com/bitgapp/eqMac/issues/714

**Comment by bouscram** [comment]
Hi. I know how to look for crash reports, but there are none for eqMac... (as said earlier)

**Comment by bouscram** [comment]
I have unchecked the OTA updates which seems to (mostly) correct the issue. 
I just updated to v1.6.1 and re-enabled it to see what happens.

**Comment by bouscram** [comment]
Versions 1.6.x sometimes crashes, but not silently. So I'm closing this particular issue.
