### ISSUE TITLE
Bug: eqmac crashes immediately upon load (even after reinstall)

### ISSUE THREAD

**Issue by danielletx** [bitgapp/eqMac#701]
**UPDATE** : _instead of reinstalling v. 5.1, i dropped back to the previous version you have available here (v. 4.3, I think…?).  after reinstall, It was still acting wonky, and so i forced an update to v. 5.1 from there.  all preferences reset, and everything appears to be working fine now!_

roman,

just wanted to let you know that this happened on my Mac M1 (2020) machine, running 12.3 of the maverick o/s.  it *was* working fine until I ran a command line to pkill the Bluetooth module as well as the core audio.  even after successive reboots, it still won't open.  oh!  and I'm running the latest version of eqmac (5.1).

thoughts…?
~danielle

PS - and thanks again for all your hard work on this!!  ;)

**Comment by superjeng1** [comment]
Hi, looks like you have fixed this issue, so I am going ahead and close this issue.
