### ISSUE TITLE
Bug: Status bar / control center slider not being updated

### ISSUE THREAD

**Issue by krystof-k** [bitgapp/eqMac#702]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**

When changing the volume via keyboard or in eqMac UI, the sliders in status bar and/or control center are not being updated.

Not sure wheter this is a bug or limit of macOS.

**Setup information:**
 - Audio device used for playback: MacBook speakrs
 - Audio transmission interface: –
 - macOS Version: 12.5 (21G72)
 - eqMac Version: 1.5.1
 - eqMac UI Version: 4.0.3

**Screenshot**

<img width="980" alt="Snímek obrazovky 2022-07-26 v 22 45 50" src="https://user-images.githubusercontent.com/11633481/181108709-a535239d-a487-4bc9-8c0e-b70c027d870f.png">

**Comment by superjeng1** [comment]
Hi, as the previous comment should fix this issue, I would go ahead and close this issue now.
