### ISSUE TITLE
Bug: Delay

### ISSUE THREAD

**Issue by moment0fmemory** [bitgapp/eqMac#704]
hey, it's just me or everyone got delay issue whenever playing video on web browsers such as chrome, firefox, and safari. especially to pause youtube and play it back it takes about 3 seconds to hear the audio.

eqMac v1.5.1
eqMac UI v4.0.3

tested on:
intel MB Pro macOS 12.5
M1 MB Air macOS 12.4
M1 Pro MB pro macOS 12.5

thank you for your hard work.

**Comment by superjeng1** [comment]
Hi, as I am not able to replicate this issue in the latest version of eqMac, I would be closing this issue for now. If you are still having this issue, please reopen this issue and leave a comment.
