### ISSUE TITLE
SOUND WONT CHANGE WHEN ADJUSTED.

### ISSUE THREAD

**Issue by jimmare** [bitgapp/eqMac#708]
I paid for and set up the app to my liking and the volume would not change from max even when lowered down and the channel sliders will not work. I have restarted the app and my computer countless times and even reinstalled the app. The eq doesnt work. Basically nothing has worked right since installing and paying for the app.

**Comment by aldaw** [comment]
Could you tell what Device you are using M1 or Intel? which OS version?
Have you tried the Beta? You can turn in on in the settings.

**Comment by jimmare** [comment]
I’m running Catalina 10.15.7 on an Intel Mac. I have not tried the beta,
I’m using the full paid version

**Comment by jimmare** [comment]
Where is a download to the beta

**Comment by superjeng1** [comment]
Hi, as I am not able to replicate this issue in the latest version of eqMac, I would be closing this issue for now. If you are still having this issue, please reopen this issue and leave a comment.
