### ISSUE TITLE
Bug: Crashes after my Mackbook was in sleep mode

### ISSUE THREAD

**Issue by GiulioIannattone** [bitgapp/eqMac#709]
After my Mackbook leaves the sleep mode, eqMac is crashed. I have to kill the app and restart it.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Start the MacBook Pro M1 with Monterey 12.5 and eqMac (App. v1.4.6, Driver:v2.0.5 UI:v3.2.4) working.
2. Close the cover to set the MacBook in sleep mode.
3. After some minutes open the MacBook and login.
4. See error - eqMac is crashed.

**Expected behaviour**
eqMac should work like bevor the sleep mode.

**Setup information:**
 - Audio device used for playback: [Macbook speaker]
 - Audio transmission interface: [none]
 - macOS Version: [12.5]
 - eqMac Version [1.4.6] 
 - eqMac UI Version [3.4.4]

**Comment by aldaw** [comment]
I have similar behaviour:
https://github.com/bitgapp/eqMac/issues/714

**Comment by aldaw** [comment]
You could go CMD + Space and then look for console.app.
Then go to crash reports, look for eqMac and copy past it here.
<img width="1149" alt="Bildschirmfoto 2022-08-06 um 22 21 32" src="https://user-images.githubusercontent.com/16668679/183265014-ff9650c8-b7ca-4097-a507-2b0358d3968d.png">

**Comment by superjeng1** [comment]
Hi all, I am closing this issue since the latest versions are way more stable now, if there is any other related issue, please browse for a similar open issue and comment on it. If there are none, please create a new one. Thanks!
