### ISSUE TITLE
Keyboard volume buttons don't work after sleep/wake + temporary workaround

### ISSUE THREAD

**Issue by serif** [bitgapp/eqMac#712]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description**
Keyboard volume buttons don't work after sleep/wake (at least on an older version of MacOS, 10.14). 
System GUI shows volume changes, but changes not mirrored in the eqMac GUI.

**Steps to Reproduce**
1. Launch eqMac
2. Sleep
3. Wake
4. Attempt to change volume with keyboard (F11/F12)

**Expected behavior**
After sleep/wake, physical volume buttons should change volume in eqMac, as they do when first launched.

**Setup information:**
 - Audio device used for playback: any / Macbook internal speaker
 - Audio transmission interface: any / [internal or 3.5mm Jack]
 - macOS Version: 10.14
 - eqMac Version 1.3.2
 - eqMac UI Version 3.2.4

**Additional information**
Problem resolves if eqMac is closed and reopened. There's a suggestion [here on StackExchange](https://apple.stackexchange.com/questions/159216/run-a-program-script-when-the-screen-is-locked-or-unlocked) for a notification you could listen for to reinitialize things on wake.

**Temporary Workaround**
Automatically close and relaunch eqMac using [Sleepwatcher](https://www.bernhard-baehr.de/).

Setup for version 2.2.1. Run in Terminal after downloading and extracting to Desktop:

    sudo mkdir -p /usr/local/sbin /usr/local/share/man/man8
    sudo cp ~/Desktop/sleepwatcher_2.2.1/sleepwatcher /usr/local/sbin
    sudo cp ~/Desktop/sleepwatcher_2.2.1/sleepwatcher.8 /usr/local/share/man/man8
    sudo cp ~/Desktop/sleepwatcher_2.2.1/config/de.bernhard-baehr.sleepwatcher-20compatibility.plist /Library/LaunchDaemons/de.bernhard-baehr.sleepwatcher.plist
    sudo cp ~/Desktop/sleepwatcher_2.2.1/config/rc.* /etc
    sudo launchctl load /Library/LaunchDaemons/de.bernhard-baehr.sleepwatcher.plist

Create scripts:

    echo $'#!/bin/sh\n\nosascript -e \'quit app "eqMac"\'' > ~/.sleep
    echo $'#!/bin/sh\n\nopen -n /Applications/eqMac.app' > ~/.wakeup
    chmod +x ~/.sleep
    chmod +x ~/.wakeup

**Comment by superjeng1** [comment]
Hi, as I am not able to replicate this issue in the latest version of eqMac, I would be closing this issue for now. If you are still having this issue, please reopen this issue and leave a comment.
