### ISSUE TITLE
Bug: Duplicate device names when USB devices are plugged in again

### ISSUE THREAD

**Issue by PengchongLiu** [bitgapp/eqMac#713]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.
![Screen Shot 2022-08-06 at 9 43 47 AM](https://user-images.githubusercontent.com/34066991/183251645-5648fbf5-27a1-4598-a30b-3b4263f231c5.png)

**Describe the bug**
When a USB DAC device is unplugged and plugged in again, the device switcher will created a new device record with identical names, with the existing device record deemed "currently unavailable". 

**Info** 
version v1.5.1.
OS: macOS 12.5

**Comment by nodeful** [comment]
Ah that sucks, that means that the manufacturer of the device is generating a new random ID for the device each time, instead of having a same one for me to be able to track it. I will have to put in some kind of a workaround then.
Thank you for the report. I will try to sort this out as soon as I can.

**Comment by ragauskl** [comment]
This should have been resolved a while back. If the issue still occurs let me know and I'll reopen the issue.
