### ISSUE TITLE
Bug: AutoEQ preset for Beyerdynamic DT 990 (general) not correct

### ISSUE THREAD

**Issue by xZoeRx** [bitgapp/eqMac#715]
**Describe the bug**
The preset in Expert mode for Beyerdynamic DT 990 (general) does not seem to be the correct one from the AutoEQ database, even though it's supposed to be.

**Steps to Reproduce**
Steps to reproduce the behavior (feel free to change the placeholder as you need):
1. Go to Expert Mode
2. Click on the headphones icon (on hover, it should display a popover showing "AutoEQ")
3. Choose Beyerdynamic from the menu
4. Then choose DT series
5. Then choose DT990
6. Then choose DT990 (general)

**Expected behaviour**
The preset should be the same as found on AutoEQ.

**Setup information:**
Macbook Air M1, macOS Monterey 12.5
 
**Screenshots or Console.app logs**
![image](https://user-images.githubusercontent.com/34140349/183350482-8fc20582-64d4-42bd-b55d-8a99fa72709b.png)

**Comment by nodeful** [comment]
Hey thanks for reporting this.
AutoEQ project has recently updated the measurements and I just release a UI update (where the Presets are shipped) v4.0.7 yesterday and you should be able to see the new preset values if you're running eqMac v.1.5.X

**Comment by superjeng1** [comment]
Hi, I am closing this issue since the profile has been updated. The AutoEQ project has updated the profile for this model however, but we are working on updating the presets right now, so this should be fixed soon.
