### ISSUE TITLE
No sound at all after install

### ISSUE THREAD

**Issue by SEDRAproject** [bitgapp/eqMac#717]
I just installed a free version of eqMac to test it out. It just cuts the sound altogether when it starts. Quitting eqMac restores the sound. Tried with internal speakers, bluetooth, USB. Clicking the "reload" icon to the left of the output device selection you hear a fragment of sound for a fraction of a second. Tried restarting audio via Terminal, nogo. No other apps running. I also tried the previous version of eqMac (1.5.1), same thing. The driver is there and looks fine. Just no sound and nothing moving in the eqMac panel. 

Macbook pro 2012, 10.12.6 and iMac 10.13.6 both give same result

**Comment by superjeng1** [comment]
Hi, as I am not able to replicate this issue in the latest version of eqMac, I would be closing this issue for now. If you are still having this issue, please reopen this issue and leave a comment. Note that the no audio issue could still happen in the latest version really rarely. If that happens, either reboot your Mac or run the command below, which would attempt to restart the macOS audio service, although it might not actually do it.

`sudo launchctl kickstart -k system/com.apple.audio.coreaudiod`
