### ISSUE TITLE
Bug: Virtual devices created by Loopback software leave permanent items in eqMac

### ISSUE THREAD

**Issue by m13253** [bitgapp/eqMac#718]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Using a 3rd-party software called “[Loopback](https://rogueamoeba.com/loopback/)”, the user can create multiple virtual devices. However, each creation of virtual device will leave an item in eqMac, even after it is deleted.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Open eqMac
2. Open Loopback (Note: It's a paid software with free 20-minute trial)
3. Click on “New Virtual Device”
4. Click on “Delete”
5. Repeat step 3 and 4 a few times
6. Go to eqMac, check the device list

**Expected behaviour**
- Either the deleted virtual devices are automatically removed from eqMac,
- Or the user is provided with a menu to manually remove unused devices.

**Setup information:**
 - macOS Version: 12.5.1
 - eqMac Version: 1.5.1
 - eqMac UI Version: 4.1.2
 - Loopback App Version: 2.2.9
 - Loopback ACE Driver Version: 11.8.2

**Screenshots or Console.app logs**
![Screen Shot 2022-08-25 at 16 43 54](https://user-images.githubusercontent.com/1808930/186723742-71981a01-39b5-4bc7-94fb-504cdbbc0543.png)

**Comment by nodeful** [comment]
Hmm yeah that's annoying, I will fix in the next update!
Thank you for reporting this

**Comment by nodeful** [comment]
In update v1.6.1 that you can download now through the Beta Program (enable it in eqMacs settings) I've improved the way I'm caching the devices, plus you can Reset Device cache in Output Settings to clear up the list from the old devices:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/8472525/188427141-30d3317f-44de-47b9-89f0-a60a12d05d64.png">

**Comment by m13253** [comment]
Looks good to me.
I think this change can also solve #713.
