### ISSUE TITLE
Sample Rates issues

### ISSUE THREAD

**Issue by hectorituarte** [bitgapp/eqMac#720]
Currently (MBP 2019 on the latest MacOS Ventura Beta) any sample rate of over 44100 results in 'slowed-down' audio. The higher the rate, the slower the audio (and number of dropped samples too.)

This happens regardless of the output device. Tried so far on headphones, speakers and iPods Pro.

**Comment by EricAckerman** [comment]
**Working fine now:** 13.0 Beta (22A5331f) iMac 3.8 GHz 8-Core Intel Core i7
Was slow for me too before beta v1.6.1 update.

**Comment by superjeng1** [comment]
Hi, This has been fixed in later versions of eqMac, so I am closing this issue now.
