### ISSUE TITLE
Bug: the menu bar sound icon does not change to an airpods icon when eqmac is running

### ISSUE THREAD

**Issue by bztravis88** [bitgapp/eqMac#725]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
In the menu bar in Mac OS Monterey, the sound icon indicates the output device for system sound. Without EQMac running, it will change from a generic speaker to an AirPods icon once AirPods are connected. However, when EQMac runs, that icon reverts to a generic speaker even when AirPods are connected, in addition to that menu not indicating that the AirPods are connected.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Connect AirPods to Mac
2. Open EQMac and run the program by enabling "EQMac Bypass"
<img width="375" alt="image" src="https://user-images.githubusercontent.com/60321202/188337917-1f1bf344-d85c-4957-938f-0c439afabd6e.png">

**Expected behaviour**
<img width="362" alt="image" src="https://user-images.githubusercontent.com/60321202/188337901-cbee7b50-d5d8-487f-8307-ebfb78bd8f77.png">

**Setup information:**
 - Audio device used for playback: AirPods Pro 1
 - Audio transmission interface: Bluetooth
 - macOS Version: 12.5.1
 - eqMac Version: 1.5.1
 - eqMac UI Version: 4.2.0 (Remote)

**Comment by nodeful** [comment]
There's no public API available to developers to change this :(

**Comment by nodeful** [comment]
I've messaged Apple about this and they refused to help.

**Comment by superjeng1** [comment]
As Apple does not allow this at the moment, I would close this issue for now. Please track issue #812, this would make eqMac display a custom icon for devices, but it is not easy to implement.
