### ISSUE TITLE
v1.6.1 Crashes When Switching Device Output

### ISSUE THREAD

**Issue by glenndarwis** [bitgapp/eqMac#726]
When switching device output between the various output devices, eg. bluetooth headphones, external speakers, internal speakers, the program crashes. I had to revert back to 1.5

1. Click on sound icon
2. Select device
3. See error

**Setup information:**
 - Audio device used for playback: Sennheiser HD 4.40, internal macbook pro speaker
 - Audio transmission interface: bluetooth, internal speaker, external speaker
 - macOS Version: 11.11
 - eqMac Version 1.6.1
 - eqMac UI Version 2

**Comment by nodeful** [comment]
Thanks for your report, but I would appreciate a Crash Report please :)

**Comment by superjeng1** [comment]
Hi all, I am closing this issue since the latest versions are way more stable now, if there is any other related issue, please browse for a similar open issue and comment on it. If there are none, please create a new one. Thanks!
