### ISSUE TITLE
audio mutes several times an hour until volume is adjusted

### ISSUE THREAD

**Issue by danielletx** [bitgapp/eqMac#728]
running v1.6.2 but began seeing this issue in v1.6.1.
running osx Monterrey 12.3 on M1 silicon 
using Bose AE2 SoundLink

every couple of hours, the volume knob turns red, and sound no longer outputs until I press the keyboard volume up or down.  after that, everything works great until the next time that the same thing happens (usually about two or three times an hour).  assuming this may be related to the program taking possession of the audio driver…?

UPDATE: this issue occurs less often if I restart eqMac…but *does* eventually return—and with increased frequency (until reboot).

![189552290-9ece037a-0a6b-43d8-a337-43675700bb15](https://user-images.githubusercontent.com/83250198/189579713-5310a7b7-b512-44de-87ac-e2d54cc990f2.png)

**Comment by mardulas** [comment]
Kind of same. If I'm doing something (surfing, so changing tabs and windows) then it cuts out like every 5-10 minutes: system volumes slider goes to zero (muted icon) and EqMac Volume slider turns to red. Then I need to manually adjust either for sound to start working again. 
SUPER annoying.

It started w. the last update (1.7.2) tho.

**Comment by superjeng1** [comment]
Hi all, I am closing this issue since the latest versions are way more stable now, if there is any other related issue, please browse for a similar open issue and comment on it. If there are none, please create a new one. Thanks!
