### ISSUE TITLE
Bug: Sound is disrupted when another program push notification with sound

### ISSUE THREAD

**Issue by khoile-0902** [bitgapp/eqMac#730]
**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Start eqMac
2. Play music
3. Use a notification app (Slack for example) to receive a notification
4. Observe the disruption

**Comment by mintyleaf** [comment]
I can admit that I can hear the same behavior when i just using Soundflower + Hosting AU with LAConvolver at 2048 buffer size
so, seems like that this is more deep problem

**Comment by superjeng1** [comment]
Hi, may I confirm if this issue is still happening?

**Comment by superjeng1** [comment]
Hi, I would close this issue since it is related to this one. #724
