### ISSUE TITLE
Audio popping/distorting in Amazon Music desktop app after Updating to v1.6.2

### ISSUE THREAD

**Issue by jaggrnaut** [bitgapp/eqMac#734]
Running MacBook Pro (Retina, 15-inch, Mid 2014) with Catalina—running audio out of headphone jack to edifier speakers

Popping and audio distortion. I toggled eqMac off and on and it's definitely the eqMac—when it's off the app sounds fine.

All other apps I use worked fine with 1.6.2  (spotify, all browsers, etc), but Amazon music desktop app was having audio issues.

Tried re-installing amazon music app and eqMac, but still had issues.

Had to revert to older eqMac version 1.4.6 and it's working fine.

**Comment by hlynurstef** [comment]
I'm experiencing the same while using version 1.6.2 and Spotify

**Comment by jhuggart** [comment]
Same here. Also on a 14-inch 2021 mbp. During the latest upgrade, it looks like new audio drivers were installed. Could that be the issue?

**Comment by hlynurstef** [comment]
@jaggrnaut @jhuggart I sent a message to the eqMac discord and got some valuable answers. Apparently, there is a bug in M1 Macs in Coreaudiod if the ram usage is high causing the audio to pop and distort randomly. I was running at about 28/32gb ram and when I closed eqMac the problem persisted which told me it was probably the Coreaudiod bug. After I restarted the computer I was at about 7.5/32gb and the problem went way.

So essentially:
1. When the pops occur, try closing eqMac and see if the problem persists
2. If the problem persists, check your ram usage
3. Try to lower the ram usage by closing applications or restarting
4. Check if the problem still persists with low ram usage

I think this is an issue with Apple and not with eqMac

**Comment by jaggrnaut** [comment]
Thanks, I'll keep an eye on it. I might just stick with v1.4.6 on my system for now since it's working fine.

**Comment by superjeng1** [comment]
@hlynurstef Glad to hear I helped you on Discord, I remembered that. Back on topic, @jhuggart Please let me know if this is still an issue on the latest version of eqMac, thanks!

**Comment by superjeng1** [comment]
Hi, this is related to #724 so I am closing this issue. Please refer to that issue for further updates.
