### ISSUE TITLE
Bug: Pull down menu issues on Mac

### ISSUE THREAD

**Issue by TLWAudio** [bitgapp/eqMac#736]
I'm a new user working on a Mac laptop with a trackpad and running Mac OS Big Sur. I've purchased a subscription. 

I'm finding that none of the pull-down menus (e.g  for selecting one of the 31 presents in Expert EQ, or, choosing from the list of headphones in AutoEQ) are allowing me to scroll down beyond the initial options that show up in the window. 

There is no visible scroll bar on either side of the pulldown so I'm using my trackpad and arrow keys -- but the menus don't move up/down. Help? (Is it not compatible (updated) for my OS?)

<img width="391" alt="Screen Shot 2022-09-13 at 1 38 01 PM" src="https://user-images.githubusercontent.com/113464860/189973473-54a5f19e-92d1-4b43-8bbf-e02f3f73b958.png">
Help?

**Comment by ian-h-chamberlain** [comment]
Hi @superjeng1, I think I'm facing the same issue although my interface looks a bit different (I've disabled most of the features in the UI). I'm not a pro subscriber so perhaps that's also related? The two most common problems I've noticed are in the output device "settings" page and the output device dropdown, using either popover or windowed mode.

Here are some screenshots, maybe they will help track it down:

UI Settings:
![Screenshot 2023-07-25 at 09 42 38](https://github.com/bitgapp/eqMac/assets/11131775/36b738ab-b1fc-4a4f-ac75-9958e920f5b1)

resulting in main UI page looking like

![Screenshot 2023-07-25 at 09 41 59](https://github.com/bitgapp/eqMac/assets/11131775/1d9cf8c3-7891-4f02-8035-cb8ccd8b491b)


Can't scroll to select first few devices:
![Screenshot 2023-07-25 at 09 40 14](https://github.com/bitgapp/eqMac/assets/11131775/91dc2764-0762-4189-876e-6b6c57b86788) 

Can't reorder devices / change auto-select preferences:
![Screenshot 2023-07-25 at 09 40 23](https://github.com/bitgapp/eqMac/assets/11131775/87804222-94a7-47f2-b36b-6c8f8b8f7d4e)

----
macOS ventura 13.4.1

App info: ![Screenshot 2023-07-25 at 09 45 30](https://github.com/bitgapp/eqMac/assets/11131775/4af0032d-d06a-478b-b510-4d402feaa603)

**Comment by MrKistic** [comment]
I have the same issue on macOS 13.5.1 (22G90), also eqMac v1.7.10. It is not possible to resize the window in any way and the popups don't trigger any auto resizing the way expanding the EQ does for example. In fact the only way I can get to the full list of devices is to expand the EQ first so the window resizes and then click the output settings button!
