### ISSUE TITLE
Bug: system volume keys/buttons not working while eqMac is active

### ISSUE THREAD

**Issue by ElhemEnohpi** [bitgapp/eqMac#737]
- [x] I have checked for a similar issue and sure it hasn't been reported before.
[Possibly #287 refers in part to this issue, but the report was closed as incomplete, and seems to be about multiple issues.]

**Describe the bug**
[edit: The problem happened after a first-time install. I tried restarting various things, finally, restarting the whole computer seemed to fix the problem.]
While eqMac (free version) is enabled, the mute and volume control keys on the keyboard, or buttons on headphones, don't change the volume. The system volume graphic overlay pops up and shows the volume being adjusted, but it's not synchronized to eqMac. Changes are synchronized at the moment of enabling or disabling eqMac, but not while it's running.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Install eqMac (free version), and turn on the main Bypass, so that it's red and processing is disabled.
2. Adjust the system volume with the keyboard (or headphones with volume buttons). Observe that the volume overlay display pops up, showing the volume being adjusted, and the output volume changes.
3. Click the Bypass so that it's green. Observe that eqMac adopts the current system volume level setting in its own volume control.
4. Adjust the system volume with the keyboard again. Observe that the overlay pops up and shows the adjustment, but that eqMac's volume doesn't update, and the actual output volume doesn't change.
5. Adjust eqMac's volume control. Observe that the output volume changes, but the system volume as displayed in the popup overlay does not.
6. Click the Bypass so that it's red again. Observe that the output volume remains about the same, and the system volume as displayed in the overlay adopts the value that was set in eqMac.

**Expected behaviour**
The keyboard and headphone volume control buttons should adjust the actual output volume of the computer. Adjusting the volume with the volume keys/buttons should update eqMac's volume control, and thus the output volume, and vice-versa, while it's running, and not only at the moment it's enabled or disabled.

**Setup information:**
 - Audio device used for playback: M1 Mac mini
 - Audio transmission interface: 3.5 mm headphone jack
 - macOS Version: 12.6
 - eqMac Version: 1.6.2, downloaded from Github releases.
 - eqMac UI Version: 4.2.1 (Remote)

**Screenshots or Console.app logs**
There are various Console messages, but I don't see anything that looks related, or that happens at the time of adjusting the volume.

**Additional information**
First time install of eqMac, so I don't know if this worked in previous versions or other hardware, or if it's even intended to work.

**Comment by TerrorSquad** [comment]
Same issue.
Macbook Pro 14 M1 Pro, macOS Ventura 13.4 (22F66)

**Comment by superjeng1** [comment]
Hi, this is supposed to work just fine, and it seems like @ElhemEnohpi has fixed the issue by restarting the computer. So I am closing the issue right now. If anyone here has a similar issue, please comment or create a new issue.

**Comment by meetkaushal** [comment]
This bug still exists. I am facing this on the latest build of eqMac Pro [free]. This is what is stopping from buying a full license. Restarting the computer does not help. See attached video. Please note that I am pressing the Volume Up Function key on an Apple Magic keyboard.

Mac Studio M2 Ultra: 64GB, Sonoma 14.0
eqMac Pro v1.7.10, Driver v2.4.3


https://github.com/bitgapp/eqMac/assets/187447/42286539-dce4-4eb1-a8b1-4a8cf0c7da7d
