### ISSUE TITLE
Audio not working when turning volume all the way down and back up

### ISSUE THREAD

**Issue by therick0996** [bitgapp/eqMac#738]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When putting the volume all the way down, and putting it back up, there's no audio until you change the device

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. adjust volume all the down
2. adjust volume back up
3. no audio
4. change device
5. audio now works

**Expected behaviour**
audio should work after turning volume all the way down and back up

**Setup information:**
 - Audio device used for playback: Schiit Modi 3+ >  Schiit Magni > HD6xx headphones
 - Audio transmission interface: USB
 - macOS Version: 12.5 (21G72)
 - eqMac Version: 1.6.2 Driver: 2.2.0
 - eqMac UI Version [e.g. 0.0.4] **(if UI related issue)**

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by superjeng1** [comment]
Hi, I could not replicate this issue in the latest eqMac. I am closing this issue now because of that. If you are still having issue on this, please reopen this issue and comment on the details.
