### ISSUE TITLE
Bug: The first half second or so of system alerts don't play through eqMac on Ventura.

### ISSUE THREAD

**Issue by barnabasjohnthomas** [bitgapp/eqMac#739]
The first bit of all the system sounds seem to be cut off when using eqMac on macOS Ventura - took me a while to figure out it was actually cutting out the first half second instead of not playing them at all (which was what I first thought it was doing.) It's a brand new (like unboxed an hour ago) Mac, so I don't think any other software is interfering with it. Regular video and audio appear to play fine, and eqMac is functioning correctly apart from this.

Thanks for the work you do on this - you've really got a great piece of software here.

**Comment by ichbinJulien** [comment]
I've had this problem for a while, even before macOS Ventura. Every eqMac version higher than 1.3.2 just cuts off the first half-second of every sound -- as long as nothing else is already playing. When I listen to music, meaning when eqMac is already working, other sounds appear perfectly fine.
It's like eqMac goes into a sleep mode and takes half a second to wake up. I've had this exact problem with a JBL soundbar that was connected to my TV, it was quite frustrating so I sent it back. Luckily, with eqMac, I can just revert back to 1.3.2, which still works like a charm. Every time there is a new version, I'm crossing my fingers, hoping that it might resolve this issue, and then I end up going back to 1.3.2...

I'm writing this in the hope that the information, that the older version is still good, will somehow help. Either with someone experiencing the same problem, or with fixing whatever is causing it. eqMac is an amazing little tool that I don't want to miss out on, thanks to the devs for creating it, now let's hope this issue can be resolved.

**Comment by superjeng1** [comment]
Hi, @barnabasjohnthomas @ichbinJulien  I would like to check if this issue is still happening to you with the latest version of eqMac.

**Comment by ichbinJulien** [comment]
> Hi, @barnabasjohnthomas @ichbinJulien I would like to check if this issue is still happening to you with the latest version of eqMac.

Hi, thanks for taking the time to reply.

Sadly, the update to version 1.7.10 did not resolve my specific issue, all sounds are still cut-off at the very beginning, very short sounds disappear completely.

Reverting back to 1.3.2 once more...

**Comment by superjeng1** [comment]
Thanks @ichbinJulien for your reply! We would try to investigate this issue, thanks for the information.

**Comment by superjeng1** [comment]
Hi @ichbinJulien, I would like to know if this issue happens to every device and what app do you observe this happening?

**Comment by ichbinJulien** [comment]
> Hi @ichbinJulien, I would like to know if this issue happens to every device and what app do you observe this happening?

Hi, sadly I only have a Mac Mini (M1, 2020, Ventura 13.4.1) so I can't test eqMac on another device.
As for which app, it's the entire system that behaves this way. No matter if it's system alerts, music through the Music app, Firefox playing YouTube -- every single sound is cut-off at the beginning.

**Comment by ragauskl** [comment]
Sorry it took us so long to get back on this issue with a solution, it was available for a while now but there was no time to go through Github issues.

You can try setting the 'Pause Audio Processing' to 'Never' in eqMac settings 
<img width="397" alt="image" src="https://github.com/bitgapp/eqMac/assets/9280160/d050fa81-c6ca-4e62-ad1c-5525727b210f">

This will cause eqMac to prevent sleep, however you can see if that helps in first place and then try decreasing it a bit and see if the issue reoccurs, if not you can continue using the time higher than default but not 'Never'

**Comment by Pietro228** [comment]
@ragauskl Thank you! This actually fixed my issue! :D

**Comment by ichbinJulien** [comment]
@ragauskl You did it! This is awesome, thank you for fixing this issue! 😁

**Comment by ragauskl** [comment]
All thanks to @nodeful, he's the dev :D I've just recently started helping with catching up with/handling customer support and communications between users and him so he can focus on improving the software for everyone

As it seems this is fixed for multiple people I'm closing the issue as complete
