### ISSUE TITLE
No option to remove app icon from dock bar.

### ISSUE THREAD

**Issue by LondonIsCrazy** [bitgapp/eqMac#740]
I had to reinstall Mac 12.6 on a MacMini (M1, 2020)
eqMac App:  v1.6.2
Driver:  v2.2.0
UI:  v4.3.0 (Remote)

It's working OK except the app icon is stuck on the lower dock bar.  I'm sure it was never there before and I can't find any options in the program to hide it.

![Screenshot 2022-09-20 at 15 34 48](https://user-images.githubusercontent.com/114003100/191287645-f4be129c-e0ce-4d14-a7be-e3d683358e0e.jpeg)

**Comment by nodeful** [comment]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/8472525/191384130-172d54b1-f550-4405-8927-fadee4040c2b.png">
eqMac Settings > Icon Placement

**Comment by LondonIsCrazy** [comment]
Thank you so much. Don't know how I missed it. Feel a bit sill now!

**Comment by LondonIsCrazy** [comment]
Thank you so much. Don't know how I missed it. Feel a bit sill now!

**Comment by nodeful** [comment]
No worries, easy to miss, packed UI
