### ISSUE TITLE
Bug: Audio sounds slowed/pitched down and skipping to 'catch up'

### ISSUE THREAD

**Issue by jdkoeppen** [bitgapp/eqMac#742]
When streaming from Spotify, browser, or a podcast app the audio sounds slowed down and skips every couple of seconds like it's catching up. Issue stops when eqMac is bypassed or shutdown. Tried reloading audio engine, restarting music apps, restarting eqMac, in different orders. Sometimes the issue corrects itself randomly, but reoccurs any time eqMac is restarted after stopping. 

App v1.6.2, Driver v2.2.0, UI v4.3.1 (Remote)

**Comment by superjeng1** [comment]
Hi, as this issue is similar to #724, I am closing this issue. Please track this bug at the issue mentioned.
