### ISSUE TITLE
No Sound from Caller when using WhatsApp on MacbookAir

### ISSUE THREAD

**Issue by Wostruha** [bitgapp/eqMac#744]
Hi,

when I have a WhatsApp Call or VideoCall, I don't hear the Sound of the other Caller when EqMac is switched on.
If I quit the program or switch off the Main button, I can hear the sound.

Do I have to enable the sound for specific Apps?

Best regards
Jörg

**Comment by superjeng1** [comment]
Hi, currently, there are some issues around calling and WhatsApp. I would close this issue now since there is already one that is pretty similar to this. #648
