### ISSUE TITLE
Device Auto Switching does not always work

### ISSUE THREAD

**Issue by bouscram** [bitgapp/eqMac#746]
**Describe the bug**
The auto switching feature does not always work.

**Steps to Reproduce**
I have an M1 Mac Mini connected to a LG display via HDMI. I have set the LG display to be the highest priority in the auto switch devices list, as shown here:
<img width="446" alt="image" src="https://user-images.githubusercontent.com/1451624/193402835-6966cb95-9dc9-4956-b3e3-0e131f998eaa.png">

Sometimes, but not always, when the Mac exits from sleep, eqMac selects the internal speaker, and doesn't switch to the display.

**Expected behaviour**
The LG display should be selected

**Setup information:**
 - Audio device used for playback: LG HDR 4K display
 - Audio transmission interface: HDMI
 - macOS Version: 12.6
 - eqMac Version 1.6.2, driver 2.2.0

**Comment by YYotai** [comment]
Same problem, same config with an ASUS screen. 99% of the time when resuming from standby, eqMac reverts to internal Mac mini speakers even though the display has 1st priority.

**Comment by PaulWilliamWoods** [comment]
I also have this problem with a BenQ EW3280U external monitor.

**Comment by avj73** [comment]
Same.  When macbook pro (m1) leaves sleep, it reverts to the internal speakers instead of my monitor connected via USB C.

**Comment by tonypconway** [comment]
I'm having the same issue with an M1 Mac.  @nodeful is there a log file or report we can share that might help you diagnose this?

**Comment by hkjasf687261gh** [comment]
same config and issue, with samsung tv

**Comment by bouscram** [comment]
This issue appears to be corrected with versions 1.7.x (I'm using 1.7.2)

**Comment by ryanaltvater** [comment]
Update 1.7.2 appears to be SO close, but the issue still partially exists for me.

1. Playing music through my speakers
2. Put my AirPods in
3. eqMac automatically switches to my AirPods
4. Take my AirPods out
5. eqMac doesn't automatically switch back to my speakers
6. Open eqMac
7. Click "Reset Audio Engine"
8. eqMac automatically switches to my speakers

**Comment by ryanaltvater** [comment]
@bouscram Update 1.7.2 appears to be SO close, but the issue still partially exists for me.

1. Playing music through my speakers
2. Put my AirPods in
3. eqMac automatically switches to my AirPods
4. Take my AirPods out
5. eqMac doesn't automatically switch back to my speakers
6. Open eqMac
7. Click "Reset Audio Engine"
8. eqMac automatically switches to my speakers
