### ISSUE TITLE
Activating boost without incredible increase in volume

### ISSUE THREAD

**Issue by philipdygeus** [bitgapp/eqMac#749]
**Description:**
On MacOS Monterey volume increases dramatically if one presses the boost check box.

**User flow & interface:**
On MacOS Monterey volume increases dramatically if one presses the boost check box, even if the volume is set low (10-15%). With in-ear monitors plugged it's so loud that there's risk of damage to eardrum. Please consider implementing significantly lower volume to start from to enable user to find the appropriate listening volume.

**Comment by superjeng1** [comment]
Hi, this is implemented in the newer version of eqMac, please try out the latest version.
