### ISSUE TITLE
Bug: System Audio Capture Driver Typo

### ISSUE THREAD

**Issue by giulianofichera** [bitgapp/eqMac#750]
**Describe the bug**
When setting up eqMac, the System Audio Capture Driver Window has a typo. In the second paragraph, the word "hidded" should be (I think) hidden.
I tried searching the repository code for the specific typo to create a PR but couldn't find it. It's probably in the closed source part of the app.

**Steps to Reproduce**
1. Reinstall the driver by opening Terminal and removing the driver
`sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/ `
2. Restart coreaudio
`sudo launchctl kickstart -k system/com.apple.audio.coreaudiod`

**Expected behaviour**
The word "hidded" should be (I think) hidden.

**Setup information:**
 - macOS Version: 12.6
 - eqMac Version 1.6.2
 - eqMac UI Version 4.3.1
 
**Screenshots or Console.app logs**

<img width="444" alt="image" src="https://user-images.githubusercontent.com/80286668/195208136-88af12e1-1484-47ba-ac98-877dbeb2989c.png">

**Comment by superjeng1** [comment]
Hi, yes you are right, it should be "hidden" and the typo is fixed now in the newer versions.
