### ISSUE TITLE
[Question] Assign Preset to Device?

### ISSUE THREAD

**Issue by davidmakesbeats** [bitgapp/eqMac#751]
Just wondering if it is, or would be, possible to have a functionality that allowed specific EQ presets to be assigned to different devices?

For example:  when I have my headphones plugged in, having the app recognize them and switch to the "Flat" or "Electronic" presets, but then when I remove my headphones, having it recognize the "built-in speakers" output and switch to "Bass Reducer" or a manual preset (trying to mitigate destroying my macbook pro speakers with anything <80hz)

Thanks for this amazing and long overdue app!

**Comment by ayozemr** [comment]
+1 I have a preset for speakers to reduce room resonance around 100hz but I use flat when using Airpods... So I was looking for a way to achieve this but seems its a feature request, so here we are!

**Comment by m4ttheweric** [comment]
+ 1

I came here looking for this specifically!

I have some speakers that are a bit treble heavy that connect via bluetooth and I'd like to be able to reduce the treble for that specific output device.

**Comment by joe-dir** [comment]
I was hoping this was already a feature, but I guess not. I have a headphone amp connected via USB and I would love for a specific Advanced EQ to be applied whenever it is selected as the output device.

**Comment by nodeful** [comment]
![Screenshot_20221223_053430_com.android.chrome.jpg](https://user-images.githubusercontent.com/8472525/209265941-09a7491f-771c-4e8a-ac2c-e183809c0ade.jpg)

**Comment by superjeng1** [comment]
Hi, super presets has already been implemented! Here is a comment where I explained the feature briefly. https://github.com/bitgapp/eqMac/issues/732#issuecomment-1616801192 Please update to the latest version and check it out! Thanks!
