### ISSUE TITLE
Bug: Sound started to clip when I boost to 200% Volume

### ISSUE THREAD

**Issue by mfaseehuddin** [bitgapp/eqMac#753]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [✅] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Following the new driver update, the sound clips and the volume lowers. It did not use to happen in the older version, and the low end of the sound is also quite dull now, where as it used to be better.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Go to 'EqMac'
2. Raise Volume to 200%
3. Play something
4. The sound clips

**Expected behaviour**
Like the previous version of the driver, at 200% volume, the sound of music and speech was amazing, and rich.

**Setup information:**
 - Audio device used for playback: MacBook M1 Air 2020
 - Audio transmission interface: Speakers
 - macOS Version: 12.6
 - eqMac Version: 1.6.2
 - eqMac Driver Version: 2.20

**Comment by superjeng1** [comment]
This is sort of unavoidable since this is what the boost feature does, it boosts the volume of the actual signal, and if the signal goes over 0dBFS, it would by definition "clip". Please let me know if you have any questions.
