### ISSUE TITLE
Cannot see Reflector 4 [http://www.reflectorapp.com]  in source app. Does not work for this source when receiving from iPhone13 IOS16.0.3.

### ISSUE THREAD

**Issue by gadleman** [bitgapp/eqMac#754]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):

**Expected behaviour**

**Setup information:**
 - Audio device used for playback: [eg AirPods or Macbook speaker or Bose QC32]
 - Audio transmission interface: [eq HDMI or Bluetooth or 3.5mm Jack]
 - macOS Version: [e.g. 10.15]
 - eqMac Version [e.g. 0.0.1] **(if audio related issue)**
 - eqMac UI Version [e.g. 0.0.4] **(if UI related issue)**

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**

**Comment by superjeng1** [comment]
Hi, you didn't change the issue body text to describe on what issue exactly that you are having. I have assumed you mean the Reflector 4 app doesn't appear in the "App Mixer" feature section in eqMac. I had verified that it does and the volume control does work. So I am closing this issue. If you have anything to add, please reply/comment on this and I would have a look at it.
