### ISSUE TITLE
Bug: Latency when monitoring in Logic Pro

### ISSUE THREAD

**Issue by dgwise** [bitgapp/eqMac#758]
Hi, was hoping to use EqMac to make my Sennheiser Momentum 4's not sound like complete shit in Passive Mode (powered off) to use as monitors when recording in Logic Pro (having them powered on produces latency, even when wired). 
The EQ in EqMac sounds fine, but it adds a latency of its own, which unfortunately defeats the purpose. Just wondering if this is expected, and/or if there's any solution to this? I tested out SoundSource as well for comparison, and while I don't like the interface as much and it costs $20, it has no detectable latency for me.

Thank in advance!

**Setup information:**
 - Audio device used for playback: Sennheiser Momentum 4
 - Audio transmission interface: Motu M2 for mic input, 1/8th jack for headphone output
 - macOS Version: 12.6
 - eqMac Version: 1.6.2

**Comment by superjeng1** [comment]
Hi, eqMac does add a bit of latency for processing the audio. To make sure the audio is reliable, we add a buffer to the process, which adds about 40ms of latency with 48kHz of sample rate. If you want to have the least latency, I would recommend adding "AUNBandEQ" to the monitoring chain of Logic Pro (I never used Logic Pro, but I think that is possible after a quick Google https://discussions.apple.com/thread/251460017) It is not as easy to use as eqMac but this AU plugin uses the same underlying library to do the EQ as eqMac. Please try this out. You can still use eqMac for general global EQ purpose of course. I hope this help! Please let me know how this goes!

**Comment by patrickrushton** [comment]
40ms latency? That's unfortunate. SoundSource is about 8ms on my system.
