### ISSUE TITLE
Can not install eqMac's driver as the button isn't shown on Ventura

### ISSUE THREAD

**Issue by owenzhao** [bitgapp/eqMac#759]
<img width="446" alt="截屏2022-11-22 12 14 00" src="https://user-images.githubusercontent.com/2182896/203219738-d4d48712-a81d-4533-87a0-3fcdb6d9d310.png">

As you can see, the button is beneath the window and can't be clicked.

**Comment by owenzhao** [comment]
Version 1.6.2. 
macOS Ventura 13.0.1.

**Comment by beakly** [comment]
Happened to me too
Version 1.6.2
macOS Monterey 12.6.1

Workaround for me was to quit eqmac and restart coreaudio:
```
sudo launchctl kickstart -k system/com.apple.audio.coreaudiod
```
On next launch eqmac's driver install dialog window will display the full window and the install button.

**Comment by superjeng1** [comment]
I think this is fixed in the later versions. And I think the workaround in the last comment would work. Please try it out if you are still having this issue, or reply/comment/reopen this issue.
