### ISSUE TITLE
Safari in app mixer

### ISSUE THREAD

**Issue by benfade** [bitgapp/eqMac#760]
**Describe the bug**
all audio sources are in the app mixer except for safari.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):

**Expected behaviour**
at least one slide fader for safari browser in the app mixer

**Setup information:**
 - Audio device used for playback: Traktor Audio 6
 - Audio transmission interface: USB cable
 - macOS Version: 13.0.1
 - eqMac Version 1.6.2
 - eqMac UI Version [e.g. 0.0.4] **(if UI related issue)**

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**
<img width="401" alt="Bildschirm­foto 2022-11-26 um 16 03 47" src="https://user-images.githubusercontent.com/119120889/204095463-260d6765-5c70-4f77-8a9d-0248828313cd.png">

**Comment by nodeful** [comment]
When you hover over the Icons that are question marks, what does the tooltip display? It will be something like com.company.app 
Please let me know

**Comment by benfade** [comment]
<img width="399" alt="Bildschirm­foto 2022-12-11 um 13 46 50" src="https://user-images.githubusercontent.com/119120889/206904394-69b8bd04-31de-4503-a451-3ad62eca8170.png">

this is what you get. it offers translating via Safari. but you cant really click that.

**Comment by superjeng1** [comment]
Hi, I believe this is fixed in the newer version of eqMac. Please update to the latest version and try it out.
