### ISSUE TITLE
[Question] Where is the eq settings located in finder?

### ISSUE THREAD

**Issue by braydenleung-Git** [bitgapp/eqMac#761]
So i just did a fresh install of the os into my MacBook and I didn't export the eq presets from the app before hand but I did had a time machine backup, is there a path or something that I can locate the eq settings I've made in the app?  inside the time machine disk ? thankyou

**Comment by LeeBinder** [comment]
Would appreciate to know, too 👍

**Comment by superjeng1** [comment]
Hi, it would be in `/Users/[your username]/Library/Preferences/com.bitgapp.eqmac.plist`
