### ISSUE TITLE
Can't install "driver"

### ISSUE THREAD

**Issue by plqu** [bitgapp/eqMac#764]
Man, I don't want to jump through a bunch of hoops, but just so you know, on Mojave your opening dialog looks like it wants to install something but there's no button because the dialog is too small to display the entire message. 

![image](https://user-images.githubusercontent.com/57424168/206983573-7279bbfb-daba-43ef-984f-8c09e1553b8b.png)

**Comment by LeeBinder** [comment]
That's just an image meant for depiction .. ;)

The actual window for input is in macOS 👍

**Comment by cubaLT** [comment]
Check issue #759 and answer https://github.com/bitgapp/eqMac/issues/759#issuecomment-1334487065

**Comment by superjeng1** [comment]
Hi, the workaround is provided by the issue linked in the previous comment so I am closing this issue.
