### ISSUE TITLE
microphone won't work when I answer a call on my Mac from my iPhone 

### ISSUE THREAD

**Issue by GaHub** [bitgapp/eqMac#766]
When answering a call on my Mac routed from my iPhone, I can hear the sound but the caller can't hear me speaking unless I kill eqMac

any help?

**Comment by HFX-93** [comment]
me too

**Comment by superjeng1** [comment]
Hi, this is a known issue in macOS with CallKit. The mic would become really quiet. This is called "ducking". We currently don't know why it was triggered, but we are finding ways around it. There is already a open issue #605 on this and we prefer to track the issue over there. Thanks!
