### ISSUE TITLE
Bug: Compatibility issue with MacOS Catalina on v1.7.0 or higher

### ISSUE THREAD

**Issue by Acorn9443** [bitgapp/eqMac#769]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Installing v1.7.0 or higher does not appear to be compatible with MacOS Catalina (version 10.15.6).

After installing eqMac and it's driver, the application launches normally. There is audio playing through the app but no EQ effects or other presets are working (no changes can be heard). 

Animated audio visualizer is also not seen when music is playing. 

This issue is true for both 1.7.1 and 1.7.0. 

Tested with older build v1.6.2 and all features working normal. 

**Expected behaviour**
All EQ features and visualizer functioning on latest version of eqMac 1.7.1

**Setup information:**
 - Audio device used for playback: Audio-Technica ATH-AD500X, DAC-X6 (FX Audio) 
 - Audio transmission interface: USB (DAC), 3.5mm headphone
 - macOS Version: 10.15.6
 - eqMac Version 1.7.1

**Additional information**
App works normally after installing older builds. V1.6.2 is working. I plan to update OS to BigSur soon and will update if issue is still OS specific.

**Comment by Acorn9443** [comment]
Also tested this without the DAC and plugged straight to headphone port but still the same issue was replicated.

**Comment by benfade** [comment]
confirming on catalina with 1.7.0., no effects or volume control.
downgrading to 1.6.2. was an easy fix

**Comment by LeeBinder** [comment]
downgrading an app is in general never a "fix" but merely a temporary work-around, until there _is_ a fix .. ;)

**Comment by benfade** [comment]
thank you for your wise words, downgrading did indeed fix the problem of eqmac not working.

**Comment by Jackxei** [comment]
yess i have the same iusse and how do i downgrade it

**Comment by Stafa2** [comment]
Same Issue here on 10.13.6 won't open at all after upgrade to newest version. Where I can find older versions ?
thanks

**Comment by Acorn9443** [comment]
> yess i have the same iusse and how do i downgrade it

You can find all releases here https://github.com/bitgapp/eqMac/releases

**Comment by Jackxei** [comment]
Tganks but i dowloaded the downgrade version and it still bring the new verstion?

**Comment by Acorn9443** [comment]
> Tganks but i dowloaded the downgrade version and it still bring the new verstion?

Be sure to scroll down far enough for 1.6.2 download from the releases page and do not accept auto update when launching the app.

**Comment by nodeful** [comment]
I'm looking into this now, very strange as I tested everything before the release and there were no complains during a Beta rollout. 
Will report back when I find something.
Apologize for the issues this has caused :(

**Comment by LeeBinder** [comment]
Catalina is not supported/ supplied with security updates by Apple anymore so is considered an unsafe and dying OS. There is no need to run it because with the Clover bootloader, newer versions of macOS even run on older Macs which Apple decided to block. @Acorn9443 by any means, upgrade to at least Big Sur, please!

Therefore @nodeful no need at all to apologize - no need for you to fix this, unless in an act of generosity, if you feel like it 👍

**Comment by nodeful** [comment]
@LeeBinder thanks for explanation of something I very much agree with :) There is no need nowadays to stay on older OS versions.

I did find the issue that was causing this: 
To better support latest versions of macOS I updated the SDK which completely broke the code library linking for older versions of macOS. I managed to fix it by embedding the libraries with the app itself, which will cause a slight increase in size of the binary but needs to be done to support older OS (which I'm still keen on doing because it's a little bit of work and is a slight competitive edge)
I will be releasing update v1.7.2 in the coming hours.

**Comment by nodeful** [comment]
Here's the release:
https://github.com/bitgapp/eqMac/releases/download/v1.7.2/eqMac.dmg

Can you please try it out and let me know if this has fixed the issue

**Comment by LeeBinder** [comment]
Good job. I do have a Catalinia test installation in which v.1.7.x stopped working, too, so can also test your new upcoming gem :)

**Comment by LeeBinder** [comment]
kudos Roman - v.1.7.2 confirmed working again in my "Catalina for testing" installation 👍 🥇

**Comment by Acorn9443** [comment]
@nodeful thank you so much! 

Updated to 1.7.2 and confirming app in now working like a dream on Catalina ✌️

**Comment by LeeBinder** [comment]
@Acorn9443 out of interest & curiosity: what makes you stick to Catalina? Some app that doesn't run anymore in current macOS?

**Comment by Acorn9443** [comment]
> @Acorn9443 out of interest & curiosity: what makes you stick to Catalina? Some app that doesn't run anymore in current macOS?

I run a non-apple PC build running macOS, aka a 'Hackintosh'. Nature of the build means updating OS is a bit more involved (updating and validating config.plist, Kexts, Drivers, etc) so I only do it when totally necessary out of laziness, lol 

I'll be updating to Big Sur in the coming weeks for work-related app requirements though.

**Comment by LeeBinder** [comment]
OK gotcha, thanks for shedding light on the mystery. Good luck updating your hack.
