### ISSUE TITLE
eqMac versions higher than 1.3.2 cut off first half-second of every sound (like a sleep mode)

### ISSUE THREAD

**Issue by ichbinJulien** [bitgapp/eqMac#771]
There actually already is a similar issue, but I'm unable to comment on it in order to provide my insights, so I'm opening a new issue instead. Maybe someone can merge it? I don't know, I'm new to GitHub.

The bug: For me, every version of eqMac higher than 1.3.2 is cutting off the first half-second of every sound that plays, as long as nothing is already playing. System notifications is where it's most notable, but it applies to every other sound as well. 
Interesting thing is, that as long as there's something else playing, the other sounds seem perfectly fine. So when I listen to music, system sounds play like normal, but when I stop the music, they get cut off again.

It's like eqMac is going into a sleep mode and just takes some time to wake up. I actually had the same thing happen on a JBL soundbar and it was infuriating enough for me to return it. Luckily, with eqMac, I can just revert to version 1.3.2 which still works like a charm.  Every new version, I'm crossing my fingers, hoping that this time around it will work just as well, but so far, no luck.

I'm using eqMac on a Mac Mini M1 on macOS Ventura 13.1 right now, but the same problem was present on previous versions. Sound is playing on my TV through HDMI, if that helps.

I do love eqMac and I don't want to miss out on it, I just wish this one issue could be resolved so I don't have to be stuck with version 1.3.2 all my life.

**Comment by superjeng1** [comment]
This seems like a duplicate to #739. I am closing this issue now and please comment on that issue if you like. Also please let me know if this issue is still happening in the latest version of eqMac. Thanks!
