### ISSUE TITLE
Problem with EQ (especially 8k slider)

### ISSUE THREAD

**Issue by U2GT** [bitgapp/eqMac#773]
Hello,

I just upgraded to the latest version on 12/24/22.  Something is different with the EQ.  I had a preset that I always use for music and when I was playing a few songs, something was not the same.  The sound was very tinny and awkward.  I can't quite describe it, but something changed in this update.

So I started to adjust the sliders on my preset.  I only had three adjustments from flat.  I had raised 4k, 8k and 16k.  After moving these again I noticed that they were no way too high whereas they were ok before.  The 8k slider is especially strange.  When I turn it all the way up, it not only boosts 8k, but it removes many other frequencies.  It's as if the Q value for 8k was lowered so that the slope of the filter is much wider and now affects many of the frequencies next to it.  So I had to lower the 4k, 8k and 16k frequencies compared to where they were set before.  In the last version, I could push the 8k all the way up, and it did not affect the other frequencies.

Maybe I missed something else that changed in this update.  

Thank you!

**Comment by superjeng1** [comment]
Hi, I am sorry that you are facing this issue. We had changed the bandwidth values of the bands internally to better match what other EQ software does. This provides more consistency across software and makes sharing profiles simpler. If you would like total control of what the filter does in terms of how wide and the exact position of the filters, you would have to use "Expert" EQ mode in the app. This is however a subset of "Pro" features within the app unfortunately. You could try out the pro features for unlimited times in five minute intervals, so you can see if that is what you wanted. I am closing this issue now, if you do have any questions, please reply/comment/reopen this issue, I would be here to help.

**Comment by U2GT** [comment]
Thank you for the explanation.
