### ISSUE TITLE
Updated today, eqMac no longer works

### ISSUE THREAD

**Issue by coryarmbrecht** [bitgapp/eqMac#774]
Now at:
App 1.7.1
Driver 2.3.0
UI: v4.4.1 (Remote)
macOS Catalina 10.15.7

Worked up until the update, the UI still works, but not actually changing any EQ; that's all I have to report. That and thank you for a cool audio utility!

**Comment by yakabay** [comment]
exactly same for me

**Comment by nodeful** [comment]
Can you please try this release:
https://github.com/bitgapp/eqMac/releases/download/v1.7.2/eqMac.dmg

**Comment by yakabay** [comment]
already answered in https://github.com/bitgapp/eqMac/issues/769
you can just downgrade to the old version: https://github.com/bitgapp/eqMac/releases

**Comment by unxmaal** [comment]
Confirming this problem on macOS Mojave 10.14.6, and confirming v1.7.2 resolves the issue.

**Comment by superjeng1** [comment]
Looks like this issue is solved. If this is not the case, please open another issue along with the details of it. Thanks!
