### ISSUE TITLE
Total crash after selecting a VST plugin with v.1.7.2

### ISSUE THREAD

**Issue by blackforest2014** [bitgapp/eqMac#777]
Thanks for the update v.1.7.2. The audio problem with Catalina 10.15.7 has been fixed.
Unfortunately, total crash after selecting a VST plugin. App can no longer be started or even after a reinstallation. Do I have to delete files manually for a complete reset of 1.7.2? if so, how and where?
I have now activated the stable version 1.6.2 again.

**Comment by nodeful** [comment]
Thank you for reporting this, I have came across this as well now. Will issue a fix very soon!

**Comment by blackforest2014** [comment]
Thank you for the quick reply. I am still enthusiastic about the eqMac in its basic functionality and use it every day! Good luck and happy 2023!

> Thank you for reporting this, I have came across this as well now. Will issue a fix very soon!

**Comment by nodeful** [comment]
Hey there, sorry I was ready to release a small fix for your specific issue but I like to bundle a couple more fixes when I'm doing an update and unfortunately those few extra fixes ended up taking too much time... I hope to release an update on Thursday or Friday

**Comment by nodeful** [comment]
Hey there,
I have published a Pre-Release of v1.7.3 that you can download here:
https://github.com/bitgapp/eqMac/releases/tag/v1.7.3
It may have fixed this issue that you've experienced.
Could you let me know if it's fixed or still persisting?

Thank you!

**Comment by blackforest2014** [comment]
thank you, I only see it now and will test it at the weekend and give feedback

**Comment by blackforest2014** [comment]
ok i uninstalled the 1.6.2 and the eqMac audio driver.
it was an error message that the eqmac audio driver is not installed and I get a macos report.
Should I send you this report.
I have now reinstalled the 1.6.2 and it is working

**Comment by blackforest2014** [comment]
Hi I did an OS upgrade to Ventura and the Version: 1.7.2 installed and runs without any problems. 
Thanks for your service :-)
