### ISSUE TITLE
Feature:missing EQ for HIFIMAN EDITION XS

### ISSUE THREAD

**Issue by waldi1992** [bitgapp/eqMac#781]
could you please implement the setting for HIFIMAN EDITION XS

https://www.reddit.com/r/oratory1990/wiki/index/list_of_presets/

https://www.dropbox.com/s/5st1w8rpe5iggwd/Hifiman%20Edition%20XS.pdf?dl=0

thank you

**Comment by nodeful** [comment]
It's already there:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/8472525/210906083-7bb53f1a-593d-4666-a126-962d4bc8db5a.png">
