### ISSUE TITLE
Bug: App Mixer Only Works with Apple Music

### ISSUE THREAD

**Issue by donCarlosOne** [bitgapp/eqMac#782]
**Disclaimer:** 

- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Purchased the Lifetime License the other day  One thing I was MOST keen on was controlling the volume of individual apps.  This only works for Apple Music, and nothing else - not even the System Volume.  Every other app is displayed, but changing the levels have no effect (particularly YT Music and WhatsApp).  Note that I've tried enabling/disabling all settings, re-installing, uninstalling-rebooting-installing - no difference.

**Steps to Reproduce**
1. Go to App Mixer
2. Click on the slider for System Volume (the first one). Slide down to 0%, Slide Up to 100%. No error, but no change to system volume either.
5. Click on the slider for Apple Music - it has a green bar indicating the current level - Slide down to 0% - volume level changes to 0%.  Slide up to 100% and volume level increases accordingly.
7. Click on slider for WhatsApp - green bar is not present  - Slide down to 0%, Slide Up to 100%. No error, but no change to system volume either.
8. Click on slider for YT Music - green bar is not present  - Slide down to 0%, Slide Up to 100%. No error, but no change to system volume either.
9.  Repeat for other open apps, such as Microsoft Edge, Google Chrome, etc - green bar is not present  - Slide down to 0%, Slide Up to 100%. No error, but no change to system volume either.

**Expected behaviour**
The whole point of an App Mixer is to control the volume of individual apps.  If all it can do is support Apple Music, why bother with having it at all?

 - Audio device used for playback: Lanchiya MK70 (identified as mvsilicon BT usb audio) AND MacBook Pro Speakers
 - Audio transmission interface: USB AND/OR Bluetooth (for Lanchiya) AND Internal for MacBook Pro Speakers
 - macOS Version: Ventura 13.1
 - eqMac Version [e.g. 0.0.1] 1.7.1

**Screenshots or Console.app logs**
![image](https://user-images.githubusercontent.com/2841617/211246785-912d4071-f838-4d23-8a35-831337d32065.png)

**Additional information**
I specifically purchased the lifetime license to be able to use the App Mixer capabilities.  If this cannot function, I would like a full refund.

**Comment by nodeful** [comment]
Hey @donCarlosOne 
Well you won't hear any effect until the audio starts playing, as the Audio is playing for Apple Music you hear the difference, but how can you tell if there's any difference for other apps? Can you record a video on your phone showing the problem so I can validate what is going on?

**Comment by nodeful** [comment]
Also not sure what Youtube Music app are you using, I can find an officially supported YT Music app for Mac

**Comment by nodeful** [comment]
Also try to run Safari and just go to YouTube so that Safari appears in the Volume Mixer and adjust the Safari Volume while your YT Music app is playing, you will likely find that adjusting Safari volume will in turn adjust the YT Music volume.
This happens because there's a lot of "apps" on the Mac that are just glorified websites in an .app container and they basically use a Safari WebView to play whatever media is playing, and unfortunately there's no way to distinct which playing webview is coming from which app :(

**Comment by nodeful** [comment]
https://user-images.githubusercontent.com/8472525/211431739-4d0d5c11-f824-4093-9cca-1acc0d5f8a45.mp4

**Comment by nodeful** [comment]
So it took me only 2 weeks of constant work to make this work correctly but it now finally works....
Will be releasing a Beta update soon

**Comment by nodeful** [comment]
Hey there,
I think I have fixed this in this release: https://github.com/bitgapp/eqMac/releases/tag/v1.7.3
Could you please try it out and let me know if this resolved the issue for you?

**Comment by superjeng1** [comment]
Hi, I as I believe this issue has been fixed, I would close this issue for now. If you are still experiencing this issue, feel free to reply/comment/reopen this issue. Thanks!
