### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by marcLeeroy** [bitgapp/eqMac#784]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
The app crashes randomly but more specifically when using an video/audio call application like slack or google meet. But sometimes i'm just using spotify and it just hangs or crashes all together.

**Steps to Reproduce**
1. Run slack (huddle) or google meet
2. Might stop working in the middle of it or not, depends from time to time

**Expected behaviour**
To not crash when these things are used.

**Setup information:**
 - Macbook Pro M1 speakers
 - Direct sound from the computer
 - macOS 13.0
 - app 1.7.2
 - ui 4.4.1

**Screenshots or Console.app logs**
No screenshot since it's a crash 

**Additional information**
Wish i could give you more info

Otherwise, very very good app.

**Comment by superjeng1** [comment]
Hi, there is some issues around calling in general, and I would prefer this issue to be tracked here #605. As for crashes, I think the latest version is more stable now, please try it out. If you still have crashing issues, please reply/comment/reopen this issue, thanks!
