### ISSUE TITLE
BUG: no volume slider control over brave browser

### ISSUE THREAD

**Issue by benfade** [bitgapp/eqMac#786]
<img width="369" alt="Bildschirm­foto 2023-01-12 um 23 09 34" src="https://user-images.githubusercontent.com/119120889/212191833-e4894112-8f2d-42bb-b243-ed023dfe4263.png">

all apps work and can be volume adjusted in the mixer except for brave browser. The slider moves up and down but does nothing to the level of this app

running M1 Mac on latest Ventura
interface: NI Traktor A6. no difference with other devices

**Comment by nodeful** [comment]
Hey there, thanks for reporting this.
Please try this Pre-release v1.7.3: https://github.com/bitgapp/eqMac/releases/tag/v1.7.3
I have changed the Audio Client calculations, this may have fixed the issue you're experiencing!

**Comment by benfade** [comment]
Hi, it seems it fixed the issue but I get random crashes when pause/playing in Brave now. Here are two crash reports.

￼￼

**Comment by superjeng1** [comment]
Hi @benfade , is this still an issue with the latest version of eqMac?

**Comment by benfade** [comment]
hi superjeng, Brave browser working now but another app wont show up anymore. It´s a live beat loop app called tablebeats in the app store

**Comment by benfade** [comment]
found it, had to restart the app. fine now

**Comment by superjeng1** [comment]
Hi, seems like you have solved the issue. I would close this now.
