### ISSUE TITLE
Bug: No volume control slider in app mixer for TheBrain

### ISSUE THREAD

**Issue by mtrifiro** [bitgapp/eqMac#787]
TheBrain is an app for the Mac that can be downloaded at www.thebrain.com. It has a built in web browser. Audio played inside the built in browser is not mixable or mutable in eqMac.

**Comment by nodeful** [comment]
Please try this release: https://github.com/bitgapp/eqMac/releases/tag/v1.7.3
I changed the way I'm calculating audio clients so it may have been fixed in this release!

**Comment by superjeng1** [comment]
Hi, I think the newer versions has fixed this issue. Please try the latest version out. If you are still having this issue, please reply/comment/reopen this issue.
