### ISSUE TITLE
allow the users the ability to manually input system levels 

### ISSUE THREAD

**Issue by TakeT04** [bitgapp/eqMac#788]
allow for users to be able to input the specified amount of shift under the bass, trebile, and mid. by clicking on the number and typing. similar to how users can alter the decibels under advanced, this would allow for an easier UI.

- create manual input.
- change user input levels in basic.
- allow users to type inputs by clicking on the current sound dB.

**Comment by nodeful** [comment]
Thank you for the suggestion, although Basic EQ was meant to be used with less precision I guess it doesn't hurt to add it.
I've implemented it and released as an OTA update, you should already see it working if you have OTA enabled :)
Just click on the dB value screen and you will see a menu show up where you can enter the gain:
![image](https://user-images.githubusercontent.com/8472525/215364248-5ae0122b-e69d-485e-bf2d-64827892d1f9.png)
