### ISSUE TITLE
Hi, Eq Not working with echo studio from Amazon

### ISSUE THREAD

**Issue by mbetan** [bitgapp/eqMac#790]
Hi, although it DOES recognize echo studio, it doesn't work when I listen to spotify.  Can you help? Thanks.

<img width="466" alt="Screenshot 2023-01-23 at 10 14 05" src="https://user-images.githubusercontent.com/65415250/214091016-178c9b7b-08b6-4141-8b9b-2491b75c70cd.png">

**Comment by superjeng1** [comment]
Hi, the newer versions has new logic around the App Mixer feature. Please check it out. I am closing this issue since I think the issue has been fixed. If you are still having this issue, please reply/comment/reopen this issue.
