### ISSUE TITLE
Bug: eqMac window always opens almost totally hidden on left side of screen

### ISSUE THREAD

**Issue by benvenker** [bitgapp/eqMac#791]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
- When initially opening eqMac, the app window flashes and then the app disappears
- When I click on the app icon in the dock, the window will appear but it is moved almost all the way off the screen, on the left side.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Open eqMac
2. See app window flash on screen, then disappear
3. Click on eqMac icon in the doc
4. See that window opens on the left side of the screen, almost completely off the screen

**Expected behaviour**
I expect the app window to open in a location that makes at least most of the app window visible on the screen

**Setup information:**
 - Audio device used for playback: M2 MacBook Air 13.6" with AirPods Max headphones
 - Audio transmission interface: Bluetooth
 - macOS Version: 12.6.1
 - eqMac Version v1.7.2
 - eqMac UI Version v4.4.1

**Screenshots or Console.app logs**

- **Video of behavior: https://cln.sh/DS8ghkmB**

![CleanShot 2023-01-23 at 13 35 07](https://user-images.githubusercontent.com/4605817/214122096-ddbbd6bc-c771-4e1d-865b-7e9c82de8c05.png)

**Additional information**

**Comment by nodeful** [comment]
Huh that's odd, yeah Window mode should be the default really, I will make this change for the next update. Is your Top Status Bar hidden?

**Comment by benvenker** [comment]
Yeah, I hide it by default, but also it's an M2 MacBook Air with the notched camera and I can't screenshot an area wider than that area of the screen and still include the status bar in screenshots.

**Comment by nodeful** [comment]
I have made Window the default UI Mode in v1.7.3 https://github.com/bitgapp/eqMac/releases/tag/v1.7.3
Wasn't able to replicate the behaviour that you've experienced even with Status Bar hidden...
Probably need to get a Macbook with a Notch to properly test it, I might get one soon.
Not sure if you want to keep this issue open or not?

**Comment by benvenker** [comment]
Sorry for the late reply. No, I'll close it with this comment. Thanks!
