### ISSUE TITLE
Enhancement: highlight top menu icons so that it’s clear what menu item is open

### ISSUE THREAD

**Issue by alexx187** [bitgapp/eqMac#792]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**My App Versions info:**
<img width="398" alt="image" src="https://user-images.githubusercontent.com/52873765/214645803-79f512c7-ec2e-4bea-9d9e-9355b47c9a32.png">

**Description:**

Currently when user clicks on buttons in the top right hand side of the window (announcements, account, help, settings) their icons don’t get highlighted in any way, thus making it hard to see what menu item is open.  See item 1 on the screenshot. Settings button clicked:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/52873765/214644435-e723c5ef-e99a-41a1-9da9-636529dba17f.png">

**User flow & interface:**
Ways to make it more clear what is active could be:
1) to inverse the colors on the active button’s icon, leaving the rest of the buttons’ icons intact. 
2) to grey out/blur out the main UI and controls that went to background (box 2 on the screenshot) after clicking a menu button, leaving only the active window and its controls clearly visible.

**Comment by nodeful** [comment]
Thank you for the suggestions, I have already released it with an OTA update and as part of v1.7.3 Pre-release:
![image](https://user-images.githubusercontent.com/8472525/215364133-98c548c2-bada-41fa-8f15-2c7d5d7f0aa4.png)
