### ISSUE TITLE
Balance percentages are not updated correctly when moving the slider

### ISSUE THREAD

**Issue by albgia** [bitgapp/eqMac#794]
Screenshot shows the Balance slider with both R/L at 100%

![Screen Shot 2023-01-26 at 8 35 45 PM](https://user-images.githubusercontent.com/5395985/214991225-7e37a6db-1d9d-4b64-9186-1e6d67e8f1d1.png)

**Comment by superjeng1** [comment]
Hi, I am closing this issue since I cannot replicate this issue on the latest version. If this is still an issue for you, please reply/comment/reopen this issue, thanks!
