### ISSUE TITLE
Audio delay in VLC?

### ISSUE THREAD

**Issue by MariuzM** [bitgapp/eqMac#8]
It might be a placebo but anyone else noticing slight audio delay in VLC with eqMac on?

**Comment by MariuzM** [comment]
Tried this test and i feel there is slight delay in audio in VLC using eqMac https://editorsean.com/articles/audio-video-sync-alignment-latency-test/

**Comment by c-bandy** [comment]
I get a consistent 1 second audio delay in general. I think its due to the nature of how this program works: Capturing a buffer of system sound and then modifying it, and playing it back on a separate output.

It would be great if it was possible to avoid this.

**Comment by c-bandy** [comment]
Actually, scratch that. It seems it desyncs over time for me and that's what I'm experiencing.

**Comment by nodeful** [comment]
In theory should be possible to have no delay what so ever, but I need to do a lot of research how to make that happen

**Comment by Sciman3** [comment]
I just noticed the same thing today with Quicktime too, so I don't think it's limited to VLC.

**Comment by pjft** [comment]
Yup. Especially when having audio calls at work it becomes extremely noticeable, and it does seem to increase the de-sync over time.

eqMac2 doesn't _seem_ to have that, but I'll let you know otherwise.

**Comment by nodeful** [comment]
I have just released a new version v0.0.1 - Download from https://eqmac.app or from GitHub
I tried removing as much delay as I possibly can for the moment.
Can you please test and report back if there's still an issue. Thank you

**Comment by MariuzM** [comment]
Much better now

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
