### ISSUE TITLE
Bug: Bitrate changes in tracks cause garbled audio

### ISSUE THREAD

**Issue by dconlon-wagetap** [bitgapp/eqMac#802]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When using Qobuz, with the output selected as Schiit Modi+3 (eqMac), if there is a bitrate change between tracks then the track on the new bitrate comes through as garbled. When the output's bitrate remains the same there is no issue.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Open Qobuz
2. Select output device "Schiit Modi+3 (eqMac)"
3. Play track at some bitrate e.g. 16bit/44.1kHz
4. Select & Play a different track at a different bitrate e.g. 24bit/44.1kHz
5. Experience jumbled and garbled audio

**Workarounds**
Switching to a different output device, then back to the (eqMac) version resolves the issue.

**Expected behaviour**
Switching between tracks of different bitrates should not cause garbled audio output.

**Setup information:**
 - Audio device used for playback: Headphones, but not relevant here
 - Audio transmission interface: Macbook Pro -> USB -> Schiit Modi 3+ -> Vali2 Amp -> Headphones
 - macOS Version: 12.6.3 (Monterey)
 - eqMac App: v1.7.2
 - eqMac Driver Version: v2.3.1 
 - eqMac UI Version: v4.4.9 (Remote)
 
Tested to not work on the Schiit Modi 3+ and the Schiit ModiMultibit 2 - same behaviour on both.

**Additional information**
My guess is that whatever header that communicates the bitrate spec is missing when going through eqMac. So problem between Qobuz and eqMac, or between eqMac and the Mac audio system, or some weird USB encoding issue under bitrate changes. Depending on the DAC I suspect the outcome is different - Schiit dacs probably garble, others probably go silent. This may be related to https://github.com/bitgapp/eqMac/issues/520

**Comment by dconlon-wagetap** [comment]
Digging a bit deeper in the issues, seems like this has been a consistent issue for a long time - albeit reported in different ways. Bitrate changes causing potentially causing a lot of glitches.

https://github.com/bitgapp/eqMac/issues/752
https://github.com/bitgapp/eqMac/issues/520
https://github.com/bitgapp/eqMac/issues/730 <= maybe? is sample rates are different
https://github.com/bitgapp/eqMac/issues/599 <= maybe?
https://github.com/bitgapp/eqMac/issues/576 <= maybe?

**Comment by nodeful** [comment]
Hey there.

Thank you for the very detailed report and the work you went through digging through old reports.
This issue was one of my main focuses on the latest update that I just released to Beta testers:
https://github.com/bitgapp/eqMac/releases/tag/v1.7.4

Can you try out this release and let me know if the issue with Sample Rate switching performs well now :)

**Comment by dconlon-wagetap** [comment]
Thanks! Initial testing is good, it looks like App:v1.7.4 Driverv2.4.0 have fixed the glitching issue.

**Comment by superjeng1** [comment]
Looks like this issue has been fixed, I would go ahead and close this issue right now.
