### ISSUE TITLE
Bug: No volume unless bypass enabled after previous update

### ISSUE THREAD

**Issue by natpelino** [bitgapp/eqMac#804]
**Describe the bug**
Since the most recent update, while running eqMac, volume only plays with bypass enabled. With bypass enabled, volume will only play (for less than one second) when switching the output source or clicking the 'Reset Audio Engine' button.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Does not matter if audio is playing before or after eqMac is opened
2. audio will stop, but progress bar on music apps will continue to move
3. enable bypass for audio to resume
4. OR, click 'Reset Audio Engine' or change output source for audio to resume for one second, then stop again

**Expected behaviour**
For audio to play as normal and allow me to use eqMac as intended

**Setup information:**
 - Audio device used for playback: Logitech desktop speakers OR various bluetooth headphones/earbuds
 - Audio transmission interface: 3.5mm Jack OR Bluetooth
 - macOS Version: Ventura 13.2 (b)
 - eqMac Version (Driver): 2.4.0
 - eqMac Version (App): 1.7.4
  
**Additional information**
I have been using the free version of eqMac for a few years now, and this is the first time I have ever had any sort of issue with the application.

**Comment by Hickory420** [comment]
+1, I am having this exact same issue. The bug described is identical to my experience.

**Comment by Hickory420** [comment]
I fixed it. Well, this worked for me. I removed any and all files/directories relating to eqMac. I have, however, lost all of my presets because of this. :( 

Make sure you export them before doing this! I wish I did...

```bash
# Delete the app
rm -rf /Applications/eqMac.app

# Delete the audio driver
sudo rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/

# Delete all of this output
# Take care of the directory names with spaces in them. They won't get deleted with this command.
sudo find /Users/${USER}/Library -iname "*eqmac*" | xargs sudo rm -rf

# I had to change directory to remove this one for some reason
cd "/Users/${USER}/Library/Application Support/"
sudo rm -rf com.bitgapp.eqmac
```

Keep running the `find` commands until there is nothing left. Quit (not stop) anything that would be using your audio driver (spotify/youtube web browser, for example).
Then reinstall (I use `brew install eqmac`).

Now I need to set up all of my eq presets again :/

Hope this helps others.

**Comment by strppngynglad** [comment]
+1 really would like a fix that doesnt require complete install

**Comment by aluchaninov** [comment]
@Hickory420 thanks for instructions. Helped in my case as well ;)

**Comment by superjeng1** [comment]
Seems like cleaning eqMac up and reinstall it worked. I would close this issue for now.
