### ISSUE TITLE
UI Freezes when using Advanced EQ Impoprt

### ISSUE THREAD

**Issue by infdaze** [bitgapp/eqMac#805]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [X] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
I'm importing what I believe is a correctly formed JSON with acceptable values. The preset is imported successfully but when I click on it in the list, the entire UI freezes (and no audio change occurs)

**Setup information:**
 - Audio device used for playback: External speakers using built-in audio jack
 - Audio transmission interface: 3.5mm
 - macOS Version: 13.2
 - eqMac Version 1.7.4
 - eqMac UI Version 1.7.4

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**
Json is as follows (filename is "new hd6 mira.json"):
[{"id":"69","isDefault":false,"bands":[{"type":0,"gain":10,"bandwidth":1,"bypass":false,"frequency":40},{"type":0,"gain":-4.2,"bandwidth":6.077,"bypass":false,"frequency":45},{"type":0,"gain":9,"bandwidth":7.396,"bypass":false,"frequency":62},{"type":0,"gain":10,"bandwidth":5.297,"bypass":false,"frequency":95},{"type":0,"gain":-10,"bandwidth":4.332,"bypass":false,"frequency":135},{"type":0,"gain":-4,"bandwidth":8.342,"bypass":false,"frequency":155},{"type":0,"gain":-9.4,"bandwidth":1,"bypass":false,"frequency":253},{"type":0,"gain":8.3,"bandwidth":5.376,"bypass":false,"frequency":385},{"type":0,"gain":-2.9,"bandwidth":1,"bypass":false,"frequency":948},{"type":0,"gain":-6.7,"bandwidth":3.202,"bypass":false,"frequency":4000}],"name":"New HD6 Mira","global":0}]

**Comment by nodeful** [comment]
This doesn't look like a correct preset format for Advanced EQ.
Here's a comparison of a Preset I exported from Advanced EQ and the one you've posted:
![image](https://user-images.githubusercontent.com/8472525/216842331-765a3663-efbb-4ec0-b6ee-baffbc8e5b85.png)

The one that you posted looks more like Expert EQ:

![image](https://user-images.githubusercontent.com/8472525/216842470-af6b3942-df1f-4f1a-bb00-921192731c0a.png)

I'm planning to add REW presets support into the next update so it should become much easier to share presets between all the apps.

**Comment by nodeful** [comment]
Discussed over Discord, fixed, pushed, confirmed working, so closing :)
