### ISSUE TITLE
EQ for Mac won't open and sits ideal in activity monitor

### ISSUE THREAD

**Issue by ThaStache** [bitgapp/eqMac#808]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
EQ for Mac will not open, and sits ideal in activity monitor

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
open eq for mac

**Expected behaviour**
to open and start eq'ing my system

**Setup information:**
 - schitt audio modious
 - Woo Audio WA\7
 - USB
 - macOS Version: 13.2
 - eqMac Version [most current
 - eqMac UI Version most current

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 
![Screenshot 2023-02-10 at 9 39 13 AM](https://user-images.githubusercontent.com/50588273/218133641-532b62fb-42b5-48ce-9af3-08ef5bdbcc51.png)

![Screenshot 2023-02-10 at 9 39 31 AM](https://user-images.githubusercontent.com/50588273/218133656-5d47c958-ca07-4cc3-b85e-b9dc1256aaa5.png)

console.app logs
[eqMac.pdf](https://github.com/bitgapp/eqMac/files/10709065/eqMac.pdf)

**Additional information**

**Comment by superjeng1** [comment]
Hi, this is related to #578. I would close this issue right now, please refer to that issue in the future. Please try to switch networks and see if the UI shows up.
