### ISSUE TITLE
Bug: AUHostingService (PID 734) and eqMac not responding when installing any 1.7.x version

### ISSUE THREAD

**Issue by dudeon41** [bitgapp/eqMac#816]
I've tried a few different 1.7.x releases and get the same issue with all of them (no issues on 1.6.2 or previous). As soon as I install the upgraded version, eqMac will not respond (beach ball over menu bar icon and Not Responding shown in Activity Monitor). Also the process "AUHostingService (PID 734)" shows as Not Responding in Activity Monitor and it's memory usage will be 1GB+.

Only way I've found to fix it is just to uninstall and downgrade to 1.6.2, which is the most recent version that works for me.

Setup information:
 - Audio device used for playback: Macbook speakers or Focusrite Scarlett 2i2 audio interface to Yamaha HS7 monitors
 - Audio transmission interface: Macbook speakers or USB-C to audio interface
 - macOS Version: Ventura 13.2.1 on M1 MBP
 - eqMac Version: All 1.7.x releases

Any help would be appreciated. Thanks!

**Comment by nodeful** [comment]
AUHostingService is only spawned if you added Extra Effects (AU PlugIns) to the audio chain.
Do you remember adding any specific Effects?

**Comment by dudeon41** [comment]
I didn't add any effects, but a while back I did install Blackhole (https://github.com/ExistentialAudio/BlackHole) to be able to record the computer audio while screen recording and I'm wondering if that's the issue. "Blackhole 2ch" and "Multi-Output Device" both show up as output options to choose from in eqMac.

I went to try and uninstall Blackhole to see if that would fix it, but the uninstaller didn't work and when trying to uninstall it manually the program files and driver were not in the directories they were said to be (uninstall instructions: https://github.com/ExistentialAudio/BlackHole/wiki/Uninstallation) so now I'm not even sure what to do.

**Comment by dudeon41** [comment]
Just tried updating again to the newest version and I'm still having the same issue. Any ideas?

**Comment by superjeng1** [comment]
Hi, since this is quite old I am closing this issue. The service mentioned is only started when there are effects in "Extra Effects". Otherwise it might be some other processes using the service. Please reopen this issue if you are still experiencing this issue.
