### ISSUE TITLE
eqMac causes speakers to POP when waking from sleep

### ISSUE THREAD

**Issue by lobuzz311** [bitgapp/eqMac#817]
I have my audio output through HDMI, and every time the computer wakes from sleep, the speakers POP really loudly. This does not happen when eqMac is not enabled, and the audio is going through the same HDMI output.

**Comment by jacobweberbowery** [comment]
I'm having a similar issue, using a USB audio device (UA Volt 2). Happens whenever the Mac starts up. OS 13.3 on a MacBook Pro.

**Comment by superjeng1** [comment]
Hi, I remembered having this issue, however I haven't encountered it for quite a while so I would assume this has been fixed. If this is not the case for you, please reopen this issue and comment on it. Thanks!
