### ISSUE TITLE
Bug: Webex audio from audience is routed into Microsoft Teams microphone input when using eqMac

### ISSUE THREAD

**Issue by bharatrajagopalan** [bitgapp/eqMac#824]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.

[x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
I use eqMac to balance volumes between Cisco Webex and Microsoft Teams when I am attending two meetings at the same time to control volumes between the two. It has been confirmed that speaker audio from one application is getting routed into the microphone input of the other-  specifically in this case Webex speaker audio -> teams microphone input. 

This makes the app basically unusable for my usecase.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Start two meetings on Webex and Teams
2. ensure that both are using eqMac for audio and microphone
3. When Webex audience speaks, the teams audience hears their audio in the background

**Expected behaviour**
Webex and Teams audio is to be completely isolated.

**Setup information:**
 - Audio device used for playback: Headphones
 - Audio transmission interface: 3.5mm jack
 - macOS Version: 13.2.1
 - eqMac Version 1.7.10
 - Driver Version 2.4.3
 - eqMac UI Version 4.6.3 

**Screenshots or Console.app logs**
N/A

**Additional information**
N/A

**Comment by superjeng1** [comment]
Hi, can you make sure what microphone is selected in both apps?

**Comment by bharatrajagopalan** [comment]
@superjeng1 

> Hi, can you make sure what microphone is selected in both apps?

In my steps to reproduce, I do state 
_ensure that both are using eqMac for audio and microphone_

Does that answer the question?

**Comment by superjeng1** [comment]
@bharatrajagopalan Hi, the eqMac mic would output what eqMac gets from the input. You should select your real mic in a call.

**Comment by bharatrajagopalan** [comment]
@superjeng1  
> You should select your real mic in a call.
OK will give it a try

> the eqMac mic would output what eqMac gets from the input_

I think I understand - you are saying that anything that is sent to eqMac for processing (including output audio from one of the applications - which is why the faders work to reduce volume) become part of eqMac "input".

Makes sense now - I had simply thought the eqMic "input" was simply a representation of device inputs.

Closing this issue

**Comment by superjeng1** [comment]
Glad to hear you figured that out. Note that the eqMac mic outputs exactly what it gets, so it's before any processing and EQ.
