### ISSUE TITLE
Not even launching anymore

### ISSUE THREAD

**Issue by Half-N0te** [bitgapp/eqMac#825]
Title says it all, since the last update (I guess) I can't even launch EqMac anymore.

Still using a MacBook Pro M1 Pro 10/16 and Ventura 13.2.1

**Comment by Lida-Chen** [comment]
MacBook Pro M1 Pro 10/16
Ventura 13.2.1
cannot launch

**Comment by lukinsb** [comment]
Same for me, it launches and then freezes
Ventura 13.2.1
Macbook Pro M1

**Comment by takethecan0lis** [comment]
Same issue for me.  When I try to load I get a blank white screen

13.2.1 (22D68)
Macbook Pro M1 Max

**Comment by nicoarcu** [comment]
Same here, 

Ventura 13.2.1
Mac Mini M1

**Comment by JiDey247** [comment]
Same here since weeks

Ventura 13.2.1
M1 Max MBP16

**Comment by liamd101** [comment]
Ventura 13.2.1
M2 MacBook Air

**Comment by rjbunge99** [comment]
Same here.

**Comment by superjeng1** [comment]
Hi, are you getting a white screen or the app crashes on start?

**Comment by d-karstens** [comment]
Unsure if it's the same issue, but mine also stopped launching for a long time (no white window or crash, just seemed to hang in the background) and I was able to get it working again by reinstalling the app

M1 Pro 13.4.1

**Comment by superjeng1** [comment]
Interesting, as reinstalling could fix this, I would close this issue now. If you are still having this issue, either reopen this issue, or create a new one with the details filled in. Thanks!
