### ISSUE TITLE
Audio completely broken after eq crashed for the 5th time today

### ISSUE THREAD

**Issue by ktleary** [bitgapp/eqMac#828]
Beyond the usual 5 eqMac crashes a day on my M1 Air, today after it the last crash, the system audio no longer works, just gives you the audio sign with a line through it. 

matrix:Music user1$ ps -ax | grep -i eqm
22271 ??         0:00.01 /bin/bash -c (if [[ ! -d "/Library/Audio/Plug-Ins/HAL" ]]; then rm -rf /Library/Audio/Plug-Ins/HAL && mkdir -p /Library/Audio/Plug-Ins/HAL && chmod 755 /Library/Audio/Plug-Ins/HAL && chown -R root:wheel /Library/Audio/Plug-Ins/HAL; fi) && (rm -rf /Library/Audio/Plug-Ins/HAL/Contents) && (rm -rf /Library/Audio/Plug-Ins/HAL/eqMac.driver/) && (cp -f -r "/Applications/eqMac.app/Contents/Resources/Embedded/eqMac.driver" /Library/Audio/Plug-Ins/HAL &>/dev/null) && (launchctl kickstart -k system/com.apple.audio.coreaudiod) && (sleep 1) && (killall SystemUIServer || true) && (killall ControlStrip || true)

**Comment by superjeng1** [comment]
Hi, I am not sure what I am seeing in the command that you typed. It looks like a script you ran that is running. I am closing this issue now because the description is too vague. If this is still a bug that is happening to you, please comment/reply and reopen this issue. I would look into it.
