### ISSUE TITLE
Enhancement: Ability to remove default presets in Advanced EQ mode 

### ISSUE THREAD

**Issue by stupid-user-name** [bitgapp/eqMac#833]
There are so many Advanced EQ presets. I only need 4. Two for headphones and two for speakers. I can't find my 4 in the long list that includes so many useless defaults. How do I delete the useless defaults? Can I delete the useless defaults?

**Comment by superjeng1** [comment]
Hi, you can hide the default presets by going to the settings of "Advanced EQ" (on the left of where you select "Advanced"), then uncheck "Show Default Presets". Please reply if you have any questions regarding this, thanks!
