### ISSUE TITLE
Feature: Update AUTOEQ Headphone Presets

### ISSUE THREAD

**Issue by mikhail-ru** [bitgapp/eqMac#839]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
The app is built with LEGACY presets.
The presets were updated and the old ones are moved to the LEGACY folder. https://github.com/jaakkopasanen/AutoEq/tree/f624f4f7d0cfaf702fb206827abb5a54cf6be6ba/results/Headphone.com%20Legacy
The app provides links to presets that are not in the folder.
Example: https://github.com/jaakkopasanen/AutoEq/tree/master/results/headphonecom/headphonecom_harman_over-ear_2018/Koss%20SportaPro?referrer=eqMac&referer=eqMac&utm_source=eqMac

**User flow & interface:**
No updates. Regular headphones button usage.

**Comment by superjeng1** [comment]
Hi, according to this [list](https://github.com/jaakkopasanen/AutoEq/blob/master/results/README.md) in their repo, the recommended result for the "Koss SportaPro" headphone is the new Legacy folder mentioned. And I can verify that the database built-in to eqMac is outdated. We are now looking into updating it. Thanks!

**Comment by superjeng1** [comment]
Hey there, good news, the AutoEQ presets were updated in UI version 4.7.0 which is available right now. Please check it out.
