### ISSUE TITLE
Selection son eqmac dans la capture quicktime

### ISSUE THREAD

**Issue by Ph-P37** [bitgapp/eqMac#841]
Depuis la mise à jour, la capture ecran via quictime ne fonctionne plus. Le son eqmac est bien reconnu, il est visible visuellement si je choisis "enregistrement audio" (diodes actives) mais lors de l'écoute du fichier, il n'y a plus rien. cette fonction fonctionnait encore il y a un mois. Quelque chose a t il changé ?

**Comment by superjeng1** [comment]
Hi, please select the eqMac device as the mic. I just tried it and it works. If you have any questions, please reply/comment/reopen this issue.
