### ISSUE TITLE
Feature: Ability to hide Dock Indicator when GUI is closed

### ISSUE THREAD

**Issue by BigBrainAFK** [bitgapp/eqMac#849]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
I would love a simple checkbox or similar to disable the Dock activity indicator when the app runs closed to the systembar icon.

**User flow & interface:**
As mentioned above a simple checkbox or system bar dropdown option (or anything similar really) to enable/disable this.

**Comment by superjeng1** [comment]
Hi, do you mean the eqMac icon in the dock? You can hide it by going to settings (it could be accessed by clicking the wrench icon on the top right corner of eqMac), then select "Status Bar" for "Icon Placement".

If I misunderstood your problem, please reply and reopen this issue so we can work this out. Thanks!
