### ISSUE TITLE
Bug: Login fail using magic link method

### ISSUE THREAD

**Issue by pikerflinn** [bitgapp/eqMac#850]
Have repeatedly tried to log in to my account and get a magic link sent, but the site says my email is already in use. I initially logged out of the app, thinking this was causing it, but still keep getting the same message.

Since I cannot get a magic iink sent, I can no longer use eqmac, which is a tad disappointing, given I'm a subscriber. I've always used this method for loggin in, but do wish I'd set up my own password - stuck in a rut now. 

How do I get this sorted please?

**Comment by pikerflinn** [comment]
This has been closed without a response to me? Why?

**Comment by nodeful** [comment]
Hey Peter,

Looks like you were the one closing and reopening this issue:
![image](https://github.com/bitgapp/eqMac/assets/8472525/5360b49d-7e75-4ffd-8b2d-db4fa3f11f62)

I have sent you and email with further instructions :) Let's continue the conversation there!
