### ISSUE TITLE
iPhone Mobile App

### ISSUE THREAD

**Issue by U2GT** [bitgapp/eqMac#851]
Your app is fantastic.  Could you build one for the iPhone.  I've tried several in the app store and none work well.  The iPhone needs exactly what you provide on the Mac.  Thank you!

**Comment by superjeng1** [comment]
Hi, this is impossible. Reason being iOS does not provide any method of capturing the system audio and processing it. If we were to make an iOS app, it has to be a media player/streamer or a remote controller for eqMac. I will close this issue now since this is unfortunately not possible yet.
