### ISSUE TITLE
Bug: Airplay broken, uninstall did not repair. MacOS reinstall did not repair.

### ISSUE THREAD

**Issue by stackk1** [bitgapp/eqMac#856]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
After uninstalling eqmac and driver I am unable to airplay to HomePod from control centre. was working prior to eqmac install

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. install eqmac
2. un install eqmac
3. play audio
4. open control center
5. open sound
6. select HomePod as output
7. macOS and HomePod both indicate that they have connected and that audio is playing but no sound will come from HomePod. 

**Expected behaviour**
Removal of eqmac should restore macOS to default audio behaviour

**Setup information:**
 - Audio device used for playback: [MacBook Pro 14, iPhone 12 mini (to confirm homepod is otherwise functional), HomePod mini]
 - Audio transmission interface: [AirPlay]
 - macOS Version: [e.g. MacOS 14 Sonoma]
 - eqMac Version [latest as of post] **(if audio related issue)**
 - eqMac UI Version [latest as of post] **(if UI related issue)**

**Screenshots or Console.app logs**
No reference to eqMac in Console.

**Additional information**

**Comment by superjeng1** [comment]
Hi, HomePods uses AirPlay 2 and eqMac does not currently support that. This is an duplicate to #390 so I am closing this issue now. Please track the progress over there.
