### ISSUE TITLE
Input drops to almost nothing when using FaceTime

### ISSUE THREAD

**Issue by fluffyemu** [bitgapp/eqMac#857]
Hi, I downloaded eqMac to try to boost the volume when I use FaceTime. However, my input disappears to almost nothing when I turn eqMac on, according to the people I'm talking to. I am just using my built-in speakers/microphone, and don't really want to use earbuds/headphones. Is there a way to make it so that my regular built-in microphone works on FaceTime with eqMac enabled to boost the output volume?

**Comment by superjeng1** [comment]
Hi, this is a known issue that we are trying to fix. There is already an open issue regarding this. #605 So I am closing this issue as it is duplicate to that.
