### ISSUE TITLE
Bug: pro license is not uinlocking pro features on app on new computer

### ISSUE THREAD

**Issue by stabbotco1** [bitgapp/eqMac#880]
Bug description:
Old computer is replaced and scraped.
New mac m2 has eqMac installed
Logging in and applying pro licnese does not result in app becoming usable
Emails to support go unanswered

**Comment by oskarsh** [comment]
Similar problem here. Did you buy the 1 lifetime license only? It might be the case that its registered to your old pc.

Is there a way to transfer licenses? I got rid of my old mac and was very surprised to find my lifetime license not working.

**Comment by BradSiegler** [comment]
I am also having this issue. I downloaded today, signed up for the pro plan, created a license online for my mac, and went into the app's UI and clicked "generate license" to no avail... Frustrating to put it nicely.

**Comment by nodeful** [comment]
Guys you can just edit the License serial number on your account page: https://eqmac.app/account
And it will generate you a new License for your new Mac:
<img width="707" alt="image" src="https://github.com/bitgapp/eqMac/assets/8472525/0c5b514a-dbd7-45c7-b5a2-ceae9a72d6ce">

Just click the Edit pencil button and copy paste your serial number to transfer:
<img width="287" alt="image" src="https://github.com/bitgapp/eqMac/assets/8472525/a0e1ae09-54ba-459f-b850-1b69fbd8583e">

I'm sorry this inconvenience and miscommunication on my part. I'm currently working on an update to bring this into the eqMac app itself and also working on Helpdesk articles to improve the communication about this.
