### ISSUE TITLE
Bug: Can't see button to install drivers, popup too small

### ISSUE THREAD

**Issue by HadrienKulik** [bitgapp/eqMac#883]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Cannot click on "install driver" as the popup is too small, and can't be resized or scrolled.
Can't clic kon anything, keyboard has no effect either. Completely stuck on that screen.

**Steps to Reproduce**
Install eqMac
Get that screen
![image](https://github.com/bitgapp/eqMac/assets/1494897/1cec2d44-e8f5-4ef2-9269-4c990c958928)

**Expected behaviour**
See the entire screen, be able to scroll or resize. Be able to press ESC or ENTER.

**Setup information:**
 - macOS Version: 13.5.2 (22G91)
 - eqMac UI Version : can't see it, but I just reinstalled it with latest version as of time of posting.

**Additional information**
I have been using eqMac pro for a while. I don't know why I'm getting this message to install drivers again, and get stuck on that page.

**Comment by ragauskl** [comment]
There have been some fixes to UI, do you still experience same issue with v1.8.7?

**Comment by HadrienKulik** [comment]
I think it's fine now, yes
