### ISSUE TITLE
How to import presets?

### ISSUE THREAD

**Issue by magwa101** [bitgapp/eqMac#889]
I generated a JSON preset file using autoEqMac. That is because the headphone I have, HIFIMAN Nano is not listed.

However, nowhere on the interface can I find a place to import a downloaded preset.

Thanks

**Comment by ragauskl** [comment]
Presets can be imported in EQ settings left of Basic/Advanced/Expert selection 
<img width="398" alt="image" src="https://github.com/bitgapp/eqMac/assets/9280160/cd063c0f-4c02-484d-8240-65be17a333af">
<img width="395" alt="image" src="https://github.com/bitgapp/eqMac/assets/9280160/5b214f4f-9baf-4a4e-bfb2-9410899d50fc">

**Comment by mikhail-fedosenko** [comment]
@ragauskl i'm trying to import a preset using a trial mode in v1.8.11. I've found the "Import" button, but clicking on it gives me nothing - nothing is displayed, nothing happens at all... same happens for "Export" button.

<img width="427" height="461" alt="Image" src="https://github.com/user-attachments/assets/cbfefa5e-ef82-4aba-bb0b-09d97de27760" />

The system didn't ask to allow access to file system, so I suppose there is a culprit somewhere in that place...

**Comment by ragauskl** [comment]
Also, try switching to 'Advanced' equalizer and try clicking Import/Export there with and without the trial mode, see if that works and let me know if it doesn't

**Comment by mikhail-fedosenko** [comment]
I've noted the version of eqMac in the original message, it's 1.8.11
macOS 15.6.1 (24G90) (latest too).
I've tried importing/exporting in "Advanced" equalizer - it worked (at least, the Finder opened, i don't have correct JSON file at hand).
I've switched to "Expert" eq in the same run - it didn't work...
Attaching screen recording: https://www.dropbox.com/scl/fi/0q028zouj6zvjfvwsin8e/2025-09-06-12.22.00.mov?rlkey=g1chn995jt2x6v4f6jgm9dvp7&st=xyzx22t2&dl=0
