### ISSUE TITLE
Bug: eqMac has disappeared from the Menu Bar, with no way to open the app at all

### ISSUE THREAD

**Issue by daveidivide** [bitgapp/eqMac#899]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
I am finding since the latest Mac OS release, the eqMac item no longer appears in the menu bar at the top.
I have always had it in the mode that eqMac only appears in the Menu Bar.

Because of this, I can no longer access eqMac. 

Things I have tried:

- Quitting eqMac with Activity Monitor and then restarting
- Restarting my Mac.
- Reinstalling latest eqMac.
- Removing other items from my menu bar (in case the issue was I had too many items)
- I have gone into my Control Center settings and nothing appears to fix. eqMac is not an option in there.

I would happily run the app as an item in my dock at the bottom of the screen, but I cannot even open the app to change this setting.

**Comment by declark** [comment]
I'm having the same issue. I tried similar steps to resolve the issue.

**Comment by nodeful** [comment]
Can you open eqMac if you Cmd + Space and search for eqMac.app
Or open it from the Applications directory and then go to Settings and tell me which Icon Placement is set:
<img width="410" alt="image" src="https://github.com/bitgapp/eqMac/assets/8472525/8a9fc31b-26c6-4af1-8291-0ea3b4fa1f5c">

It should be either Both or Status Item for the icon to appear on the top bar

**Comment by declark** [comment]
@nodeful it won't open at all. It was set to "Status Bar" previously.

**Comment by nodeful** [comment]
Do you have any crash reports related to eqMac or CoreAudio in Console.app? (under Crash Reports tab)

**Comment by nodeful** [comment]
Also what if you use Exposé (like the 4 finger up motion on the trackpad or the Function button (for me it's F3)) do you see the window appear?

**Comment by daveidivide** [comment]
Using 4 finger thing:
![image](https://github.com/bitgapp/eqMac/assets/7994685/72643ff8-2726-4c99-9828-82b6d69c548b)

I can see that eqMac is running through activity monitor
![image](https://github.com/bitgapp/eqMac/assets/7994685/58c4296a-4b2d-4115-842d-203a1d874005)

How do I find these crash reports? Sorry not sure where you mean.

Thanks for helping!

**Comment by daveidivide** [comment]
Just found the crash reports...

Nothing I'm afraid.

I closed eqMac via Activity Monitor and restarted too.

![image](https://github.com/bitgapp/eqMac/assets/7994685/11b68914-e1e7-4f29-9422-bd489e092724)

I think the app is running fine. I just have no way to actually interact with it

**Comment by nodeful** [comment]
And the Audio Output device is set to the driver or not?

**Comment by daveidivide** [comment]
Do you mean this?

![image](https://github.com/bitgapp/eqMac/assets/7994685/4277fa27-0b69-4097-bfb8-cd2a6ff0471b)

I think that used to have eqMac as an option, but can't say 100%.

**Comment by nodeful** [comment]
So something is blocking eqMac from accessing internet I think, even though it should not be a requirement to have internet, but just to check:
Visit this page in the browser: https://ui.eqmac.app/v5/success.html
Also try to run this command in Terminal.app: `ping ui.eqmac.app`

**Comment by nodeful** [comment]
By any chance you guys have some Firewall settings or VPNs running?

**Comment by daveidivide** [comment]
I do sometimes have to a run a VPN for work stuff, but it has never been an issue before.

Just hit that URL and works fine (VPN is off right now, and has been all day)

![image](https://github.com/bitgapp/eqMac/assets/7994685/f84084d9-28bc-4163-8b44-6c414b6be3e8)

Pinging fine too
![image](https://github.com/bitgapp/eqMac/assets/7994685/03228ac3-f786-4778-97d1-47bd71369088)

**Comment by nodeful** [comment]
Also can you Sample eqMac process and send me the report as a file:
<img width="1660" alt="image" src="https://github.com/bitgapp/eqMac/assets/8472525/f6e44873-9371-4851-8dec-1dcf0b5033f5">

**Comment by daveidivide** [comment]
Here you go mate:

[Sample of eqMac.txt](https://github.com/bitgapp/eqMac/files/14012129/Sample.of.eqMac.txt)

**Comment by nodeful** [comment]
Ok for now I have no ideas what is going on, as if it just ignores the code I wrote. Gotta love computers

**Comment by daveidivide** [comment]
All good mate, appreciate your time looking into it and providing this open source!

I also just ran `sudo killall coreaudiod` to see if that did anything, but it did not.

**Comment by HudsonGraeme** [comment]
I'm able to workaround by killing the task and re-opening via terminal;
> `/Applications/eqMac.app/Contents/MacOS/eqMac`

**Comment by daveidivide** [comment]
@HudsonGraeme could you let me know exactly how I start it via terminal?

**Comment by HudsonGraeme** [comment]
> @HudsonGraeme could you let me know exactly how I start it via terminal?

Yes, in terminal the command should just be `/Applications/eqMac.app/Contents/MacOS/eqMac`

**Comment by nodeful** [comment]
I think I know what is happening, but not sure why.
Basically the app is trying to  show you an update prompt but fails to show the prompt window.
Please just download the update here and install:
https://github.com/bitgapp/eqMac/releases/tag/v1.8.4

This should resolve your issue

**Comment by daveidivide** [comment]
Ok, so I quit eqMac via Activity Monitor, then ran:

`open /Applications/eqMac.app/Contents/MacOS/eqMac` via terminal.

The application has started running, but same issue. Shows in AM but not in the menu bar.

**Comment by daveidivide** [comment]
@nodeful it worked!!!

You legend!

Thanks so much :)

![image](https://github.com/bitgapp/eqMac/assets/7994685/4c7a0dd0-cfc7-46e5-8d73-f24d1d4a76b3)

**Comment by declark** [comment]
Worked for me too! Thanks @nodeful
