### ISSUE TITLE
Bug: Super Preset feature is not working properly

### ISSUE THREAD

**Issue by Goyadoy** [bitgapp/eqMac#900]
Before I had a 'super preset' for automatic switching of an EQ. I turned off EQ for MacBook Speakers and turned on EQ for headphones out and my usb audio dongle.
Previously it worked great, and when I switch to speakers it turned off an EQ, and when I plug in a headphone it turned EQ on.
But starting MacOS Sonoma and EqMac 1.8 this feature is broken. 

**Steps to Reproduce**
1. Create 2 super presets, for 1st turn on automatic switching for Speakers, for 2nd turn on automatic switching for headphone out
2. Enable EQ for 2nd preset
3. Try to switch physical audio outputs - automatic switching is not working.
4. If you click 'Super Preset' radio button twice - EQ preset is selected as it should, so I think the app just can't capture swtiching event for some reason

**Expected behaviour**
EQ must switch according to selected audio out

**Setup information:**
 - macOS Version: Sonoma 14.3, reproduced on previous Sonoma versions as well
 - eqMac Version 1.8+
 - eqMac UI Version 5.0.6

**Comment by nodeful** [comment]
Thank you for the report, should be fixed in v1.8.5:
https://github.com/bitgapp/eqMac/releases/tag/v1.8.5

**Comment by Goyadoy** [comment]
That's great! I've tested it, and it's really fixed! Thanks!
