### ISSUE TITLE
Bug: incomplete audio using "say" command from terminal

### ISSUE THREAD

**Issue by jawsoftware** [bitgapp/eqMac#905]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
I have a crontab shell procedure that uses speech synthesis for some alerts, using the shell command "say".
If eqMac is enabled often the phrase pronounced is reproduced missing the first two or three words.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Launch Terminal
2. Try to use the "say" command; e.g: say "it's a beautiful day to go swimming"
3. Often you will hear only "...beautiful day to go swimming" or even less.
4. If it plays correctly, just try some more time, it will happen.

**Expected behaviour**
The full phrase should be audible

**Setup information:**
 - Audio device used for playback: Not important, internal or headphones
 - Audio transmission interface: internal or 3.5mm Jack
 - macOS Version: 11.7.10
 - eqMac Version 1.8.5
 - eqMac UI Version 5-0-7

**Screenshots or Console.app logs**
-

**Additional information**
Some problem found on two different Macs

**Comment by ragauskl** [comment]
If 'Pause Audio Processing' is not maxed out try increasing it or setting it to 'Never' and see if that helps, if it helps I suggest decreasing it at least a bit and see if it still works, as 'Never' may work but will also prevent device from going to sleep

<img width="397" alt="image" src="https://github.com/bitgapp/eqMac/assets/9280160/b666e676-326b-455c-85ae-23e5091ddd52">

**Comment by jawsoftware** [comment]
Using "Never" seems to solve the problem, I'll do some test gradually decreasing the value. Thanks.
