### ISSUE TITLE
eqMac falhando apos atualizacao 1.8.5 

### ISSUE THREAD

**Issue by HeroBass** [bitgapp/eqMac#907]
Uso o eqMac a muitos anos no meu MacBook Pro meados 2019 Intel masOS Sonoma 14.2.1, após a atualização do eqMac para 1.8.5 começou aparecer os seguinte problemas:

Após 3 minutos de uso o som fica falhando, dai eu reinicio algumas vezes funciona (volta ao normal ) outras não.
Fiz varios procedimentos do site eqMac mas nada resolveu.
desistalação de versões anteriores:

1. Reinicie seu Mac e, assim que a tela ficar em branco, pressione e segure ⌘R (Isso irá inicializá-lo no Modo de Recuperação/Seguro)
2. Execute o Terminal sem menu suspenso Utilitários
3. csrutil desativar
4. isso desativara o SIP.

reinicie o mac abra o terminal:

Se você tiver o eqMac2 instalado (por volta de 2017-2020):

sudo rm -rf /System/Volumes/Data/Library/Extensions/eqMac2Driver.kext/
sudo rm -rf /Library/StagedExtensions/Library/Extensions/eqMac2Driver.kext/
sudo rm -rf /Sistema/Biblioteca/Extensões/eqMac2Driver.kext/
sudo rm -rf /Biblioteca/Extensões/eqMac2Driver.kext/

após isso fiz o seguinte passo para resolver esse problema de som falhando:
Pressione o botão "Redefinir Reprodução" perto do menu suspenso Seleção de Saída no eqMac. 
Reinicie o eqMac. 
Reinicie seu Mac e execute o eqMac novamente. 
Reinicie o serviço CoreAudio executando este comando em Terminal.app:  
sudo launchctl kickstart -k system/com.apple.audio.coreaudiod 
Reinstale totalmente o eqMac baixando-o deste site.

Resultado nao funcionou, alguem pode me ajudar?

**Comment by ragauskl** [comment]
Please follow this issue on https://github.com/bitgapp/eqMac/issues/927
