### ISSUE TITLE
Bug: Volume mixer not staying at set level for device and phone, other apps works fine

### ISSUE THREAD

**Issue by PapiPeppers** [bitgapp/eqMac#916]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When using the volume mixer, I can successfully set the volume for Apple Music and other apps, but when I try to set the volume for the device audio and call audio, the setting jumps back to 100.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Go to the volume mixer
2. Set device audio or call audio at less than 100
3. Wait a second

**Expected behaviour**
The volume to stay where I set it at.

**Setup information:**
 - Audio device used for playback: Grado SR225X; Q Audio 3020i
 - Audio transmission interface: 3.5mm Jack; speaker wires
 - macOS Version: 14.4 (23E214)
 - eqMac Version 1.8.7
 - eqMac UI Version 5.0.8

**Screenshots or Console.app logs**
See comment below

**Comment by PapiPeppers** [comment]
https://github.com/bitgapp/eqMac/assets/57047860/4f9ddc39-acd3-49c8-a726-0eea4ca3836a

**Comment by ragauskl** [comment]
Could you reupload the video if this is still an issue? As is seems like it failed to upload and it's just blank. Dev said it would be best if you could specifically call  from your phone to computer and send a screen capture from the computer with the issue occurring.

**Comment by PapiPeppers** [comment]
Just checked and issue seems to have been resolved. I'll close this out and reopen with a video if it happens again.

**Comment by PapiPeppers** [comment]
Ran into this issue again today. Only difference I can think of from the other day when I did not see this issue is today I was actively using the sound output while the other day I was not playing anything on my device.

https://github.com/bitgapp/eqMac/assets/57047860/f74f23e4-b05d-493d-aebd-5897048cdce6

**Comment by PapiPeppers** [comment]
Issue resolved with upgrade to version 1.8.8.
