### ISSUE TITLE
EqMac does not work on macos 15 dev beta 1

### ISSUE THREAD

**Issue by UnknownCrafts** [bitgapp/eqMac#932]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
EQ Mac does not work at all in macOS 15 (dev beta 1). I know that this could have happened but just letting you guys know. One observation I have made is that the eqmac sound driver has completely been removed after the macOS update (it does not show up in sound settings). Another thing is that eqmac does not try to reinstall the sound driver even though it's nowhere to be seen. The app GUI seems to be functional though.

Extra info: Disabling and re-enabling eq mac seems to make it timeout (timeout error)

**Steps to Reproduce**
Update to macos 15 (dev beta 1)
just let eqmac launch like normal

**Expected behaviour**

EQMac should be able to output sound using its sound driver.

**Setup information:**
 - Audio device used for playback: Sony XM4
 - Audio transmission interface: Bluetooth
 - macOS Version: 15 dev beta 1
 - eqMac Version 1.8.7
 - eqMac UI Version 5.0.8
 - eqMac driver version 2.5.3

**Screenshots or Console.app logs**

**Additional information**

**Comment by DrPurrple** [comment]
I am also on MacOS 15 beta 1 and can confirm that eqMac does not work, it's not there in sound output options.

**Comment by yarecco** [comment]
I'd say this is rather MacOS 15 bug than eqMac.
I have SoundBlaster app drivers for my Soundblaster external card and the driver in /Library/Audio is ignored by system as well. 
I guess all drivers installed in /Library/Audio and not /System/Library/Audio are simply ignored by the new system.
This is first developper beta. Needs time to make things right.

**Comment by chanisagithub** [comment]
I'm on the same os version( 15 beta). I have tried uninstalling the driver and the app and killing all coreaudiod services. But still not working.

**Comment by nitec427** [comment]
Same here

**Comment by jonatino** [comment]
It's working on Beta 2

**Comment by UnknownCrafts** [comment]
Download macos 15 beta 2 to make eq mac work again.

**Comment by nodeful** [comment]
just as I was about to issue and update with a fix.
I need to post a statement somewhere for people to not expect eqMac to work on Beta Releases of macOS.
Otherwise it's a big waste of everyone's time for everyone, I got hundreds of support messages and having to explain it to everyone is impossible

**Comment by chanisagithub** [comment]
Thanks for the update.
